### ISSUE TITLE
Person Following List Sometimes Not Populating With Phone Numbers

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1002]
I'm currently following four people all of which have mobile and home numbers. 

In the Person Following List only two of those people are displaying numbers in either of the cell or home columns. 

I've got a .csv file containing the values from the PhoneNumber table of the people I was following (with the phone numbers obscured) that I'm happy to share.

**Comment by nairdo** [comment]
@arranf I've not had much luck trying to repro this. How many people are you following, and how many phone types do you have defined?  Can you also run this query and let me know if it returns the Mobile and Home phone types?

    SELECT * FROM DefinedValue WHERE Guid = '407E7E45-7B2E-4FCD-9605-ECB1339F2453' OR Guid = 'AA8732FB-2CEA-4C76-8D6D-6AAA2C6A4303'

**Comment by arranf** [comment]
3.2, Chrome, Windows 7

I have three phone types defined. I can confirm that it returns the Mobile and Home phone types. 
I'm going to email you the .csv file I mentioned in my original issue (just in case it helps!).

**Comment by ccofnow** [comment]
Arran,

Did you import your data with Excavator? I've found that it program imported only the straight number, such as 5551231234 and did not enter any value for "NumberFormatted" like (555) 123-1234. Usually Rock just defaulted to showing the normal number when the NumberFormatted was null, but there are a few places where it ends up just showing no number at all. In fact, I just today fixed that issue for us because it was making the Group Toolbox roster page rather useless.

**Comment by arranf** [comment]
@ccofnow Thanks for flagging this up. I was chatting with someone else who was having an issue with the group toolbox and I remembered that we did as well (following an Excavator import!) which I ended up having to fix.

I completely forgot about this open issue, it's probably the same thing occurring here.

**Comment by arranf** [comment]
@ccofnow Was completely right
