### ISSUE TITLE
Check-in Security Code has a '-' added

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1017]
Here's a strange one:

A few times now, we've had a dash added on to a security code:

![imag0062](https://cloud.githubusercontent.com/assets/1859094/7456004/17262372-f24f-11e4-892b-d01ccffb23b9.jpg)

(it also looks like we need to train volunteers again on label alignment...) The crazy thing is, I remember this one - it did it last time on the code SMM too.  There have been a few other instances of different codes where this has happened, but I don't have any more example tags. I'd guess this has happened about 10 times now.  The volunteers have just have the child check in again and get a new code to fix the problem.

In the case of the tag above, there is no - in the database on the code:

![2015-05-04 11_14_20-sqlquery2 sql - rock newpointe org rock-production rock 72 _ - microsoft sql](https://cloud.githubusercontent.com/assets/1859094/7456030/4c489ab2-f24f-11e4-80ee-a4e846de302c.png)

As far as I know from what's been reported to me, this has only happened at one campus - that may just be coincidence because it's been our largest campus. Let me know if there is any other info I can provide.

**Comment by bwitting** [comment]
We got another one this week.  The kiosk and check-in group were different, and the code started with a different character - but it ended with 2 M's (just like last time) and got a dash stuck on the end:

![imag0096](https://cloud.githubusercontent.com/assets/1859094/7919293/5f6d7262-0865-11e5-9858-ed7bebd535cf.jpg)

Just like before, there is no dash in the database, it just got printed from some reason.

**Comment by ccofnow** [comment]
Bronson-

This dash is appended by the Zebra printer automatically when it believes the string is too long to fit in the space provided by the label - it considers the width of the characters in the font when it figures that out, and when the string is found to be too wide, it will attempt to wrap onto a second line with a dash to indicate it should be connected. But it doesn't actually PRINT on a second line, it does a carriage return without a line feed and prints the second line OVER the first line.

So what's happening (I'll use your first example) is that it's printing:
SM-
M
but the third character is printed right over the "SM".

The fix is to manually edit your label file- widen the code field so it can accept a longer string.

I'll refer you to a rather long "Answer" I posted a while ago: http://www.rockrms.com/Rock/Ask/Using/Questions/351#a685 and encourage you to put in your label (minus any graphics) at http://labelary.com/viewer.html and see what it's doing for yourself- you can tweak it live there until it works and then copy the codes back into your label file (don't forget to put your graphics codes back in place when you do!)

**Comment by bwitting** [comment]
@ccofnow - great, thanks for the info! That seems to be exactly what is going on.  I've widened those fields, so hopefully that won't be a problem anymore.
