### ISSUE TITLE
PledgeList code is tied to PersonId instead of PersonAliasId

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1032]
The Pledge table is linked to a Person using the PersonAliasId column.  
![screenshot 2015-05-12 17 13 50](https://cloud.githubusercontent.com/assets/1210933/7598702/4aa1cf04-f8ca-11e4-97ff-04236ebb8a3a.png)

However, the code for [PledgeList](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/PledgeList.ascx.cs#L155) tries to filter on PersonID instead of PersonAliasID.   So in our database where the AliasID doesn't match the PersonID, the filter doesn't show anything.

In most Rock databases, the PersonId and PersonAliasId will match but we've been deleting and merging people in testing.

**Comment by mikepetersonccv** [comment]
@dcs619 I'm pretty sure PledgeList is already doing the Person filter correctly.  It consistently uses PersonId as a Filter and not PersonAliasId.  However, when the account filter is set to none, it was trying to filter to accounts that have an Id of 0. If that seems to be what is going on, let me know and I'll update the description of this issue so it mentions the account filter instead of the person filter

**Comment by dcs619** [comment]
@mikepetersonccv you're right, that was the issue. I'll update the title.
