### ISSUE TITLE
Multi-selection Group Topics

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#1037]
I will try to describe this as best I can.

I went to Group Attributes category, edited the "Topic" attribute to select the checkbox for "Allow Multiple Values".

When I changed the Group Topic to "Allow Multiple Values", the Group Search tool on our website changed from multi-selection to a single selection dropdown. So, I am back to the same problem. Members cant search on more that one topic. Is this a bug, or do I need to make additional changes?
When I changed the Topic back to single selection, then the group search tool went back to multi-selection.

**Comment by MrUpsideDown** [comment]
There is some further discussion around this issue here:
http://www.rockrms.com/Rock/Ask/Using/Questions/590

**Comment by arranf** [comment]
I'm taking a look at this

**Comment by arranf** [comment]
I'm not sure on the best way of how to proceed here, I'm not very familiar with all the plumbing that's gone in to producing the filters so I'm a bit hesitant to make changes.

Here's what I've discovered. The issue as described relates to the Group Finder block not the Group Search block.

It seems like Rock.Field.Types.DefinedValueFieldType.FilterValueControl is setting the allow multiple value key to false which causes EditControl to create the drop down rather than the check box list. I'm not sure why that method is being called, I'm assuming I'm missing something there?

The default behaviour of the check box list with multiple values is an "and" comparison, i.e. Groups that match Topic 1 **and** Topic 3. I'm guessing the behaviour we'd want in this instance is an "or" comparison.

**Comment by nairdo** [comment]
The Group Finder block supports allowing members to search by multiple topics event if the group's topic attribute (as a Defined Value) has been changed to allow multiple values:
![image](https://cloud.githubusercontent.com/assets/383807/21185673/e2ab1700-c1ce-11e6-9fda-38a869b19491.png)

I've confirmed this via [the demo site](http://rock.rocksolidchurchdemo.com/page/236) which is currently running Rock v6.1.

![image](https://cloud.githubusercontent.com/assets/383807/21185503/23c6e076-c1ce-11e6-9240-576031ef9a32.png)
