### ISSUE TITLE
Group Detail Lava: Leader Add Member Broken

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1042]
Leaders of groups are unable to add members to their groups using the Group Detail Lava block as they are unable to search the database.

Reproduced on the demo site. Judging by the block description "Page to use for adding a new group member. If no page is provided the built in group member edit panel will be used. This panel allows the individual to search the database." this is not by design!

**Comment by nairdo** [comment]
Unless you've given your leaders a role which is allowed to use the Person Search REST api, you're right.  We're planning on updating the Person Picker to detect when there's been an unauthorized (401) and show an appropriate message on screen...instead of just showing nothing. (Perhaps something like https://gist.github.com/nairdo/49dbcc9733b70d4cff10)

**Comment by arranf** [comment]
TIL about the REST auth controllers! Thanks.
