### ISSUE TITLE
Metrics job fails because of table name

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#1071]
This may night be a bug but I wanted to have other eyes on it also just in case. With 3.4 our rock cleanup job is now working but Metrics is failing. 

![jobmetrics](https://cloud.githubusercontent.com/assets/7595345/7963033/b0d124da-09de-11e5-9620-e57f02c3dcae.png)

**Comment by bwitting** [comment]
Just wanted to comment that I'm on 3.4 and using the metrics features, and I have not seen this issue.

**Comment by arranf** [comment]
I'm seeing an exception, a different one, following the update.
`Exception when calculating metric for (Object reference not set to an instance of an object.)`

**Comment by arranf** [comment]
@kcirgjd Is this still an issue for you?

**Comment by kcirgjd** [comment]
I am not sure. Our leadership decided to stick with using Church Metrics from Life.church so I have stopped working to get them setup in Rock.

**Comment by cabal95** [comment]
I'm going to close this as I think it has already been fixed or was possibly due to custom SQL on a metric that was invalid. There is only one reference to `CreateDateTime` in the repo and it's an HTML comment. If anybody is still having this issue and can confirm it is not custom metric SQL, we can re-open.
