### ISSUE TITLE
OK button for check-in errors doesn't work

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#1073]
If someone enters a phone number with no matches or hits the check-in button without choosing a service time, they get an error message. The OK button on the error message doesn't work. You have to wait check-in session to time out and start checking in the family from search again. If someone clicks OK, then that restarts the timer for the timeout so we've had families stand there clicking OK repeatedly and they never get timed out to the search by phone button.

**Comment by bwitting** [comment]
@KelleyLangkamp - did you customize your check-in theme?  This happened to us when we did the 3.0 update because of the change in the way modals work. 

If you have a custom check-in theme, make sure you copy the new modal sections out of the checkin-theme.less file in one of the default themes and re-compile your .css file. 

If you didn't make a custom check-in theme, switch to one of the other defaults that ships with Rock and see if the issue happens with a different theme.

**Comment by KelleyLangkamp** [comment]
Copying the modals section took care of the issue.
