### ISSUE TITLE
Data View Filter 'Is Blank' on Date Fields Results include 'Current Date'

### ISSUE THREAD

**Issue by arranf** [SparkDevNetwork/Rock#1126]
Steps to Reproduce:

1. Create a Data View to filter 'Is Blank' on a Person Field where the field-type is 'Date'
2. 'Current Date' records will be returned

**Comment by arranf** [comment]
Additionally filtering "Is Equal To" and selecting 'Current Date' will not return any options which are 'Current Date'

**Comment by nairdo** [comment]
@arranf In your case, I wonder if the date values stored correctly?  I think we're seeing a similar issue and when I looked at the data we imported from our old ChMS, all the date values are stored in the 'MMM DD YYYY HH:MM:TT' format instead of the proper ISO-8601 format as seen in these two examples:

```
Aug 11 2001 12:00AM
1972-04-02T00:00:00.0000000
```

**Comment by arranf** [comment]
@nairdo I'll look into this. From my memory this was occurring with data input in Rock as well as imported data.

**Comment by arranf** [comment]
Yeah these as stored as Dates not DateTimes
