### ISSUE TITLE
Only Rock Admins Can Delete Org Tags

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#1180]
Staff Users can add organization tags but can't removed them.  Only assigning them Rock Administrator fixes the issue.  Giving them Edit and Administrate rights on the block and page doesn't.

**Comment by pufferdude** [comment]
I can confirm this behavior. To be clear, the UI lets you go through the motions of deleting the tag (on the user's Profile page), and it disappears, but is not really deleted and comes back when you nav away from the user and return. Seems like it's not a simple "no rights" issue (otherwise you wouldn't be able to click the x on the tag to delete it), but something under the hood is not completing when you're not an admin.

**Comment by nairdo** [comment]
Out of the box (at least for v6 where I'm testing this), a person with the _RSR - Staff Workers_ role can add a person to an organization tag, remove a person from a tag, but they cannot delete the organization tag.  They are also not able to elevate a person tag to an organization tag.
