### ISSUE TITLE
Unchecking 'Completed' on Workflow edit page does not remove Workflow CompletedDateTime 

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1239]
http://mysite/page/291?workflowId=2660
Edit, Details tab, Completed [  ] check box.

Unchecking the 'Completed' flag on editing a Workflow should reset the CompletedDateTime field on the Workflow record. It currently doesn't do this, so to 'reopen' the workflow this date has to be manually removed.

**Comment by azturner** [comment]
Unchecking the 'Completed' checkbox does set the completedDateTime field to null, however, since the workflow is immediately processed whenever it's updated, if there are not any active activities/actions, the workflow will immediately be completed again by the processing engine.  

Are you also unchecking the 'Completed' for an activity and one ore more actions in the activity?

**Comment by azturner** [comment]
Closing for now, please re-open if you feel there is still an issue
