### ISSUE TITLE
Create person with a campus id through the API

### ISSUE THREAD

**Issue by ghost** [SparkDevNetwork/Rock#1257]
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Rest/Controllers/PeopleController.Partial.cs#L191

I'd like to be able to create a person with a campusId through the REST API.  Currently I would have to create the person.  Figure out the person's newly created family group.  Update the family group with the campus id.

My thought for solving this would be to modify the Post method (linked above) to take a PersonWithCampus model, which is a model that inherits Person and adds a nullable campusid.  It's pretty straightforward, but ugly because it requires creating a whole new model with an irregular name.

FYI @dcs619

**Comment by dcs619** [comment]
@mikepetersonccv Any thoughts?  Right now [PersonService.SaveNewPerson](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Rest/Controllers/PeopleController.Partial.cs#L191) passes null as the Campus parameter that could be used when creating a new family group.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
