### ISSUE TITLE
Content Channel View Block not Respecting Query Parameter Filtering

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#1276]
I've got a page where I'm trying to display information from 2 different Content Channels (message series and individual messages).  I want to pass and Id for the message series in the URL to get the specific message serries, so I'm appending ?Item=## to the URL and enabling Enable Query Parameter Filtering for that Content Channel View block.  However, the content channel View Block where I * don't* want to filter on the Parameter still only gets the item from the URL parameter anyways, event though the Enable Query Parameter Filtering box isn't checked.

**Comment by nairdo** [comment]
@bwitting I think I've been able to confirm what you're seeing.  I set up a test page here for you to review: http://rock.rocksolidchurchdemo.com/page/5315?Item=9 

Is that what you're seeing?  If so, it's even a little worse than you describe since the second ContentChannelView block is showing an item that's not even in its channel.

(I also confirmed this issue is still in the current 4.0 build.)
