### ISSUE TITLE
[EN] Allow verification to be disabled for individual Family addresses.

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#1286]
We currently have a problem where some families have addresses that are not recognized by the verification service (in our case, Bing). The service sometimes incorrectly modifies the address to a similar (but incorrect) value. The best way to prevent this would be to allow verification to be disabled for a specific address so it is not standardised or geocoded by the service.
The intention is to add a "Verify this Address" checkbox that is checked by default, but can be unchecked for addresses that can't be validated correctly by the verification service.
@azturner @mikepetersonccv  Your thoughts?

**Comment by arranf** [comment]
@MrUpsideDown. The issue with that method is that you won't know,
necessarily, that the address will standardise poorly.

I think the best way to tackle that is to save the previous address and
then standardise. Thoughts?

**Comment by MrUpsideDown** [comment]
@arranf Yes, that is a problem for us also. To make matters worse, if the address is standardized incorrectly, the change is not logged in the history because it is done before the record is actually saved. To get around that, I propose validating the address when it is first added or updated (when the green check mark is clicked), but before the family record is saved.

**Comment by arranf** [comment]
@MrUpsideDown Another potentially useful change when tackling this would be to pass the location type to the location service. I can see a case for having one location service standardise business addresses or the same location service handle home and work addresses differently. Thoughts?

**Comment by MrUpsideDown** [comment]
@arranf Do you have any concrete examples of where this would be useful? We use Bing, and I can't see any way that different location types could be treated differently there.

**Comment by arranf** [comment]
For me specifically sometimes businesses have their addresses standardised
so that we lose address information with the location service we're using.
It'd be nice to format business addresses specifically so that the business
name was address line 1 and the rest was squished into address line 2.
If it's niche then there's no point changing it because I imagine that'll
make the process slower, but if there's a more generic use it might be
nice. Thoughts?

**Comment by MrUpsideDown** [comment]
I think I see what you mean - in situations where an address has additional identifying information that is not recognized by the verification service, it can be stripped out during standardization. To handle this, I would suggest adding a new address field "Building" to capture descriptions of sub-divisions that are more fine-grained than the address service can handle, and omitting that field from the validation/geocoding process. For now though, the simplest solution is to just switch off verification for that address.

**Comment by arranf** [comment]
In the shower this morning I remembered exactly why I was thinking about this. Some people have registered businesses at their home address which causes a home address to appear as:

Business Name
Address Line
City
Postal Code

Being able to toggle any business names being stripped from the address if it is a home location would be much cleaner and prevent some rather strange mail merges happening.

**Comment by MrUpsideDown** [comment]
@arranf I've addressed this problem for our system by modifying the Bing search component to ignore everything that precedes the last comma. So if you have "Business Name, Street Address" in the Address Line 1 field, "Business Name" will be stripped out before validation. This is a postal standard (for Australia anyway), and it seems to address most of these problems. As I mentioned previously, the more comprehensive solution would be to provide an additional field (like "Building") to separate out any address qualifiers that can't be standardized or geocoded.

**Comment by azturner** [comment]
For now we're giving administrators the ability to disable verification (standardization/geocoding) for a particular location. This is accomplished by a new gear icon next to each address on the person profile that admins will see and can use to set the address and/or geopoint to any value, and then optionally disable verification services for that location.

**Comment by MrUpsideDown** [comment]
@azturner In the future, can I ask that you please consult with the person who raised an issue marked with the "[EN]" prefix before making any proposed changes in that area? I have a mostly completed solution for this that I was intending to PR, and this commit has just broken it.

**Comment by azturner** [comment]
Sorry, didn't see any comments indicating that you were working on fix. We see the fact that you couldn't turn off verification for a particular location as more of an issue than an enhancement, and our change was a simple fix to wire up a link to the existing location detail block that already provided this capability. We felt it important to get this into v4.0 which were trying to wrap-up all changes for. How were you addressing this in your pull request?

**Comment by MrUpsideDown** [comment]
Ok, my understanding is that the purpose of the "[EN]" prefix is to announce an enhancement that the submitter is intending to work on. I opened this up for discussion and mentioned you and Mike to get some feedback on how best to address it, but my assumption was that it would be left to me to resolve. In the future, I think it would be helpful if you could indicate your intention to take ownership of the issue in the comments before making changes.

**Comment by MrUpsideDown** [comment]
I think my PR is somewhat complimentary to yours. I have adopted the approach of validating the address when the user clicks the checkmark to update the address. This way, they get instant feedback if the address can't be validated, and they have the opportunity to correct it or disable address verification for that address.

**Comment by MrUpsideDown** [comment]
This fixes a major problem that we have encountered when the standardization process modifies the address incorrectly and then saves it without the user noticing.

**Comment by arranf** [comment]
Instant feedback is _very_ helpful in this area

**Comment by treyhendon** [comment]
I agree.  Helping a church out, they're using Smarty Streets and the apartment number is being stripped out of the address because it's not in the USPS system for Smarty Streets to validate.

It would be great for them to enter the Apartment in the Home address type, see the number stripped out (but get the +4 on zip), then have the option to go back and change a flag for the address to keep it from validating in the future and manually add back the apartment number.

**Comment by azturner** [comment]
Re-opening this as @MrUpsideDown is still working on PR to update EditFamily block to an indication of unsuccessful verification when user clicks the green check box to save an address. @MrUpsideDown.

**Comment by arranf** [comment]
:thumbsup:

**Comment by MrUpsideDown** [comment]
@azturner Thanks, I hope to have a PR ready shortly.
@treyhendon What is your format for a street address with an Apartment number? In our case, we  enter something like "4/16 Main St" or "Unit 4, 16 Main St", so I am stripping out anything before a "/" or "," prior to validation, then adding it back after validation. Would this work for you? Not sure about your reference to the "+4 on zip"?

**Comment by arranf** [comment]
Here's another test address for you:

Flat E2B-05
Cooper's Hill Lane

**Comment by treyhendon** [comment]
@MrUpsideDown  The +4 is a US Postal standardizing thing (provided by Smarty Streets).  It's supposed to help the USPS with deliverability.

Regarding format, here are the way our two use-cases are coming back from Smarty Streets messed up:

1. PO Box 977
 * Returns nothing, saving the family with no address.
2. 123 Main St, Apt 23
 * If Apt 23 is not registered at USPS, Smarty Street removes and only saves 123 Main St in Location table.

I was envisioning that a "do not validate" check box would do two things.  It would need to leave a flag on the Location record (preventing the Job from trying to validate in 6 months) and then retain Address Line 1 (and 2) as-is (rather than from the standardization service).  That would let the USPS +4 and Lat/Long be saved.

**Comment by MrUpsideDown** [comment]
@treyhendon We have exactly the same problems with Bing. I have done what you suggested, except that disabling validation also disables geocoding. The reason is that we have also experienced the case where Bing returns high-confidence matches after completely changing the street name that was entered! So I have gone down the path of retrieving the standardized match, and if the fields do not correspond exactly to what was entered, requiring the user to confirm the standardized address or switch off verification of the address before saving the address. Does this sound reasonable?

**Comment by treyhendon** [comment]
I think that would work, yes.

Two thoughts to consider in addition:
1. Would you consider 2 checkboxes (bypass standard & bypass geo)? OR
2. Would you consider not erasing the Geo Code info if returned lat/long is blank (option via Org Attribute t/f)?
 * ie.  I do the standard on my apartment.  It gets geocoded correct, but the apt # is removed.  So now, I go back, add the apt # and check "don't standardize".  This would let the existing geo code info on Location table remain in place on save - rather than blanking out.  (This assumes the Location will be updated and not create a new row in that table.)

Those thoughts come from our case of the apartment address geocoding correctly, but only apt is removed in process.

Is this way overcomplicating the matter?

**Comment by MrUpsideDown** [comment]
I think (1.) is unnecessary, because if the standardization fails it implies the address service doesn't understand the address well enough to give an accurate geocode. To address the issue of apartment info being removed for our implementation, I have taken the approach of stripping out the apartment details before sending the address for validation to Bing, and if the return address matches the stripped address I accept the geocode and add back the apartment info. This works, but it relies on parsing the Address Line 1 field to remove info before a "," or "/". This is a postal standard in Australia, but not elsewhere - ideally, this should be implemented using a separate field ("Building"?) that contains address info that is never sent to the validation service, so it is consistent for all addressing schemes.

**Comment by treyhendon** [comment]
Ahh.  That makes sense.  Yeah, don't worry about it for now then.  Hopefully the by-pass will not be the norm and we won't see major impact.  Worst case I could add an extra "geocode without standardization" option back in.

**Comment by edmistj** [comment]
This can be done fairly easily using the gear next to address, unfortunately the gear was only visible to those with administrate access to the block. After looking at the options on the location editor it seems like anyone with 'Edit' access to the family bar should be able to view the location edit screen so I change the code to reflect that.

![lock](https://user-images.githubusercontent.com/548178/41741583-5ffe01d2-7550-11e8-89c8-8a9abdf3a918.gif)
