### ISSUE TITLE
Postal address case changes aren't saved

### ISSUE THREAD

**Issue by jezhailwood** [SparkDevNetwork/Rock#1331]
I've noticed that when making corrections to capitalisation within a postal address, the changes are not saved. For example, changing a postcode from _ab1 1cd_ to _AB1 1CD_ does not do anything. This also happens in other address fields.

**Comment by DerekMangrum** [comment]
Tested in Rock v4.2

Confirmed, in part. When using 'Edit Family | click pencil to edit address', the reported behavior is confirmed. When hovering over the address on a Person Profile page and then clicking the 'gear' icon, any edits to the address are saved as expected.

**Comment by cabal95** [comment]
I believe this is expected behavior (not saying correct, just expected). When saving an address the database is searched to see if there is a matching record already there (to make sure we don't end up with 7 duplicate addresses that are no longer attached to anything). SQL does case-insensitive text matching so it would see `ab1 1cd` as equal to `AB1 1CD` and thus return the existing record.

The "gear method" actually edits the raw address record which is kind of an unsafe operation. You are making raw modifications to the address (location) record which may have unintended consequences. If you completely change the address to another street, city + state then other things which reference that location would then have their address updated as well and that may not be intended. But that is why this method works, because it doesn't search for an existing address, it just modifies the existing record.

A possible solution would be that after the address is found in the database to then check for case differences in the address and re-save the location if there were differences in the capitalization of any field.

@edmistj thoughts on that solution?

**Comment by edmistj** [comment]
I agree that:

> A possible solution would be that after the address is found in the database to then check for case differences in the address and re-save the location if there were differences in the capitalization of any field.

Makes sense. It would be nice if this was don't at the service layer so that the logic is consistent vs doing it on the block.
