### ISSUE TITLE
Schedule recurrence does not override the effective start date

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#1350]
Opened on behalf of Kreston Lee:
For example, if the start date is 1/16/2016 but set the recurrence to be every 3rd Sunday of the month, the effective start date should be 1/17/2016 (17th is a Sunday while the 16th is a Saturday).  In the current situation, the event shows up on the 16th and the 17th.

![image](https://cloud.githubusercontent.com/assets/383807/12310193/2f23b1a8-ba0c-11e5-99c5-e86f6d6cdd19.png)

In the case of Outlook the initially selected start date is overridden and the correct effective date is used.

![image](https://cloud.githubusercontent.com/assets/383807/12310294/ad2e670a-ba0c-11e5-973d-98bcd26cafb4.png)

...which becomes:
![image](https://cloud.githubusercontent.com/assets/383807/12310301/c8dd7838-ba0c-11e5-9b22-e555ac221704.png)

**Comment by azturner** [comment]
@nairdo , when you mention that "the event shows up on the 16th and the 17th", what block are you referring to?

**Comment by nairdo** [comment]
@azturner via the CalendarLava block.  Here's a demo showing an event occurrence whose schedule has this and it being displayed on the calendar: http://alpha.rockrms.com/page/397

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
