### ISSUE TITLE
PersonAlias Id column does not match PersonAliasId column

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1402]
I did a fresh install of Rock and I didn't notice it till running Excavator. It looks like the two default persons created in the database are Admin Admin and Giver Anonymous. PersonAlias table has the row id for Admin Admin 10 and Giver Anonymous 11 whereas their PersonAliasId is 1 and 2 respectively.

I will update their Alias Ids to match their row Ids but wanted post the issue (sorry if it a duplicate issue).

**Comment by dcs619** [comment]
@BEGamache The ID discrepancy is by design since we were running into issues with blocks that referenced PersonId instead of PersonAliasId: [code change](https://github.com/SparkDevNetwork/Rock/blob/2a952baabc59febf80167fa958cef2fdc3f79b5e/Rock.Migrations/Migrations/Version%200.1%20(Pre%20Beta)/Version%200.1.4/201401221752081_PersonAlias.cs#L53).  

What issues were you running into?  A bug with Excavator?

**Comment by BEGamache** [comment]
Ok. Thanks for letting me know. I was aware of that.

No, it is an issue I may have created but when tracking it down I noticed the different IDs. 

I'll mark this issue as closed. Thanks David.
