### ISSUE TITLE
[EN] Consistency sweep on API methods, ModelService methods

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1424]
Browsing around various models, I've noticed consistency issues with the way we're using the RockContext and [Model]Services.  Would it be helpful to do a sweep & PR with those changes?

For instance, in PeopleController.Partial, [GetImpersonationParameter](https://github.com/sparkdevnetwork/Rock/blob/develop/Rock.Rest/Controllers/PeopleController.Partial.cs#L609) uses 
`var rockContext = this.Service.Context as Rock.Data.RockContext;` 

while [GetByEmail](https://github.com/sparkdevnetwork/Rock/blob/develop/Rock.Rest/Controllers/PeopleController.Partial.cs#L103) uses
`var rockContext = new Rock.Data.RockContext();`.

I can't think of a reason why those *should* be different, but I'm happy to be wrong. @nairdo @edmistj

**Comment by azturner** [comment]
The context returned from the `this.Service.Context` property has ProxyCreation disabled. so when objects are read from a service class using that context, lazy-loading of navigation properties is not supported (which includes OData requests). Since `GetByEmail` returns an IQueryable result, it needs to support OData queries and thus needs a new context. Because `GetImpersonationParameter` only returns a string value it doesn't need to use a context with ProxyCreation enabled. Same for the `Get` method that just returns a single Person object (OData only works with an IQueryable).

**Comment by dcs619** [comment]
Ah, thanks for the explanation @azturner!  Good to know.
