### ISSUE TITLE
The 'Help' property does not work for either the RatingInput or LocationPicker controls.

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#1444]

**Comment by garrettjohnson** [comment]
Looks like a help property has been added for the [RockRating](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/RockRating.cs#L78) input. But the [Named Location Picker](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/UI/Controls/Pickers/LocationItemPicker.cs) is missing on the current dev branch.

**Comment by cabal95** [comment]
This appears to be fixed in v8 (pre-alpha) unless I mis-understood the original problem.

The Named Location Picker that @garrettjohnson linked to inherits from ItemPicker which does implement the Help property, so this should be working unless we have more information on exactly what isn't working and in what context.

![image](https://user-images.githubusercontent.com/1119863/41440276-cdb73298-6fe2-11e8-80b4-d8ffab7562d7.png)
