### ISSUE TITLE
Report lava field not sorting text numbers

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#1451]
I am trying to sort a report on a text 'Giving Number' person attribute.  This contains numbers like 
2, 102, 202
Sorting on the text GivingNumber attribute field gives expected text sorting: 
![lavasort3](https://cloud.githubusercontent.com/assets/4658177/14056840/37960f1a-f356-11e5-96ec-d4555c62c2cb.JPG)

I tried adding this lava field:  {{ GivingNumber | Plus: 0 }} and sorting on this.  This gives an unexpected and unsorted output:
![lavasort1](https://cloud.githubusercontent.com/assets/4658177/14056752/35e4cc8e-f355-11e5-95d6-6dc529770bea.JPG)

I tried sorting on this lava field: {{ '00000' | Truncate:4, GivingNumber }}.
This gives this output:
![lavasort2](https://cloud.githubusercontent.com/assets/4658177/14056798/b8cdddde-f355-11e5-806c-2fbdf89d5304.JPG)

It seems the sorting is being done before the lava is being applied.

In general, there seems no way to be able to sort a number stored as text, or output as text from lava, to get a numeric sort order.  Is there any way to type the lava output as numeric?

I can work around this by changing the type of the attribute to integer:  this allows the report to be sorted correctly on GivingNumber, so it's not a biggie.  (But this is not a permanent solution because I need the GivingNumber to be text for other reasons.)

**Comment by azturner** [comment]
@ElimAdmin , unfortunately there's not really an easy way to sort the lava fields in the reporting interface since the values are being formatted after the querying/sorting of the data. Because of that, we have updated the report block so that it only shows fields that can be sorted in the order by selection: https://github.com/SparkDevNetwork/Rock/commit/94b4550b7ed28303071fbab99609ef270283bbc4
