### ISSUE TITLE
Group is required on Group Member List block

### ISSUE THREAD

**Issue by KelleyLangkamp** [SparkDevNetwork/Rock#1500]
I'm having the exact issue listed https://github.com/SparkDevNetwork/Rock/issues/1431. My production environment is running v4.4 and my testing environment is running v4.5. It happens in both of them. When I try to set the detail pages for the Group Member List block. It requires me to choose a group instead of allowing it to come from the page parameter.

**Comment by bwitting** [comment]
@KelleyLangkamp we had this issue too.  It's fixed in v5.  In the meantime, if you need the fix now and you're comfortable editing block code, change line 41 to `[GroupField( "Group", "Either pick a specific group or choose <none> to have group be determined by the groupId page parameter", false )]` (you're adding the `, false` to tell the picker not to require a group)

**Comment by KelleyLangkamp** [comment]
@bwitting Thanks for the detailed fix! I'm fine editing the code as long as someone tells me exactly what to edit.
