### ISSUE TITLE
Following Notices for deceased people showing up

### ISSUE THREAD

**Issue by mikepetersonccv** [SparkDevNetwork/Rock#1558]
If you are following a person that is deceased, you'll still get following notices for them.  For example, if that person has an upcoming Birthday or Wedding Anniversary, it will still send the notice.

**Comment by arranf** [comment]
I'm thinking to a degree there may be some use to this. I don't think I
would want to remain following after someone is marked deceased but I may
wish to follow someone who is deceased.

For instance following the dead significant other or family member of
someone in my small group so that I can be aware of when they may need
additional support, around birthdays or anniversaries.
