### ISSUE TITLE
group member workflow trigger not passing Person entity

### ISSUE THREAD

**Issue by dcagnetta** [SparkDevNetwork/Rock#1576]
Hi
I added a group type and added a Group Member Workflow to trigger when the members status changes.
However it does not pass in the Person entity as the documentation says:

> When workflows are started from the group member triggers, they will pass in a few attributes for your convenience. These include:
> 
> Person: The person that the group member represents.
> Group: The group that the person is a member of.

I tested this by setting the workflow to use to be the "Photo Request" which is suppose to email the passed in Person 

thanks

**Comment by tcavaletto** [comment]
Hi,
When a Group Member Workflow is triggered, it passes in the GroupMember as the Entity, and then sets the Group and Person workflow attributes to the Group and Person of the groupmember if the workflow has those attributes.

The problem with testing using the Photo Request workflow is that one of its actions is to set the workflow's 'Person' attribute to the workflow's Entity. In the case of a 'Group Member Workflow', that means that it sets the Person attribute (stored as the person's PersonAlias Guid), which is already set to the correct person, to the GroupMember's Guid. 

When the SendEmail action fires off, it then tries to find someone with a PersonAlias Guid matching the value stored in the workflow's Person attribute. However, since the Guid stored in the workflow's Person attribute is actually the GroupMember 's Guid, it returns no results and the email is not sent.

Just make sure that no workflow actions are overwriting your Person and Group attributes unless you want them to and you should be good.
