### ISSUE TITLE
Calculate duplicates exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#1607]
This was happening with 4.6 but also in v5beta. We are seeing exceptions when the Calculate Person Duplicates job runs, but curiously it seems to only happen every-other day. You can see in this screen shot that it caused the exception on 7/2 and 7/4 but ran fine on 7/3 and 7/5. 
![pasted image at 2016_07_05 11_32 am](https://cloud.githubusercontent.com/assets/3903408/16597228/6dcced86-42bd-11e6-9b06-472b35b161d0.png)

**Comment by azturner** [comment]
This is due to the fact that a Production and Test instance of Rock are both running the duplicate finder job at same time on the same SQL server. Even though the instances of Rock are using two different databases, they both share the same TempDB database, so when the proc creates a temp table with a named constraint, that constraint is not unique to each connection. The creation of the temp table needs to be updated so that it does not use a named constraint and SQL can take care of making it unique.
