### ISSUE TITLE
FinancialTransaction.BatchId not a required field (migration)

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#1608]
When checking our data integrity, I found a lot of FinancialTransactions that don't have a BatchId.  Without the BatchId being set, [History isn't saved](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionDetail.ascx.cs#L304) when editing a transaction, [users cannot navigate](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionDetail.ascx.cs#L1004) to the next TransactionDetail, and [transaction matching](https://github.com/SparkDevNetwork/Rock/blob/1858a2e89a5340ebcc46a96a7cf2a2daccc6fa93/RockWeb/Blocks/Finance/TransactionMatching.ascx.cs#L204) is more difficult.  There may be issues with Giving Analytics as well.

TransactionList, TransactionDetail, and [ScheduledTransactionService](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/FinancialScheduledTransactionService.Partial.cs#L427) add a default batch when working with Transactions, but if that transaction is posted over REST or added via SQL it's not required.

This would need a migration and a new FinancialBatch (`Missing Batch Transactions` or similar) to associate with existing FinancialTransactions.

**Comment by dcs619** [comment]
For development reference, the [FinancialBatchService](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Model/FinancialBatchService.Partial.cs#L41) has an array of Get() methods that will return a new or existing batch based on the name/date/type.

**Comment by mikejed** [comment]
I'm going to tag this "confirmed" because we've long had this issue with random dumps from SecureGive (see http://shouldertheboulder.com/Article?id=559 ). I can tell you a fix would be very nice- Rock is REALLY not designed to handle transactions without them being in a batch.

It needs to be considered, however, what happens when API users attempt to create Financial Transactions without a batch (which has historically worked). I don't know if they will gracefully handle a new error being thrown or not, and it would cause issues in the community if those imports just silently failed. Perhaps a quick survey of the financial plugins would be in order, and a note sent to the providers informing them that Batches will be required, also alerting them as to what error to expect if a batch is not provided... ?

**Comment by dcs619** [comment]
Closing, won't fix
