### ISSUE TITLE
"Group and Role" Workflow Attribute Type Not Editable

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#1687]
Having created a trigger to create a particular workflow type, I created a workflow attribute and ran the "Set attribute from Entity" action as the only action in the workflow to see what is passed when the workflow is triggered from a "Group Member Workflow". Since Group Role didn't appear to capture the data (though if I print the GUID stored in the attribute and search for that, I do find it in the [GroupRole] table), I changed the attribute to type "Group And Role".

Immediately upon saving the workflow type, the existing workflows disappear from the list of that workflow type.

Upon editing the workflow again and clicking the "Edit" button on the attribute, the following exception is thrown:

```
Error
The given key was not present in the dictionary.
   at Rock.Field.Types.GroupAndRoleFieldType.EditControl(Dictionary`2 configurationValues, String id)
   at Rock.Web.UI.Controls.AttributeEditor.CreateFieldTypeDetailControls(Nullable`1 fieldTypeId, Boolean recreate)
   at Rock.Web.UI.Controls.AttributeEditor.set_FieldTypeId(Nullable`1 value)
   at Rock.Web.UI.Controls.AttributeEditor.SetAttributeProperties(Attribute attribute, Type objectType)
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.ShowAttributeEdit(Guid attributeGuid)
   at RockWeb.Blocks.WorkFlow.WorkflowTypeDetail.gAttributes_Edit(Object sender, RowEventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by ccofnow** [comment]
Reproduction:
http://rock.rocksolidchurchdemo.com/page/136?workflowTypeId=2016
1) Created a new workflow type with a single "Set attribute from Entity" action, single attribute. In this case, a person attribute to start
2) Allowed the workflow type to be launched from a person profile
3) Launched the workflow from a person profile
4) Verified the person showed up in the workflow grid
5) Edited the workflow attribute to be of type "Group"
6) Verified the workflow grid showed the person alias GUID instead of the person name (since the GUID does not represent a valid group)
7) Edited the workflow attribute to be of type "Group and role"
*8) Note that the workflow grid is now empty
9) Attempt to edit the workflow attribute, get the above-listed exception*

Seems very likely to be an issue with switching to what I presume is a multi-value type attribute (group and role) when a single-value attribute is already stored therein, since it handles switching from other attribute types just fine (person to group, for instance).

**Comment by arranf** [comment]
I suspect this is because the value for group and role attribute is two GUIDs delimited by a | character.

**Comment by ccofnow** [comment]
I quite agree. and it's an edge case to be sure. But the UX was difficult enough (the only fix is to delete the attribute, create a new one and link it back in wherever it may have been used) that it seemed some error checking and idiot-proofing (referring to myself) may be desirable. I've learned much on workflows in the past 30 days so I know how to do this now, but everyone has to start somewhere ;) Wanted to at least make it known
