### ISSUE TITLE
User Entry Forms Can be Submitted Without Required Workflow Attributes

### ISSUE THREAD

**Issue by Kronos11** [SparkDevNetwork/Rock#1705]
# Context

When testing a workflow on our local Rock site.
I created a workflow that had a user entry form with various required fields. We found people were not putting values into the Address Field and the workflow wasn't completing properly. The Address attribute is required as both an attribute and as a field in the user entry.
# Expected Behaviour

I expected a prompt to be given to the user to fill out the required fields.
# Actual Behaviour

The user entry form submits just fine.
# Steps to Reproduce

http://rock.rocksolidchurchdemo.com/WorkflowEntry/2016
1. Do not fill out any details
2. Click Submit
# Environment and Diagnostics Information
- **Rock Version**:Rock McKinley 5.0
- **Client Culture Setting**:en-US

**Comment by cabal95** [comment]
It appears a number of ICompositeControls, such as AddressControl and GroupAndRolePicker (among others) never set the ValidationGroup of the RequiredFieldValidator. Meaning this issue is not limited to just Workflows. I verified the two above mentioned controls do not enforce validation when used as a Person Attribute either.
