### ISSUE TITLE
Group Participation Report Field Type not updating Group Role Types to roles within the specified data view.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1707]
# Context and Steps to Reproduce

When setting up a report and using the Group Participation Field Type I select Output Format to Group List: Name and Role. Participates in Groups is set to a data view that looks up all groups under the Connect Group Group Type (Small Group renamed). The issue is, Group Type Role does not update to include all Roles under that Group Type it just has Leader and Member. We have a Host role in this Group Type but it does not appear. Is it just looking at whether the role is marked Is Leader or is not leader? Or should it list all roles for the group type(s) it pull through the data view?
# Expected Behaviour

I expected it to display all group member roles within the group type.
# Actual Behaviour

Just listed Leader and Member
# Environment and Diagnostics Information

v5.1

**Comment by ccofnow** [comment]
I don't believe this is a bug. But it is very likely that it's going to turn into an enhancement request, I believe. It is rather confusing.

Creating a report of "Person"s, there is an option to add a field of type "Group Participation" [example here](http://rock.rocksolidchurchdemo.com/page/149?ReportId=1003)

The filters for that field offer to filter for people "with Group Role Type" which is easily misread "with Group Role".

So yes, it is offering to filter for "Leader" role **_types_** (which is different than a singular role which may be called "Leader"), versus non-leader roles (which it is calling "members" and of which the Small Group group type has one default role, called "Attendee").

It may be less confusing to re-label the options "Leader roles" and "Non-leader roles", but it would be IDEAL to instead provide what is expected here- an actual list of roles available in the group type definitions of any groups listed in the selected Group type DataView. Which is **_extremely_** non-trivial, from a coding standpoint, but much more consistent to the user, since the resulting report actually does list the singular ROLE (not role type) that the person holds in the identified group.

<img width="636" alt="group participation" src="https://cloud.githubusercontent.com/assets/6932047/18377416/db298718-761b-11e6-9730-a04a04a15317.PNG>
<img width="314" alt="group participation report" src="https://cloud.githubusercontent.com/assets/6932047/18378105/c6dae3fc-761f-11e6-80e1-a51263f5a4fd.PNG">
G">

**Comment by edmistj** [comment]
Thanks for the scteenshots. Super helpful!

**Comment by arranf** [comment]
I agree with @mikejed this is naming issue as well as an enhancement request. I'll tackle the naming side of things.

**Comment by arranf** [comment]
Looking at this a bit more closely I'm not sure that it'd make sense to have the actual Group Role as part of this select as well as the Leader/Member designation. You're likely to want to filter by Leader/Member **or** by a multi-select of roles.

**Comment by arranf** [comment]
Closing this as the initial issue has been tackled.
