### ISSUE TITLE
[EN] Include Adult/Child Family Role in People Merge

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1788]
### Prerequisites
* [x] Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and client culture setting?
* [x] Have you attached your [environment and diagnostics information ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) to this issue?
* [x] Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?
### Description

Our church has hundreds of families with generational suffixes that we don't know about (Jr / Sr / I / II etc) (See #984). For these families, it's very important that the Adult/Child status shows in the people merge screen so that our staff doesn't merge family members that are different people.

### Steps to Reproduce
1. Select two people with a Adult status and a Child status
1. Open Merge People

![screenshot 2016-10-06 15 23 29](https://cloud.githubusercontent.com/assets/374209/19172856/efbafdd8-8bd8-11e6-9d38-37afe828fdb0.png)

**Expected behavior:** Show the Adult/Child status in the merge view so the "winning" child status can be chosen.

**Actual behavior:** Adult/Child status is not shown, and it's unclear which status wins if they are merged.

### Versions
* **Rock Version:** 5.3
* **Client Culture Setting** en-US
  [Included from your Rock installation ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information)

**Comment by nairdo** [comment]
Hmm... A person doesn't have a "role" (adult/child) outside of their membership in their families... and since a person can belong to multiple families, the role would probably have to be shown in the family members section or perhaps something similar to this mock-up:
![image](https://cloud.githubusercontent.com/assets/383807/20734194/1343ebce-b655-11e6-9fa7-4dcb8ad27676.png)

**Comment by garrettjohnson** [comment]
In terms of usability, if the value is different I think it might make sense to place it on the grid beneath the header, even if it isn't a value cannot be selected for change.

![screenshot 2016-11-29 17 17 11](https://cloud.githubusercontent.com/assets/374209/20735854/b0a8ce64-b657-11e6-81e3-3d1bc7cf3510.png)

The family role row would match the behavior of other person attributes and hide itself if the values were identical. In the case of multiple families with different statuses, maybe something like this could work?
```
Miller Family - Adult
Jones Family - Child
```

It might be worthwhile to think about how to display the name of the person you're merging when it is the same first and last name. (Since it's touching the same code) Our data volunteers have had to stay very cognizant of who they selected on the previous screen, especially in the case of fully duplicated families.

**Comment by edmistj** [comment]
I like Garrett's latest screenshot on this.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
