### ISSUE TITLE
Group Attendance Shows 100% Attended for Kiosk attendance

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#1793]
When checking into a Group that has membership required - the Group Attendance will always show 100% until you go into the group - click Edit on the Attendance item and then hit save. It then calculates the percentage attended correctly. 

### Steps to Reproduce
1. Set up a group for check-in as membership required. 
1. Add 4 members to the group. 
1. Check 3 of the group members in. It will show 100% attended.
1. Click edit on attendance with in the group- then click save. It will now show 75% attended. 

Here is a video of doing this:
[http://www.screencast.com/t/54wrm8BADOtO](http://www.screencast.com/t/54wrm8BADOtO)

* group with four people: ![<a href="https://user-images.githubusercontent.com/383807/72925958-cdd0b680-3d10-11ea-9ced-75a8f7a538da.png">https://user-images.githubusercontent.com/383807/72925958-cdd0b680-3d10-11ea-9ced-75a8f7a538da.png</a> image]()
* Add one attendance record via check-in or workflow action, etc.  Group attendance says 100%: ![<a href="https://user-images.githubusercontent.com/383807/72926175-33bd3e00-3d11-11ea-9109-8915c52576ef.png">https://user-images.githubusercontent.com/383807/72926175-33bd3e00-3d11-11ea-9109-8915c52576ef.png</a> image]()

* edit group attendance record and press save (change nothing): ![<a href="https://user-images.githubusercontent.com/383807/72926122-1ab48d00-3d11-11ea-99ed-9e2572352681.png">https://user-images.githubusercontent.com/383807/72926122-1ab48d00-3d11-11ea-99ed-9e2572352681.png</a> image]()
* Percent changes to 25% because now four records exist: ![<a href="https://user-images.githubusercontent.com/383807/72926179-3750c500-3d11-11ea-9ce7-873e2e56bb5b.png">https://user-images.githubusercontent.com/383807/72926179-3750c500-3d11-11ea-9ce7-873e2e56bb5b.png</a> image]()

**Expected behavior:** [What you expected to happen]

Percent attended would be correct when using Kiosk check-in. 

**Actual behavior:** [What actually happened]

Percent attended is incorrect. Always shows 100%

### Versions
* **Rock Version:** 5.4
* **Client Culture Setting** en-us

**Comment by dcs619** [comment]
We've seen this behavior too, but I think it's by design or by limitation of check-in attendance and group rosters.  

When you check someone in, you create a single attendance record in the system with `DidAttend = 1`.

When you post attendance within a group, it creates attendance records for *everyone* in the group with some as `DidAttend = 1` and some as `DidAttend = 0`.  That creates a snapshot of both the current group roster and their attendance for the selected datetime.

In order to get intended functionality, you'd either have to 
1) add/update attendance records for everyone in a group when one of its members checks in ( 👎 ), or 
2) change the calculation for Group Attendance to 
`# members attended for selected date / # members on roster with DateAdded < selected date`.  This option doesn't give you an accurate snapshot when members have been removed though.

**Comment by cabal95** [comment]
What about a Job that is configured with the GroupTypes to "fix attendance percentages" for that creates the `DidAttend = 0` records? It wouldn't be instant but could be setup to run nightly at 2am or something. Possibly a configuration option as well to tell it how many days back to check and fix.

**Comment by TheCoreyHall** [comment]
Any update on this? Im inserting attendance with the Group Member Attendance Add workflow action, and until I go in, edit, and save, it reports attendance for the group at 100%.

**Comment by nairdo** [comment]
Hi Austin @austinspooner  & Corey @TheCoreyHall We're planning on changing that column.  It will no longer be based on the number of attendance records in the table, but instead based on number of members in the group (it will therefore only have relevance on groups with members.)

The column will be renamed "Percent Members Attended" and have a tooltip stating: _this is the percent of active members that were marked "Did Attend"._

**Comment by nairdo** [comment]
I have some unfortunate news to report.  We've re-examined this solution and the issue that it is causing and we've decided that we're going to revert this back to the original behavior for v10.3 until we can design a more complete solution.
