### ISSUE TITLE
Date Range Person Attributes not accessible in Data Views for reporting.

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1857]
### Description
When a data view applies to Person and the filter type is Person Field, attributes that are set as **Date Range types do not appear in the Person Attribute list**. This makes it unable to run reports based off of attributes that use the Date Range field type. Not sure if this is by design or not.

### Steps to Reproduce
1. Create Person Attribute with Date Range Field Type.
1. Save.
1. Create new Data View. 
1. Set Applies To: Person. 
1. Filter Type is Person Fields. 
1. Search for the Date Range Person Attribute you created, you won't see it listed in the Person Attribute list.

**Expected behavior:**
Display all attributes of all field types.

**Actual behavior:**
Date Range Attributes aren't listed. Not sure what other field types may be missing as well.

### Versions
v5.3

* **Rock Version:** v5.3-v9

**Comment by dcs619** [comment]
The issue here is with the [DateRangeFieldType](https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Field/Types/DateRangeFieldType.cs#L162) not having a filter control, so it doesn't get added to the list of Attributes you can report on.  I'm working on adding a filter now.  

@mikepetersonccv any particular scenarios you can think of where adding a Date Range filter might break something?

**Comment by chrisfunk** [comment]
@nairdo  and @edmistj can the priority of this please be re-evaluated by the core team. The DateRangeFieldType is used heavily in Fundraising Groups and it detrimental to not be able to filter fundraising opportunities by the Opportunity Date  or DateRange person attributes as @BEGamache  has reported.

**Comment by edmistj** [comment]
@dcs619 This issue is currently assigned to you. Do you have a PR coming or should we re-assign this?

**Comment by dcs619** [comment]
@edmistj I worked on it for a bit but never found a solution I was comfortable with.  The DateRange fieldtype needs to render dynamic controls in the UI as well as define business logic to apply each filter for two dates... what does `DateRange Greater Than DateRange` look like?  are the begin dates inclusive/exclusive?  Should we disable any of those options for the DateRange fieldtype?

If you can clarify those questions I can keep working on it, otherwise reassign it.

**Comment by edmistj** [comment]
@dcs619 Yeah I see the complexity of this. It would be nice to have some use cases to consider, but since none were provided I would think it should be something like:

[Attribute Name]      [comparison options]       [sliding date range control]

_Note: the sliding date range control is normally returns a single date, but it could also be a date range._

Where the comparison options are:
- Covers (the filtered date/date range full falls between the source date range)
- Intersects (the filtered date/date range falls between the source date range)
- Does Not Interest (the filtered date/date range does not touch the source date range)

Does that make sense?

**Comment by arranf** [comment]
@dcs619 Am I okay to unassign you from this?

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
