### ISSUE TITLE
[EN] Show person inactivation note in timeline

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1944]
### Description
ENHANCEMENT. When a person is deactivated, add a note to the person's timeline, similar to what happens with an event registration. Currently viewing the deactivated note is only possible through editing the person.

### Versions
* **Rock Version:** 5.1-6.1
* **Client Culture Setting** en-US

**Comment by JimMichael** [comment]
Pretty sure you could do that today with a Workflow trigger that looks for a change on RecordStatusValueID or similar.

**Comment by garrettjohnson** [comment]
Fixed via #2289 and Workflows

**Comment by azturner** [comment]
@garrettjohnson , we actually like the idea of the inactive reason being written as a person history note in the timeline which I don't think the fix you mention added. So re-opening this.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
