### ISSUE TITLE
[EN] Transaction Entry block Enhancement

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#1948]
### Prerequisites

* [ ] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

For the Transaction Entry block, would it be possible to have a block attribute for which card types the organization accepts? We don't take Amex but the logo appears on the Transaction Entry block; when it is displayed donors or registrants think we accept it. I have removed the logo but it is only a temp fix until the next update. I'm thinking a block attribute would be better.

### Versions v6.1

* **Rock Version:** [Enter Rock version here]  
* **Client Culture Setting** [Enter Client Culture here]

**Comment by nairdo** [comment]
@BEGamache I'm assuming your solution is hiding the logo via CSS and you're stating that it's only a "temp fix until the next update" because your CSS will be overwritten?  If this is the case, put your change into the CSS Overrides of the theme and they should not be overwritten on update.  http://www.rockrms.com/Rock/BookContent/14/100#themestyler

![image](https://cloud.githubusercontent.com/assets/383807/21659878/e26f36ba-d289-11e6-9d06-60f5384a990c.png)

**Comment by BEGamache** [comment]
I actually went in and removed the list element from the block's file. I didn't think of overriding it using CSS and that would be a better solution.

**Comment by dcs619** [comment]
You'd have a couple options when using CSS to keep it from being overwritten: either include it in your theme, add it to External Site > Site Detail > Advanced Settings, or add it to the Give block PreHtml:

`<link type="text/css" rel="stylesheet" href="/Plugins/org_crossroadschristian/givingoverride.css">`

**Comment by nairdo** [comment]
Excellent.  I'm going to close this issue to focus on the more urgent ones.
