### ISSUE TITLE
Triggered Workflow fails with Person Property Update Action

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#1953]
### Prerequisites

* [x] Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
* [x] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When setting a workflow trigger with a "Person Property Update" that updates a defined value Rock cannot save without adding a delay to the workflow.

### Steps to Reproduce

1. Create a workflow trigger for Person with a trigger type of Immediate Post Save
2. Set a workflow action with a Person Property Update that updates a defined value
3. Edit and save a person

**Expected behavior:** 

Person property is updated.

**Actual behavior:** 

Error is thrown on save, and workflow is never actually triggered.
![screenshot 2017-01-03 09 20 08](https://cloud.githubusercontent.com/assets/374209/21619104/1d93329c-d1a3-11e6-98dd-76faa3510933.png)

### Versions

* **Rock Version:** 6.1
* **Client Culture Setting** en-US

**Comment by nairdo** [comment]
Unfortunately, it's not possible to trigger (successfully) a pre-save or immediate-post-save workflow that updates properties of the person that's being _currently_ saved.  For now, I just documented the related situation's cautionary note over in the Workflow guide here: http://www.rockrms.com/Rock/BookContent/12/99#launchingworkflows

In your case, you'll need to use the Post-Save trigger or a delay in the workflow so that the save attempt is not being made while the original save transaction (lock) is happening.
