### ISSUE TITLE
Enhancement: Allow Selection of Valid Credit Card Types

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#2076]
This is an enhancement request. 

We would like to be able to specify what credit card types we accept for Giving as well as Event Registration. 

Currently we had to modify the code inside the RegistrationEntry.ascx file to remove the <li> for American Express from the <ul class="card-logos list-unstyled"> section. 

We also wanted to be able to add a note before the credit card number entry but there was no good way to do that outside of modifying this file as well.

It would be awesome if additional block settings could be added to handle this. Here is how we modified the file:

![image](https://cloud.githubusercontent.com/assets/657005/24102871/5005e1f0-0d4b-11e7-9638-4c4ad5f050b4.png)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
