### ISSUE TITLE
Metrics not displaying LastValue but showing CumulativeValue when using SQL to create metric

### ISSUE THREAD

**Issue by MisterOptimist** [SparkDevNetwork/Rock#2083]
### Prerequisites
*  Put an X between the brackets on this line if you have done all of the following:
  []  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
   [x] * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
   [x] * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using SQL to track attendance for children's check-in on a weekly basis, I'm experiencing issues when trying to display this information through the "Liquid Dashboard Widget". It pulls in the Cumulative value of the metric but is NULL when it comes to the "LastValue".

<img width="421" alt="screen shot 2017-03-22 at 9 05 33 am" src="https://cloud.githubusercontent.com/assets/3005311/24201808/275eaa30-0edf-11e7-960c-7fdd3c7dfe1d.png">
<img width="474" alt="screen shot 2017-03-22 at 9 05 28 am" src="https://cloud.githubusercontent.com/assets/3005311/24201806/275b9570-0edf-11e7-9d0c-9d6c61afb6f0.png">
<img width="1007" alt="screen shot 2017-03-22 at 9 09 48 am" src="https://cloud.githubusercontent.com/assets/3005311/24201873/672de572-0edf-11e7-947d-7099c1f487cc.png">

### Steps to Reproduce

1. Must have Children check-in data from previous week.
2. Create a new metric and choose the "Source Type" as SQL. Enter in the SQL we're using to select the Group IDs of our children's check-in groups. We setup the Sechedule to run on Monday mornings. 
<img width="999" alt="screen shot 2017-03-22 at 9 00 25 am" src="https://cloud.githubusercontent.com/assets/3005311/24201807/275ca000-0edf-11e7-93fb-9856f17bb6a5.png">
3. On the dashboard page, add the "Liquid Dashboard Widget" block.
4. Select the metric you just made.

**Expected behavior:** 

We should see last week's value display with the Cumulative number under it. 

**Actual behavior:** 

What we're actually getting is no value displaying for the last week and only seeing the cumulative. Using Lava Debug Info, we see that there is no value in "LastValue" which is the problem.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by cabal95** [comment]
It looks like this is caused when your Schedule has a time other than midnight. A temporary fix would be to change the schedule for midnight, if that is possible.

Dev information:

For example if the Schedule is set to run every day at 2:15am then the Job sets the MetricValueDateTime to '??/??/?? 2:15am'. When the code in MetricsController runs to populate the LastValue (line 95), it takes just the Date portion of the MetricValueDateTime and stuffs that into LastValueDate. Then it uses LastValueDate (which has midnight instead of 2:15am) to load the metric values matching that date - but since there is no time portion it finds no matches.
