### ISSUE TITLE
Giving page allows blank credit card information

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2084]
### Description
The give now page does not validate the existence of any credit card information. So, blank credit card and check information is sent to the payment gateway without generating an error.

### Steps to Reproduce
1. Go to a give now page
1. Enter no details on the payment information page.
1. Click Finish on the confirm information page

**Expected behavior:**

Rock generates an error on the payment information page, requiring all credit card fields to be filled out before advancing to the next page.

**Actual behavior:**

Rock does not validate the credit card information, instead relying on errors generated by the payment gateway. NMI generates a "Required Field check_name is Missing or Empty" error that is displayed.

### Versions
* **Rock Version:** 1.6.2
* **Client Culture Setting** en-US

**Comment by garrettjohnson** [comment]
**Proposal:** 
1. Include the `required` CSS class on all credit card form-groups to show the fields as required.
2. Use Stripe's [jquery.payment](https://github.com/stripe/jquery.payment) plugin to do client side validation of the credit card, as well as the bank account. Since the NMI gateway is bypassing posting to Rock the solution has to be mostly client side. The plugin would replace the jquery.creditcardtypedetector script Rock currently uses as it can return the card type.
3. Create user friendly errors for the NMI gateway

**Comment by gladsonj** [comment]
@garrettjohnson I tested this in the Rock Demo Site. It seems to be working fine. Screenshot attached. Did I test it wrong?

![image](https://cloud.githubusercontent.com/assets/21976051/24298467/779ebfa0-107c-11e7-8d5c-329b90d4bcde.png)

**Comment by garrettjohnson** [comment]
@gladsonj On the demo site it's using a non-NMI gateway. With NMI all the built-in checks for payment are bypassed because that information goes to the [NMI iframe](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L3108)

**Comment by garrettjohnson** [comment]
Duplicate/Related to #1700. Where validation is not firing for missing transaction amount

**Comment by arranf** [comment]
@garrettjohnson  Looking at #2337 and #2531 can this now be closed as fixed?

**Comment by kmeister2000** [comment]
Howdy! I was tracking down why a custom gateway plugin we wrote for a client using Rock stopped working after they upgraded from Rock 10 to 11.

The issue was that the 'next' button on page 2 of the TransactionEntry form was no longer doing anything. They would enter in their payment info and click next and never move to the next screen.

I think I tracked it down to @MikeDPeterson 's commit on 3/11 with the removal of [this handler](https://github.com/SparkDevNetwork/Rock/commit/542e175d2861da09f805317032ddf809330e5009#diff-f183d1b2c32d2802064a87586ab5dc60351c8692edddcb015c4ce506ae22aba6L3237)

Some of the changes in this commit for this block seem [very specific to supporting the NMI gateway](https://github.com/SparkDevNetwork/Rock/commit/542e175d2861da09f805317032ddf809330e5009#diff-f183d1b2c32d2802064a87586ab5dc60351c8692edddcb015c4ce506ae22aba6R3249).

What is the path forward for those of us who rely on the previous behavior?  Is there a new way for facilitating the same behavior or is the only path forward to develop our own custom block for transaction entry?

**Comment by jonedmiston** [comment]
Hi @kmeister2000 there as been some movement in that code in 2020. I believe additional changes were made in later code to get that working again for you. Have you tested this in the latest version?  

On the topic of testing, I would recommend that you are testing your integration during each alpha release. If you find these issues during alpha testing we can address them before your customers run into them. Since this is a plugin we aren't able to test this in our normal process.

**Comment by kmeister2000** [comment]
Are the alpha releases the 'dev' branch or do you tag them explicitly?

**Comment by jonedmiston** [comment]
Pre-alpha is the develop branch. Releases each have their own branches and are tagged.
