### ISSUE TITLE
Deleting a Group Member Causes Group Attributes to Disappear

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2107]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

On the group detail page if you delete a group member the postback causes the attributes of the group to no longer display,

### Steps to Reproduce

1. Goto: http://rock.rocksolidchurchdemo.com/page/113?GroupId=3189&ExpandedIds=3087%2C40
2. Delete a group member
3. Notice that the Topic attribute disappears.

**Expected behavior:** 

It would stay

**Actual behavior:** 

It does not stay

### Versions

* **Rock Version:** [v6.2]  
* **Client Culture Setting** [na]

**Comment by trevor-tart** [comment]
So after reviewing this for quite some time, I wanted to post some findings/options to see if anyone had some suggestions on this issue. 

The Problem:
  When a user is deleted from the grid, the GroupAttributes and Location Map (if shown), will disappear from the GroupDetails. This is because the data for those controls isn't loaded OnPageLoad when it's a postback (only on !Page.IsPostBack). It works fine when adding a user because this actually navigates to a linked page then comes back, running a full page lifecycle again and thus loading all the data. However, when delete is clicked, the GroupMemeberList control just deletes the row and rebinds the grid, but no page redirection happens so those values aren't populated.
  
Possible Solutions:
1. Add a call to ShowReadOnlyDetails (or the like) OnPageLoad regardless of PostBack. Obviously, this would run numerous times when not needed. I also think this could lead to duplicate information in the details sections. So perhaps this isn't really any option, just something considered and dismissed.
2. Add a NavigateToCurrentPage call in the GroupMembersList delete function, but it seems like that's poor functionality given this control could be used numerous places.
3. Potentially interrogate Request.Form["__EVENTTARGET"] && Page.IsPostBack in the OnPageLoad because it contains GroupMembers when firing for a different user control....also feels sloppy.
 
 Question:
- When there are multiple user controls on the page, is there a better way to determine if the control that is "Loading" is the one that fired the event on the page, or if a different control has caused the postback?

Thoughts??

**Comment by azturner** [comment]
@trevor-tart , Ideally all dynamic controls should be created first during the pageload event (when not a postback), but then always recreated during a postback in the LoadViewState event (before form values are reapplied to edit controls). Something like this: https://gist.github.com/azturner/1febe819ad5dee3b931fa0b2c882f146/revisions?diff=split

**Comment by cabal95** [comment]
This has been previously fixed in v8, bug no longer present when deleting a group member.
