### ISSUE TITLE
[EN] Add Duplicate Email Post-Filter Transform

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2116]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When using Data Views there's currently no way to exclude duplicate email addresses, meaning that if a husband and wife share an email address in a given data view, they're going to receive the message twice. Adding a transform to remove duplicate emails, and only allow one person record per email is needed for all church emails, etc..

### Steps to Reproduce
1. Create a couple with the same email address and have them visible in a data view
1. Click the communicate bubble and compose an email

**Expected behavior:**

One email is sent per email address.

**Actual behavior:**

An email is sent for every person in a view using the same email address.

### Versions
* **Rock Version:** 6.2
* **Client Culture Setting** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
