### ISSUE TITLE
Merge Codes reset when replacing Check-in Label File

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2136]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When uploading a new file to an existing Check-in Label the Merge Code fields get reset to all be `Security Code` (see screenshot). Bloody annoying when you have a bunch of merge codes to reset while trying over and over again to get your label correct. :)

<img width="1004" alt="screen shot 2017-04-06 at 4 45 56 pm" src="https://cloud.githubusercontent.com/assets/1119863/24779964/b01728ba-1ae8-11e7-8a27-f06801ed252d.png">

### Steps to Reproduce

1. Edit existing check-in label.
2. Download label file.
3. Upload file you just downloaded to replace the label.
4. Cry when you have to reset the drop downs by hand.

**Expected behavior:** 

Existing data selections should not be lost.

**Actual behavior:** 

Existing merge code selections are indeed lost. Weeping and Gnashing of Teeth ensue.

### Versions

* **Rock Version:** 6.2
* **Client Culture Setting:** en-US

**Comment by mikejed** [comment]
Confirmed on my own installation just now, but from experience I have lamented this since v1. Programmatically when a label is uploaded it must be re-scanned for merge fields, and understandably fields may have been added or removed (or even renamed), so it's presumably quite a trick to re-match the "old" settings with the "new" fields. But if it can be fixed, it would be very nice. It might qualify this for an "enhancement" tag instead of "bug", but I'll leave it for now since to an end user it would look very much like a bug. Devs feel free to swap the tags if appropriate
