### ISSUE TITLE
Azure Install has Unterminated String error on Public Home Page

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#2155]
### Prerequisites
* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Fresh install of Rock on Azure (Windows 2016 and Azure SQL) and open Public Home Page.

**Expected behavior:** 

Sample rotator and ads display.

**Actual behavior:** 

![image](https://cloud.githubusercontent.com/assets/3513589/25094135/beb88552-2363-11e7-8226-aac5fe7cb7a3.png)

`Unterminated string. Expected delimiter: ". Path '[1]', line 5, position 1.`

I am assuming this is related to lava.  I found some lava tags closed as `{% endif -%}`.  Unfortunately, just removing the `-` did not resolve the issue.

Here is the Home rotator Lava.
```
<div id="announcement-rotator" class="carousel slide" data-ride="carousel">
  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    {% for item in Items %}
    {% if forloop.index == 1 -%}
    <div class="item active">
      {% else -%}
      <div class="item">
        {% endif -%}
        <a href="{{ LinkedPages.DetailPage }}?Item={{ item.Id }}">{{ item | Attribute:'Image' }}</a>
      </div>
      {% endfor %}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#announcement-rotator" data-slide="prev">
      <span class="fa fa-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#announcement-rotator" data-slide="next">
      <span class="fa fa-chevron-right"></span>
    </a>

  </div>
```

### Versions

* **Rock Version:** 1.6.2  
* **Client Culture Setting** en-US

**Comment by edmistj** [comment]
I believe this is a known issue with Azure that goes away after a reload. @nairdo  can you confirm that. 

A trailing - is accurate syntax in lava.

**Comment by gladsonj** [comment]
Just Edit the Block and Save. This Issue will be fixed.

**Comment by treyhendon** [comment]
Great to know that the `-` is not going to cause an issue @edmistj !  You're right @gladsonj  opening the block properties and saving did fix it.  I'd still class that a bug of some kind for the Azure install category. Thanks!

**Comment by gladsonj** [comment]
@treyhendon it's not specific to Azure. This is common in any hosting, if you use the latest Install File.

**Comment by cabal95** [comment]
The core problem in this issue is that the JSON generated in the database is invalid. It apparently started generating invalid JSON with the new installer, but I am not sure why. It is the JSON that is stored as the filter data for the block. When displaying there is no `catch` in place so it errors. When editing there is a `catch` in place which "throws away" the filter value and starts fresh. Thus editing and saving "fixes" the problem by erasing the invalid JSON filter data.

This has been reported in Slack on various installations, including self-hosted.

**Comment by azturner** [comment]
This is an issue with the default data in the DataViewFilter table. It looks like some values got truncated during the creation of the default data script when the install was packaged (see the two "SecondaryAudiences" values in screenshot):

![image](https://cloud.githubusercontent.com/assets/548180/26324919/ae0fd4d4-3ee9-11e7-8f1b-e6e7f14b9a91.png)

They can be fixed with these sql statements:
```
update DataViewFilter
set selection = '[
	"SecondaryAudiences",
	"8",
	"b364cdee-f000-4965-ae67-0c80dda365dc"
]' 
where selection = '[
	"SecondaryAudiences",
	"8",
	"4cdee-f000-4965-ae67-0c80dda365dc\"\"
]'
 
update DataViewFilter
set selection = '[
	"SecondaryAudiences",
	"8",
	"57b2a23f-3b0c-43a8-9f45-332120dcd0ee"
]' 
where selection = '[
	"SecondaryAudiences",
	"8",
	"2a23f-3b0c-43a8-9f45-332120dcd0ee\"\",
]'
```

**Comment by azturner** [comment]
The installer has been updated to fix this issue.
