### ISSUE TITLE
Global Attributes Cannot Access Person Properties and Attributes

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2162]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

In 6.3 Global Attributes can no longer access person properties and attributes. 

### Steps to Reproduce

1. Create a global attribute containing `{{ Person.NickName }}`
2. Place the global attribute in any lava block or communication

**Expected behavior:** 

Render the person's nickname. (Behavior found in 6.2 and prior)

**Actual behavior:** 

Nothing is rendered.

### Versions

* **Rock Version:** 6.3 Beta
* **Client Culture Setting** en-US

**Comment by cabal95** [comment]
This doesn't appear to be a regression, it appears to be a "never worked in the first place". Verified the same issue in 6.2 and the code hasn't been changed since it was first introduced 2 years ago. The issue seems to be here:
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Lava/RockFilters.cs#L1520

The render of global attribute values containing Lava does not get passed any variables. Not sure the best way to go about this. I guess walk all the Environments and all the Scopes of the context and build a list of "current variables"?

**Comment by azturner** [comment]
@cabal95 Using something like {{ Person.NickName }} in a global attribute would be something specific to communications. When sending a communication, Rock should be loading the current recipient as a "Person" merge field for the communication to use (including any global attributes).  Did you happen to try that scenario?  This wouldn't (and as far as I know never did) work outside of a communication.

**Comment by cabal95** [comment]
@azturner I didn't try specifically using `Person.NickName` from a communication, since I was testing with an HTML block. I tried with `{{ CurrentPerson.NickName }}` in both the global attribute and the HTML block (to verify that it showed in one but not the other).  I made an edit after posting my comment showing the exact test I did which probably don't show up on your notification stream.
