### ISSUE TITLE
User Preferences cache not cleared with "Clear Cache"

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2206]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The core issue is that I had two browsers open logged into the same rock site and looking at the same page. The user preferences were out of sync. Which seemed odd to me. Looking in the database I confirmed there was only one row of preferences for that block. I decided to delete the row and to my surprise nothing changed in the UI, the same preferences were in place. I then emptied the Rock cache and the preferences were still in place.

Finally I dived into the code and realized that the preferences are cached in the Session data rather than the standard rock cache. I don't like that preferences can get out of sync, but it's more confusing to me that I can't use the Clear Cache button to try and fix the problem for the end-user.

### Steps to Reproduce
1. Open browser in Firefox and go to a page that supports filtering.
1. Set your filters
1. Open another browser in Chrome and go to the same page.
1. Set different filters.
1. Go back to Firefox and refresh page, original filters are in place.
1. Close Firefox and re-open Firefox and go back to the page, the new "Chrome" filters are in place.

**Expected behavior:**

I should be able to clear preference cache when I clear the rest of the rock cache.

**Actual behavior:**

I get very confused.

### Versions
* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by azturner** [comment]
It would be frustrating for user's if their saved preferences were lost anytime someone cleared the cache, which is why we don't cache the preferences in server memory. We also don't want to have to continually read them from database, which is why they are saved to session. Not sure that opening Rock in two different browsers is something that most users do on a regular basis :).

It would be a nice enhancement though if an admin could clear a particular user's preferences. This would be helpful if for some reason a saved preference is causing an exception, and user can't load block to change the setting (i.e. sorting a grid with bad sort expression). That would still require them to restart their browser though to clear the session values.

**Comment by dcs619** [comment]
I wrote a power tools block that cleared preferences per user for the Lava tester, @jbaxleyiii might be able to post screenshots of that and we could make a PR from it.

**Comment by cabal95** [comment]
@azturner Wouldn't it make sense to store the in-memory cache in the standard Rock cache like everything else (with proper expiry time) but on write store them into the database? This would allow the admin to clear cache and have it clear any in-memory cache causing the GetUserPreference() method to pull from the database and re-cache.

Doing it this way would also reduce page load size as, from what I can tell, all user preferences are loaded into the Session data and never expired.

The only thing I can see that would have to be resolved is the ability to store user preferences for non-logged in users. One solution that would be to use the Session.SessionID as a unique key for the RockCache preference data.

I would also be curious about how you cleared session data for another user. For an unrelated project I was trying to do that once and never could figure out how since the session data is stored on the browser and not the server.

**Comment by edmistj** [comment]
@arranf  and I talked and we'd propose adding a button (block) to the top of the `My Settings` page that would clear all preferences for a person. Looking at the data that makes up person preferences there's no trust-worthy pattern to limit removing preferences to a specific page, so it's all or nothing.

![image](https://user-images.githubusercontent.com/548178/41744237-0a4f90cc-7558-11e8-8f90-a0529807ac92.png)

Delete attribute values of attributes of the `Rock.Model.Person.Value` entity type for the specific person.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
