### ISSUE TITLE
Registration linkage group does not update if person changes

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2215]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Using Rock event registrations; If a registrant is changed to a different person record, the record in the linked group is not updated to the new registrant. 

### Steps to Reproduce
1. Create an event with a group linkage
1. Register a person for the event.
1. Open the registrant entry from the registrant tab on the event instance.
1. Edit the registrant, and using the person picker change the registrant to a different person.

**Expected behavior:**

Rock should update the record in the linked group to the new person.

**Actual behavior:**

The original registrant is left in the linked group without being changed or removed.

### Versions
* **Rock Version:** 6.3 
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1112046158262240">image.png</a>

**Comment by cabal95** [comment]
If the old record is completely removed a warning note should probably appear in the UI when changing the registrant just to make it clear to the staffer what exactly is happening. I agree what you suggest would be expected behavior, but it could cause confusion especially if there are custom group member attributes that have been filled out.

![image](https://cloud.githubusercontent.com/assets/1119863/26328418/ca0d5b76-3ef7-11e7-940d-5f2588b6f7a3.png)

**Comment by garrettjohnson** [comment]
@cabal95 I agree, some sort UI is a good call. Maybe a modal confirmation box? 

On a related issue to this one, if a registrant is deleted, the linkage group member is not removed.
