### ISSUE TITLE
CalendarItem.lava file has invalid Lava syntax for displaying Contact Person name

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2249]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The file contains `{% if %}` statements with embedded filters, causing the if statements to not work correctly.

https://github.com/SparkDevNetwork/Rock/blob/master/RockWeb/Themes/Stark/Assets/Lava/CalendarItem.lava#L40

As well as line 43.

### Steps to Reproduce

1. Open file
2. Read code

**Expected behavior:** 

`FullName | Trim` needs to be assigned to a temp variable and used for comparison.

**Actual behavior:** 

Broken `if` statement.

### Versions

* **Rock Version:** 6.3
* **Client Culture Setting:** en-US

**Comment by mikejed** [comment]
This still doesn't fix all the issues - Person.Fullname needs to be changed to Person.FullName

**Comment by azturner** [comment]
@mikejed Where are you seeing Person.Fullname in the updated files (or is there a different file?)

**Comment by mikejed** [comment]
Sorry @azturner I just glanced at the commit and saw the same lines I had tested for https://www.rockrms.com/page/278?Question=1685
...but failed to note they were highlighted in red. It looks like the incorrect capitalization was only in the {% if %} tag, not in what printed.
Interesting that the original If conditions tags appeared to work if I fixed the Person.FullName capitalization. I suppose it was only because all my events do have a contact.
I'm in the process of re-loading Alpha again to make sure the fix works on my site, but I do expect it to now.

**Comment by mikejed** [comment]
Confirmed this fix works. Sorry again for sounding an alarm before doing a thorough test- I know that 6.9 beta is due very quickly so I wanted to get this out based on what I (thought) I saw and then post back with further testing. You're really quick to respond ;-)

**Comment by azturner** [comment]
@mikejed No problem. Thanks for all your help with the alpha and beta testing.
