### ISSUE TITLE
[EN] Refactor AD Authentication

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2325]
### Description

In working with AD authentication I've found numerous issues with either performance dependent on certain ports (389, 636, 3268, and 3269 open on TCP, and 389 and 3268 open on UDP).

Additionally, in order for Rock to run on *nix with Mono or another engine (VS Mac?), the dependency for `PrincipalContext` is unsupported.

I realize performance is primarily a network configuration issue, but in order to kill two birds with one stone I plan on refactoring the AD Auth provider to use LDAP.  Some preliminary research [here](https://stackoverflow.com/a/10938574/1853867) and [here](https://github.com/dotnet/corefx/issues/2089).

**Expected behavior:** 

Fast logins over AD.

**Actual behavior:** 

Slooooooooow logins over AD.

**Comment by edmistj** [comment]
Couple of questions:

1. Is the intent to allow authentication to an LDAP source? If so perhaps this should be a different Auth provider. If you're thinking this would still only be for AD then perhaps a config setting should be added to the Auth provider to allow using LDAP or native AD (perhaps defaulting to LDAP).
2. Can you also research that LDAP is fully enabled and working by default on AD. It looks like it is, but we'd want to make sure that was the case so one does not need to do any config on the AD side.

**Comment by cabal95** [comment]
Having a config setting would mean it still can't be used on Mono since it would not be able to compile, due to the reference to `PrincipalContext` - unless you did a major amount of Reflection to load everything at run-time.  While running under Mono is not a priority, this is one of the two "major" blockers to a clean compile without modifications to Rock.dll. The other, oddly enough, being the Pluralization service not existing in Mono (there are various NuGet alternatives).

I know Mono support is not a core priority - just mentioning it.

**Comment by JimMichael** [comment]
Is this just a documentation issue (currently)? We had the mentioned perf problems but were  always able to solve it by opening up both 389 and 636 between Rock and a D.C.

**Comment by edmistj** [comment]
If going forward please implement as a new provider.

**Comment by dcs619** [comment]
Closing, won't fix
