### ISSUE TITLE
FollowingsHelper.SetFollowing() should be called in OnPreRender

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#2368]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

If one block on the page has a followings helper control and another block on the same page has a postback event that automatically sets the following state, the on-screen control will not reflect this change because it is set in the Load method which happens before any postback events process.

The OnPreRender method is called after the postback events but still allows for changes to controls.

Reference: http://www.c-sharpcorner.com/UploadFile/8911c4/page-life-cycle-with-examples-in-Asp-Net/

Tested with a custom set of controls being developed and moving the `FollowingsHelper.SetFollowing` call to the `OnPreRender` method works as expected.

**Expected behavior:** 

The SetFollowing() method should be called after any postback events have processed, thus allowing it to display the most up-to-date information.

**Actual behavior:** 

Postback event causes the following to be turned on while the UI control still shows not following.

### Versions

* **Rock Version:** Git-2017-07-23
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
Closing as invalid after a chat with @cabal95.

Closing thoughts:
"I think it worked in my case [the solution above] because both controls were within the same UpdatePanel.  It looks like when you have multiple update panels (i.e. 2 Rock blocks), both will render server-side, but only one has it's new content sent (makes sense). So my fix in that report only actually fixes it if the event causing the following state change happens within the same update panel.."
