### ISSUE TITLE
Lava will not pull GroupId if single member family

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#2373]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A person in a family of one does not pull the GroupId via lava. Also if you add a person to a family of one that is inactive the child will not pull the GroupId.

<pre>
{% assign families = Person | Groups: "10",'All' %} 
{% for family in families %}
{{ family.GroupId }}
{% endfor %}
</pre>

### Steps to Reproduce
Single Member of Family
1. Create a new Family with one record.
2. Use the lava provided and nothing will display.

Inactive Record
1. Make a Single Member Family member Inactive
2. Add child to family
3. Use lava provided for child or adult and nothing will display.

**Expected behavior:** 

I expected all person records to pull this Id for the family they are in regardless of the number of members.

**Actual behavior:** 

Members of a family with one person do not display a Group id when using this Lava.
<pre>
{% assign families = Person | Groups: "10",'All' %} 
{% for family in families %}
{{ family.GroupId }}
{% endfor %}
</pre>

### Versions

* **Rock Version:** Rock McKinley 6.8
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
I haven't tested this, but since `family` is a group shouldn't this be `family.Id`?

**Comment by cabal95** [comment]
Since the `Groups` filter actually returns `GroupMember` records, his Lava syntax is correct. It should be `family.GroupId`. I haven't had a chance to replicate the issue yet, just verified that the syntax he gave should (and does on my server) return a group Id number on a normal record.

My hunch, is that somehow a family group is not being created for the person in question.

**Comment by edmistj** [comment]
@cabal95 you're right. Might suggest adjusting the variable names to be:

```
{% assign familyMembers = Person | Groups: "10",'All' %} 
{% for familyMember in familyMembers %}
{{ familyMember .GroupId }}
{% endfor %}
```
Would make readability easier since families are actually groups.

**Comment by cabal95** [comment]
Think I may have found it. The `Groups` filter limits to Groups that are Active. For some reason, Alisha Admin on the demo site's family group is inactive.  @edmistj should Familiy groups ever be IsActive = false?

**Comment by cabal95** [comment]
@randyjreed Run this SQL and see what comes up. This should be a list of all Person records that are themselves not in-active _but_ are members of only Inactive families. We have a single record here at Shepherd that comes up and the Alisha admin record also matches this query.

```
SELECT P.Id,P.FirstName,P.LastName,P.RecordStatusValueId,G.Id AS [GroupId], G.[Name] AS [GroupName],G.IsActive
	FROM [Person] AS P
	LEFT JOIN [GroupMember] AS GM ON GM.PersonId = P.Id
	LEFT JOIN [Group] AS G ON G.Id = GM.GroupId AND G.GroupTypeId = 10
	WHERE G.IsActive = 0 AND P.RecordStatusValueId != 4
	  AND 0 = (SELECT COUNT(*) FROM [GroupMember] AS GM2 LEFT JOIN [Group] AS G2 ON G2.Id = GM2.GroupId WHERE G2.GroupTypeId = 10 AND G2.IsActive = 1 AND GM2.PersonId = P.Id)
```

If it is just a few people that come up, I would pull them up and edit them and save to fix the record. If it is a lot then you might need to do SQL or something to activate all those families.

**Comment by randyjreed** [comment]
@cabal95 The only result is our admin account. Same as the demo site.

**Comment by cabal95** [comment]
The only way I can replicate this is by running the above Lava against a person that is inactive (other than the previously mentioned case where the data is wrong and the person is active but the family is not). When a person is made inactive and they are the only one in their family then the family is also set inactive (which hides it from the `Groups` results). If an active child is moved into the inactive family then the child becomes inactive and `Groups` would also filter out the family since the family is inactive.

The best I could say is perhaps what you need for your use case is a enhancement request on the `Groups` filter that provides a 3rd parameter to specify that inactive groups should be included in the results.

Also, you may want to update your Lava to only pick the first result. If a child is in two families then you would get a really long number as it would display both numbers back to back.
