### ISSUE TITLE
[EN] Make search by name match characters with accents

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2382]
### Description
When searching by name accented characters are not matched by their unaccented counterparts. For example `Rodriguez` does not match `Rodríguez`, `Cafe` does not match `Café`, etc. This causes issues for checkin and search by name.

This [Stack Overflow question ](https://stackoverflow.com/questions/2461522/) might be relevant as well as this: https://stackoverflow.com/questions/7418624/linq-where-ignore-accentuation-and-case

### Steps to Reproduce
1. Create a person with last name of Rodríguez
1. Search by Rodriguez

**Expected behavior:**

Rodríguez to be matched

**Actual behavior:**

No matches

### Versions
* **Rock Version:** 6.8
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
