### ISSUE TITLE
[EN] Family Id as Report Option

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2400]
### Description
It's pretty straight forward.  I think that Rock reports should give you an option to include Family Id's a column so you can dedupe on them in Excel when you're doing mailers or counts.  I feel like I explain the same way to do it 5 times a month, and having a filter that handles the lava for you would make it easier to explain to people.

Currently, I include the Person Id as a column in the report (usually under the name `pid`) then I include a lava column with the Lava `{{ pid | PersonById | Groups:'10','All' | First | Property:'GroupId' }}`

In the case of multiple families, I think it should be the option to take the first one, or all of them (separated by commas).

Bonus points if you could the report option filter families for display by them meeting a DV (if there's more than one family showing up)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
