### ISSUE TITLE
Can't Find Blocks Linked to Context Parameters

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2452]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Playing with a block on the Connection Request editing page, I noticed that the values for the Context Parameters are required.  The values for those parameters were empty before I showed up and if you wanted to save a change to the page (like giving it a route) you would be forced to enter garbage values (or helpful values) in it.

![image](https://user-images.githubusercontent.com/19762670/30251067-76c9aa90-961e-11e7-93af-b00db88bb8b5.png)

### Steps to Reproduce

1. http://prealpha.rockrms.com/page/5352?ConnectionRequestId=1009&ConnectionOpportunityId=1
2. Page Settings -> Advanced Settings -> Check (or uncheck) Force SSL
3. Save

**Expected/Actual behavior:** 

The required fields of the Context Parameters are enforced

**Recommended behavior:** 

The Context Parameter fields should not required, or should have some other way of choosing to not fill them if you don't want to or can't.

### Versions

* **Rock Version:** Rock Version: Rock McKinley 7.0 (1.7.0.39) (prealpha.rockrms.com server)
* **Client Culture Setting:** en-US
Diagnostic file (just in case)
[RockDiagnostics-1DYRXV.txt](https://github.com/SparkDevNetwork/Rock/files/1290710/RockDiagnostics-1DYRXV.txt)

**Comment by cabal95** [comment]
I've run into this too. The problem for me is also the fact that there is (that I can see) no way to know which block(s) is requiring that context. If possible, I think the Help text for each context should include which block(s) are causing that context to show up. Like Chris said, usually this happens when I go to edit an existing page with a number of blocks. The page is already working and I don't really want to set a context and then wonder if suddenly the page is going to break. If I know which block(s) are affected I at least have an idea of specifically what to test once I set a value (garbage or not).

**Comment by edmistj** [comment]
I'm not sure I get this. This behavior means that there are blocks on the page that need this configuration to work. Seems like you should be forced to provide it or go remove the blocks from the page.  Allowing a page to edited when it's known to be mis-configured seems like an issue.

**Comment by NuclearTacos** [comment]
I definitely agree that allowing to save a page in a way that is going to cause issues is no bueno.  The not-so-fun thing was that page I arrived on was misconfigured from the start.  So I was stuck with the issue of poking everywhere to "Fix" something that wasn't causing an issue on the page.

I agree with @cabal95  that adding the Block's name (and region?) to the tooltip if it needs that context parameter would be nice.

@edmistj In the page I linked, I can't find the block asking for the Person context. (there might be a bug there, but I just might be blind)

**Comment by cabal95** [comment]
@NuclearTacos The problem is some blocks have a block configuration option for what entity to use for Context (Like Html Content). Others have it hard coded and show no indication of this on the block settings dialog. These are the most difficult ones to find because, AFAIK, the only way to track them down is to look at the source code for each block on the page.

@edmistj Many blocks that "require" context don't actually require it, they just use it if it's available. If we don't feel good about making those context parameters optional, then I would say at the very least we need to have them somehow indicate which block(s) are calling for them so we can track them down.

Our staff Dashboard page has a block with context on it for Campus. But for the life of me I can't figure out which one it is in order to determine if maybe I'm using the wrong block (I don't want any of the blocks to look at campus context). I ended up putting a bogus query string parameter in.

**Comment by edmistj** [comment]
A PR to list the blocks that need the context (perhaps as the help topic of the parameter) would be great.

**Comment by cabal95** [comment]
I'll take a look at adding this as part of the help text expanded by clicking the `?`.

**Comment by JimMichael** [comment]
Can I get some clarification on this fix? It looks like it does not address anything except listing what blocks "need" context... is that accurate? I've just run into a similar/same issue with the Prayer Request Entry block... I simply put the block on a new page, and it worked fine, but then I went to add a page route and the dialog complains I don't have "Person Parameter Name" context entered... SHOULD I put something there, even though the block doesn't seem to need it? 

![image](https://user-images.githubusercontent.com/3903408/34498573-d90f9626-efc7-11e7-9975-a3184231d5f2.png)

**Comment by edmistj** [comment]
@cabal95 I'll let you respond.

**Comment by cabal95** [comment]
@JimMichael Correct. The "fix" simply identifies which block(s) are stating they need it. That doesn't mean they need it to operate correctly, just that they "want context". Some blocks (like the person details page blocks) have a "hard need" for context and throw an error without it. Other blocks, like this one, use the context if it's available.

In this case, the Prayer Request Entry block doesn't have a _required_ need, just an _optional_ need. But as far as the UI knows for configuring the page it's a "need" and must be filled in. In the code for defining these context uses there isn't any way to specify if it's "optional" or "required" so the UI just assumes it's required.

In this case, let's say you put `personId` in that Person Parameter Name. If you browsed to the page with `?personId=1` then it would hide the FirstName, LastName and Email fields and use the values from Person Id 1. If you don't specify a `?personId=###` (or give it an invalid number) then it will show those fields and let the user type them in instead.

Why this particular block works this way instead of using `CurrentPerson` I'm not sure, but there is probably a reason. I've barely touched the prayer system so I'm not sure if there are pages with links to this block that pass a person Id in.

Hope that helps.
