### ISSUE TITLE
UI Proposal for Workflows

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2455]
### Description
One of the most difficult aspects of configuring workflows is creating an action and finding a field required by the action is empty. When a select control is effectively disabled, it would be helpful if Rock disabled the form input and added help text that included the name of the attribute needed to enable the control.

Proposed disabled text: `Add a "Attribute Name" Attribute` (with quotes) or `Add a Attribute Name Attribute` without quotes or `- Add a "Attribute Name" Attribute -`.

Example UI:
![](https://user-images.githubusercontent.com/374209/30253336-98f87614-9637-11e7-9166-ccc06f77dc36.png)

### Versions
* **Rock Version:** Prealpha
* **Client Culture Setting:** en-US

**Comment by arranf** [comment]
@garrettjohnson I love this. The workflows panels could be made far more efficient and this is a great step in that direction!

**Comment by edmistj** [comment]
Sounds good. Should not be too hard to update the WorkflowAttribute class to do this.

**Comment by arranf** [comment]
I'll take this one.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
