### ISSUE TITLE
{% sql %} Results Don't Work With Some Filters

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2457]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Results of SQL in Lava don't work with Array Filters unlike their identical results from an Entity Command.  I tried to format my Lava in a way that makes it easy-ish to read, and easy to understand the results of.

### Lava I tested
** Tests were run from demo site**
```
{% sql %}
    Select * From Person Where LastName = 'Decker'
{% endsql %}

1 -- {{ results | ToJSON }}<hr>

2 -- {% for person in results %}
    {{ person.FirstName }}
{% endfor %}<hr>

3 -- {{ results | Where:'FirstName','Theodore' | First | Property:'Id' }}<hr>

4 -- {{ results | Select:'FirstName' }}<hr>

{% person where:'LastName == "Decker"'%}
    5 -- {% for person in personItems %}{{ person.FirstName }}{% endfor %}<hr>
    6 -- {{ personItems | Where:'FirstName','Theodore' | First | Property:'Id' }}<hr>
    7 -- {{ personItems | Select:'FirstName' }}
{% endperson %}
```
### Results
![image](https://user-images.githubusercontent.com/19762670/30333943-ca5d7b42-97a3-11e7-919e-33a29095fdd2.png)
1 = JSON results of SQL query
2 =  Iterating over `FirstName`s of results in SQL query
3 = Using `| Where` filter on SQL results to get Ted, then return his Id
4 = Using `| Select` filter on SQL results
Then a similar Entity command is run
5 = Iterating over `FirstName`s of results of Entity Command
6 = Using `| Where` filter on Entity Command results to get Ted, then return his Id
7 = Using `| Select` filter on Entity Command results

**Expected behavior:** 

I'd expect Identical Entity Commands and `{% sql %}` to behave identically.

**Actual behavior:** 

It seems something fishy is going on with the results of `{% sql %}` but I'm not a C# aficionado yet, so IDK what.

### Versions

* **Rock Version:** 6.2 Demo 6.5 CFC Production Server
* **Client Culture Setting:** en-us

**Comment by arranf** [comment]
I think this is going to be an enhancement rather than a bug.

I'm not quite versed enough in the new Lava commands to say _exactly_ what's going on but the entity commands return a list of entities (`IEntity`)(https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Lava/Blocks/RockEntity.cs#L384) whereas the SQL command returns a `DataRowDrop` (https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Lava/Blocks/Sql.cs#L94). I wouldn't expect the DataRowDrop to play nicely with the `| Select`, `| Where` commands etc.

I might be wrong but I think the only way to get the consistency you're expecting would be to have some sort of ILavaObject interface which the results of entity commands, SQL, and standard lava objects would implement and filters would use. That would be a significant amount of refactoring.

**Comment by NuclearTacos** [comment]
That's no fun!  Is there any other practice I could follow to "clean it up" to be able to use those filters on the results?

I wouldn't think that `{% assign %}` wouldn't alter it in any way, but I don't know for sure.

**Comment by edmistj** [comment]
I agree with Arran this would be tricky to implement and that this is an enhancement. I have an idea though that I can look at later.

**Comment by edmistj** [comment]
Just pushed an update that should allow for these new features.
