### ISSUE TITLE
Filter Transactional Email in Communication History

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2550]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
It would be awesome to be able to filter the communications history if it's a transactional email, or an actual user generated email. Rock currently credits the Contact on a Registration Instance for being the "Creator" of an email on auto-generated messages (receipts, event reminders, payment reminders), being able to quickly filter the communications history to remove these messages would be awesome.

### Versions
* **Rock Version:** 6.9-Prealpha
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
