### ISSUE TITLE
Note Type Security Can Interfere with Note Security

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#2551]
### Description
When trying to make notes that can be used to make the note visible to just the author and Pastors.
My solution was to make a Workflow to explicitly allow the creator of a note view/edit rights of the note they created.  I discovered this issue troubleshooting why it didn't work even though the security page looked right.  I confirmed this on my server, Demo, and Pre-Alpha.

### Steps to Reproduce
**Please Note**
When I refer to explicitly granting Person B viewing rights, I am referring to adding the user to the viewing rights page, not a group they're in

1. Start with Person A and Person B.  Person A is in a Security role that Person B isn't.
1. Create a Note Type that can be **viewed** by A, but not viewed by B, and can be **edited by either A or B**_(The edit but not view rights allows the person to create notes of that type in the timeline block on the Person Profile page)_
1. Create a Note of the new Note Type that normally Person B wouldn't be allowed to view.
1. Explicitly permit Person B to be able to view that note.
1. Login as Person B and try to view that note.

Bonus weirdness.  In testing on my server, I found that someone who is granted view rights on a note type, but is explicitly denied rights on the note isn't able to view the note.  This would be the expected behavior, but is counter-intuitive considering the issue I'm reporting.

**Expected behavior:**

I expected Note Security to override Note Type Security in all cases.

**Actual behavior:**

Explicitly stated note view security seems to be overridden by Note Type Security.

### Versions
* **Rock Version:** 6.2, 6.9, 7.0 (on Demo, My Production Server, and Prealpha respectively)
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Here are some more details, with a more specific example on the Rock demo site. I'm ignoring the **edited by** portion as that doesn't seem to be a direct relation to the core problem.

1. Create a new Person Note Type called `Secure Note`.
2. Set security on the note to Allow `RSR - Rock Administration` and `Ted Decker` to view the note type then Deny `All Users`. So only Rock Administrators and Ted Decker should be able to see this note type.
3. Configure the Timeline block on the Person Details screen to use the new note type (for clarity, add in a few others as well just so the drop down shows up).
4. As Alisha Admin, add a new note to the Alisha Admin person with the Secure Note type. Save.
5. Edit the note and edit the security for this note. The Inherited Permissions from the Note Type show up correctly.
6. Add a new user to the security for this note, and Allow `Jenny Michaels`. In theory, Jenny should be able to view this particular note now.
7. Login as Jenny and try to view the note, it will not show up.

This may be intended behavior, I'm not sure - but I think it's contrary to what users would expect since we can set specific security on a note, via a standard UI.

<img alt="screen shot 2017-10-18 at 10 34 10 am" src="https://user-images.githubusercontent.com/1119863/31733247-e948d64c-b3ef-11e7-9a07-89ba327a1bb0.png">

<img alt="screen shot 2017-10-18 at 10 34 42 am" src="https://user-images.githubusercontent.com/1119863/31733285-0f379f28-b3f0-11e7-9c60-b9362d5a0fb6.png">

<img alt="screen shot 2017-10-18 at 10 35 10 am" src="https://user-images.githubusercontent.com/1119863/31733291-118c3ac2-b3f0-11e7-999f-5d6be1fcc8e9.png">

**Comment by NuclearTacos** [comment]
Got it, the "Edit" portion of the instructions are to allow Person B to create notes of that note type.  (in line with the goal stated above, but not directly inline with the bug)

**Comment by arranf** [comment]
Reproducible in 8.0 pre-alpha
