### ISSUE TITLE
Family Pre-Registration

### ISSUE THREAD

**Issue by edmistj** [SparkDevNetwork/Rock#2573]
Working on a possible project for The Crossing church that would allow people to preregister families from their website.  Below are the requirements. Let me know if anyone has other ideas to add. 

This block would allow people to pre-register their families for weekend check-in.

![03-11-2017_08-22-49-applicationframehost](https://user-images.githubusercontent.com/548178/32455774-841d6b20-c2e0-11e7-9604-d575d4f3deae.png)

## Block Settings
* Adults
    * Show/Require Gender
    * Show/Require Birthdate
    * Show/Require Email
    * Show/Require Mobile Phone
    * Show/Require Suffix
    * Attribute Category
* Children
    * Show/Require Gender
    * Show/Require Birthdate
    * Show/Require Suffix
    * Show/Require Grade
    * Show Mobile Phone
    * Attribute Category
* Family
    * Attribute Category
* Workflow Type Id
* Connection Status
* Record Status
* Show/Require Planned Visit Date
* Show Campus         

## Additional Features
* Entry Throttling – A block setting should allow a throttle to be set to keep a bot from rapidly entering new people into the database. This setting would limit a single IP to X number of entries per day.
* Auto-Matching – This block setting would determine if Rock should attempt to auto-match to current records in the database. This would be default to on, but one could disable this.
One difficult part of this configuration would be how to create the families that are registering. For example, if the relationship between the children and guardian is ‘Friend’ or ‘Grandparent’, we’d want to create two families with the individuals linked together with known relationships that allowed for check-in. Below is a sample of how this configuration would be achieved.

One difficult part of this configuration would be how to create the families that are registering. For example, if the relationship between the children and guardian is ‘Friend’ or ‘Grandparent’, we’d want to create two families with the individuals linked together with known relationships that allowed for check-in. Below is a sample of how this configuration would be achieved.

![03-11-2017_15-35-03-applicationframehost](https://user-images.githubusercontent.com/548178/32455792-97e48166-c2e0-11e7-84dd-7a81a74cadd4.png)

**Comment by cabal95** [comment]
Do you have any thoughts on how the Workflow would be triggered, specifically what data would be passed to it? Especially in the case of "Guardian" where two families are created. Some use-cases would want to know the person that registered (to e-mail them something) and other use-cases would want to know the children that got registered (to alert staff to expect them, or to attach a person attribute to them).

**Comment by mikejed** [comment]
How would the "Planned Visit Date" attribute be used? Is it to be simply available as an attribute of some kind for our programmatic use (for instance, in the workflow)? Or will it be used out-of-the-box in some way (a notification e-mail of people intending to attend this coming weekend, for instance)?

And, if the Planned Visit Date control is omitted using the block settings, it looks like this could double as a self-registration kiosk page if needed. Would you agree that is a plausible use of this block as well? Perhaps with that in mind, additional settings would be useful which could allow us to specify what page is loaded upon completion (My Account, a success page, or re-loading the same page for the "next" person to register, being three examples I could see being used frequently), and whether "Parent/Guardian 1" is logged into Rock upon completion or not.

If auto-login is enabled (or intended as currently envisioned), I wonder if it makes sense to rename "Parent/Guardian 1" or add something to it, such as "Parent/Guardian 1 (you)", or have another block setting to specify the titles.

**Comment by cabal95** [comment]
I would think auto-login would not be supported since there is no login account being created. This would be consistent with other places in Rock. e.g. when registering for a small group, after you enter your info you aren't logged into Rock (unless I've lost my mind and somebody corrects me).

**Comment by mikejed** [comment]
In light of the coming "interactions" concept in Rock, perhaps there's a distinction between a true login (which should need a login account), and the ability to set a cookie so there is an "indicator" (there's a better term I'm not being able to pull right now) of who the visitor _may be_ next time they visited the site, etc...

A true login could be dangerous, if someone put in a staff member's information and was thus "matched" and then logged in. But losing data which can help customize a church's site appropriate to the person visiting seems like a shame, given that part of the vision of Rock.

**Comment by JimMichael** [comment]
Yeah, the idea was to have as friction-free a process as possible for brand new people to pre-register their kids for check-in, thus no login required as that would create a LOT of friction. I asked Jon to put this issue out here since it would be a block that goes into core, and I didn't want to get down the road and have others be like "why doesn't it do this or that", or worse... "why does it allow this risky behavior?"

The option to NOT do matching is my attempt to make it safer as I don't even like the idea of someone being able to add themselves to an existing family by only knowing a name and email, and other than doing an email verification loop I didn't see a way to mitigate that, other than to not match at all... and in our case we're expecting this to be used 95% by new people that aren't in the system anyway. At least that's the intent.

All that said... I hope this doesn't turn into a pie-in-the-sky "lets throw everything in but the kitchen sink" type of discussion, as that would affect cost. ;-)

**Comment by cabal95** [comment]
> All that said... I hope this doesn't turn into a pie-in-the-sky "lets throw everything in but the kitchen sink" type of discussion, as that would affect cost. ;-)

If you're footing the bill, who cares about cost? :)

Seriously though, looking over our current Workflow solution (which hasn't even been implemented yet), I think the only thing we have different is it will ask if the child lives with the parent/guardian, and if not ask for an address of the child. I think that is a "would be nice" item as opposed to a "must have" as I would suspect that more often than not, the people that would preregister all live under the same roof.

Beyond that I think this covers everything we would need - with the exception of the question I posed about the workflow triggering. I think that's the only "hard to solve" part because of the potential dual-family situation.

**Comment by Wec2it** [comment]
I am curious about the Attribute Category. Will these be selectable from any Attribute Category or will it be coded to specific attributes?  

Could the Campus be an optional default block setting?  I can see setting this up on a page for each campus as they may need to track different attributes.  It would limit them to the correct campus.

**Comment by JimMichael** [comment]
@cabal95 Thanks for the input. The vision we had for the workflow trigger was more about alerting internal staff that someone had just registered their family, not so much about sending welcome emails and instructions, though now that I see if I can see that being useful, too. What do YOU think should be passed to the WF?

@Wec2it The attribute category would be select-able from any existing category. Any attributes in that category would then be exposed. Since attributes can exist in multiple categories, all you'd need to do is create a specific category for this use and put the attributes you want to expose in it.

**Comment by cabal95** [comment]
Well, my thought for sending to the parent/guardian would be things like instructions on where to go - which could change depending on the age of the kid(s) being registered. So, sadly I would say both family units. Since that isn't possible...

### Option 1
* Pass the guardian family as the workflow Entity
* Pass a comma separated list of Person IDs to the workflow via a pre-defined workflow attribute name (such as `PersonIds`).

### Option 2
* Pass nothing to the workflow as the Entity
* Pass a comma separated list of Family IDs to the workflow via a pre-defined workflow attribute name (such as `FamilyIds`).

I think Option 1 would be the easiest to implement both from a dev perspective and a workflow builder perspective. In pure-lava we can pretty easily parse a comma separated list of integers and pass them to `PersonByID` to get the person object and make logic decisions about the text to include in the e-mail, or even what other activities to trigger.

This should allow for fairly easy formatting of an e-mail to staff informing them that a family registered with links and ages to all the kids; as well as sending an e-mail to the "guardian 1" with some "to help you get ready" instructions, where to go, etc.

**Comment by edmistj** [comment]
Regarding passing to the workflow. How about:

Entity = Parent Family

Optional Workflow Attributes (used if exist)
ParentIds - Comma separated list of the Parent Person Ids
ChildIds - Comma separated list of the Child Person Ids
PlannedVisitDate - This is the only place this date would be used.

**Comment by cbump** [comment]
@edmistj We actually have a custom block we wrote which is really pretty similar to this and already does a lot of this work.  You can see it in action here:
https://www.southeastchristian.org/visit/children/register

I've attached a copy if it. . . .

[PreRegistration.zip](https://github.com/SparkDevNetwork/Rock/files/1571706/PreRegistration.zip)

**Comment by edmistj** [comment]
@cbump, thanks this will be a good start,

**Comment by edmistj** [comment]
Closing this as we're ready to get started.
