### ISSUE TITLE
[EN] Add Person Context support for Pledges

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2575]
### Description
As part of giving enhancements we've built, the PledgeList and PledgeDetail blocks don't pass through Person contexts.   Upcoming PR to add this functionality, allowing you to add a Pledge from the Person > Contributions > Pledge list and it carries the Person context forward.

This functionality does not yet exist in either v6 or v7 versions.

### Steps to Reproduce
1. Click Add a Pledge from Person > Contributions
1. Be directed to the Pledge Detail page
1. Expect the Person to be pre-selected
1. Lower such expectations
1. Re-pick the Person from the picker
1. Finish creating the Pledge

![screenshot 2017-11-06 13 52 35](https://user-images.githubusercontent.com/1210933/32458251-d2255cb0-c2f9-11e7-9fd2-c95b3c8813d4.png)

![screenshot 2017-11-06 13 52 24](https://user-images.githubusercontent.com/1210933/32458250-d214bf0e-c2f9-11e7-860a-0b2700df35b9.png)

**Comment by edmistj** [comment]
Sounds good.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
