### ISSUE TITLE
7.0 - Radio button on person picker is slightly hidden on Mac computers. 

### ISSUE THREAD

**Issue by matthewmeekins** [SparkDevNetwork/Rock#2649]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [x ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
The person picker is slightly hidden behind the border on Mac computers. I checked in Chrome and Safari browsers. 
![](https://user-images.githubusercontent.com/10676326/34581005-e92dfd40-f15c-11e7-8807-978face1b9bb.png)

### Steps to Reproduce
1. [First Step]
1. [Second Step]
1. [and so on...]

**Expected behavior:**

[What you expected to happen]

**Actual behavior:**

[What actually happened]

### Versions
* **Rock Version:** 7.0
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by cabal95** [comment]
Confirmed on pre-alpha site.

**Comment by edmistj** [comment]
Can you add an additional screenshot highlighting the issue. I don't see it in the one above and don't have a mac readily available to confirm.

**Comment by cabal95** [comment]
<img width="432" alt="screen shot 2018-01-04 at 11 51 37 am" src="https://user-images.githubusercontent.com/1119863/34581656-24075536-f146-11e7-9366-fc36366aa654.png">

The issue seems to stem from the fact there is a margin-left applied to `input.radio` types of -20px. If I change that to -19px it shows fine. Why this is only an issue here I'm not sure. I don't see anything in the parent elements that is shifting it left any more than standard. Maybe it's always been like this but never left-aligned in a container that hides overflow before?

**Comment by matthewmeekins** [comment]
<img width="121" alt="screen shot 2018-01-04 at 2 57 35 pm" src="https://user-images.githubusercontent.com/10676326/34581773-a2c83548-f15f-11e7-996e-4e4008b926f2.png">
