### ISSUE TITLE
[EN] Allow Person Photo field to be used as Registration Template item

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2669]
### Description
There's a need for multiple churches that want to get a person's image during an event registration.   I realize you can configure to kick off the Photo Request workflow after the registration is completed, but the conversion rate will be less.

In the Person Field section on v6/v7, there isn't an option for Image:
![screenshot 2018-01-16 14 25 00](https://user-images.githubusercontent.com/1210933/35008296-fbd29c64-fac9-11e7-80ca-bf3937dd4ff4.png)

I plan to add support for that as a registration template item, similar to PR #2668.

### Steps to Reproduce
1. Create a registration form
1. Look for Person Field: Photo so people can upload their own
1. Use a Registration Attribute of type Image instead
1. Spend a few hours after registration ends manually reconciling photos.

### Versions
* **Rock Version:** v7
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@dcs619  OK, be sure to use the same logic as other profile photo blocks which require the photo be be cropped to a square.

**Comment by nairdo** [comment]
Hi @dcs619 -- I'm not sure if you ever got around to this.  Do you want us to keep this one open or should I close it?

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
