### ISSUE TITLE
Mark FinancialPaymentDetail as required for Contribution Statement Generator purposes

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2682]
### Description

As reported in Slack by @mikejed, the statement generator does not pull transactions that don't have a FinancialPaymentDetail.  The FinancialTransaction block does create a blank Payment Detail if you add/save a transaction, but testing with 6.10 and v7 that field is not required at the DB level.

### Steps to Reproduce

1. Add a new FinancialTransaction without a payment detail from the database
2. Run the statement generator
3. Troubleshoot why that transaction is missing

<img width="961" alt="screenshot 2018-01-18 17 46 57" src="https://user-images.githubusercontent.com/1210933/35125667-7b05ee82-fc78-11e7-9a7e-62bdab365224.png">

**Expected behavior:** 

Expect the transaction to show up in the statement generator

**Actual behavior:** 

Nothing shows up

### Versions

* **Rock Version:** v7
* **Client Culture Setting:** en-us

**Comment by rutledgek** [comment]
I would add that the statement generator is locked at looking at only the Contribution Transaction Type.  If a church creates a different value and uses it, the generator ignores it.  

I would either make all transaction types listed as a selectable option for which to include or remove this filter completely and show all transactions of all types for the funds selected.

**Comment by JimMichael** [comment]
I would further add that the online Lava contrib statement doesn't seem to filter out transaction types in this way, so making them consistent would be ideal.

**Comment by edmistj** [comment]
@dcs619  We will add a feature that will consider unknown currency types to be 'Cash' for the statement generator. 

We would consider not having a FinancialPaymentDetail record to be corrupted data though so it could cause issues in other areas. Unfortunately, we can't make that field required now since some people have missing values. The best we could do is to add something to the clean-up job to look for this and correct it by creating a record labeled as Cash. Doing that would lead to some incorrect data based on assumption. Not sure what is better incorrect data or corrupted data.

Do you know how that data was imported into Rock? We should figure that out and make sure we stop the bleeding.

**Comment by edmistj** [comment]
@rutledgek Seems a little odd to add a configuration to select transaction types other than Contributions for use on Contribution Statements. Seems like that would be a super advanced configuration that everyone would have to look at. We'd probably would want to hide it under a menu setting to help the average non-technical person from having to configure too much. 

I don't think we could get to this in time for the 2017 run. The next time we're in there making IU changed we could try to knock it out.

**Comment by edmistj** [comment]
@JimMichael Updating the blocks to match that same settings and templates is something we plan to do at some point. This project was a last minute one based on two churches paying for it for they're own needs. We decided to make it available for others immediately. Kinda wishing we hadn't now...

**Comment by cabal95** [comment]
@rutledgek and @JimMichael Could you guys add new issues to track those specific items? While related, I think it would be better to track them separately as they might very will be worked on at different times.

I think hiding the transaction types behind some sort of "advanced options" makes sense. I was thinking that myself. It is a handy feature, as it would allow the statement generator to be used to generate statements for other things (e.g. sports payments) without having to re-invent the wheel. But we don't want to end up with dozens of screens for everybody else to have to click through each time.

**Comment by rutledgek** [comment]
@edmistj While I agree it is strange which is why, I wouldn't think any filtering on transaction type would be advisable.  If the transaction uses a tax deductible account that is selected, then it should be included.  The use case/challenge is that I spent the better part of a day working with someone whose church created a defined value called offering under which all their transactions were assigned.  The statement generator was not giving any results because of this.

**Comment by dcs619** [comment]
> Do you know how that data was imported into Rock? We should figure that out and make sure we stop the bleeding.

@edmistj Unfortunately I don't know how long ago this particular data was imported. All the code I've [seen](https://github.com/NewSpring/Excavator/blame/master/Excavator.CSV/Maps/Financial.cs#L308)  or [written](https://github.com/NewSpring/Excavator/blame/master/Excavator.CSV/Maps/Financial.cs#L308) includes a "blank" Payment Detail for each new FinancialTransaction.  That's been there since [12/16/15](https://github.com/NewSpring/Excavator/commit/20f00189b762609dfda8b5cf3537d7617d414b54).

**Comment by edmistj** [comment]
The primary issue described in the initial report is fixed in v7.3
