### ISSUE TITLE
Add paymentInfo.Description to contributions

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2704]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Sending a description to the payment gateway from contribution transactions would be helpful. Currently Rock creates a description for event registrations [RegistrationEntry.ascx.cs#L2929 ](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Event/RegistrationEntry.ascx.cs#L2929). Adding a similar description for contributions `Fund Name (Fund GlCode) = $XX / Fund Name (Fund GlCode) = $XX` which would allow for contributions to multiple funds.

### Steps to Reproduce
1. Create a contribution

### Versions
* **Rock Version:** 7.0
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
