### ISSUE TITLE
Multiple Child Labels are Not Printing

### ISSUE THREAD

**Issue by colobren** [SparkDevNetwork/Rock#2713]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When printing check-in tags for families with multiple children, only the first child tag prints.  Subsequent child tags do not print.

### Steps to Reproduce

1. Using any method (iPad, Windows App, etc), check in a family with multiple children.

**Expected behavior:** 

A labels should be printed for the first child, then any other labels for the family (parent receipt, etc), then the following children's labels should follow.

**Actual behavior:** 

The first child's labels prints, followed by the labels for the family.  No further labels print for the remaining children.

### Versions

* **Rock Version:** 7.1 
* **Client Culture Setting:** en-us

**Comment by cabal95** [comment]
Just to add some clarification from my chat about this on Slack.  This is not a "printer jam" kind of issue.  For example:

1. Family checks in two children, only the first child's tags print.
2. Second family walks up to same kiosk and checks in two more children, only the first child of this family's tags print.

So the issue seems to be that, for whatever reason, the labels are just not created in memory.

I don't have printers to verify this bug, but looking at the code there was a substantial (in terms of lines of code) change to the Create Labels workflow action. My hunch is something went wrong with that refactor causing the labels to not be generated when the same label type is generated, even for a different child.

From the original report, last week everything worked fine on 7.0. In the interim they upgraded to 7.1 beta and made no changes to any other check-in configuration.

**Comment by JimMichael** [comment]
I am unable to dupe this on 7.2 (1.7.2.53)... however, it could also be that we have a different configuration that doesn't trigger a problem. We print a separate parent label for each kid, not the combined one. On this version, checking-in multiple kids causes a normal printing sequence (all child labels print first, then all parent labels, then all basket tags). Another difference is that I checked all kids into the same test group... I don't have a quick setup to test kids going into different groups. Just adding this as another data point. Here is the config we're using:
![image](https://user-images.githubusercontent.com/3903408/35478811-e1c67f70-03ac-11e8-9dd1-78f156827606.png)

**Comment by austinspooner** [comment]
We can replicate this here - using a single parent label per family.

**Comment by kcirgjd** [comment]
We reproduced it here also. It seams to not be honoring "print label for individual" and is setting each label to print one per family.

**Comment by azturner** [comment]
Fixed Here: https://github.com/SparkDevNetwork/Rock/commit/da8aa4746f81604a99157571faf23333e7d64939
