### ISSUE TITLE
Add support for a Minimum number of Registrants in Event Registration

### ISSUE THREAD

**Issue by mrskatiewalters** [SparkDevNetwork/Rock#2737]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Feature Request: In event registrations, include the ability to have a minimum/required amount of registrants.

Example: Married event registration, they should not have to choose "2" registrants from the first page of the form registration. It should default if Minimum and Maximum are the same.

**Expected behavior:**

It should default to the number of registrants required if Minimum and Maximum are the same. 

**Actual behavior:**

There is a max. now but no minimum.

### Versions
* **Rock Version:** 6.7

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
