### ISSUE TITLE
v8 still uses legacy Lava in External Inquiry workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#2780]
### Description

The Capture Note action in the Open activity uses legacy Lava syntax

**Expected behavior:** 

New versions of Rock should eliminate Legacy Lava in core areas

**Actual behavior:** 

User form. action references several WF attributes with legacy syntax, preventing the enabling of No Legacy mode without users manually fixing this up.

### Versions

* **Rock Version:** all

**Comment by ethan-sparkdevnetwork** [comment]
Fixed in 3e21ed58.

**Comment by maurice-ellis** [comment]
I see that this was fixed, but is there something that I have to do? Im running Rock McKinley 8.3 en-US, but receiving a warning Legacy Lava Syntax Detected for our external inquiry workflow. Im not sure how to fix it, I looked at where Lava is used and it's in the setting the workflow name, looked at Rock Demo and dont see a difference between what I have.

**Comment by mikejed** [comment]
@maurice-ellis I just took a look at the demo server and I don't see legacy Lava in that action (or indeed, anywhere in that workflow). The action you identify uses
>{{ Workflow | Attribute:'FirstName' }} {{ Workflow | Attribute:'LastName' }} ( {{ Workflow | Attribute:'Topic' }} )

which is not legacy Lava. Legacy Lava would look like `{{ Workflow.FirstName }}` and the like, rather than using the Attribute filter.

Can you confirm that your workflow's Lava does indeed match what's on Demo? I think there may have been checks that prevented the Lava from being updated automatically if you've already edited the workflow yourself, so we don't overwrite anything you've done.

**Comment by maurice-ellis** [comment]
@mikejed thank you, I was able to find the legacy Lava. For those who may run into the same issue, the  lava in the Set Name action was correct, however, there was some legacy Lava in the Capture Notes action, which needed to be updated.
