### ISSUE TITLE
'Login' on Account Confirmation page for new user does not show user logged i

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#2793]
### Description
**Actual behavior:**

When a registering user comes to the Account Confirmation page from the Confirm link in the confirmation email, 

and if the user is in no security groups that will force the menu bar to refresh (I think)

then the page does not show 'Hello User' but shows 'Login'.  Clicking 'Login' does nothing.  I expected clicking Login to either take me to the login page, or show 'Hello User' .

![loggedon1](https://user-images.githubusercontent.com/4658177/36332976-4fd0827c-13d9-11e8-8b0b-a11217f369b7.jpg)

If you refresh the page (F5), the Login is replaced with 'Hello User'.

![loggedon2](https://user-images.githubusercontent.com/4658177/36332982-53f899fc-13d9-11e8-972e-c1397bc5426f.jpg)

This does not happen if the user is in a security group that forces the menu to refresh.  In this case the page correctly displays 'Hello User.'

**Expected behavior:**

On the Account Confirmation page replace 'Login' with 'Hello User' to indicate to the user they are logged on, and show all the logged on user menu items.  (Force the menu bar to refresh??)

OR 

On the Account Confirmation page Instruct the user clearly to login again, and make the Login button go to the login page (it currently does nothing).

### Steps to Reproduce
1. Create a new user from the external site.  Make sure the user is not in any security groups.
1. Click the 'confirm' link in the confirmation email.
1. Click 'Login' at the top right on thte Account Confirmation page.

### Versions
Rock Version: Rock McKinley 7.2 (1.7.2.53)
Client Culture Setting: en-NZ

**Comment by ElimAdmin** [comment]
User is actually logged in at the Confirmation Page but menu does not reflect logged in status.
Maybe change the "Your profile is now confirmed." message to say "Refresh the web page by pressing F5."

**Comment by nairdo** [comment]
Greetings @ElimAdmin (Ken) Just FYI...that content can be customized today by the Rock administrator via the block settings -- if you want to do that on your system:

https://prealpha.rocksolidchurchdemo.com/page/103?Page=213&ExpandedIds=1%2c206&Redirect=false

![image](https://user-images.githubusercontent.com/383807/57310449-af515f00-709e-11e9-823a-6bc815e4b636.png)

I've actually explored another approach (redirecting back to the page _after_ confirmation so that any other secured content, menus, login status, would all be refreshed). But working out the mechanics to be perfect was taking me a bit longer than I had hoped it would (then I ran out of time).

**Comment by ElimAdmin** [comment]
Thanks Nick.  You guys are amazing.  Appreciate everything you are doing.
Ken

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
