### ISSUE TITLE
Migration Bug: Nulls vs. Empty String

### ISSUE THREAD

**Issue by mrskatiewalters** [SparkDevNetwork/Rock#2797]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A person cannot save a value of Null into an AttributeValue record pertaining to a person entity.

**Expected behavior:** 

We expect no errors.

**Actual behavior:** 

When a Null value is migrated over in a sync, Rock throws an error in the Extended Attributes section of Person Page. 

Or if Null value is not supported, need to migrate over as an empty string.

### Versions

* **Rock Version:** 7.2

**Comment by cabal95** [comment]
For a bit more clarification on the exact issue that was encountered, a Person attribute of field type Value List had some NULL values stored in the database for certain people. These values came from a migration. Most (maybe all?) of the field types do not check for null values before processing the value, so in this case a `value.Split(...)` was performed, assuming a non-null string, in the FormatValue method of the ValueList field.

**Comment by azturner** [comment]
@cabal95 I looked at the Migration scripts that were used to convert their data. The scripts have always had a check for null attribute values, and will instead save a blank string instead of the null value. Also, the migrations scripts don't create any 'Value List' attributes or values.  Are there anymore details for the error that we can look into (i..e which of their attribute was this happening on).

**Comment by cabal95** [comment]
@azturner Sorry I wasn't more specific. This wasn't related to any specific form of migration, just a general issue.  If the AttributeValue database has a NULL value, then many field types do not check to see if the value is NULL before trying to do, for example, `value.Split(',')` and thus throw an error. Which in many cases makes it impossible to fix the value without going into the database directly.

Since the database column allows nulls, the field types should probably check for nulls as well. Another solution would be to have GetAttributeValue() check for NULL and convert to String.Empty, but I don't know if that would have unintended side affects.
