### ISSUE TITLE
Add Alt Text to image component in email wizard

### ISSUE THREAD

**Issue by garrettjohnson** [SparkDevNetwork/Rock#2799]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The new image component in the Rock Communication Wizard doesn't include an option for ALT Text. Since most email clients block images by default, including ALT text will help communicate the content of the message; especially in emails that are primarily images.

### Steps to Reproduce
1. Insert image component in communication wizard

**Expected behavior:**

Ability to add alt text

**Actual behavior:**

No alt text

### Versions
* **Rock Version:** 7.2
* **Client Culture Setting:** en-US

**Comment by edmistj** [comment]
Awesome, we had this on an internal todo. I've linked these two items.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
