### ISSUE TITLE
[EN] Event Registration option to Show Family Members with Same Family > Ask

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2821]
### Description

Since v6.3, the only way to Show Family Members is to select `Yes` for "Registrants in Same Family".  This seems like an unintentional side effect of fixing #2074, as the behavior in v6.2 allowed Show Family Members for `Yes` or `Ask`.  This allows a registration to be filled out faster regardless if all of the registrants are in the same family.

<img width="721" alt="screenshot 2018-02-23 08 05 39" src="https://user-images.githubusercontent.com/1210933/36595734-59883f48-1871-11e8-86d6-4ac0297adbc6.png">

I already have code that enables Show Family Members for `Yes` or `Ask`, but wanted to check for discussion before doing the PR.

### Steps to Reproduce

1. Configure Event Registration template with Registrants in the Same Family > Ask
2. Expect the family members could be selected from a dropdown
3. The ShowFamilyMembers property does not display in RegistrantTemplateDetail
4. The family members dropdown does not display in RegistrantEntry.

### Proposed Change

![screenshot 2018-03-15 11 14 02](https://user-images.githubusercontent.com/1210933/37472273-0da34600-2842-11e8-93d6-47bcd9fc20a4.png)

![screenshot 2018-02-21 16 30 16](https://user-images.githubusercontent.com/1210933/36595863-d2b65d14-1871-11e8-820e-d78ee3838e12.png)

### Versions

* **Rock Version:** v7.2
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@dcs619 I think this is working as intended. If it worked as described in v6.2 we'd see that as a bug. The problem with supporting both the "Individual is in the same family as" AND "Family Member" picker at once is a person could provide conflicting input. "Alexis is not in the same family as Noah" but select "Alexis" from the family member picker where "Noah" is in the same family.

**Comment by dcs619** [comment]
@edmistj What if I change the UI so the family dropdown only shows after clicking "Individual is the in the same family"?

**Comment by edmistj** [comment]
@dcs619 I'm not sure that would help. The family member list is in the context of the currently logged in user. The "Individual is the in the same family" doesn't have a context the relationship of the logged in person (until the final screen).

**Comment by rutledgek** [comment]
I do agree though that the fix went in the opposite direction than I had hoped.  When someone is logged in, I believe there should always be an option to quickly select a member of their family in the registratio, whether they use it or not.  

You end up with someone registering and paying for a neighbor but because of that they can’t quickly register their own kids.

**Comment by dcs619** [comment]
@edmistj Here's a video of the proposed update based on your feedback.  I'm currently logged in as Ted Decker, registering Noah and Alex, as well as a non-family member Brian Jones.  

![familyregistration](https://user-images.githubusercontent.com/1210933/37471646-a9851e74-2840-11e8-9ceb-9f5ec5a696a8.gif)

**Comment by edmistj** [comment]
Couple of questions/points.

- Why does the first registrant start as Ted Decker? Seems like this should be blank to force a pick.
- I'm assuming if there was a fourth registrant that if you picked any family other than the 'Alex & Noah Decker' the drop down would disappear (and reappear if you re-selected it)?
- Since 'In the same family as...' radio list does not auto-select the family member dropdown should probably be hidden until the select the one family tied to the logged in user.
- The link to 'Alex and Noah' as a shared family to the logged in user is important. The logic for this would need to take into account several different use cases. Like what if I only wanted to register one person to my family, but they were not in the family member dropdown (not in the database). Seems like the when the family member selector is in play the 'In the same family as' should start with an option for the currently logged in user.

I think this is getting close, but we should probably work out some of these edge cases otherwise we'll need to refactor this.

Maybe another video with these edge cases considered? Might be better as an mp4 so you can rewind.

**Comment by edmistj** [comment]
@dcs619 Any update on this?

**Comment by dcs619** [comment]
@edmistj Code is finished for Rock 7.4, I'm awaiting feedback from the client then do a PR for v8.  Do you foresee this going into a 8.X release or waiting for v9?

**Comment by edmistj** [comment]
@dcs619 v8.0 has left the dock, but it might be able to be added to a point release. I don't think we ever saw a final video of some of the edge cases we inquired about above. Were those taken into account? Could we see an updated example before the PR?

**Comment by dcs619** [comment]
@edmistj Here's a video: https://www.dropbox.com/s/oy4267bcxlxpcyd/familyregistration.mov?dl=0

**Comment by edmistj** [comment]
@dcs619  Looks good.
