### ISSUE TITLE
Confirmation email for registration never receieved

### ISSUE THREAD

**Issue by maurice-ellis** [SparkDevNetwork/Rock#2879]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

Confirmation email for registration is never sent. This is based off of Mailgun never receiving a request. Emails sent through communications works fine. I've tried resending the confirmation several times, even though Rock says the email has been sent, Mailgun never receives anything nor do I.

I just discovered that an email for the registration instance is needed in order for the confirmation email to be sent.

[RockDiagnostics-CFTN-ROCK-WEB.txt](https://github.com/SparkDevNetwork/Rock/files/1820142/RockDiagnostics-CFTN-ROCK-WEB.txt)

### Steps to Reproduce

1. Created an event
2. Registered for the event and included email for confirmation emails
3. Submitted registration, receive the success page
4. Try resending confirmation email

**Expected behavior:** 

The confirmation email to be sent or a correct message saying the email was never sent

**Actual behavior:** 

The confirmation email is not being sent, but receiving a message that it was.

### Versions

* **Rock Version:** Rock McKinley 7.3 (1.7.3.55)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Additional details from discussing this in Slack. For some reason, when the Person Profile of the logged in person has no e-mail address (i.e. it's blank), then the `.Email` property of the registration state is null instead of a blank string.

Confirmed against demo site on 7.0. Can't confirm against prealpha as it's broken at the moment.

![image](https://user-images.githubusercontent.com/1119863/37544440-3ea285c8-2922-11e8-8bd4-639c278bccd7.png)

**Comment by ethan-sparkdevnetwork** [comment]
Problem:
The From address for the Registration Template is configured with lava e.g. {{ RegistrationInstance.ContactEmail }}
The Contact or the contact email in the Registration Instance is not selected; or the selected contact does not have an email address.
The Resend notification button does not immediately send an email, it enqueues it.
When the system sends the email it checks for a from address, it sees the lava and allows it to pass.
When the merge takes place the lava does not resolve to anything and becomes an empty string.
The sending code checks the from address and doesn’t send it because it is an empty string.

Fix:
Code will attempt to merge lava fields first.
If from address or name is empty after an attempted merge then use the global organization email and name for the from info.
If still empty then log error "A From address was not provided and no Organization email address is configured."
This will still not display a failure when enqueuing since the email was successfully enqueued. But it will reduce failures and provide a more meaningful error in the log.

Note:
This fix will not do anything for missing info in the email subject/body caused by lava referencing a missing or incomplete registration instance contact.
