### ISSUE TITLE
[EN] Update Site.Master to wrap main page elements

### ISSUE THREAD

**Issue by dylan-gregory** [SparkDevNetwork/Rock#2885]
Add a `<div>` around the `.main-feature`, `<main>`, and other mid-page elements.

**Steps which explain the enhancement**

1. Inserting a `<div>` tag around the placeholders [here ](https://github.com/SparkDevNetwork/Rock/blob/7aee1031a8f590e4716e0e6b5f637f70986f1023/RockWeb/Themes/Stark/Layouts/Site.Master#L71)

**Current and suggested behavior**

Currently, page specific content zones are lumped into `<body>` along with the more site-wide `<header>` and `<footer>` (see screenshot below).

![](https://user-images.githubusercontent.com/22873277/37622032-0002e106-2b97-11e8-96cb-6d1d599a1c44.png)

**Why would the enhancement be useful to most users**

If the content was wrapped, it would be a lot easier to add content-specific styles.

**Rock Version:** 6.10

**Comment by cabal95** [comment]
I'm not sure how addition an additional node would help CSS styling? You can already target these specifically with `body > header`, `body > section.main-feature` and various other methods. Can you give an example of what you are trying to accomplish that you cannot currently do?

**Comment by dylan-gregory** [comment]
@cabal95 The basic issue came from whitespace after the footer when there's not enough content on the page to push it to take up the whole view height. Looking for a global way to do so would mean targeting the element above the footer - but having multiple zones that don't always have content makes that difficult. A parent container would make which zones used irrelevant.

**Comment by cabal95** [comment]
Hmm. You should be able to edit your theme file and add them in yourself. (BTW, just in case you haven't you will want to duplicate the Stark theme rather than use that as your own theme otherwise any changes you make will get wiped out on each upgrade).

But to clarify what you were asking for, you were saying that all 3 of those items (section.main-feature, main, section.lower-feature) should be wrapped in a div together, not each one be given it's own div?

**Comment by dylan-gregory** [comment]
@cabal95 Yep, I know to do that. It would add one more level of organization for the page content, excluding the navbar and footer. And you're correct, like such:

`<header></header>
<div class="content-wrap">
     <section class="main-feature"></section>
     <main class="container"></main>
     <section class="lower-feature"></section>
</div>
<footer></footer>`

**Comment by edmistj** [comment]
@dylan-gregory feel free to do a PR

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
