### ISSUE TITLE
[EN] Add support to Email Preference block to inactivate all family members

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#2919]
### Description
Currently when someone clicks the Unsubscribe link they only have the option to inactivate themselves when choosing the "I am no longer involved" option.  I have an additional block of code that allows that them to inactivate the rest of their family as well.  If that seems helpful for others I can do a PR.

Attached are screenshots of the proposed functionality. This is sponsored by [Woodmen Valley Chapel ](woodmenvalley.org).

### Steps to Reproduce
1. Click "I am no longer involved" and Submit
1. That person will be marked inactive in Rock
1. Rock admins look for inactive/active inconsistencies
1. Rock admins manually inactivate the rest of the family 

**Current behavior:**

![screenshot 2018-04-02 12 35 02](https://user-images.githubusercontent.com/1210933/38204804-492acca0-3672-11e8-8a34-ef7da3e27728.png)

**Proposed behavior:**

![screenshot 2018-04-02 12 30 41](https://user-images.githubusercontent.com/1210933/38204790-3858b7d4-3672-11e8-9906-df4d130a92bd.png)

### Versions
* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

**Comment by edmistj** [comment]
@dcs619 sounds good. Could you add that with a block setting to enable/disable. Default I guess should be enabled as I would think most would want that feature.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
