### ISSUE TITLE
Enhancement: Change to Download Payments Job

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2932]
The Download Payments downloads and updates transaction status . This allows us to see when things have settled, and even if the transaction is returned for insufficient funds which could serve as a trigger for a refund.  Unfortunately, this only updates the status of scheduled transactions.

I suggest changing the job so that it downloads transactions and updates for all transactions that occur within the time window(days back) set in the job.  This by itself would be extremely helpful in reconciling transactions to deposits since you can see all transactions that settled on a particular date where the status is settled.

If however, it also downloaded all transactions and lumped unmatched transactions in a batch like the check scanning process, then you could use Transnationals credit card swipe systems to get transactions into rock.

Here is a status update downloaded by rock for a scheduled transaction.

"4/8/2018 8:22 AM: Sale; Status: AP 4/9/2018 12:30 AM: Settle; Status: OK"

If I am wrong and it does download all transactions and not just scheduled transactions, it downloads the status inconsistently which I would imagine is a bug.
[Image of Some updated transactions ](https://files.slack.com/files-tmb/T0AFJGC56-FA3BZ4VCZ-a22d4750fe/screenshot_2018-04-09_22.19.20_960.png)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
