### ISSUE TITLE
Modify Phone Number Click to Dial Link on Mobile

### ISSUE THREAD

**Issue by randyjreed** [SparkDevNetwork/Rock#2935]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers ](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When using a plugin that enables click to dial. The phone number becomes a link that initiates the call. This prevents the built in mobile click to dial that would use your phones application.

### Steps to Reproduce
Install plugin that enables this feature (FreePBX. Still in testing) Use a mobile browser and attempt to dial the number on a profile page. This will dial your local extension instead of using the built in phone application.

**Expected behavior:**

When clicked on a mobile browser it would use my phone application.

**Actual behavior:**

When clicked it dials the users local extention.

### Versions
* **Rock Version:** 7.3 
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Tagging as bug since it changes pre-existing behavior.

Two initial options to fix would be:

1. Change the way the phone number is displayed to increase the size of that phone button (so it's easier to click) and remove the href from the phone number. Thus if you click the phone icon it does click-to-dial, if you click the phone number (on mobile) it uses the built-in handling of tapping phone numbers.
2. Detect if on mobile and if so disable the click-to-dial functionality altogether.

**Comment by JimMichael** [comment]
I think #2 might be problematic if there are people using phone integrations and _want_ the link to click-to-dial even on mobile. I know at least with the Switchvox plugin, you can have it initiate a call from your cell (which looks like you're calling from your desk to the receiving end), not just your desk phone. 

I think I'd vote for option #1, but only because I don't know at this point how much (if at all) what I describe above will occur.

**Comment by edmistj** [comment]
I agree with you Jim, but think #1 might be difficult to click the right place and might be confusing. I could make a block setting so the church decides what’s best.

**Comment by cabal95** [comment]
@edmistj can you expand a bit on what you are thinking for the block setting? Are you thinking a toggle between current functionally (only works on desktop) and disabling click to call (only works on mobile) or some in between toggle option?

**Comment by edmistj** [comment]
The block setting would be:

Mobile Click-to-Call:
+ Use Server Click-To-Call
+ Use Mobile Device

**Comment by cabal95** [comment]
Okay, so if a church wants to be able to do have some users be able to click-to-dial from desktop browser and some users be able to tap the phone number from their mobile phone, they would need a custom solution?

**Comment by edmistj** [comment]
No, the proposed setting would only impact mobile devices. Basically say, "If you're a mobile device, do you want the device click to call  or server side click to call."

Desktop would always be server click to call.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
