### ISSUE TITLE
Error storing attendance manually when location is not a child of a campus

### ISSUE THREAD

**Issue by mikejed** [SparkDevNetwork/Rock#2940]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When using the `GroupAttendanceDetail` block for a location which is not a child of a campus, saving the attendance causes an error, since `locationService.GetCampusIdForLocation( _occurrence.LocationId )` returns 0 instead of null or a valid Campus Id

### Steps to Reproduce

1) Create a location which is outside of the campus hierarchy.
2) Set that location in a group Meeting Details
3) Visit that group in Group Viewer, and click the "Attendance" button.
4) Add an occurrence
5) Select the location which is not "under" any campus, and choose someone to mark as present.
6) Click Save

**Expected behavior:** 

Attendance is stored

**Actual behavior:** 

Attendance is not stored; instead the following error occurs
![image](https://user-images.githubusercontent.com/6932047/38833095-6bcecaa6-4179-11e8-9886-7e043cdc4136.png)

### Versions

* **Rock Version:** 7.3, v8 prealpha
* **Client Culture Setting:** EN-US

**Comment by cabal95** [comment]
Dev Notes: The LocationService.GetCampusIdForLocation() method seems to assume that at some point up the chain a Campus location will be found. But it is perfectly valid to create a top-level location, not tied to a campus. For example, you might have a group of people that meet at the local park to do bible study and jogging, but it's people from various campuses so putting it under a "campus" location doesn't make sense, therefore you create a top-level location without a campus for it.

The GetCampusIdForLocation() method should probably be switched internally to deal with `int?` values instead of `int` (therefore the `FirstOrDefault()` method will return null when not found), or a simple check at the end and if the `locationId` is 0, return null instead.

**Comment by ethan-sparkdevnetwork** [comment]
GetCampusIdForLocation() will return the campus ID if it exists or null;
