### ISSUE TITLE
Print Label for each Location doesn't work

### ISSUE THREAD

**Issue by lpeterson1** [SparkDevNetwork/Rock#2941]
Before completing your first issue we highly recommend reading this post on [Effective Ways To Get Help from Maintainers](https://www.snoyman.com/blog/2017/10/effective-ways-help-from-maintainers).

### Prerequisites
* [ x] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A check-in label selected to print once **per location** prints once **per child** instead.

### Steps to Reproduce

1. Create a simple test label.
2. In the label definition, choose to print it for each location. Assign it to a check-in area.
3. Using family check-in, check multiple children from one family into one location.

**Expected behavior:** 

One test label **per location** should print

**Actual behavior:** 

One test label **per child** prints

I tried various check-in settings on the demo site, and nothing changed. When I elected to print the test label **per family** it printed once for the family as expected.

I think there might be some confusion about printing per location. The _Checking Out Check-In_ guide says that the stock note label should print once per location by default, but this label has per-child information on it, so it doesn't seem to make sense that it would print once per location.

### Versions

* **Rock Version:** 7.3
* **Client Culture Setting:** en-us

**Comment by azturner** [comment]
@lpeterson1, even though multiple people may be checking into the same location, Check-in still considers that different locations due to how it stores it's object hierarchy: 

Family
  Person
     Group Type
         Group
            Location
                Service Time

The "Once per Location" was actually the default behavior for all labels before "Per Person" and "Per Family" were added with the addition of "family" check-in. "Per person" now lets you print just one label for each person, even though they may be checking into multiple groups/locations/services. And same thing for "Per Family" since that is the top-level, it can then just print one label even though there may be multiple person/group/location/service times.

We'll look at the documentation and see if we can clear that up a bit.

**Comment by lpeterson1** [comment]
@azturner So I think I'm understanding you to say that if a person checks into multiple groups/locations/services the "per location" setting will print one label for each location a person checks into, i.e. one person will get multiple labels, where with "per person" selected they'll only get one. Correct? Thanks for explaining.

**Comment by azturner** [comment]
Yes, that's correct.
