### ISSUE TITLE
Migration Timeout is Too Short

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#2951]
### Description
When doing a V7 update, I noticed that the update never completed. After viewing the _Migrations table, I identified the migration it was stuck on was for Communications. Upon further investigation, the Exception table had a lot of "timeout" errors. I ran a quick `Select Count(*) FROM [Communication]` and noticed that it over 5 million records.

I confirmed it was timing out by running the following SQL
`sp_who2 'active'`

`SELECT TOP 50 * FROM [ExceptionLog] ORDER BY [Id] DESC`

Ideally, I think it would be great to move the timeout setting from here: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.Migrations/Migrations/Configuration.cs#L31

into here: **web.config**

This would not only give you the ability to manually tweak the setting, but you guys could update web.config right before a large update to ensure this kind of thing doesn't happen.

### Steps to Reproduce
1. Create a lot of communication
1. Do V7 update

**Expected behavior:**
V7 update to complete without any issues

**Actual behavior:**
V7 update times out

### Versions
* **Rock Version:** 6.10 going to 7.0
* **Client Culture Setting:** en-US

**Comment by tscrip** [comment]
**Note:** the only way I got this to run was going from 8GB of RAM to 24 GB.
I also made a slight modification to Global.ashx.cs to increase the timeout. @cabal95

**Comment by cabal95** [comment]
We ended up setting the command timeout to 900 seconds and that got it through the `ALTER TABLE ADD CONSTRAINT` statement that was causing the problem. I don't think this has anything to do with v7 being a "huge update" as it was this one single statement that was taking over 300 seconds to run which was causing a timeout. I would suggest the default timeout be updated to 900 seconds for migrations and potentially a web.config option to set the migration timeout rather than having to resort to modifying code.

**Comment by edmistj** [comment]
@tscrip Could you verify for us when you did the update and was it in Alpha, Beta or Production. We thought we fixed all the performance issues in the migration, but maybe there's still more to do.

**Comment by tscrip** [comment]
@edmistj This was a Production update. I preformed the update on 4/24.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
