### ISSUE TITLE
Communications Enhancement

### ISSUE THREAD

**Issue by rutledgek** [SparkDevNetwork/Rock#2962]
With the advent of the communications wizard and email templats, there are a few suggestions that I think would bring Rock on Par with ease of use when sending out bulk email. I propose the creation of a couple of additional Communication Attributes.

Preview Text: Web browsers naturally show the first 2 lines of an email in the preview text. A preview text attribute would allow you to easily insert text into the top of the email that is set at a font-size of 1px.  The email client would still see its presence and use it as the preview text, but the body of the email would not be affected.

UTM Campaign Builder:  I know that not everyone uses google analytics, and I don't know if other analytics companies use the same code, but adding campaign information in the building of the email that is then appended to each link in the email would be a helpful way of implementing analytics for communications.

Example:
![campaign url builder google analytics demos tools - google chrome 2018-05-02 08 59 36](https://user-images.githubusercontent.com/24379548/39524648-98c1f31a-4de7-11e8-82b9-79c361056c9e.png)

While I know how to create atributes for all of these things, I do not know how to do the work of appending them to the email(preview text) or appending them to all links(UTM).

**Comment by edmistj** [comment]
Thanks @rutledgek, both of these are on the future feature list. In fact the UTM codes have already been added to the Interactions table to support this.

**Comment by nairdo** [comment]
@rutledgek  I know Jon mentioned it's on the future feature list, but we now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
