### ISSUE TITLE
[EN] Add keyboard shortcuts to Transaction Matching block

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3092]
# Feature Request
**Describe the Feature Request**
As a Finance Admin quickly sorting through a large batch of transactions to match, a keyboard shortcut would be helpful for `Assign to New` (with focus set on the name search input).  Subsequent tab order should already be set on the fund options.

![screenshot 2018-06-25 12 44 07](https://user-images.githubusercontent.com/1210933/41863792-dd672108-7875-11e8-9600-4f4fe44b5a4f.png)

**Describe Preferred Solution**
The current keyboard shortcuts on grids and other Rock pages follow the pattern of `AccessKey="s" ToolTip="Alt+s"`.  I don't know if the PersonPicker supports the `AccessKey` property but could be added.

**Describe Alternatives**
Continue to use the mouse to select Assign to New.

**Providing Code**
I will provide code if feature request is approved: TBD

**Comment by edmistj** [comment]
I would implement it like the Group Member Add block. If no one exists in the `Individuals` drop down then have the `Assign to New` person picker auto open. with the cursor in the textbox.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
