### ISSUE TITLE
[EN] Make Number Input Not React to Scrolling

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3098]
### Description

The new "up/down" arrows at the end of number input fields introduced in 7.x are becoming problematic. They react to a mouse scroll, which allows inadvertent input of crazy numbers you didn't intend to enter.

### Steps to Reproduce

1. Edit a batch control amount, or any other place that has a new-style number input
2. Scroll up or down and notice the values change
**Expected behavior:**

Numbers would only change if I enter them, or explicitly click the up/down arrows

**Actual behavior:**

Depending on your mouse type, you can easily enter bogus numbers into such a field by attempting to scroll the page when the field still has focus.

Here's an example where I was changing the approval threshold on the communication wizard, then tried to scroll down but the field still had focus.
![image](https://user-images.githubusercontent.com/3903408/42111851-6687ca68-7bab-11e8-9b3b-dd4103ba7d12.png)

### Versions

* **Rock Version:** 7.x-8.0

**Comment by Tschrock** [comment]
This is a built-in feature of browsers for number input fields (and a lot of native UIs have this behavior as well). I think Rock used to use text input fields for numbers which is why this didn't show up before. From my limited testing, both Chrome and Firefox have this behavior and Edge and IE don't. In the case of Chrome/FF, this only happens when the input is focused and the pointer is over the input. Edge and IE seem to just treat it as a text input. I'm not sure the best thing to do here since [some people would consider it a bug if it _didn't_ behave like this.](https://bugzilla.mozilla.org/show_bug.cgi?id=1261673)

That said, there does appear to be some ways to override this behavior, though they come with their own issues like preventing the page from scrolling or unfocusing the input field (see: https://stackoverflow.com/questions/9712295). If you want a quick workaround for your whole site, you can stick the following Page Header Content in the Advanced Settings for the Site:
```html
<script>
$(document).on("wheel", "input[type=number]", function (e) {
    $(this).blur();
});
</script>
```

**Comment by garrettjohnson** [comment]
Fixed via https://github.com/SparkDevNetwork/Rock/commit/2b1eb14f2e6e47c7aa044d20fb9bba2f52ee299b
