### ISSUE TITLE
Add support for inherited fundraising group types to Fundraising blocks

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3111]
# Feature Request
**Describe the Feature Request**

Currently if you want to create inherited Fundraising Group Types, for example to have different groups have different attributes defined, you cannot really use them with the fundraising system as they do explicit checks for the fundraising group type id.

Requesting enhancement to allow for those inherited group types to work with the existing fundraising blocks:

* Fundraising List
* Fundraising Progress
* Fundraising Donation List
* Group Detail (currently has partial support for only 1 level deep)

**Describe Preferred Solution**

The majority of the solution would be to add a new method to `Group` entity called `IsGroupOfType` that checks the (cached) group type inheritance tree to see if the indicated group type id is in the inheritance tree of the group.

The individual blocks would then use a check of: `if ( group.IsGroupOfType( fundraisingOpportunityTypeId ) )` to see if the group is "of fundraising group type".

**Describe Alternatives**

No alternatives really considered. Other options would be to put explicit inheritance check code in each block, which seems silly.

**Providing Code**
I will provide code if feature request is approved: **YES**

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
