### ISSUE TITLE
Clean up HTML Content block versioning

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3116]
# Feature Request
**Describe the Feature Request**
The versioning system in the HTML block does not have a mechanism to "clean up" old content. This leaves lots of rows laying around for no purpose, and keeps content in the db that you might want deleted.

**Describe Preferred Solution**
It would be nice to have the ability to selectively delete content rows (when viewing content history). It might also be useful to have the block ask "do you want to delete existing content history?" or similar when you _had_ versioning enabled and you subsequently _disable_ it. At that point, in most cases you're disabling versioning because you decided you don't want/need it on that block, but all of those old versions still hang out in the db... forever.

**Describe Alternatives**
To my knowledge there is no mechanism beyond SQL to clean up old content versions.

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
