### ISSUE TITLE
Update Event Registration note to have a link back to registration, to match history entry

### ISSUE THREAD

**Issue by luke-infoministry** [SparkDevNetwork/Rock#3121]
For timeline notes created programatically due to event registrations, it would be nice if that note were a link back to the originating event registration.

**Describe Preferred Solution**
For event registrations, notes are inserted on the timelines of the registrar and registrant (if they are separate).  Desired behavior would be that the event registration name on the note would link to the originating event registration details page.  Right now historyService adds the link to history as a URL back to the registration, noteService just provides a string.  Pretty please make the note text also a link to the registration?

**Providing Code**
It's somewhere on Registration.cs between lines 397 - 482, maybe as many as 3 places, in the formatting of what gets written by noteService

I think it has to do with using registrationInstance.Name (used in Note) rather than Rock.SystemGuid.Category.HISTORY_PERSON_REGISTRATION.AsGuid() (used in History)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
