### ISSUE TITLE
Calendar-Audience Filter not honoring selections

### ISSUE THREAD

**Issue by winmastr** [SparkDevNetwork/Rock#3140]
The block ignores the filter settings on the Lava Calendar. 

Select the Filter Audiences type defined values for calendar items as they are created.
Using the Lava Calendar Block, select only one of the audience types (we selected kids). When viewed, the block includes Youth, Mens and Womens audience Items that are not slected in that calendar view block settings.

**Expected behavior:**
Expect that if only Kids Audience types are selected, that what we would see.

* **Rock Version:** [7.4]
Windows 10 clients using both Chrome and IE

**Comment by mikejed** [comment]
The `Filter Audiences` option that you're using, only sets which filters are available _to the end user_ for filtering the calendar. This change isn't obvious if that's all you change, because the default `Audience Filter Display Mode` (just above it) is set to Hidden by default.

If you set `Audience Filter Display Mode` to something besides Hidden, the use becomes more clear: the user will be able to choose an option to show only events geared toward a particular audience.

![image](https://user-images.githubusercontent.com/6932047/43165880-e0719afa-8f49-11e8-95f5-b0065aae990b.png)

results in:
![image](https://user-images.githubusercontent.com/6932047/43165889-edf6489c-8f49-11e8-9af3-6543a725dd7b.png)

**Comment by mikejed** [comment]
One more note: if you want a particular page to always show only events for a particular audience, you _may_ be able to do so by modifying the Lava template which that block is configured to use by default, and only output the event information if it is set to the audience you're interested in showing.

However, that would not prevent other events on the calendar from making the dates on the mini-calendar boldface
