### ISSUE TITLE
Statement Generator - Event Registration Transaction Type

### ISSUE THREAD

**Issue by BemaDavidBensen** [SparkDevNetwork/Rock#3143]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The transaction type "Event Registration" check box does not change if transaction types of event registration show up on the statement

### Steps to Reproduce

1. Go to 'Statement Generator application '
2. Click on 'Check mark "event transactions" - Step 6 (advanced)'
4. Generate the statment and notice that those transactions are still not showing up

**Expected behavior:**

If the Event Transactions, Transaction Type is selected, "event transactions" in the checked funds should show up on the statement  

**Actual behavior:**

All transactions with the event transaction type are not included in the statement 

### Versions

* **Rock Version:** [7.3]
* **Client Culture Setting:** [en-US]

**Comment by mikejed** [comment]
@BemaDavidBensen , I just tested this functionality on my own server. Granted it's 7.4, so it may have changed/been fixed.

I selected "Event Registrations" in step 6, and got a printout with only my two event transactions for the year (that is, it showed those transactions and also left off all of my contributions, as expected).

Please note that frequently event registrations are assigned to a different account; please be sure that the Event Registration account (if any) is selected in the accounts selection box. You will most likely have to tell the software to show non-tax-deductible accounts in the list to see it (since event registrations are usually not tax-deductible). Reopen this issue if it's still not working, especially if you're able to test on 7.4 (which is presently the latest update)

Thanks
