### ISSUE TITLE
Set "Campus" filter on Dynamic report from authenticated user's family "campus" value

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#3145]
# Feature Request

**Describe the Feature Request**
In cases when dynamic reports have a Campus value, we would like to have an empty campus selection replaced with a "smart" preset.

**Describe Preferred Solution**
Within the scope of Dynamic Reports, we would like to pre-set the "campus" filter's value to match the Campus assigned to the authenticated user's Family campus. Pulling from the Family campus seems to be the most likely default way to identify what campus' data the authenticated user is likely to be working with.

**Describe Alternatives**
We are open to sourcing the campus from another location, such as a person attribute, though at this time we don't have such an attribute. Since the scope of this request is limited in usefulness to our staff (the people accessing the reports), we could consider a "staff primary campus" person attribute or something of that nature.

**Providing Code**
No

**Comment by mikejed** [comment]
This seems most easily accomplished if the Dynamic Report block were modified to accept URL Parameters to pre-set available filters. Otherwise, this is one of those features that every church would want to work a little differently _(default to people with no campus? Default to people with any campus? Default to people with the same campus as CurrentPerson? and what about non-campus filters? All such requests would have to be one-off improvements)_

If the dynamic report block respected/used parameters from the URL in order to set filters, you could add a bit of Lava to the page which would check for the existence of such a parameter, and if it doesn't exist, reload the page with the parameter set. Among other use cases such as providing links to pre-filtered versions of the page. So I'll mark this as an enhancement request, with my recommendation that if the block is modified to accept URL parameters, you use Lava to auto-set the filter as you wish it on your page.

**Comment by kenmulford** [comment]
Yeah, that's a great idea Mike. We would be totally fine with that.

**Comment by kenmulford** [comment]
@mikejed Thanks for all of this! It is very helpful!
