### ISSUE TITLE
Group-based Data Views - add ability to filter on Campuses?

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#3146]
# Feature Request
**Describe the Feature Request**
We would like to situationally select multiple campuses from the Campus filter on a dynamic report.

**Describe Preferred Solution**
When adding "Campus" to a report record, provide the option to designate the Campus filter as either single-select or multi-select. Current behavior allows the user to either select a single campus or to disable the filter (which includes results from all campuses). We have scenarios where users will work with multiple - but not all - campuses.

**Describe Alternatives**
If the location for this setting belongs on the data view filter or on the dynamic report filter configuration, that's fine as well. The main goal is having an option to allow the user to optionally select multiple campuses.

**Providing Code**
I will provide code if feature request is approved: [Yes/No]

**Comment by mikejed** [comment]
@kenmulford if you use the `Campuses` filter in your DataView rather than `Campus`, I believe you'll get exactly the multi-select option you're looking for:

![image](https://user-images.githubusercontent.com/6932047/43272598-3c9d377e-90af-11e8-86c9-e90a8215c70e.png)

Additionally, you can "pre-filter" the Dynamic Report using `?CampusId=2,3` in the URL (thinking of the other request from yesterday).

**Comment by kenmulford** [comment]
@mikejed My Data View is based on the Group entity, and the Group entity does not have a "Campuses" filter type. It only has "Campus" (single select). I'd like to re-open this enhancement.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
