### ISSUE TITLE
Allow Event Registrations to use more than one Discount Code

### ISSUE THREAD

**Issue by ajfick** [SparkDevNetwork/Rock#3150]
# Feature Request
**Describe the Feature Request**
Allow a registrant to use more than one discount code on a registration. This would be particularly useful for giving Staff Discounts for families along with other discounts for trips and events. 

**Describe Preferred Solution**
Allow users to register with more than one discount Code.
Allow Administrators to determine if a specific discount code can be used alongside other codes.
Make sure that codes can not result in negative amounts owed!

**Describe Alternatives**
Allow Administrators to tell Rock that if a specific person registers, their price should be different either from a person dataview or from a person picker in the discount section. 

**Providing Code**
I will provide code if feature request is approved: No, though I would be more than willing to help collaborate to create the best possible solution!

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
