### ISSUE TITLE
Show badge of plugin updates

### ISSUE THREAD

**Issue by taylorbrooks** [SparkDevNetwork/Rock#3153]
It would go a long way to have a little badger next to "Purchases" under the Store Links menu that shows plugins that are available to update.

![](https://user-images.githubusercontent.com/117657/43488473-8bdd41b0-94df-11e8-8c3c-adafda287a2b.png)

**Comment by kld3207** [comment]
YES!!! Over the past couple weeks, I spent too much time trying to resolve errors with two separate plugins.  When I reached out to the developers, the answer to both errors was "install the update".  We only have three plugins now, but I can imagine how much time this would save once I have more.

**Comment by cabal95** [comment]
I agree this would be a helpful addition. But as a short term solution, there is a plugin in the Rock Shop that will notify you of new plugin releases as well. It's called `Rock Shop Notifications`.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
