### ISSUE TITLE
Scheduled Transactions do not include Entity Information

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3172]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues) to see if your bug or enhancement is already reported?

### Description
Let's say that you are running a Fundraising Opportunity for your church. When someone gives to a Fundraising Opportunity, they have the ability to select a person to give to. Behind the scenes, it sets the EntityType to 90 (for Group Member) and the EntityId to the Group Member Id.

When you make a one time donation, everything seems to be working perfectly. When you do the same process but scheduled, the EntityType and EntityId get created on the Scheduled Transaction Detail (FSTD) correctly, but the Transaction Detail (FTD) is missing it's Entity information.

### Steps to Reproduce
1. Create a Fundraising Opportunity with a person in the Group.
1. Make a regular transaction to the person and notice the Entity fields in the FTD table are there.
1. Make a scheduled transaction to the same person and notice the Entity fields are in the FSTD table.
1. Run the ProcessPayment job to generate the Financial Transactions.
1. Notice the generated FTD does not have the Entity fields.

**Expected behavior:**
FSTD Entity fields should be passed to "child" FTD.

**Actual behavior:**
FSTD Entity fields are not passed to "child" FTD.

### Versions
* **Rock Version:** 7.4
* **Client Culture Setting:** en-US

**Comment by treyhendon** [comment]
Just testing this with someone today in 1.8.3 and I've found that the FinancialScheduledTransactionDetail does not get the EntityType or EntityId set when using the Transaction Entry block.  `SaveScheduledTransaction()` does not exercise `GetTransactionEntity()` to set the details in the FinancialScheduledTransactionDetail.

I've hot-fixed this on someone's server, and if Core is ok with it, I'm happy to submit a pull request for the Transaction Entry block to set the entity info on the FinancialScheduledTransactionDetail.

Regarding the expected behavior listed above - FinancialTransactionDetail including the EntityType and EntityId from the FinancialScheduledTransactionDetail, that is deeper in the Rock code. Specifically somewhere in this loop, the EntityType and EntityId would need to be set: https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.8.4/Rock/Model/FinancialScheduledTransactionService.Partial.cs#L434

Not sure if Core wants the deeper change in `ProcessPayments()` but I'd be happy to submit that as well.

For what it's worth @tscrip I'm going to use a Job running SQL to mark the entity info in the FinancialTransactionDetail table for any rows which came from a scheduled transaction with entity details set once we manually add the missing entity info to the scheduled transactions.

**Comment by jennifertroeger** [comment]
Any update on having this fix implemented? This is a big one for us!

**Comment by edmistj** [comment]
@jennifertroeger I'll assign a developer to get this into v8.6.
