### ISSUE TITLE
Merge Duplicate Businesses

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3186]
# Feature Request
**Describe the Feature Request**
We have had instances where duplicate business are created in the system because of the giving data people have entered.  At present we can move the giving records, but there is no way to merge the two business records to remove the duplicate.  It would be nice to have a Merge feature on the Business list screen.

**Describe Preferred Solution**
I would prefer a Merge option on the Business List screen.

**Describe Alternatives**
A delete option when there are no financial transactions associated with a Business would be another alternative.

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
