### ISSUE TITLE
Provide a total results in Data View preview modal

### ISSUE THREAD

**Issue by stevelipinski** [SparkDevNetwork/Rock#3192]
# Feature Request
**Describe the Feature Request**
The current Data View previews selects the top 15 rows.  However, without saving the new/changed DV, one cannot tell how many total rows will result.  It would be very convenient if the preview title bar (or somewhere else) contained the total matches for the DV - e.g., (top 15 of 1254)

**Describe Preferred Solution**
(top 15 of XXX) in the DV preview modal title

**Describe Alternatives**

* Include total elsewhere in the Preview modal - e.g., bottom row, near the dismiss button, etc.
* Dynamically/Automagically updated HTML element in the DV editor
* Using a Count button (next to Preview button) on the Edit page with either a JS-updated HTML element or a count modal.

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
