### ISSUE TITLE
New Batch List Filter: Contains Source Type

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#3214]
# Feature Request
**Describe the Feature Request**
This adds a new filter to the BatchList block called "Contains Source Type".  This filter will only display batches that contain transactions with a specific source type.  This is similar to the "Contains Transaction Type" filter.  Christ's Church of the Valley has been using this filter for several years and would like to offer it back to core.

![image](https://user-images.githubusercontent.com/2349102/44596923-cce5cf00-a782-11e8-89a8-e9e8e75508bd.png)

**Describe Preferred Solution**
Adding the filter.

**Describe Alternatives**
N/A

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
