### ISSUE TITLE
Shortlinks with matching routes go to the wrong site

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3230]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description
When you create a Route on one site and a Short Link with the same name on a different site, the short link will be ignored and it will always follow the route no matter what site you're on

### Steps to Reproduce

1. Create a short link of `testlink` on the external site.
2. Create a route of `testlink` for a page on the internal site.

**Expected behavior:**

`externalsite.com/testlink` follows the short link on the external site.
and
`internalsite.com/testlink` goes to the page on the internal site.

[2/12 Update: In all cases, if "testlink" does not exist, it should go to the configured 404 page of the matching site.]

**Actual behavior:**

Both URLs go to the page on the internal site.

### Versions

* **Rock Version:** 7.5
* **Client Culture Setting:** en-US

**Comment by MikeDPeterson** [comment]
Undid fix since it introduced an issue where all page routes were all showing lowercased in the browser

**Comment by ethan-sparkdevnetwork** [comment]
See commit: https://github.com/SparkDevNetwork/Rock/commit/d975959cf86a9499e293487269679fee2781ec33

There were two issues going on:
1. Having the same route name on two different sites with different casing (e.g. "internalsite.com/testpage" & "externalsite.com/TestPage") would cause all requests to go to the first route created, restarting Rock would not resolve this issue.
2. When a new route is created for a page it would not got to the intended page if the same route already existed on another site until Rock was restarted.

The global.asax.cs registered the routes stored in the page route table by building a collection using Linq with the GroupBy function on the route name. This worked fine except when casing differed, in which case it sometimes worked depending on what the compiler decided you meant. For instance "TestPage" and "testpage" would be grouped separately but "aTestPage" and "atestpage" would not. The normal work around for this would be to use ToLower() when doing the compare in Linq, but that would not do much to solve issue 2.

Issue 2 is a problem because the PageProperties and PageRouteDetail do not even try to group routes and pages, it just adds and deletes them from the collection. The result is the first matching route in the route table is used and our site logic in the RockRouteHandler is not used because there is only one page for the route. This problem would self resolve when Rock was restarted, as the global.asax.cs would group the routes.

I updated RoutePageExtensions.AddPageRoute() to not take a collection of PageAndRouteIds but only a single one. The method would check for an existing route name (case insensitive) in the route table and add to it if it already exists.

Updated global, PageRouteDetail, and PageProperties to use the new extension and presto, routes are grouped appropriately and everything works without needing a restart.

The RockRouteHandler will select the page in the following order:
1. PageId
2. Route match and site match
3. ShortLink match and site match
4. Route and no site match
5. ShortLink with no site match
6. If there is no routing info in the request then set to default page
7. 404 if route does not exist

**Comment by JimMichael** [comment]
While testing 8.7beta, I am still able to reproduce the original issue as described. 
1. I created a shortlink of `www.externalsite.com/testlink` to a page on the external site.
2. Tested #1 and ended up at the right page
3. Added `testlink` as a route on an internal page.
4. Now browsing to `www.externalsite.com/testlink` takes me to the internal page.

**Comment by ethan-sparkdevnetwork** [comment]
After further testing and review the routing is working correctly.

**Comment by JimMichael** [comment]
Yes, my apologies. Classic ID10T error on my part.

**Comment by edmistj** [comment]
We all miss a detail occassionally. Your track record though is pretty stellar. We appreciate all you do!
