### ISSUE TITLE
"Label Field" On Group Does Not Override Group Type Label

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3265]
### Description
The docs describe a method for having a different label print for a specific group vs. the one defined on the Check-In area the group belongs to, in the _Label Field Type in Group Attributes_ section here https://www.rockrms.com/Rock/BookContent/10/140#appendixadvancedoptions

The label added to the group in this way functions fine, _except_ that both the group-specific label _and_ the one already defined on the group type (Check-in Area) _also_ print, which (while not stated specifically) is implied should not happen, and it doesn't make sense that you'd want both to print.

### Steps to Reproduce
1. Identify a group type that has a check-in label (e.g. Serving Team) that prints, but you want a different label to print for this specific group.
1. On the Serving Team group type, add a Group Attribute of type Label and choose the desired label (but different from the one the group type prints)
1. Clear cache, then check in as someone in the group and observe that BOTH the default (check-in area/group type) label AND your new group-specific label print.

**Expected behavior:**

Only the label specified on the Group (or Person, as that is also an option) should print, and should override the label(s) defined on the check-in area/group type the group belongs to.

**Actual behavior:**

Both labels print.

### Versions
* **Rock Version:** 7.4-8.3

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1133745773957034">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1160629670750046">image.png</a>

**Comment by lpeterson1** [comment]
I'm not sure it's safe to assume that the group label should automatically replace the group type label. If a group type has multiple labels, like most children's types do, which of the labels would be replaced? It seems that there would need to be some sort of functionality that presents the user with choices (replace or not, and which one(s)).

**Comment by JimMichael** [comment]
Well, the way I think it should work is that it should not “replace” any labels, but completely _override_ them. If I choose a specific group-level label, _none_ of the group type labels should print. Even the example in the docs where you put a label on Person attribute so that you can prevent them from checking in (they get a “banned” label or similar) only makes sense if the _normal_ labels that would print (all of them) did not in fact print, and only the one on the group/person printed. 

It’s not clear if adding multiple label attributes to a group/person makes them all print, but if it does that would solve any problem of “replacing only one” label because you could just define the others on the group/person as well.

**Comment by BEGamache** [comment]
I agree, it sounds as though if there is a label on the group then the Group Type label(s) should be ignored and the Group label(s) should be used instead, since that group was set a specific way (different from the group type). 

We have a Special Events Group Type where the majority of the groups use a general participant tag but there are some groups/events that have their own labels (usually these are special cases for events that happen once or twice a year but have uniquely designed labels). Setting labels on the group so that they override the Group Type's labels would be beneficial and efficient since I currently have to revert the Group Type label back to its original label(s) the day after the event.

**Comment by cj-walk** [comment]
Agree with Jim Michael. In setting this up I assumed the label added to the group would override the label on the group type. I think my 2 options are 1)completely restructure my checkin groups so that different labels can be used for adults than for the children; 2) remove/add a different label with each different meeting type. I guess I should have fully tested this before I let the leaders tell me what they required on their labels. Really hope this is a bug and can be fixed.

**Comment by jsw-austin** [comment]
manual has been updated to say, "Note: this label prints in addition to the labels printed for the area, or group type."

**Comment by cj-walk** [comment]
I don't see any updates in release documentation on this label issue. I see the post above saying that the manual has updated wording but that's not really a bug fix. @JimMichael has the right idea. Any plans to work on this?

**Comment by nairdo** [comment]
Hi @JimMichael  and everyone... we've talked this over and it is working as it was intended.  It is _not_ an override, it will print these labels _in addition to_ any others.  We've updated the admin manual again to make this even clearer and removed the misleading example that was in that section.  I'm **very sorry** if we gave you the wrong impression about how it was going to work and I hope that you forgive us.
