### ISSUE TITLE
Contribution Statement Lava Does not Satisfy Pledge from Child Accounts

### ISSUE THREAD

**Issue by treyhendon** [SparkDevNetwork/Rock#3273]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
The Contribution Statement Lava block Pledges are only loaded as `t.AccountId == pledge.AccountId`.  This causes the Pledge balance to not reflect contributions to child accounts.

### Steps to Reproduce
1. Create a parent Account for CC and a child account for Cash/Checks.
1. Create Pledge against the parent (CC) account.
1. Create transactions against both accounts.
1. Open lava statement and see that only the CC gifts are credited to the pledge.  (However in pledge analytics it is satisfied.)

**Expected behavior:**

Transactions to child accounts should be recursively credited to the parent account (like the pledge analytics SP).

**Actual behavior:**

Only transactions to the one account are included in the pledge balance.

### Versions
* **Rock Version:** 1.7.4.57
* **Client Culture Setting:** en-US

**Comment by jennifertroeger** [comment]
We use child accounts often; this would be a great help!

**Comment by jennifertroeger** [comment]
We have found that our online statements are incorrect because we have a non-cash pledge child account and these amounts are not rolling up and being accounted for. Some people will purposefully log in to re-print or compare the statements (the printed statement is correct), so this can be a big deal at tax time. Would love to see this fix rolled out in the near future.

**Comment by MrUpsideDown** [comment]
The Contribution Statement Lava block has been marked as [Obsolete] as of v1.12.4, when it was superseded by the ContributionStatementGenerator component. The generator includes a configuration setting which specifically addresses this situation: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Financial/FinancialStatementGeneratorHelper.cs#L713
On that basis, this issue is being closed.
