### ISSUE TITLE
Person not being listed in Name Search quick results

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3325]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

Don't know how to reproduce this yet.  I've had a quick look in the demo but can't see this happening.

### Description

I have a situation where names are not showing up in the quick results on a name search.  

I do not yet know how to reproduce this.

### Steps to Reproduce
Example:
In our database we have a Person named Chris Villasis.
In the name search box, he shows up if I type "Chris v" but not if I type "Chris".

![name2](https://user-images.githubusercontent.com/4658177/46704198-665f3680-cc86-11e8-81fa-ad68226d08ce.jpg)

![name1](https://user-images.githubusercontent.com/4658177/46704194-5f382880-cc86-11e8-8633-38ead11190e0.jpg)

If I type "Chris" and press enter, he does show up in the Person Search results.
![name3](https://user-images.githubusercontent.com/4658177/46704229-82fb6e80-cc86-11e8-8fad-740b1450ea05.jpg)

This is happening for other names too:

![image](https://user-images.githubusercontent.com/4658177/46705616-c5c04500-cc8c-11e8-974d-4830ca7a6756.png)

We have "Allow search by first name" turned ON.

**Expected behavior:**

All names should be included in the search results.  

**Actual behavior:**

Some names not included in the quick search results.  Can't see any reason why they aren't.

### Versions

Rock Version: Rock McKinley 8.3 (1.8.3.36)
Client Culture Setting: en-NZ

**Comment by cabal95** [comment]
The quick results popup is limited to 15 results. So the issue you are running into is just that "Chris Villasis" is not contained in those first 15 results. The same happens to me on our database when I search for "Daniel". We have a lot of daniel's and it picks 15 to display, but does not include me. I don't know what order this uses, it may simply be ordered by Person Id. But, it's working as intended. If I type "Dan" in the search field, I would not want all 5,000 records in our database that match "Dan" to show up in the quick results bar.

The purpose of the quick search results is so that if they do type "chris v" and see the exact name they want, they can click the name instead of having to type the rest.

**Comment by ElimAdmin** [comment]
Ah! Okay, thanks for the explanation @cabal95 and the quick response.  That's a trap for newbies. 

(Can you please edit your reply to take out Chris's surname so it doesn't get indexed.  Thanks.)
