### ISSUE TITLE
[EN] Default Page Menu lava files should support Include Page List pagesg

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3326]
### Prerequisites
* [x] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
The Page Menu block is not showing pages that are added to Include Page List block attribute.
In testing I have tried to add a page named Locations using ~/page/267 but haven't been able to get this to show up in the lava templates. After adding it I have refreshed and cleared cache thinking that may be what is preventing the added pages from showing but those actions haven't helped.

These are the lava templates I have tried: 

```
{% include '~~/Assets/Lava/PageListAsBlocks.lava' %}
{% include '~~/Assets/Lava/PageListAsTabs.lava' %}
{% include '~~/Assets/Lava/PageNav.lava' %}
```

### Steps to Reproduce
1. Add Page Menu block to a page
1. Edit the block properties and add a page to the Include Page List field
1. Save settings.
1. Refresh page and/or clear cache and see if added pages are visible.

**Expected behavior:**

Additional pages listed be visible.

**Actual behavior:**

Only child pages are visible.

### Versions
* **Rock Version:** 8.3 (1.8.3.36)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
@BEGamache You have to customize the Lava to show these. They are available in a Lava variable called `IncludePageList`. The primary reason for this is that full Page information is not available because you are just providing a list of names and URLs, so they cannot be included in the normal `Page` variable which is used to traverse the page tree.

**Comment by BEGamache** [comment]
Great I'll add that to the template but shouldn't the Core Lava templates already have that in the code if the block allows extra pages to be listed?

**Comment by cabal95** [comment]
The problem comes from "where does it get displayed" I think. On top? on Bottom? Somewhere in the middle? Everybody would probably want it different. With "real" pages it's easy, just use the Order of the pages the user has defined. Since we are now mixing two arrays together things get a little more hairy.

I updated the title to more precisely reflect that the Lava files should be updated. Perhaps the default one (I forget which it is) should just include it in a `{% comment %}` section so that it at least shows how to do it. Not sure, I'll let one of the core guys weigh in on that particular point.

**Comment by BEGamache** [comment]
That sounds good. Thanks for updating the title.

I do think it should be included in the Lava templates, especially since there may be churches that don't have access to modify the lava templates or churches that may not know how to modify the templates.

I think adding the additional pages to the end would suffice and maybe use the order in which additional pages/links are created, if the code maintains that order, (i.e. if I press the Add button the first time, that becomes Order = 0. When I press Add again, the next one becomes Order = 1). That way if they want to move anything around, in the way of the additional pages/links, they just have to retype the Names and Links in the order they want it. I don't know how feasible that is though.

**Comment by cabal95** [comment]
If you do end up writing the Lava for your own use and want to post it here, that would be a huge help to whomever ends up working on this down the road. Any time we can save the core team a few minutes is a big win.

**Comment by BEGamache** [comment]
Here's something I came up with, posting with the rest of the lava content for context:
```
<div class="panel panel-default list-as-blocks clearfix">
	<div class="panel-body">
		<ul>
			{% for childPage in Page.Pages %} 
			<li>
				<a href="{{ childPage.Url }}" {% if childpage.displaydescription !='true' %} title="{{ childPage.Description }}" {% endif %}>
					{% if childPage.IconCssClass != '' %} 
						<i class="{{ childPage.IconCssClass }}"></i>
					{% endif %} 
					<h3>{{ childPage.Title }}</h3>
				</a>
			</li>
			{% endfor %} 
			{% for includedPage in IncludePageList %}
			{% assign pageInfo = includedPage | PropertyToKeyValue %} 
			<li>
				<a href="{{ pageInfo.Value }}" title="{{ pageInfo.Key }}">
					<h3>{{ pageInfo.Key }}</h3>
				</a>
			</li>
			{% endfor %} 
		</ul>
	</div>
</div>
```

If the Page Menu block allowed Rock Entity lava commands you could add the following code to try and pull the page icon if one is present and the link contained a page number.
```
{% assign pageId = pageInfo.Value | Remove:'/page/' %} 
{% page id:'{{pageId}}' %}
	{% if page.IconCssClass != '' %} 
		<i class="{{ page.IconCssClass }}"></i>
	{% endif %}
{% endpage %} 
```

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
