### ISSUE TITLE
[EN] Make Address Field in Pre-Registration Form Required or Optional

### ISSUE THREAD

**Issue by edcylam** [SparkDevNetwork/Rock#3329]
# Feature Request
**Describe the Feature Request**
Make the address field in the Family Pre-Registration form configurable: required, optional, and optional.  This is requested because our Family Ministry wants to mail new families physical welcome letters. 

**Describe Preferred Solution**
Make the address field configurable in the Family Pre-Registration block.

**Describe Alternatives**
None

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
