### ISSUE TITLE
[EN] Add Connection Status to one of the lines on the Following Event Notification email.

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3335]
# Feature Request
**Describe the Feature Request**

Please add Person Connection Status to the Following Event Notification email, so the Connection Status of the person can be clearly seen before we call them.

- - -
![notif6](https://user-images.githubusercontent.com/4658177/46991700-7df55e00-d163-11e8-8256-5eea733f57e6.jpg)

- - -
**Describe Preferred Solution**

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved: [Yes/No]     NO  (I wish I could...!)

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
