### ISSUE TITLE
[EN] Add 'Add Activity' button next to 'Complete' button on Connection Request Detail

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3364]
# Feature Request
**Describe the Feature Request**

To add an activity to a connection request on the Connection Request Details page, you have to scroll right to the bottom of the page to get to the (+) button.  Why not add an 'Add Activity' button next to the 'Complete' button in the top part of the screen?

And consider changing the button Edit to read Progress - this seems to be the real action of the button - to progress the Connection.

**Describe Preferred Solution**
![connection1](https://user-images.githubusercontent.com/4658177/47428202-0d97ae00-d7ef-11e8-8a98-923aa504a1a9.jpg)

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved:   NO

**Comment by NuclearTacos** [comment]
I know this isn't a substitute for this feature, but on windows (most browsers) Alt+N hits the plus button.  On Mac, Option+Control+N does the same.

And obviously, neither of those options matter on mobile.  It also might be possible to use CSS to jam an extra button in there, or at the top that does the equivalent of hitting those shortcuts.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
