### ISSUE TITLE
[EN] Show Group History For Security Roles?

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3381]
# Feature Request
**Describe the Feature Request**
I notice that you can enable Group History on a Security Role, but the Group Detail block does not show the History button when displaying a security role. Is this an oversight, or by design?

**Describe Preferred Solution**
I thought it would be nice to be able to have a history on security roles just like normal groups, so you could see who-added/deleted-whom-and-when type stuff for roles... but I'm unclear if there are security/info leakage issues that caused this to be _intentionally_ disabled for security roles, or if it's just an oversight.
![image](https://user-images.githubusercontent.com/3903408/47656701-8edba180-db5d-11e8-88f2-07562933bfe1.png)

I do notice that security roles (when History is enabled) DO show in the Person Group History block on Person profile page.

**Providing Code**
I will provide code if feature request is approved: No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
