### ISSUE TITLE
Dynamic Report block does not work with Workflow Attributes on Filters

### ISSUE THREAD

**Issue by jamrphy-bwd** [SparkDevNetwork/Rock#3407]
### Description
The Dynamic Report block does not work with Workflow Attributes. 

### Steps to Reproduce
1. Create a Data View (applies to Workflow) with filters for any workflow attribute 
1. Create a Report on the Data View. Column Selection is arbitrary.
1. Add the Dynamic Report block to a page. In the configuration, select the report from step **2**.
1. Make all selected Attribute and Property Filters Visible and Configurable in the Block Configuration.
1. See below for error behavior.

**Expected behavior:**

The page should load to show all filters marked "Visible" in the settings. Attribute-based filters should show selection mechanisms (i.e. a drop down list) based on the data type of the attribute. Clicking the "Reset Filters" link should clear the adjusted selections, but leave the form unchanged. Submitting the form via the "Filter" button should apply the selected filters from both properties and attributes to the underlying DataView and return the correct results through the Report. 

**Actual behavior:**

On load, the page shows the "Toggle" checkboxes for all attribute filters. However, the "Configuration" selection mechanisms are not shown. Clicking the "Reset Filters" link seems to correctly load the form (the Attribute Filter selects then show). Submitting the form via the "Filter" button applies Property-based filters to the results, but no attribute filters. The block reloads having cleared selections on attribute filters. The label for the attribute filters "Toggle" displays nonsense (perhaps an ID) such as "51fe9641-fb8f-41bf-b09e-235900c3e53e".

### Versions
* **Rock Version:** Rock McKinley 7.5 (1.7.5.59) and Demo Site (8.4)
* **Client Culture Setting:** en-US

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1162288533054823">image.png</a>

**Comment by BEGamache** [comment]
I was able to replicate this and got some slightly different results. 
Property filters do display in the filter section correctly. Attribute filters only show the checkbox and the attribute's GUID, no filter controls. Clicking Reset Filters does reload and display the missing attribute filters but since it is using the Attribute's GUID you don't know what attribute you are filtering on.

The results are not correct. In the Data View I created for testing, I only have one result that correctly displays. In the Dynamic Report there are 19 rows--all but one don't match the filters I placed in the Data View.  In further testing, when Visible, Configurable and Toggle Filter are not checked for the attributes in the block's settings, the results are correct.

<img width="749" alt="Screen Shot 2019-10-24 at 4 47 53 PM" src="https://user-images.githubusercontent.com/5738650/67529439-c9e5b780-f681-11e9-8844-5911a9e68c7c.png">

![screencapture-rock-rocksolidchurchdemo-page-19-2019-10-24-16_50_17](https://user-images.githubusercontent.com/5738650/67530050-8724df00-f683-11e9-9e9f-f522c161459d.png)



This is also where I got different results.  I tested this in v10 Alpha and when Visible, Configurable and Toggle Filter are check in the Dynamic Report's block setting it cleared the Data View filters I had on workflow attributes. I can setup the data view again with the proper filters but once I reload/access the page with the Dynamic Report it clears the filters in the Data View -- not the workflow fields, only the workflow attribute values filters. As a result of it altering the data view's filters I don't have proper filter controls in the Dynamic Report block.

In v9 it didn't alter the Data View but in v10 it alters the Data View by clearing out attribute filters.



Data View before:
<img width="868" alt="Screen Shot 2019-10-24 at 5 16 44 PM" src="https://user-images.githubusercontent.com/5738650/67530138-d10dc500-f683-11e9-90d0-28f92282f996.png">


<img width="755" alt="Screen Shot 2019-10-24 at 5 19 38 PM" src="https://user-images.githubusercontent.com/5738650/67529840-f5b56d00-f682-11e9-98ac-d02f898f1e22.png">



Report Before:
<img width="893" alt="Screen Shot 2019-10-24 at 5 17 19 PM" src="https://user-images.githubusercontent.com/5738650/67529821-e504f700-f682-11e9-9593-1cb271afbbe4.png">


Dynamic Report Block:

<img width="1188" alt="Screen Shot 2019-10-24 at 5 21 04 PM" src="https://user-images.githubusercontent.com/5738650/67530287-44173b80-f684-11e9-80a3-5573a3a0f3be.png">


Data View After Running the Dynamic Report:
<img width="889" alt="Screen Shot 2019-10-24 at 5 24 00 PM" src="https://user-images.githubusercontent.com/5738650/67529978-59d83100-f683-11e9-9064-b3b7e4f5216a.png">

**Comment by SteveSwaringen** [comment]
Seeing the same issue trying to reference a date attribute on a workflow. Running 10.2 and seeing the data view corrupted.
