### ISSUE TITLE
copy registration instance

### ISSUE THREAD

**Issue by karenn-ccbc** [SparkDevNetwork/Rock#3422]
# Feature Request
**Describe the Feature Request**
  Would like to be able to copy a registration instance. We have 27 classes of the same "event" that have the same contact person, event account, registration dates and maximum amounts. It would be great to copy those details and just change the name of the instance to the day and time of the class and add any other details needed. (This registration occurs every fall, spring and summer for us!)

**Describe Preferred Solution**
COPY an event registration INSTANCE 

**Describe Alternatives**
 Would need an ability to enforce limits on registration attributes or fees in an event registration to avoid having to create so many different instances so that a max limits can be achieved.

**Providing Code**
I will provide code if feature request is approved: [Yes/No] No ( I would if I knew how!)

**Comment by karenn-ccbc** [comment]
The copy Event occurrence in the calendaring section does not copy the contact person, location or schedule. Only copies the attached event registration. Seems like a bug.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
