### ISSUE TITLE
Connection Opportunity Sign-up block allows signing up for inactive opportunities

### ISSUE THREAD

**Issue by Tschrock** [SparkDevNetwork/Rock#3455]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Steps to Reproduce

1. Mark a connection opportunity as inactive.
2. Go to the signup page for that opportunity.

**Expected behavior:**

A message saying the Opportunity is inactive/unavailable.

**Actual behavior:**

You can sign up for the Opportunity.

### Versions

* **Rock Version:** 8.3, prealpha (1.9.0.9)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
Just for the record, because the "Connection Opportunity Search" block already hides inactive connection opportunities, you would have to have a link already to the details page (w/Connection Opportunity Detail Lava block).

Our recent change was to the ConnectionOpportunitySignup block but we're also going to make another change to the detail block to show a message there and disable the "Connect" button if the opportunity is Inactive.
