### ISSUE TITLE
[Slingshot] Update new group memberships for existing people and groups

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#3459]
### Description
When updating an install with a fresh copy of Slingshot data and "Always Update People" checked, if any existing people were added to an existing group, those group memberships are not being created.

### Steps to Reproduce
1. Have a subset of data
1. Refresh the subset with a larger, more recent data set 
1. New people and groups are added
1. Existing people are not added to existing groups
1. Re-run the import process
1. Confirm group memberships are still missing

**Expected behavior:**

All group memberships should be updated or added

**Actual behavior:**

Unknown, group memberships are still missing.

### Versions
* **Rock Version:** 8.4
* **Client Culture Setting:** en-us

**Comment by JoshuaMaiorino** [comment]
Bema has created a fix for this.  We just have to create the PR. It also fixes Financial Transactions as well.  Currently the only thing updated are people.  We've also added logic to skip an import if it doesn't exists.  i.e.  If your sling shot file doesn't contain people, it won't try to import people.  We've seen some clients with Large sets of data, and you can run into time outs even when there's no import data.  So,  It helps :).  We're hoping to submit the PR sooner rather than later, just have to find some free time.

**Comment by dcs619** [comment]
@JoshuaMaiorino Thanks, had I known it was an open issue I could've fixed it during pre-import prep ([3027](https://github.com/SparkDevNetwork/Rock/pull/3027)).

**Comment by nairdo** [comment]
I know this is an old item and it's possible that some (or all) of the desired feature was possibly implemented in these two PRs: #3479 (https://github.com/SparkDevNetwork/Rock/pull/3479/files) or #3666 (https://github.com/SparkDevNetwork/Rock/pull/3666/files#diff-99410503f4aa3233ba0a657d0e5d9c47R1281) but since the original intent of Slingshot was for single use importing, we're going to close this feature request.
