### ISSUE TITLE
[EN] New Workflow Action - Send Email From Communication Template

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3466]
# Feature Request

**Describe the Feature Request**
Would like to be able to Send Emails in a Workflow from a Communication Template (with Lava Merge fields).  It can be done using existing tools but is complex to get to work properly and in a maintainable way.

**Describe Preferred Solution**
Something similar to Send System Email but for a Communication Template.

**Describe Alternatives**
I've written this as a workflow using Lava.  But it's not very maintainable and a pain to duplicate.  This seems like an obviously missing action.

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by edmistj** [comment]
@bobrufenacht please start using the new Ideas community feature instead of Github issues going forward. 

As to using communication templates in workflows the issue I see is that the Lava in the templates would not be compatible with both the Communications feature and the Workflow. For instance the Lava for a communication for a salutation would be:

`{{ Person.NickName }}`

Where as in a workflow, it would be something like:

```
{% assign person = Workflow | Attribute:'Person','Object' %}
{{ person.NickName }}
```
(Lava untested)

While we might understand this incompatibility, I'm not sure an average staff person would and my try to use them interchangeably with poor results.

It would seem that a System Email may be a better template, since they are not specifically tied to a communication.

**Comment by nairdo** [comment]
Hi @bobrufenacht thanks for reaching out!  We reviewed this request yesterday.  The Communication Templates in Rock are not designed for automation/workflow/action usage -- that's what the System Emails are designed for.  The Communication Templates are intended for people, and they are only designed for _people_ to insert their content dropzones and custom content into.

Thanks again for your ideas and be sure to check out our new Community Ideas system at https://www.rockrms.com/community/ideas -- it was built especially for collecting these sorts of things and feature requests.
