### ISSUE TITLE
[EN] New Workflow Action: Send SMS from Communication Template

### ISSUE THREAD

**Issue by bobrufenacht** [SparkDevNetwork/Rock#3467]
# Feature Request
**Describe the Feature Request**
Would like to be able to send SMS from within a workflow from a Communication Template.  This would allow SMS content to be edited without having to know workflows.  Also, the existing action does not allow the SMS From Value to be in an attribute or from a template.  Having that able to be set from the Template offers additional flexibility. (Used for Guest follow-up process.)

**Describe Preferred Solution**
The Action should be able to send the Template SMS message using the Template SMS From Value.  Should take a list of recipients as well.  Not sure of the format of this - delimited list of phone numbers is functional but a list of person ids or Guids or group would be better to support Lava merge fields.

**Describe Alternatives**
Existing options can use lava and such to make this happen, but it's a bunch of coding and tough to maintain.  A simple workflow action would make the process much easier and more maintainable.  This seems like a missing piece for workflows.

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by edmistj** [comment]
See comment on #3466

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
