### ISSUE TITLE
Can't add an over-sized (larger than web.config allows) image into an component using the communication wizard

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#3540]
### Prerequisites
* [X ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
When attempting to add an image component to an email using the wizard, I'm getting a broken link icon on the image in the preview, and when switching to another component to edit, and click back on the image, the upload thumbnail is showing no image either.  This persists when the email is actually sent as well.

### Steps to Reproduce
1. Create a new email using the communication wizard
1. Add an Image component
1. upload an image

**Expected behavior:**

The image is properly added to the email

**Actual behavior:**

The image creates a broken image link

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

**Comment by JoshuaMaiorino** [comment]
I have a screen recording done on the demo site to demonstrate.  Not sure If there's a way to upload it here.

**Comment by JoshuaMaiorino** [comment]
I've done some further testing.  Apparently there's a file size limit into this working.  It's not listed on the block, and no errors are thrown.

**Comment by cabal95** [comment]
If you are trying to upload an image into Rock, there is a built-in file size limit on uploads in Rock. Though if you are running into that for an e-mail you are sending out, I would question the file you are uploading.

You can see this setting by going to System Settings > System Configuration, it's inside the Web.config settings panel.

**Comment by JoshuaMaiorino** [comment]
So, the image size was 2.5mb, while that's a little on the large size, it's certainly not above the upload threshold(100m).  Also, the image was upload able through the HTML WYSIWG editor.  But regardless, the screen / control should through a visual error if its running into file size issues.

**Comment by nairdo** [comment]
@JoshuaMaiorino Can you to verify that your "Public Application Root" setting (Admin > Global Attributes) is set with a URL that is correct and publicly available?

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
