### ISSUE TITLE
Communication Template does not have a FK to BinaryFile

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3582]
### Description
CommunicationTemplate table has a column called `ImageFileId`. This is the image that is displayed to the user as a preview when picking which template to use in the wizard. This column does not have a foreign key linking it back to the BinaryFileTable. This is causing issues with some automated scripts that I have that look for unused/unlinked binary files that can be deleted (since they are not referenced they show up as candidates for deletion).

Additionally, while there is a BinaryFile for the Blank communication template, it is not actually referenced by said `ImageFileId` field. Meaning the file is truly unused. In the Communication Wizard this causes it to use the on-disk default SVG.

### Specific items to be fixed:
1. `CommunicationTemplate.ImageFileId` needs a Foreign Key reference added to the `BinaryFile` table.
1. If the "blank" communication template has no `ImageFileId` value, then it should be set to the file stored in the database.

### Versions
* **Rock Version:** 8.6
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
ref https://github.com/SparkDevNetwork/Rock/commit/bf17b2781ec3514e6765114f9e1ffbdc479bcd0f

**Comment by cabal95** [comment]
@nairdo That commit is actually unrelated to this issue, unless that was not the commit you meant to reference.

I just looked at my dev instance running off github develop (1.10.0.6) branch, and this is still not fixed. `ImageFileId` still does not have a ForeignKey setup to the BinaryFile table.

**Comment by nairdo** [comment]
I know.  In our internal records, that commit was tied to this issue (although it's not clear to me now why it was).  Regardless, I was housekeeping our records/issue and shortly after discovered it was NOT fixed. 

Now I have a task to build the migration (once we start doing migrations in the `develop` branch again) to clean up the broken CommunicationTemplate.ImageFileId values before the EF migration that adds the ForeignKey to that table/column since it's likely there will be missing records that would otherwise cause the migration to fail.

**Comment by cabal95** [comment]
Okay great, just wanted to be sure it didn't get later flagged as fixed. :)  Thankfully it isn't a huge issue, just an oddity and should be corrected.
