### ISSUE TITLE
 Can't delete a group previously attached to registration.


### ISSUE THREAD

**Issue by morganw93** [SparkDevNetwork/Rock#3640]
[X]* Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
 [X]   * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
 [X]  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
We are on Rock version 8.6. We were trying to delete a series of groups that were previously linked to a registration. The linkages were removed, all people removed from the group and we still could not delete the group [without removing it from all related Registration records first].

### Steps to Reproduce
1. Create a group and attach it to a registration.
1. Set the target group on registrants to be the group you are using.
1. Remove the linkage on the registration
1. Remove all members from the group.
1. Try to delete the group. 

**Expected behavior:**

The group will delete.

**Actual behavior:**

You will receive an error like this:
"Information: This group is assigned to a Registration."

### Versions
* **Rock Version:** v.8.6
* **Client Culture Setting:** en_US ![Screen Shot 2019-04-04 at 2 38 01 PM](https://user-images.githubusercontent.com/30188136/55583454-86c4f680-56e7-11e9-84ad-79ab65c1ddd5.png)

**Comment by cabal95** [comment]
This isn't a bug, it's by design. The issue is that you have Registration's still tied to that group. In this case, your two options are:

1. Simply mark the group as Inactive
2. Update all the Registrations to not be tied to that Group.

**Comment by morganw93** [comment]
We did update the registration and get rid of the group, however that still leaves all the registrants with a target group set and we shouldn't have to click into each person's registration and re-save it to clear out the group. By removing the linkage, all of the target groups set on the registrants should get removed so that we can delete the group. Even removing everyone from the group does not get rid of the target group saved on each registration.

**Comment by cabal95** [comment]
Again, it's by design that it works this way. :)  Deleting the linkage should NOT invalidate all existing data, and having it auto-clear those things would do just that. I don't want somebody to be able to screw up 1,000 valid registrations because they deleted the linkage just to make it stop putting people in that group.

Essentially, what you are trying to do is use the system in a way it wasn't mean to be used. Auto placement in a group after registration is basically meant to be used for check-in. As in, as soon as they register for the 101 class, I want them to automatically be able to check-into that class when they show up. There are a few other uses cases, but they are pretty rare.

What you are asking for would be akin to "fixing" the fact that when you try to delete a Group Type that has groups tied to it, you get the following message:

<img width="518" alt="Screen Shot 2019-04-04 at 1 53 54 PM" src="https://user-images.githubusercontent.com/1119863/55587912-55492c80-56e1-11e9-866d-f9871d5e5852.png">

The problem is, that isn't a bug either. It's by design so that people don't accidentally delete things that have unintended consequences in other parts of the system.

**Comment by cabal95** [comment]
BTW, this is one of those cases where your other option is to build a workflow to do the work for you. If you can't convince your staff to do things the "right way" (in quotes because I don't mean it's the only correct way, just that it is the way the system is intended to be used), then you can provide a workflow for them to be able to work around it.

Example, the workflow called `Disassociate Groups from Registrations` could present a simple User Entry Form with a Single Select attribute populated (via a SQL statement) with all the active Registration Instances. They can pick one and click Submit, which would then execute a SQL action to clear out all those values. Now it's something they can do without having to have you go into SQL each time to do it for them.

**Comment by morganw93** [comment]
I understand the case uses. And I'm all about protecting the integrity of the registration.
But there should be a way to get this group deleted without having to use SQL. 

After I delete the linkage, if I look at a registration it shows that the group is still set as the target group 
but when I click edit the target group is empty and then I save it and it's all good.  So Rock is removing the group ....almost.
I attached a video showing what I'm talking about: https://vimeo.com/328528177

**Comment by cabal95** [comment]
You just described the way to do it without SQL. You edit each registration, clear out the target group and click Save.

If anything, I would say the bug in what you just described is that when you edit a registration that it does not ensure the currently selected group is still an option to be selected.

**Comment by morganw93** [comment]
Again, I understand that this would accomplish it, but this is not realistic with large registrations.
I also know that deleting these kinds of groups is not going to be a common thing.  
However not every church who uses Rock is going to have SQL skills and be able to figure this out if they come across this kind of situation or have the time to click through hundreds of registrations to disconnect this. So there needs to be some kind of compromise.

**Comment by edmistj** [comment]
Thanks for all this info. We'll add this to the discussion topics to figure out a path forward.

**Comment by nairdo** [comment]
After discussing, we've decided in this case we want to honor the administrators request to delete an unwanted, empty group.  So we will make a change to automatically NULL-out the GroupId on any related Registration records.  There are still many other reasons why one might not be able to delete a group (due to attendance data, group history, child groups, etc.) so those other warnings will still exist.

**Comment by cabal95** [comment]
Sounds good to me. Thanks @nairdo

**Comment by morganw93** [comment]
Thank you! @nairdo
