### ISSUE TITLE
Pre-Registration DOB Not Forced

### ISSUE THREAD

**Issue by charlottedean** [SparkDevNetwork/Rock#3651]
If a family pre-registers with a incorrectly formatted DOB (ie, 091115 instead of 09/11/2015) it allows the family to pre-register the children with no DOB.

### Steps to Reproduce
1. Go to the pre-register block (https://rock.rocksolidchurchdemo.com/FamilyPreRegistration) fill one out with a incorrectly formatted DOB for a child
1. Click submit, and it will submit the registration when it shouldn't.

**Expected behavior:**

It shouldn't allow a DOB in an incorrect format.

**Actual behavior:**

It allows the user to submit the pre-registration

### Versions
* **Rock Version: 8.6
* **Client Culture Setting: en-us

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1118162893213498">image.png</a> | <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1122559373255212">image.png</a>

**Comment by JimMichael** [comment]
I can confirm this behavior. Entering a date as 110215 ( the "intent" being November, 11, 2015) let the form submit, but the record ended up with a blank birth date. 

Due to the importance of getting birth dates accurate/correct for the purpose of checking-in (which is the entire point of this block) I wonder if it should be switched to using a date-part-picker instead of a date picker? We've experienced people having lots of confusion over date pickers, often choosing a bad year while getting the month and day right. Date-part-picker, while more challenging to lay out nicely on that form, would probably provide a better end user experience.

Also, while the original example above points out a DOB for a child, the same problem exists for Adult DOBs, too.
