### ISSUE TITLE
Content Channel Item View Block does not support Assets attributes for selection in social media image block attributes

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#3656]
### Description
When using the Content Channel Item View block, it is currently impossible to select a Channel/Item attribute of the Assets type to be used for the social media (Twitter/Facebook) image block attributes.

![image](https://user-images.githubusercontent.com/383807/56302969-c8926b80-60ef-11e9-9264-ebe406db5fa9.png)

### Steps to Reproduce
1. Create a Content Channel Item Attribute of the Assets field type.
1. Place the Content Channel Item View block on any page.
1. Choose a Content Channel that is of the type where you added the attribute in step 1.
1. Attempt to choose the Assets attribute you created in step 1 for the "Facebook Image Attribute" under the "Social Media Settings" section.

**Expected behavior:**

Social Media Image attributes across Rock should support the Assets attribute type.

**Actual behavior:**

Social Media Image attributes across Rock only support the Image attribute type.

### Versions
* **Rock Version:** 1.9.0.15
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
