### ISSUE TITLE
Giving from a business causes error at NMI

### ISSUE THREAD

**Issue by darringraham** [SparkDevNetwork/Rock#3663]
### Description
Creating a recurring ACH gift as a business in Rock sends a recurring transaction to NMI that has an error: "Error: The Customer Name is required REFID:1575640287" First Name and Last Name are required by NMI and not passed by Rock. Rock should prompt for First/Last name and pass them to NMI.

### Steps to Reproduce
1. Go to Rock external web page - giving page
1. Fill in the Contribution Information
1. Click "Business" in the Give As section
1. Fill in all required data.
1. Click "Next"
1. Click "Finish"

**Expected behavior:**

Should create a recurring transaction at the NMI gateway without an error.

**Actual behavior:**
Creates a recurring transaction that has an error: "Error: The Customer Name is required REFID:1575640287"

### Versions
[RockDiagnostics-ProductionRock.txt ](https://github.com/SparkDevNetwork/Rock/files/3118898/RockDiagnostics-ProductionRock.txt)

* **Rock Version:** [Rock McKinley 8.6 (1.8.6.2)]
* **Client Culture Setting:** [en-US]

**Comment by darringraham** [comment]
![image](https://user-images.githubusercontent.com/38145549/56770384-10109b80-6771-11e9-9535-86114d479a37.png)

**Comment by darringraham** [comment]
That screenshot is from the NMI gateway showing that First and Last Name (and Company Name) are blank.

**Comment by jonedmiston** [comment]
Hi @darringraham ! Below is a snippet from the Giving documentation. Can you confirm this setting and see if you still have an issue?

>Note
The Prompt for Name On Card, Prompt for Bank Account Name, and Prompt for Billing Address options are provided due to the fact that NMI may or may not require this information from your users. By default, NMI does not require the Name on Card and Billing Address fields, but if you have enabled address verification in the NMI security settings, you will need to prompt the user for their billing address. If you do not enable this prompt, the user will get an error returned by the processor indicating that required information is missing.

**Comment by darringraham** [comment]
Hi Rock Team.
 
Yes, “Prompt for Name On Card” and “Prompt for Billing Address” are both set to “Yes”
 
This may only be a problem for ACH. I’ll update the bug report to specify that.
 
Thanks.
 
-Darrin

**Comment by darringraham** [comment]
We're seeing this problem on recurring ACH transactions. I don't know about recurring CC transactions.

**Comment by HansenGrace** [comment]
Thanks for all your input. We will add this into our pipeline for next steps.

**Comment by tscrip** [comment]
PR to fix this issue has been attached: https://github.com/SparkDevNetwork/Rock/pull/3682
