### ISSUE TITLE
Rock Sends to Inactive Email Addresses

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3677]
### Description

If you use the Communication Wizard (or Simple Editor) to send an email to a person with an INactive email address, Rock still sends and delivers it.

### Steps to Reproduce

1. Deactivate email address on a Person
2. Send a New Communication to that Person
3. Observe that the email is sent/delivered, even though the email is "inactive"

**Expected behavior:**

Rock would never successfully send email to an inactive address.

**Actual behavior:**

Email is sent/delivered to inactive email addresses. We're having a debate in Chat about whether this is working as designed or incorrect behavior. *I* consider it 100% incorrect (and buggy) behavior, but others think it's expected to work when you direct an email "manually" (via wizard or simple editor) to a person. I couldn't swear to it, but it sure seems like inactives were blocked from delivering in the past... 

If it (delivery to inactive addresses) IS working as designed, I'd like to suggest that this be discussed for a change in behavior. I can't see a rationale for allowing a system with an "inactive" address on a person to deliver to that address. We routinely inactivate email when we inactivate People here, and thought that was preventing "accidental" emailing to that person, but that doesn't seem to be the case on 8.6+.

### Versions

* **Rock Version:** 7.x through 8.8alpha

**Comment by cabal95** [comment]
I'm one of the ones that feels like it is correct behavior, but it really does come down to what the intended behavior was/is.

Anyway, from what I can tell by sampling a few places in Rock, the current (correct or not) behavior is that any automated sending (workflow action, system e-mail, etc.) honors the `IsEmailActive` flag. Manual actions (such as sending an e-mail via the Simple Communication or Wizard, or requesting a lost password) do not honor that flag.

My _biggest_ concern with it being switched (or fixed, whichever the case may be) to behave like Jim is describing is the fact that the `IsEmailActive` property is set automatically when an e-mail bounces. So if somebody's e-mail is temporarily broken/full and the message bounces, Rock would *never* send them an e-mail again. Even if they clicked the "forgot password" link or if I attempt to manually send them an e-mail.

Bug again, it really comes down to the intent.  Was the `Is Email Active` flag meant to be:

1. Do not send an e-mail to this address(person) under any circumstances

or

2. We don't think this address is good anymore so we aren't going to keep sending automated notices to it, but you might know better than us so we'll let you send to it manually if you want.

The Rock Manuals don't seem to say anything about this field or what it is for. So whichever way we go, it should probably be updated to clearly state what "Is Email Active" means in the UI.

**Comment by JimMichael** [comment]
I did find an old 7.4 instance I still have running and it, too, delivers to inactive addresses. So if it ever DID block them, it was probably v6... and maybe it changed when the Communication Wizard was introduced.

**Comment by jonedmiston** [comment]
Just a clarification on bounces. There are two types. Hard bounces (account no longer exists) and soft bounces (email is full). Rock only disables the email on a hard bounce.

Based on that I think we should not send to inactive emails addresses. Another option would be no only not send if the email was labeled bulk.

https://www.mailgun.com/deliverability/bounce-management-software

**Comment by cabal95** [comment]
That may be, but we use mailgun and have had to fix numerous e-mails that Rock has marked as inactive because mailgun reported the message as bounced (due to a temporary failure such as a spam filter going haywire).

**Comment by JimMichael** [comment]
We, too, see lots of inactivating due to bounces, but always assumed that subsequent sending was being blocked (the sender can easily see when/if emails aren't sending, and go investigate those people.) It was just a shock to accidentally discover that "inactive" didn't mean "can't send to" (regardless of the reason.)

**Comment by JimMichael** [comment]
The thing I don't like about not having IsActive be a true "off switch" is that my staff are then _always_ responsible for constructing their dataviews 100% correctly... always filtering for "email is active" and/or "Record Status = active"... because even an _inactive_ person will receive an email sent to them (that is also inactive) under the current system. And the chances of them getting that right all the time are zero.. so we _have_ to already be sending to inactive people we assumed we weren't because we thought Rock was being a gatekeeper and blocking them for us. Ugh.

**Comment by jonedmiston** [comment]
What if we treat inactives as is inactives and add a block that shows inactive emails (with reason and date of inactivity) that allows you to easily reactive them?

**Comment by cabal95** [comment]
I'm not in favor, but I probably will never be in favor of any change to the current behavior since IMO it is working correctly as is. Mass/automatic e-mails are blocked, user-initiated e-mails are allowed (just like if they went to their e-mail client and sent it from there - except we wouldn't get the history data).

That said, I don't want to make a big stink out of it. If the current functionality changes we'll just deal with the extra calls in IT or automate re-activating every bounced e-mail address or something.

I don't think any effort should be put into building such a block no matter what decision is made. I doubt anybody would ever actually use it since they would constantly have to sort through possibly thousands of e-mails. And we can already build a dataview/report in 30 seconds to show the same info (granted no easy button). Beyond that, I don't think it would provide enough details for them to make an informed decision on if the e-mail should be re-activated or not. 95% of them would be bounced message notices anyway.

**Comment by JimMichael** [comment]
I'm of course in favor of inactive being truly inactive (for reasons I've already described) but will understand if y'all decide current behavior is the correct/intended behavior. We'll just have to train our staff to be a LOT more careful about emailing teams and such and making sure they are always filtering out inactive emails. 

@cabal95 is looking at it from the individual sender side of the coin (and his concerns are reasonable) but we're looking at it from the mass mailing side of the coin and worried that we're sending stuff to people (for example) that just happen to still be in a group (but have inactive person/email status) yet Rock STILL sends to them. That just seems wrong.

**Comment by smross** [comment]
I'm also not sure what to make of this. I think **both** are valid points. Assumptions I had walking into this:

- An email *not "active"* would not receive email initiated from a new communication initiated by a user via a grid
- An inactive email _would_ potentially receive a system email. However, I can find nothing from my master class notes, and nothing that I can find in the documentation

Whatever is decided, I think some messaging/documentation/suggested training is needed so Org's understand *how it behaves* (it feels ambiguous currently)

I think the block could be helpful, but for us would only be used by the admin types/data integrity types (not most Rock users).

**Comment by JimMichael** [comment]
The thing I don't like about not having IsActive be a true "off switch" is that my staff are then _always_ responsible for constructing their dataviews 100% correctly... always filtering for "email is active" and/or "Record Status = active"... because even an _inactive_ person will receive an email sent to them (that is also inactive) under the current system. And the chances of them getting that right all the time are zero.. so we _have_ to already be sending to inactive people we assumed we weren't because we thought Rock was being a gatekeeper and blocking them for us. Ugh.

**Comment by Tschrock** [comment]
I checked some old communications from the beginning of 2016, and it does appear to have been skipping inactive email addresses:

![firefox_2019-05-06_13-44-44](https://user-images.githubusercontent.com/2406499/57243913-436ee800-7005-11e9-8469-02cb9a2b509b.png)

Checking in the current codebase, I can't find any references to the string "Email is not active!" or "Not delivering to previously bounced address", so it seems like whatever code had been handling those cases has since been removed.

**Comment by cabal95** [comment]
Just for final note here since it was fixed directly in a commit, this has been fixed to not send an e-mail to a person if the e-mail address is marked as inactive.

Note: I _believe_ this only applies when sending to a **Person**. If you send directly to an e-mail address (such as via a workflow) then I believe it will still send.
