### ISSUE TITLE
NMI Send Rock Business Name

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3689]
# Feature Request
This feature request is being requested by Flatirons Community Church.

**Describe the Feature Request**
Currently, when you give as a business, it is sending the contribution from a single person. Once that contribution hit your Financial Gateway (NMI in this case), you have no way of knowing if the contribution is from a person or a business.

**Describe Preferred Solution**
I believe we should be able to add a company element here: https://github.com/SparkDevNetwork/Rock/blob/develop/Rock.NMI/Gateway.cs#L857-L869

It looks like the PaymentInfo Model already has a BusinessName Property, so it should be fairly easy to update the TransactionEntry block to push this data.

**Providing Code**
I will provide code if feature request is approved: Yes

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
