### ISSUE TITLE
Family Pre-Registration addition of home phone

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3695]
# Feature Request

**Describe the Feature Request**

We would like to have the ability to show a Home Phone field to be filled in on individuals when using the Family Pre-Registration block.

**Describe Preferred Solution**

Functionality would mirror the current Mobile phone options but be for Home phone instead. Meaning the home phone option could be set to one of `Hide`, `Optional`, `Required`.

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved: **Yes**

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
