### ISSUE TITLE
Bug/Enhancement for Registration List Lava block allowing registrations outside the specified date filter

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#3698]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [[http://rock.rocksolidchurchdemo.com/](http://rock.rocksolidchurchdemo.com/) demo site ]()?
  * Did you include your Rock version number and [[https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) client culture ]() setting?
  * Did you [[https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) perform a cursory search ]() to see if your bug or enhancement is already reported?

### Description
For the Recent Registrations block (RegistrationListLava.ascx.cs) on the My Account page, when a date filter is entered, those registration instances with an event occurrence where Next Start Date is N/A are displayed in the list when they shouldn't be. Didn't notice this till now since we limit it to show registrations with a balance. 

I set the Date Range to last 3 months. When I look at the list, registrations from 2016 till now display. When comparing the different registrations, the only thing I saw in common was the Next Start Date was N/A. I also switched the date filter to upcoming 3 weeks and correctly see the registration for the event that is happening next week, however, I'm still seeing 2016-2019 registrations in the list. So the bug is it isn't properly filtering dates for calendar events that don't have a next start date.

For the enhancement side of it, which may need discussion, is there a reason why the date filter is going based off of the calendar event item instead of the registration's created date? Going based off of the registration's created date makes more sense to me. If I registered for an event yesterday but the event isn't till July, I would expect it to appear in the list if I had the date filter set to the last 3 months, instead of having it set to upcoming 12 weeks.

### Steps to Reproduce
I think it is easier to see in a live Rock instance that has registrations over a longer period and where the registrations have been linked to a calendar item. 

1. Modify the Recent Registration block to filter by date. For my testing I used last 3 months.
1. Registrations that are linked to a calendar event item but don't have a next starting should display in the list. 

**Expected behavior:**

Bug: To not display registrations outside of the date filter

Enhancement: Display recent registrations based off of the registration's created date, not the event occurrence date.

**Actual behavior:**

Bug: When the event item occurrence's Next Start Date is N/A the registrations outside the date filter display.

### Versions
* **Rock Version:** v8.7, ALPHA 8.8.2
* **Client Culture Setting:** en-US

**Comment by mikejed** [comment]
Confirmed for another church using these steps:

### Description

Registrations linked to events with no occurrence date never get filtered out of the Event > Registration List Lava by the date filter

### Steps to Reproduce

1. Create a new Event on the default Public calendar called "Test Event (no date)". (no other details/changes needed)
2. Create an occurrence of that new event.
3. Click "Add New Registration Instance"
4. Choose an existing registration template such as Baptism. Give the instance a name, and set the registration to start a few days ago and end a few days from now. Save the registration
![image](https://user-images.githubusercontent.com/6932047/58136408-ccc81200-7be2-11e9-9a27-0add3c8de5c1.png)

5. Save the Event Occurrence without editing the schedule
6. Click on the linked Registration in the Event Occurrences grid. Note the RegistrationInstanceId in the URL, then navigate to the registration page similar to rockrmsdemo.com/Registration?RegistrationInstanceId=[#] where [#] is the RegistrationInstanceId noted in the URL
7. While logged in as Alisha Admin, register yourself for the event.
8. Visit rockrmsdemo.com/myaccount. Change the settings on the "Recent Registrations" to Limit to registrations where money is still owed: No, and note the "Recent Registrations" block on the right sidebar displays the registration
9. Edit the "Recent Registrations" block settings to filter for registrations in the Next 6 Months (for instance)

**Expected behavior:**

Since we are filtering for registrations tied to events occurring within a specific timeframe, registrations with no date should be filtered out

**Actual behavior:**

No date filter can be set on the block which removes the registration we created- it will show on that block for years to come.

**Additional notes:**

If you create another similar registration but set a schedule on the event occurrence in step 4, the filter works properly.
![image](https://user-images.githubusercontent.com/6932047/58136341-9ab6b000-7be2-11e9-8e43-646e92d5cc24.png)


With no date filter set on the block:
![image](https://user-images.githubusercontent.com/6932047/58136225-3693ec00-7be2-11e9-9296-23def320ec08.png)

With a date filter set on the block which should exclude all registrations (for example):
![image](https://user-images.githubusercontent.com/6932047/58136283-62af6d00-7be2-11e9-9b75-0b4301b1aaa5.png)

**Comment by mikejed** [comment]
Regarding the enhancement request, here's why the date filter is based on the occurrence date rather than the created date:

If you have a series of classes or camps that people have registered for (say kids' Summer Camps for instance), parents will probably want to see a list of upcoming events they've registered their family for. These events should disappear from the list once the event has occurred.

To accomplish this, you might set up a filter on the block such as "show registrations from the next 6 months" - that will hide any registrations whose events have already passed. If the filter was instead based on the registration date, you wouldn't be able to have them disappear once camp came and went- you could only have them disappear some time after they registered. Depending on how far in advance they registered, they might disappear either before the event occurs or continue showing for a time even though the event has already passed.

Hopefully that helps clarify the intent of the setting.

**Comment by OnlyByGrace** [comment]
Our church has just come across and confirmed this bug. Note, it's not just calendar items without a date that cause this problem, as @mikejed mentioned, but any calendar event whose occurrence is in the past. If the event item occurrence occurred in the past, NextStartDateTime always evaluates to N/A, making it show up in the block.

**Comment by nairdo** [comment]
And just to clarify the fix above, if the "**Limit to registrations where money is still owed**" block setting is set to `true` the block will still include active registrations that have no date if there is a balance due.
