### ISSUE TITLE
REST People Controller AddExistingPersonToFamily does not authorize valid request

### ISSUE THREAD

**Issue by TimBarley** [SparkDevNetwork/Rock#3701]
### Description
When using the AddExistingPersonToFamily endpoint in the People Controller, you will always receive a 401 response.

### Steps to Reproduce
1. Set up a testApi REST Key
1. Add the desired permissions to the AddExistingPersonToFamily endpoint (or to the People Controller
1. Send a valid request to the AddExistingPersonToFamily endpoint
1. API will return 401

**Expected behavior:**

Given a valid REST API key, the action should be authorized.

**Actual behavior:**

The action receives a 401 error.

### Versions
* **Rock Version:** 8.7 release and current develop branch
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@TimBarley I've not been able to confirm the problem.  For example, using the pre-alpha server along with the VSCode REST Client, I was able to authenticate (first screenshot) with this:

```
POST http://prealpha.rocksolidchurchdemo.com/api/Auth/Login  HTTP/1.1
content-type: application/json

{
	"UserName" : "admin",
	"Password" : "admin",
}
```
![image](https://user-images.githubusercontent.com/383807/58362616-ddc88b80-7e4d-11e9-8ccd-fb61c9687bba.png)

...and then add Alisha Marble to the Decker Family (second screenshot) like this:

```
POST http://prealpha.rocksolidchurchdemo.com/api/People/AddExistingPersonToFamily HTTP/1.1
    ?personId=1
    &familyId=68
    &dataViewId=15
    &groupRoleId=4
    &removeFromOtherFamilies=false
```

...which completed successfully with a 201 (created) as shown here:

![image](https://user-images.githubusercontent.com/383807/58362626-efaa2e80-7e4d-11e9-87b1-7b6ba690f132.png)

Which is also confirmed by looking at the Decker family and seeing Alisha there:
![image](https://user-images.githubusercontent.com/383807/58362640-1c5e4600-7e4e-11e9-8c9d-ded309eb3672.png)

**Comment by TimBarley** [comment]
I believe the reason that worked is because Alisha is a Rock Admin. The original code sends the Person entity of the person that you want to move (not the person requesting the move). The issue would be that Alisha would have permission because she is an admin. If you try to move Ted, it should fail.

**Comment by Tschrock** [comment]
@TimBarley You will need to give your REST key permissions on the Person entity type (Admin Tools -> Security -> Entity Administration) in addition to the AddExistingPersonToFamily controller. I'm pretty sure other endpoints work this way too.

**Comment by TimBarley** [comment]
@Tschrock Thanks for the suggestion Tyler. I was able to confirm this morning that it does allow the API to complete when I add the API Key to the Person Entity Administration.

I guess I have a few other questions to go along with this then:
1. Is there any documentation or listing of which API Endpoints require this additional configuration?
2. Is this really the desired solution to this issue? It feels inconsistent to other API Endpoints that I have made. What makes this one different?
3. If this is not the desired behavior, does my PR actually correct it? And could the same fix be applied to the other API Endpoints that exhibit this behavior?

Please know that I'm not expecting you to know these answers, but I thought I'd express them here to get a better understanding from the community or to at least continue the conversation.

**Comment by Tschrock** [comment]
I don't think it's documented anywhere specifically, but it looks like all entity-related endpoints do that - requiring the user to have rights to both the endpoint and the entity. Note that some entities (like campuses) default to letting all users view them, so it's not immediately obvious that there's more going on.

To me, it makes sense that the security on an endpoint doesn't override the security on an entity itself - and I don't think the endpoint should immediately inherit the security of the entity either. In either case it definitely could use better documentation.

Looking at your PR, there seems to be some confusion about what the CheckCanEdit function does. My understanding is that it checks if the current user has permission to edit the entity you give it. Which means your PR actually makes the endpoint check if a user can edit themselves, rather than the person being modified - probably not what you intended.

**Comment by TimBarley** [comment]
Thanks for the clarifications. I'll close the issue and the PR.
