### ISSUE TITLE
Clearing Date Filter on Group Attendance

### ISSUE THREAD

**Issue by matthewalanwhite** [SparkDevNetwork/Rock#3752]
### Description
We are unable to clear the date filter when submitting attendance for a Group.

### Steps to Reproduce
1. Go to the Group Attendance page for a small group. https://rockrmslatest.com/page/366?GroupId=112 on Prealpha site.
1. Click on 'Clear Filter'

**Expected behavior:**

We initially expected the dates to be set to the previous set filter, but it defaults to 3/19/2019. Then when clicking on 'Clear Filter', we expect the dates to be removed.

**Actual behavior:**

Nothing happens

### Versions
* **Rock Version:** [Rock McKinley 9.0 (1.9.0.19)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi @matthewalanwhite The date [was changed](https://github.com/SparkDevNetwork/Rock/commit/d02e703d71bd62a76d5ecce2c5886d3ff88bd689) to default from 'one year prior to the current date' to 'three months' prior to reduce the amount of data returned from the list.  This was by design, but are you really asking that it should return all data when the filter is cleared?

**Comment by matthewalanwhite** [comment]
Hey @nairdo that makes perfect sense and we are all about performance. After talking through that thought process we are good to go. So I am going to close this issue.
