### ISSUE TITLE
Group Finder Map and grid do not auto-load on page if multiple filters selected

### ISSUE THREAD

**Issue by TheCoreyHall** [SparkDevNetwork/Rock#3756]
### Description
This might be a feature request rather than bug report. If it is, let me know.

If the "Days of the Week" or any attribute filters are selected in the Group Finder block settings, the Map and Grid no longer auto load on page load. The Search button must be selected for the map and grid to load. If the Campus filter by itself is there, the map and grid auto load. But if more filters are added, they do not.

### Steps to Reproduce
1. Go to https://rock.rocksolidchurchdemo.com/page/236
1. Enter the Block settings of the Group Finder block
1. Enable the Day of Week Filter or the Attribute filter
1. Refresh the page
1. The map and Grid no longer auto load

**Expected behavior:**

The map and grid load automatically on refreshing with new filters above it.

**Actual behavior:**

The map and grid do not show until the Search button is selected.

### Versions
* **Rock Version:** 8.5
* **Client Culture Setting:** en-us

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
