### ISSUE TITLE
Public Profile Edit Block Allows SMS To Be Selected On Every Number

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3761]
### Description

The Public Profile Edit block shows a "SMS" box next to every phone number exposed for editing and allows it to be checked on any/all numbers instead of making the selection exclusive.

### Steps to Reproduce

1. Go /MyAccount page
2. Click Update
3. Observe than you can select SMS on all phone numbers.

![image](https://user-images.githubusercontent.com/3903408/59946809-38dfa500-9431-11e9-9f73-57faa2797569.png)

**Expected behavior:**

Just like the internal Person Profile UI, selecting SMS on any number would un-select it from all other numbers.

**Actual behavior:**

You can select SMS on any number, but it only saves on one of them. This gives a false sense that you just enabled SMS for multiple numbers when in fact you did not.

### Versions

* **Rock Version:** v7 through prealpha

**Comment by smross** [comment]
Confirmed. I've experienced this on 8.6, 8.7, and 8.8 (no access to other versions currently).

**Comment by CompassSkelly** [comment]
Looking at this issue it seems that the 'My Account' -> Update page has changed from when this bug was submitted.  I will document what I saw on the three testing environments I am using:

Demo: No phone edit fields are showing on 'My Account' -> Update page.  This is with and without phone fields being filled out on the internal site or not.

I also wanted to make sure this wasn't because I was on the Alisha Admin account and created a test user account on the demo site with the same results.

Prealpha: Same behavior as demo site.

My v8.9 dev site: I only see one phone field available for edit on 'My Account' -> Update Page.  Same as the demo/alpha this is the same with or without a phone number being entered.
