### ISSUE TITLE
Deleting a group using the api archives the group, does not actually delete it

### ISSUE THREAD

**Issue by ickyfeet** [SparkDevNetwork/Rock#3764]
### Description
Doing a http delete on a group doesn't actually delete the group from rock, only archives it.

### Steps to Reproduce
Do a http delete on https://rock.example.com/api/Groups/{GroupId}

**Expected behavior:**

Actually delete the group, not archive it.

**Actual behavior:**

The group is archived.

### Versions
* **Rock Version:** Rock McKinley 8.7 (1.8.7.6)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
If a Group's Group Type is flagged as `Enable Group History`, I don't think it's even possible to ever delete a group, instead it is archived. Even from the UI.  If the group you tried to delete is a `Enable Group History` group, then what you are seeing is correct behavior.  If it's not, then it's a bug as a non-history enabled group shouldn't allow archiving anyway.

**Comment by nairdo** [comment]
@cabal95 is correct.  That is by design.

**Comment by ickyfeet** [comment]
I'm sure it group history is set to true but I still want to delete them using the API.  The inconsistency of the way the delete method works is troublesome.  I can already archive a group by doing a http patch + IsArchived is true.  I feel like the behavior should be consistent with deleting groups that don't have history enabled.  If there's anything tied to that group the api should throw an error until everything referencing that group has been removed then the delete should happen.

**Comment by cabal95** [comment]
The API does not allow you to delete a "history enabled" group because that is not _ever_ allowed by Rock. Once you enable group history, you are telling Rock you don't want people to delete groups. Thus the API is working correctly.

For the record, just setting `IsArchived = true` is not sufficient. There is more that happens to properly archive a group so you should stick to the DELETE method on the group to archive the group.
