### ISSUE TITLE
[EN] Scheduled Gifts workflow to allow selection of loaded credit card

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#3782]
# Enhancement Request

**Describe the Enhancement Request**
The Payment Information page in the Scheduled gift (.../scheduled-gifts) workflow does not allow user to select the credit card loaded for the organization.

**Describe Preferred Solution**
Allow selection of loaded credit card, so user does not need to re-enter credit card details.

**Describe Alternatives**

**Providing Code**
I will provide code if feature request is approved:  No

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
