### ISSUE TITLE
Cannot Send "Attachment Only" SMS via Workflow

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#3788]
### Description

Using the _SMS Send_ action, if you add an attachment (image) and leave the Message field blank, the SMS appears to send but does not. It only works if there is something non-blank (even a space doesn't fool it) in the Message field.

### Steps to Reproduce

1. Add a SMS Send action to a WF
2. Add an image attachment and leave Message blank
3. Run the WF and observe the SMS never arrives.
4. Enter anything non-blank into the Message field and run again and SMS is delivered.

**Expected behavior:**

Unsure if this is a bug in the action simply assuming something should be in the message field ("if message == '' then abort" or similar) or if a SMS without the message portion IS getting sent and dropped by Twilio and thus an empty message is truly an invalid SMS.

If an empty message is _not_ valid for some reason (Twilio can't/won't handle them), then the SMS Send UI should be modified to make Message required. But if it's just a holdover from before the time this action supported attachments, it should be fixed to allow the attachment to be sent sans message.

I did observe that sending a SMS through a New Communication _does_ require message to be populated.

**Actual behavior:**

A text sent via SMS Send WF action with an image attachment will not deliver unless there is something non-blank in the Message field.

### Versions

* **Rock Version:** 8.8

**Comment by MichaelAllen** [comment]
Rock only tries to send the message if there is something non-whitespace in the message body: https://github.com/SparkDevNetwork/Rock/blob/074fa4ffcca387a15c3f7f2903296b5a4388f659/Rock/Workflow/Action/Communications/SendSms.cs#L214

I don't think that Twilio requires the message to contain anything in the body as I was able to send a sample message to myself with only an image attachment, so that check is probably a holdover from before the action supported attachments.

**Comment by nairdo** [comment]
Also, we fixed a related bug in there which would also not include the attachment if you chose the "Save Communication History" on the SendSms action (https://github.com/sparkdevnetwork/rock/commit/c2e1ba6b53f4b636e9006281c00b336a9425c934).
