### ISSUE TITLE
Update Public Profile Edit block to allow hiding Email Preference

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#3801]
Submitted on behalf of https://rock.scottsdalebible.com/

# Feature Request
**Describe the Feature Request**
Would like the option of hiding the Email Preference option on the Public Profile Edit ("My Account") block. Currently you can hide the Communication Preference but you are not able to hide Email Preference. 

Would like to hide this field because the fear is that people will select the "No Mass Emails" option without really understanding what affect that will have on the communications they will receive (i.e. emails from their group leader, serving group leader, etc).

**Describe Preferred Solution**
Would like a "Show Email Preference" block setting (just like the "Show Communication Preference" setting).

**Providing Code**
I will provide code if feature request is approved: [Yes]

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/community) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
