### ISSUE TITLE
Connection Opportunity Signup Block is Not Setting Campus to Blank by Default

### ISSUE THREAD

**Issue by bscottdavis** [SparkDevNetwork/Rock#3825]
### Description
We have noticed that by default the Campus with the lowest Id is being automatically selected for users in the Connection Opportunity Signup block. This is resulting in many users not choosing a campus but leaving the default campus selected, even though it is not their campus. This seems to be an issue regardless of whether Enable Campus Context is enabled

### Steps to Reproduce
1. Go to page with a Connection Opportunity Serve Block that is multi-campus (https://rock.rocksolidchurchdemo.com/page/417?OpportunityId=1) in a non-logged in state.
1. See that the campus with the lowest id is selected by default

**Expected behavior:**

The campus option on a Connection Opportunity Serve Block is blank, forcing the user to select a campus. 

**Actual behavior:**

The campus option on a Connection Opportunity Serve Block is defaulted to the campus with the lowest id, resulting in many users choosing this option by accident. 

### Versions
https://admin.ccvsocal.com 

* **Rock Version: Rock McKinley 8.7 (1.8.7.5)
* **Client Culture Setting:** en-US

https://rock.rocksolidchurchdemo.com/

* **Rock Version: Rock McKinley 8.8 (1.8.8.3)
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Since v4 the first campus has been used as the default selection if a match on the opportunity/person or opportunity/page context (e.g. adding "SetContext=Rock.Model.Campus|3" to the URL or the cookie) is not found. This logic has been updated:

Original Behavior:
1. If there are any active campuses for the opportunity select the first one in the list.
2. Then check if there is a PersonGuid page parameter or if a person is logged in. If so then set the campus to that person's campus.
3. If no person and EnableCampusContext is true then get the campus context of the page. If one exists then set to that campus.

Updated Behavior:
1. If there is one active campuses for the opportunity automatically select it. Skip all other checks since there is only one Possibility.
2. If EnableCampusContext is true then get the campus context of the page. If one exists and it is in the list of campuses for the opportunity set to that campus.
3. Finally check if there is a person GUID parameter or if a person is logged in. If so check if that person's campus is in the list of campuses for the opportunity. If so then set to that campus.
4. If a campus is not found then the initial value is blank.
