### ISSUE TITLE
Required signature documents attached to registration

### ISSUE THREAD

**Issue by karscharf** [SparkDevNetwork/Rock#3838]
### Description 
Event registration using Sign Now to complete required signature documents...

If a person accidentally registers the wrong person name, when the error is corrected, the signature documents do not stay with the registration. They stay with the person's history record but not the registration. For example: a parent registering for a camp accidentally enters their name instead of child's.  When the name is corrected, the signature documents disappear from the registration. 

### Steps to Reproduce
_none given; ignored_

**Expected behavior:**

I believe that the documents should stay with registration as a whole
**Actual behavior:**

documents disappear from registration

### Versions
* **Rock Version:** [Rock McKinley  8.6   1.8.6.2]
* **Client Culture Setting:** [en-US

**Comment by chrismcgrath** [comment]
Just had this problem myself. I am still on v8.7 so something may have changed, but the SignatureDocument table has an AppliesToPersonAliasId column that links to the person, and this value combined with a long path of links back through the document and registration templates are how the document is ultimately attached to a registration.  

I don't know where else Signature Documents are used so this may not be the right answer, but for this scenario it seems to me that putting the RegistrationId on the SignatureDocument table instead of the AppliesToPersonAliasId would be the more normalized structure and would solve the problem of having to re-upload a signature document when changing the registrant.

Alternatively, the person could be updated on the document table as part of the registrant update on the RegistrationDetail block.  

I'd be interested in which route the Spark team would prefer in case I have a chance to address it.

**Comment by jonedmiston** [comment]
We're moving away from SignNow in future versions of Rock so closing this as a "Not going to fix" because of that.
