### ISSUE TITLE
Filtering Interactions Times Out

### ISSUE THREAD

**Issue by redreceipt** [SparkDevNetwork/Rock#3852]
### Prerequisites
* [ ] Put an X between the brackets on this line if you have done all of the following:
  * Can you reproduce the problem on a fresh install or the [demo site ](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture ](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
  * Did you [%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack perform a cursory search ](https://github.com/issues?q=is) to see if your bug or enhancement is already reported?

### Description
Make this request:

```
https://alpha-rock.newspring.cc/api/Interactions?$filter=((InteractionData eq '82632') and (Operation eq 'Pray')) and (InteractionSummary eq 'NotificationSent')&$orderby=InteractionDateTime desc&$top=1
```

Server times out. Doesn't crash on the demo site, I'm guessing because we have _a lot_ of interactions.

### Steps to Reproduce
1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior:**

Should get an Interaction back

**Actual behavior:**

Crashes.

### Versions
* **Rock Version:** Rock McKinley 10.0 (1.10.0.4)
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Searching across `InteractionData` and `InteractionSummary` is never going to be performant in large databases as you're doing a full text scan. Not sure what you're looking to achieve, but I'm guessing the value of 82632 in `InteractionData` is the prayer request id? If so this should be in the `EntityId` field.  That would help a bit. Not sure what 'NotificationSent' is meant to be. Maybe this could be the `Operation`. Or maybe the fact that a notification was sent should be an attribute on the `PrayerRequest`. 

Also noticing that you did not filter by a `InteractionComponentId`. That would greatly speed up the query as it will limit the search to a lot fewer items.

Sounds like though you may be using the `Interactions` table for something it wasn't meant for. It's not meant to be an extension of other tables but rather a log of how people have interacted with Rock.

**Comment by redreceipt** [comment]
This is extremely insightful thank you @jonedmiston. Here's what we're trying to accomplish:

We are using `Interactions` for storing when a prayer is prayed for to send a notification to the requestor. We are storing the `requestedByAliasId` in `InteractionData` and in `InteractionSummary` we are logging whether a notification was sent with this "prayed" session to keep notifications spaced out a little. A workflow is triggered to send a communication (OneSignal notification) when it sees the right text in `InteractionSummary`.

I can certainly filter on `InteractionComponentId` and see if that helps but I also fully understand our implementation is very hacky. We are always trying to use the available tools instead of adding a bunch of custom attributes everywhere, but can you think of a better way to accomplish our goal?

**Comment by jonedmiston** [comment]
In core we use notes as request comments/responses. It would be more performant to use that pattern as it gives you all of the fields you'd need in a way that tuned to query one. It even has a `NotificationSent` bit.

Based on this I'm going to close out this issue. Feel free to comment here if you have a follow-up though.

**Comment by richarddubay** [comment]
@jonedmiston I see the Prayer Comment note type ... which is cool. I'll be honest, I'm hesitant to create a note on someone's profile every time that someone prayed for someone else. I like the `NotificationSent` bit idea though. I assume that's typically used for making sure that some other user in Rock is notified that there is a note waiting for their approval or whatnot, but maybe we could hijack that into helping us keep track of which prayer requests we sent notifications for. 

Like @redreceipt said, we're just trying to spread out our push notifications so that a person will not get one every time someone prays for them. That could get annoying really fast. 

So we are setting interactions with an `Operation` of `Pray`. We _were_ just saying that every time an interaction of that type came in, a trigger would fire, that would kick off a workflow, that sent the notification. 

Now we are just trying to set that `InteractionSummary` text to "NotificationSent" if the last time a person got a notification was 2 or more hours ago ... and only fire that trigger for the workflow when that text exists. The trick is just that call to the `Interaction` table to get the last time a request with "Notification Sent" was added. 

Maybe notes are the best way to go?
