### ISSUE TITLE
Communication Wizard does not allow you to Default to IsBulkCommunication

### ISSUE THREAD

**Issue by tscrip** [SparkDevNetwork/Rock#3869]
### Description
This ~bug~ is submitted on behalf of Flatirons Community Church.

When you go into Communication Wizard, there is no way to default the communication to IsBulk. For larger churches, I figure this would be a nice feature to have for standard users who have to get their content approved by a Communications team member.

I would be willing to make a PR to do the following:

1. Add block setting to toggle "default communication mode".
1. Add logic to block to look at this setting when creating new communication.

**Expected behavior:**
You should be able to change a block setting to enable communications to Bulk.

**Actual behavior:**
There is no block setting or JS/CSS way of doing this. You have to hard code it in the ascx.cs file.

### Versions
* **Rock Version:** 8.x, 9.x, 10.x
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
We now have a new Ideas area on our Rock Community website (https://community.rockrms.com/ideas) for posting, discussing and voting on enhancements to Rock. Since this issue is tagged as an enhancement we are closing it and requesting that if you still feel it has merit that you add it as an idea. This allows the full community to speak into it and help us determine it's priority.
