### ISSUE TITLE
Using Grid Filter with long attribute names throws exception

### ISSUE THREAD

**Issue by cabal95** [SparkDevNetwork/Rock#3971]
### Description
With the new Abbreviated Names, there is a bug in Grid Filter (more specifically, I think the bug might be in the User Preference system). If you use a long Named attribute (common with surveys and Event Registrations) then when you go to filter the result grid and save your filter it will try to create a new Attribute to store that preference into.

The problem is, for whatever reason, the AbbreviatedName is set to the full attribute name as well which exceeds the 100 character limit.

### Steps to Reproduce
1. Login to Rock Demo site.
1. Edit the Summer Camp Event Registration Template.
1. Add a new Form Field for 'Registrant Attribute' of type Text, Show On Grid = yes, with a long name (pictured below), I used: `At Church: the staff are the Administrators, and the people are`.
1. Save Attribute
1. Save Registration Template
1. Go to the Summer Camp 2016 instance
1. Flip to the Registrants tab (it's fine that it is empty).
1. Open the filter options, enter any value for this new attribute and Apply Filter.
1. See error.

**Expected behavior:**

No error should happen. The AbbreviatedName should probably either be blank or truncated to 100 characters (not even sure why it's being set in the first place).

**Actual behavior:**

An error happens.  The filter will apply if you leave the page and come back because it's stored in Session state, but it's not saved to the database. So starting a new session resets the filter.

![](https://user-images.githubusercontent.com/1119863/67693681-57195c80-f95f-11e9-847b-37f98eda34d7.png)

![](https://user-images.githubusercontent.com/1119863/67693700-5da7d400-f95f-11e9-817e-a2ab3478f400.png)

### Versions
* **Rock Version:** 9.1
* **Client Culture Setting:** en-US

**Comment by BEGamache** [comment]
We are getting the same thing. I thought it may have been an issue with the actual attribute's abbreviated name.  It appears to be primarily an issue with the grid-filter's abbreviated name when it combines the Name and Key of the attribute.

I shortened one of the longer attribute names to 'Additional' instead of 'Additional People Serving with you (including kids)'. Here is the name and abbreviated name when I looked at the grid-filter attribute it generated: `grid-filter-186-452356-AdditionalPeopleServingWithYouIncludingKids|Additional` (77 characters long)

In this case, when I shortened the main Name field it worked. But most of the longer attribute names and keys are from registrations or workflow forms as you pointed out.

**Comment by chrismcgrath** [comment]
Confirmed, we just ran into this as well.  My one comment would be that I would want the abbreviated name value to work the same as NickName does on Person. Leave it as null if it's blank in the UI, and only let it be set manually. Otherwise a lot of event registration questions are going to have a meaningless truncated name there that would be bad to display anywhere, unless I'm totally misunderstanding the intended use case for this column.
