### ISSUE TITLE
Public calendar is very slow in 10.1 beta

### ISSUE THREAD

**Issue by kcirgjd** [SparkDevNetwork/Rock#4017]
### Description
I have not been able to replicate this because the pre-alpha site seems to be down but there was a discussion in the #betaTester channel where others have seen similar issues. 

The public calendar is taking up to a minute to switch between months or views. 

### Steps to Reproduce
1. Go to public calendar
1. change months
1. Wait

**Expected behavior:**

Less then 2 second page load. 

**Actual behavior:**

up to a 1 minute page load 

### Versions
* **Rock Version:** [10.1]
* **Client Culture Setting:** [Database Version: Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64) Jun 15 2019 00:26:19 Copyright (C) 2017 Microsoft Corporation Express Edition (64-bit) on Windows Server 2019 Datacenter 10.0 (Build 17763: ) (Hypervisor) Database Size: Unlimited]

┆Attachments: <a href="https://app.asana.com/app/asana/-/get_asset?asset_id=1152786088535373">image.png</a>

**Comment by nairdo** [comment]
@kcirgjd DJ, I was just able to confirm (on a prod-test instance with real data) that our fix for this issue does solidly resolve this problem.  We're going to re-patch v10.1 (something we don't normally like to do) since it's already in beta, but for those of you who may already have 10.1 running (in production) let me know (DM me) and I'll get you the updated block and Rock.DLL with the fix in it.
