### ISSUE TITLE
Group Scheduling using Starting On date

### ISSUE THREAD

**Issue by abeatle8** [SparkDevNetwork/Rock#4032]
### Description
In trying to schedule 5 different people on one Sunday rotating every 5th Sunday. A,B,C,D,E,A,B,C,D,E,A,B ...
Each person is giving a start on date 1 week after the last but in groups scheduling all groups members are grouped together overlooking the start on date.  This happens as well on the when changing the schedule to every 2,3,4,5, and 6th week.

### Steps to Reproduce
1. Create Group Member Schedule Template Detail Recurring, Weekly, 5 weeks, Sunday. ![image](https://user-images.githubusercontent.com/58859921/70822596-e95caf00-1dab-11ea-9cde-0f37c0922c09.png)
1. Update scheduling group member preference current schedule: 5 week template, Starting On: pick past date or future date, click Assignment schedule and location. ![image](https://user-images.githubusercontent.com/58859921/70822620-f8dbf800-1dab-11ea-9362-007846e04cb5.png)
1. Repeat with other groups members so that each group member has a 1 week different starting on date. ![image](https://user-images.githubusercontent.com/58859921/70822630-01ccc980-1dac-11ea-9ada-a97d26dbe57a.png) ![image](https://user-images.githubusercontent.com/58859921/70822649-0e512200-1dac-11ea-9111-c6fd9bfe1ab8.png)
1. Go to Group Scheduler and select Group, Week, Location, Show matching preference ![image](https://user-images.githubusercontent.com/58859921/70822668-1dd06b00-1dac-11ea-8c0d-0f5c82d6d0ef.png) ![image](https://user-images.githubusercontent.com/58859921/70822675-21fc8880-1dac-11ea-9ca8-f94c5fb69c50.png) ![image](https://user-images.githubusercontent.com/58859921/70822684-26c13c80-1dac-11ea-8792-4098d57c1f18.png)
1. Changing week will show all group members available on the same date and not available on the same dates.  Whatever week template is set to 2,3,4,5,6 all will be available at same time.

**Expected behavior:**

Each group member would be available 5 weeks after start on date and would not be available till after 5th week.

**Actual behavior:**

Group members all start first week in week dropdown and the 5th week.  The are not staggered 

### Versions
* **Rock Version:** 9.4
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@abeatle8 Currently the group member schedule templates do not support that kind of team staggering using the person's Starting On date.  It would require that a start date be added to the schedule on the template (not on the person's "Starting On"; see mock-up below) but Rock's UI doesn't currently support supplying a start date for those schedules.

![image](https://user-images.githubusercontent.com/383807/71690429-f0029480-2d61-11ea-9160-ae5a419b4544.png)

With Team A starting on the 12/1 date, Team B starting on the 12/8 date, etc.
![image](https://user-images.githubusercontent.com/383807/71690552-47a10000-2d62-11ea-8726-c58ebc9429fa.png)

You might consider opening an idea (aka feature request) over at https://community.rockrms.com/ideas for now.

**Comment by abeatle8** [comment]
Thanks for getting back with me.  Just to be clear at this time the 2nd image is only a mockup not something that I can currently do? I can’t set a start date for a schedule.

**Comment by nairdo** [comment]
> ...the 2nd image is only a mockup...?

Correct.

**Comment by nairdo** [comment]
Hi @abeatle8 I know this is an older item, but I believe what you were trying to accomplish is now possible using a [new v13.2 feature](https://github.com/SparkDevNetwork/Rock/commit/319d23deb51733a2026a46225dccb41a8e1d625b) for "List: Group Members - Matching Week" option (seen below in highlight).  (_Disregard what I was originally showing above with those A Team, B Team and C Team type Group Member Schedule Templates._)

![image](https://user-images.githubusercontent.com/383807/178378752-8eee45e0-d31e-4983-8b33-3ffd0c80879e.png)

When I set up a "Every 5 Weeks on Sunday" type schedule (as you've shown above), as long as the person's schedule preference is set correctly, it should now show that person on the 5th matching week.

![image](https://user-images.githubusercontent.com/383807/178379299-4b3b5a74-9a23-4c1b-b91b-42673861927e.png)

![image](https://user-images.githubusercontent.com/383807/178379374-d3032412-a260-4633-9f61-7f62a7532d65.png)

I'll leave this open for a week or so to see if you can confirm this too, but otherwise I'll close it if I don't hear back from you.
