### ISSUE TITLE
Regular Expressions fail as default values for Lava Shortcode Parameters

### ISSUE THREAD

**Issue by gonemob** [SparkDevNetwork/Rock#4054]
### Description
A clear and concise description of what the bug is, include screenshots if applicable.

### Steps to Reproduce
1. Edit a Lava Shortcode's Paramaters
1. Enter the regular expression of /([!-\/:-@\[-`{-~]|\sand\s)+/i as the Value
1. Click 'Save'
1. Edit this same shortcode again and observe the `|` has been replaced and sometimes the `+` too.

**Expected behavior:**

The value added in the Value field is the same, with no replacements. 

**Actual behavior:**

From what I've observed, the pipe `|` is always replaced with %7C in the database, `+` is **_sometimes_** replaced with a `space` and the reason your regex doesn't work as a default value is revealed.

Below's a screenshot from SSMS of the Parameters column. regularexpression and testregex are the parameters to observe:
![image](https://user-images.githubusercontent.com/13141251/72378721-91c9a000-36d7-11ea-8303-fde7f78aafa9.png)

Here's a screen shot displayed as a javascript var in the browser's dev tools.  The top regex is correct and was passed into the shortcode, the bottom is the same regex, but as the default value :
![image](https://user-images.githubusercontent.com/13141251/72376124-10700e80-36d3-11ea-8202-e712236cb4a6.png)

Here's the same regular expression, but as a default value in both rather than passed via the shortcode:
![image](https://user-images.githubusercontent.com/13141251/72376793-3518b600-36d4-11ea-974e-a44b28ac307f.png)

### Versions
* **Rock Version:** [9.4]
* **Client Culture Setting:** [en]

**Comment by cabal95** [comment]
For some clarification, the JavaScript under the hood to the KeyValueList and ValueList controls seem to encode a few special characters with URI encoding (such as `^` and `|`). However, `+` is not among them. That means that when the value is later URI decoded, the `+` gets translated into a ` `.

The solution may be as simple as just URI encoding the entire value instead of just those specific characters, though maybe there was a reason that couldn't be done.
