### ISSUE TITLE
Restored Group's do not Restore GroupMembers

### ISSUE THREAD

**Issue by markewampler** [SparkDevNetwork/Rock#4055]
### Description
Turn on Group History for a GroupType.

Add people to a group of that type.

Run Group History Job.

Archive the Group. 
Run Group History Job. 
Restore the Group.

Group is restored without any groupmembers.

### Steps to Reproduce
1. Turn on Group History for a GroupType.
1. Add people to a group of that type.
1. Run Group History Job.
1. Archive the Group. 
1. Run Group History Job. 
1. Restore the Group.

**Expected behavior:**

My assumption would be that when the group is restored that all of the GroupMembers would be restored with it to the Role/Status they had at the time of Archiving the group. 

**Actual behavior:**

Currently how it functions is the Group is restored and no one comes back with it.  They stay as Archived GroupMembers.  So you can get the data back, but lots of manual labor or a SQL update to change their status' back.

### Versions
* **Rock Version:** [9.2]
* **Rock Version:** [10.1]
* **Client Culture Setting:** [en-us]

**Comment by JimMichael** [comment]
Confirmed on 10.1. What's curious is that this is listed as fixed in the 10.0 release notes: 

"Updated Groups so that group members will be made inactive when the group is made inactive. Also updated groups so that group members will be archived when the group is archived. _If the group is made active again, it'll also make any group members active if they were marked inactive when the group was made inactive. Fixes: #3592 _
