### ISSUE TITLE
Group Scheduler Includes Inactive Group Members

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4106]
### Description

An inactive group member shows up and is schedule-able in Group Scheduler

### Steps to Reproduce

1. Identify a serving team group and inactivate someone, or note someone who is already inactive.
2. Click the Group Scheduler button (assuming group is already set up with a location and schedule)
3. Choose Schedule and Location.
4. Observe that the inactive person(s) show in the list of people and can be scheduled.

![image](https://user-images.githubusercontent.com/3903408/74370384-a3689b00-4d9c-11ea-8988-f89d5212b02c.png)

**Expected behavior:**

Inactive people would be excluded from the Group Scheduler function.

**Actual behavior:**

They show up. Even worse, there's nothing that identifies them visually as inactive... they look just like any other active people in the group.

### Versions

* **Rock Version:*9.4, 10.1

**Comment by JimMichael** [comment]
Note that inactive people _are_ excluded from showing in the Schedule Toolbox areas. A person will not even see a group they are inactive in within the toolbox, preventing them from setting preferences on that group. *However*, if the person already has preferences on the group and is subsequently inactivated, _Auto Scheduler_ can still schedule them as well.

**Comment by hbcpn** [comment]
I've confirmed this as well. Actually I've seen it since day 1 of the Group Scheduler v9.0 release in August '19 but hadn't gotten the chance to issue the bug (my bad).

(Serving Group Member with Status of Inactive)
![image](https://user-images.githubusercontent.com/44647719/74435693-0e64b100-4e33-11ea-8646-4d6710de45f3.png)

(Inactive Member still showing in the Group Scheduler Picker)
![image](https://user-images.githubusercontent.com/44647719/74435873-6f8c8480-4e33-11ea-954c-4a17061284e3.png)

Luckily our serving groups are rather small due to the size of our church so the ministry leaders are pretty aware of who's inactive in their groups. However I can see this being a massive problem for larger churches that are trying to schedule over 100 people on a given weekend to serve and try to figure out who is and isn't active in any given serving team.

Not sure why you'd want to expose inactive members in the picker, but to make it flexible maybe it can be allowed and the selection of who to list in the picker should be at the group scheduling block settings level with Inactive un-selected by default to not confuse new users to this feature.
