### ISSUE TITLE
Security Code Blacklist: New Combinations

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#4142]
### Description
During a powerful video testimony this week, we broadcast a security code on the screen to communicate with a parent who needed to get their child. The person on the video was a very wonderful woman but the security code was "2XL." While the video crew should have waited until after the video completed, it would be wise to add similar combinations to the blacklist.

Recommended additions to blacklist:

1XL, 2XL, 3XL, 4XL, 5XL, 6XL, 7XL, 8XL, 9XL, XXL

### Versions
* **Rock Version:** [9.4]
* **Client Culture Setting:** [us-en]

**Comment by cabal95** [comment]
It might be better to finally add a Global Attribute that provides per-church additions to the security code blacklist.

**Comment by MicahO** [comment]
My only concern with that is that I'd never think of adding 2XL. It would be nice to easily learn from other people's bad experiences.

**Comment by cabal95** [comment]
Agreed, but `2XL` (and the others) aren't really bad words. They are just context specific things that some people _could_ misinterpret and be upset by. Whereas the code `SEX` (and many others I won't mention) is probably going to cause a stir for pretty much everybody. Not to mention lots of giggles by the middle school boys.

For example, `53X` isn't in the blacklist even though `S3X` is. I'm sure somebody at some point will ask for `53X` to be added because they use a custom font to display the codes that makes the `5` look too much like `S` and one parent got upset.

The global attribute approach also means you don't have to wait 12+ months for somebody to update Rock itself and get that update installed to fix that problem you are having. And somebody could write a short Recipe that lists various sets tokens that people could look at to get an idea of "oh yea, that's a good idea, we might want to exclude set A, but I think we're okay with set B being used".

Also, not saying that `2XL` and the others absolutely should not be included in core. If Jon and the team decided that was a good call I wouldn't throw a fit. I just think for myself it's a bit too context specific of an issue to warrant removing those from everybody's system.

**Comment by nairdo** [comment]
@MicahO @cabal95 Since we're very close to moving v10.2 to beta, I'm just going to sneak these new items into the attendance code ban list.  We can still have a conversation about an idea to allow additional bad words via a global attribute, but for now, we just did not want that to happen again.
