### ISSUE TITLE
Sorting by phone number on data integrity reports 

### ISSUE THREAD

**Issue by theundecided** [SparkDevNetwork/Rock#4196]
### Description
Sorting by phone numbers will spit out error message 
![Imgur](https://i.imgur.com/DIp1elm.png)

### Steps to Reproduce
1. Go to Data Integrity > Reports > Individuals with Duplicate Phone Numbers
1. Click on sort by Home Phone**Expected behavior:**

Rock to sort report by phone numbers

**Actual behavior:**

Error Message listed above 

### Versions
* **Rock Version:** [1.10.2.3  AND  1.10.1.4  AND  1.9.3.2]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
Confirmed on prealpha as well.

**Comment by jasonhendee** [comment]
@theundecided , thanks for reporting this issue. While we agree it would be ideal to sort the specified Report by phone number(s), since the whole point of the Report is to identify duplicate phone numbers, the problem has to do with how we're using Entity Framework to aggregate this data behind the scenes. Unfortunately, we're unable to apply a true fix at this time to allow sorting on these fields. What we've chosen to do instead is to disable sorting altogether on phone number fields, so the warning ultimately won't be encountered. If you still need to sort by phone numbers, one option would be to export the Report to Excel, and sort there. Please let us know if you have any further questions or concerns!

![Issue4196_ExportToExcel](https://user-images.githubusercontent.com/59710095/83905142-05fff100-a716-11ea-926a-d21e57e38719.png)
