### ISSUE TITLE
The Person-to-Business conversion process sets the Business Connection Status

### ISSUE THREAD

**Issue by cbump** [SparkDevNetwork/Rock#4199]
### Description
When a person is converted to a business, the code sets the Connection Status on the new business to null.  Then the PreSaveChanges trigger on the Person model sets it back to a visitor.  The lines of code that do each of these things are here:

https://github.com/SparkDevNetwork/Rock/blob/b7ec816df778facf425abf9fcfb2b8d370663f26/RockWeb/Blocks/Finance/ConvertBusiness.ascx.cs#L204
https://github.com/SparkDevNetwork/Rock/blob/b7ec816df778facf425abf9fcfb2b8d370663f26/Rock/Model/Person.cs#L1997

### Steps to Reproduce
1. Go to /convertbusiness
1. Select a person to convert to a business
1. Click the "Convert" Button

Check the connection status on the business to see that they are now a visitor.

**Expected behavior:**

Since the Business Converter block sets the value to null I would expect it should remain null.

**Actual behavior:**

The ConnectionStatusValueId will be set to a non-null value;

### Versions
* **Rock Version:** 10.2
* **Client Culture Setting:** en_us

**Comment by cabal95** [comment]
I'm pretty sure I wrote the original code and based it off what I saw in our database's business records. So it's possible "null" is not really a valid value and it should be set to a non-null value. Somebody on the core team would have to weigh in on that part.

**Comment by nairdo** [comment]
@cabal95 Daniel is right.  Currently, even if you create a business via the Business Detail block, it will also default that status to Visitor due to the `PreSaveChanges` -- which _somewhat_ indicates it's required.  @cbump Does the setting of these to "Vistor" interfere with something or some process in your environment?  I'm interested in better understanding what you are using the ConnectionStatus for on Business Type records.  Also, Ignoring [the change that introduced that behavior in 2018](https://github.com/SparkDevNetwork/Rock/commit/6a41bb684fa99d3e31dd11cd60f353b069b704f7), have you run into any trouble elsewhere when they were left as null?

**Comment by nairdo** [comment]
@cbump  Does setting the connection status to the default of "visitor" cause you a problem elsewhere?

**Comment by cbump** [comment]
@nairdo I don't really think it creates a technical issue as much as it is just a head-scratcher logically.  It's really just an extension weirdness that happens because businesses are people.  In context, a business should not be a visitor or attendee . . . because that simply doesn't make sense.  That's all.

I'm not sure we actually know what will happen if we null it across the board.  We actually have a separate connection status for Businesses so after we convert to a business we manually set it to that value. . .
