### ISSUE TITLE
Group Capacity Off By One Exception

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4207]
### Description

On a Group Type with a _Group Capacity_ rule of _Hard_, the defined Capacity is not honored and an exception is thrown when trying to add someone that would make the group AT capacity, but NOT over it. 

### Steps to Reproduce

1. Identify a group type that has a Group Capacity rule of Hard. (Or just edit Small Group type and add that capacity rule)
2. Go to Group Viewer and create a new group of that type.
3. Edit the new group and set capacity to 1
4. Add someone to the group and observe the exception.

**Expected behavior:**

Group capacity would be honored and you would be able to add people up TO the defined group capacity. 

**Actual behavior:**

An exception is thrown when adding a member that would make the group AT the defined capacity. To work around the issue you must increase the desired capacity by 1 to allow the group to be at the desired capacity. This is new behavior as of 10.x and didn't occur in 9.4.

Duped on demo and prealpha. 
![image](https://user-images.githubusercontent.com/3903408/80401410-e73e4d00-8881-11ea-8004-35c8e0309a50.png)

### Versions

* **Rock Version:** 10.0-11.0

**Comment by cabal95** [comment]
It looks like this is being caused due to this chunk of code:

https://github.com/SparkDevNetwork/Rock/blob/1.10.2/Rock/Model/GroupMember.cs#L803

The code gets the current number of active members (which includes "this" since it's being saved) and then adds 1 for comparison. I'm guessing this chunk of code was borrowed from one of the blocks that did the check _before_ adding the member to the group.
