### ISSUE TITLE
Odd Formatting on Preregistration Block

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4221]
### Description

The Family Pre Registration block has different formatting/layout of the exact same fields, for both adults. 

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/FamilyPreRegistration
2. Observe that the fields, though identical (as far as I can tell) lay out differently as one wraps a field the other does not.
![image](https://user-images.githubusercontent.com/3903408/81112733-bba40e00-8ee4-11ea-87fe-53a94262b4ab.png)

**Expected behavior:**

Fields for both adults would be formatted the same.

**Actual behavior:**

One of them wraps a field that the other does not. This leads to a visually confusing data entry experience.

### Versions

* **Rock Version:** 10.2

**Comment by milescarmany** [comment]
The First Adult appears to be the exception. All children have the birthday grouped on the first line with First, Last, and Gender.

This appears to be caused by the placement of the clearfix div.

Confirmed on our instance:
- **Rock Version:** Rock McKinley 9.4 (1.9.4.1)
- **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
via https://github.com/SparkDevNetwork/Rock/commit/d8c8a3b6dbf0ccfef1c561cc482d85631c4b5d7c
