### ISSUE TITLE
Duplicate? blocks: Content Channel Item View & Content Channel View Detail

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#4223]
### Description
The blocks _Content Channel Item View_ and _Content Channel View Detail_ appear to be duplicate blocks, or at least perform the same functions. The only difference I can find is that the _Content Channel Item View_ block has a _Merge Content_ option (while View Detail does not)

The blocks have identical Block Type descriptions:
> Block to display a specific content channel item
![<a href="https://user-images.githubusercontent.com/8688424/81206627-029c0d00-8f92-11ea-866d-a615bc526886.png">https://user-images.githubusercontent.com/8688424/81206627-029c0d00-8f92-11ea-866d-a615bc526886.png</a>](https://user-images.githubusercontent.com/8688424/81206627-029c0d00-8f92-11ea-866d-a615bc526886.png)

Block configuration examples:
_Content Channel Item View_
![<a href="https://user-images.githubusercontent.com/8688424/81203989-370dca00-8f8e-11ea-8aa2-f33c288cf2e6.png">https://user-images.githubusercontent.com/8688424/81203989-370dca00-8f8e-11ea-8aa2-f33c288cf2e6.png</a> image](https://user-images.githubusercontent.com/8688424/81203989-370dca00-8f8e-11ea-8aa2-f33c288cf2e6.png)

_Content Channel View Detail_
![<a href="https://user-images.githubusercontent.com/8688424/81205431-51e13e00-8f90-11ea-92bc-55aa9dd4ff66.png">https://user-images.githubusercontent.com/8688424/81205431-51e13e00-8f90-11ea-92bc-55aa9dd4ff66.png</a>](https://user-images.githubusercontent.com/8688424/81205431-51e13e00-8f90-11ea-92bc-55aa9dd4ff66.png)

### Steps to Reproduce
1. Add some blocks to a zone
1. Select the 'Content Channel Item View' and 'Content Channel View Detail' blocks
1. Open Block Configuration for both blocks
1. They appear to be the same blocks

**Expected behavior:**

If the blocks are the same, why do they both exist?

**Actual behavior:**

Only provide one block for the stated block type description and function they serve

### Versions
* **Rock Version:** 9.4, 10.2
* **Client Culture Setting:** en-US

**Comment by smross** [comment]
FYI, I verified this on both my production instance and the Demo site. According to block types they have different filenames (but I'm not an expert there)

**Comment by nairdo** [comment]
The plan for this issue is going to be this...

During one of the next updates (v13.3 or slightly later) via a data migration, any block _instances_ that are using the old `~/Blocks/Cms/ContentChannelViewDetail.ascx` BlockType will be automatically converted into `~/Blocks/Cms/ContentChannelItemView.ascx` (`63659EBE-C5AF-4157-804A-55C7D565110E`) along with all the block instance attribute values.  Then that block type will be removed from the BlockTypes list (and the BlockType _file_ should have also been deleted during the RockUpdate process).

**Comment by smross** [comment]
@nairdo a question for clarification:
In my (non-expert) experience, the approach to writing Lava for these 2 blocks can differ very slightly; this is _probably_ related to learning better methods with the ItemView block (whereas I barely knew Lava when I used the ViewDetail block). Consequently, I would advocate for this fix and migration being listed in _at least_ 2 places so that those upgrading to 13.4 should be able to avoid surprise:
* The Release Notes
* The Upgrade Checklist

The following note would be helpful to me if I was managing a system that had both in use:

> Blocks of type _ContentChannelViewDetail_ (`~/Blocks/Cms/ContentChannelViewDetail.ascx`) have been migrated to use the block type _ContentChannelItemView_ (`~/Blocks/Cms/ContentChannelItemView.ascx`). These blocks serve the same function, and we're cleaning up the old block that is no longer needed [(#4223)](https://github.com/SparkDevNetwork/Rock/issues/4223)  **Please verify your lava templates are rendering as expected for instances where you were using the old block.**

**Comment by crayzd92** [comment]
See b2184826f088f0cde5d2c63bec39d77d10e0a2cd

**Comment by asdf1nit** [comment]
I have been meaning to post about an issue\difference with the new block vs the old block and I think this is as good a place as any. I have continued to use the old block because it doesn't require setting a specific Content Channel and the new block does. 

In our use, this means we can have a single page that can handle content from multiple content channels (think online classes where they are all different content channels but of the same type ).
![image](https://user-images.githubusercontent.com/18108765/167978101-ac9af213-512f-4a65-91f4-1abd966db2d0.png)

On the new block you are limited to only a specific content channel( a value is required), which would mean I would need a separate page for each channel. 
![image](https://user-images.githubusercontent.com/18108765/167978274-88f6d2fd-9da9-4e8e-8ad2-811afb093c46.png)

I can work with whatever the outcome is. Our use case just fits the old way better. If there's a newer block that does what I need I'm not aware of it

**Comment by nairdo** [comment]
@smross wrote:
> ...I would advocate for this fix and migration being listed in _at least_ 2 places so that those upgrading to 13.4 should be able to avoid surprise:
> 
> * The Release Notes
> * The Upgrade Checklist

I was able to add it to the "Heads Up" note of the release.  It will look pretty close to this:

![image](https://user-images.githubusercontent.com/383807/170155529-5e18d252-3120-4e12-b02e-7387d7b2ddb7.png)

**Comment by nairdo** [comment]
> The plan for this issue is going to be this...
> During one of the next updates via a data migration, any block instances that are using the old...

We've uncovered a bit of a problem during our v13.4 beta testing, so we're postponing the deletion and conversion of the block until v13.5.
