### ISSUE TITLE
Buggy Behavior in Email Editor (Video)

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#4260]
### Description, Steps to Reproduce, Expected behavior, Actual behavior:
See video documenting bugs: [http://youtube.com/watch?v=img823M11E0](http://youtube.com/watch?v=img823M11E0)

Happy to write it out if that helps—just let me know.

[NOTE: Using Chrome on a mac; unclear how this behaves for the individual using Safari on a mac.]

### Versions
**Rock Version:** Rock McKinley 10.2
**Client Culture Setting:** en-US

**Comment by jacksojourn** [comment]
This bugginess is causing ongoing issues for our staff. How can I help it get addressed?

**Comment by nairdo** [comment]
@jacksojourn We have not forgotten about you and this issue -- we've just been trying to determine how to best address it, since many of the problems are within the library (called "summernote") that Rock is currently using for that WYSIWYG HTML editor.  (_At the moment, that plugin has a number of unresolved issues._)   Having said that we were able to make a small fix partial (https://github.com/SparkDevNetwork/Rock/commit/d2537eb8dff86b5baaa6129bcf0b043c8998f669) which will be included in Rock v12. 

However, we're still investigating possible future plans for the HTML editor in Rock.

**Comment by jacksojourn** [comment]
@nairdo Thanks! Glad to know you're tracking it!

**Comment by jonedmiston** [comment]
These issues are in the SummerNote library which we are unable to fix. For v17 we are working on a complete re-write of the emila wizard which will remove SummerNote and replace it with a different WYSIWYG editor. Closing this as the new wizard will be significantly different in how it works.
