### ISSUE TITLE
Group Toolbox allows bad Group address causing Exception when Editing Group.

### ISSUE THREAD

**Issue by NuclearTacos** [SparkDevNetwork/Rock#4261]
### Description
The Group Toolbox allows you to save addresses with just a state and zip.  This causes an exception when trying to edit the group in the Group Viewer.
![pNPK65eCDf](https://user-images.githubusercontent.com/19762670/85051447-217aeb00-b15d-11ea-91f2-efc58a4dd152.gif)

### Steps to Reproduce
(on fresh demo site)

1. Visit the Group in Group Viewer and click Edit to see that it doesn't error.     ( https://rock.rocksolidchurchdemo.com/Group/111 )
1. Go to Group Toolbox page     ( https://rock.rocksolidchurchdemo.com/page/365?GroupId=111 )
1. Change block setting for "Enable Location Edit" to "Yes", and save the block configuration.
1. Refresh, click Edit
1. In the "Locations" area at the bottom, switch to "Other Location"
1. Delete All values from the address box except a state and zip code
1. Click "Select" and then "Save" to commit that address for the Group.
1. Go back to the Group in Group Viewer and click "Edit"     ( https://rock.rocksolidchurchdemo.com/Group/111 )

**Expected behavior:**

First, I expected that malformed locations would still be able to be removed by the UI on the Group Viewer.

Second, I thought malformed addresses were kept from committing to the database.

Third, I expected to be able to remove a meeting address in the Group Toolbox, but I can't.  I've seen people on my Rock instance remove all address fields to "clear" the address, and this makes it un-editable to staff.  To fix this right now, we through the UI, then set it to a bogus city, then the address can be removed on the staff side.  Choosing if a Small Group leader can remove the address from the group is probably a good block option.

**Actual behavior:**

When Small Group leaders try to remove their addresses, they instead set a malformed address for the group.  This prevented staff from being able to update the Group's attributes and make other changes like activating/inactivating.

### Versions
* **Rock Version:** 10.2, 11.0 (demo, prealpha)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@NuclearTacos  We've only addressed the exception that was being thrown when trying to save the record.  The other two expectations are under review.

**Comment by MrUpsideDown** [comment]
@NuclearTacos - Thanks for taking the time to report these issues.
Here is a summary of the commits we have added to address these problems:
Issue #1 - Malformed Locations throw an Exception (Fixed in v11.1):
https://github.com/SparkDevNetwork/Rock/commit/26df78735776658881d0e7759f560d7d2ee75ec4
Issue #2 - Required fields not correctly validated in Group Location Address (Fixed in v12):
https://github.com/SparkDevNetwork/Rock/commit/65fadf5b90bfbb50baf0f0c5df8ac4b7f95ac7e8
Issue #3 - Allow empty Group Meeting Location in Group Toolbox (Fixed in v11.2):
https://github.com/SparkDevNetwork/Rock/commit/93f0eec1cebdb0e48cb4a84a03df1dabcc3ed9da
