### ISSUE TITLE
Persisted Datasets that Use Lava Includes for Build Script Won't Build w/Job

### ISSUE THREAD

**Issue by briankalwat** [SparkDevNetwork/Rock#4278]
### Description
We have a number of persisted datasets that use a lava shortcode (we pass parameters to the same shortcode to generate various datasets) to generate the build script. That lava shortcode contains an include so we can version-control the build script lava.

As far as we can tell, the **job** throws errors for any dataset that is built with a lava include (whether in the shortcode or in the dataset build script directly). Refreshing datasets **manually** continues to work as expected. We believe this started happening after we pulled in `11.0.18`.

### Steps to Reproduce
1. Create a persisted dataset that uses a lava include.
1. Run Update Persisted Datasets Job
1. See dataset you created fail to build.
1. Replace the lava include in the build script with the actual lava from the lava template.
1. Run the Update Persisted Datasets Job again.
1. See dataset correctly build.

**Expected behavior:**

Update Persisted Datasets Job should be able to build datasets that use lava includes - both directly in the build script, and in a lava shortcode in the build script.

**Actual behavior:**

Update Persisted Datasets Job fails to build datasets which utilize lava includes.

### Versions
* **Rock Version:** 11.0.19
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Just to be clear, you are talking about a `{% include ... %}` statement, correct?

**Comment by garrettjohnson** [comment]
I think the issue is probably around using the current theme lava include, i.e. `{%- include '~~/Assets/Lava/jsontest.lava' -%} `. This lava will work when running the persisted dataset manually because the current theme is used. Whereas when the `~~` reference is ran as a job there is no theme.

The lava can run successfully by using a single ~ and manually including the theme directory: `{%- include '~/Themes/Rock/Assets/Lava/jsontest.lava' -%} `

@briankalwat  Let me know if this solves your issue.

**Comment by briankalwat** [comment]
@garrettjohnson we're currently using the Rock root path as you suggested (below). Also, if this was the issue, the datasets would not build when manually refreshed, either.

{% include '~/Themes/NewSpring/Assets/Lava/DATASETS/content-channel-items-by-channel.lava' %}

**Comment by cabal95** [comment]
I was able to reproduce this on my own system. The contents of the file I tried to include were just some static JSON:

```json
{ "Message": "Hello!" }
```

Refreshing it manually worked.  Running the job, the job will say it worked but I ended up with a Lava error inside the results instead of the expected content:

![image](https://user-images.githubusercontent.com/1119863/86263542-3d778700-bb76-11ea-8bb4-e31ad8be9e8f.png)

I suspect the `{% include %}` directive is attempting to access some object that normally exists, maybe like the current Http Request or something, which isn't available when being processed as a Job.
