### ISSUE TITLE
Cannot Open/Close Check-in Locations While Using Redis

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#4325]
Submitted on behalf of **Christ's Church of the Valley**

### Description
If a check-in location is opened/closed via manager mode, the check-in kiosk will not update unless the cache is cleared.  This only happens when using Redis as a backplane.

### Steps to Reproduce
1. Setup Redis. (We use Azure Redis but for local testing I was using this: https://github.com/dmajkic/redis/downloads )
1. Setup Rock to use Redis.
1. Bring up check-in and attempt to open/close the location using the Manager mode.
1. The check-in will not update unless the cache is cleared. 

**Expected behavior:**

The check-in should open/close when the locations are opened/closed via manager mode.

**Actual behavior:**

The check-in will not open/close.

### Versions
* **Rock Version:** 10.2, latest develop branch
* **Client Culture Setting:** en-US

**Comment by trydyingtolive** [comment]
We have a more robust version of the check in manager that had similar issues. The short of it all is that Rock can't clear partial cache, and closing a location requires that all the kiosk devices be reloaded into cache (a partial cache clear). Its all or nothing for Rock's cache. With memory cache clearing partial cache clears every bit of cache for the whole system and with a Redis backplane it just doesn't actually clear anything useful. This is a quick record of my discoveries and solution for whomsoever will be fixing the issue. 

When RockCacheManager adds an item to cache it generates a unique key for that item. It then stores the item in cache and adds the key to a second cache item containing all the keys for all items of that type. This may not make sense, but basically you can't request all the cached items of a particular entity type if you don't know what their keys are. So, for example, if you asked the cache manager for all defined types, it first requests the all the keys then loads each item by the keys it receives.

This matters because if you use memory cache or a Redis backplane the ItemCache.Clear() acts differently. If you are using memory cache only, any time you call clear for any item type ( KioskDevice.Clear() for example ) it runs Cache.Clear() which as far as I can tell clears all cache. When using Redis it merely removes the list of keys, but doesn't actually remove any of the cached items themselves. https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Web/Cache/ItemCache.cs#L312 

With KioskDevice (which is actually not a KioskDevice but is the cached representation of a Device that is set to be a Kiosk) this is a step more broken. When a KioskDevice is cached it doesn't set a key in the list (at least as of 1.10.2).. so even what it tries to delete doesn't exist. https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/CheckIn/KioskDevice.cs#L274 This is subtle because if you follow the logic it looks like it does add the key, but it actually doesn't. The logic is written so that if there isn't a key list already stored in cache, you can't add a key. Even more the key list seems to be stored in two different places? Sometimes it's stored without a region and other times it's stored in a special keys region. 

We ended up pulling all the applicable device ids from the database and individually removing them from cache. I would have preferred to use the key list, but again there isn't one.  (Again this doesn't help you directly, but maybe someone will be able to use this information).

**Comment by jhawkzz** [comment]
Been looking at this over the past week or so with our team, and still experiencing issues. The closest we've found to a "fix" is to upgrade our Redis tier in Azure, but there seems to be something going on in the underlying caching with v10.2.

Would love to get some insight from anyone available at Spark that knows how the caching works!

**Comment by jonedmiston** [comment]
@jhawkzz Will reach out to you offline to connect on this.

**Comment by ethan-sparkdevnetwork** [comment]
@trydyingtolive @jhawkzz 

Mark's summary of what is happening is correct. Rock needs to treat Redis differently to clear all items of a type from the cache. This is because the BaseCacheLibrary's (a third-party library) clear method for a type when using Redis will clear all items of all types from the cache. This is not a desired behavior. The second issue is we can't get a list of keys or items from the BaseCacheLibrary, only request items by key. So we have to create this list ourselves, and once this list is created we have to assume it is accurate. So the first time a cached item is requested we can't just create a list for that type without first getting all of the keys, otherwise we would have to compare the key list to the DB every time it is used and lose the advantage of the cache. In most cases this isn't a problem, but check-in is different. Here is a summary of the fix:

1. Add a parameter to ItemCache.GetOrAddExisting() to pass in a function to get all keys.
2. Use this function in AddToAllIds if the list is null (i.e. when creating a list for a type for the first time)
3. Created ItemCach.FlushAllItems() to loop through the keys and remove each item
4. Use FlushAllItems in ItemCache.Clear() when using Redis
5. Added method KioskDevice.GetAllIds() as the delegate and use it in KioskDevice.Get()

We are looking at other ways to do this more generally in v12/13 where we won't need to call Clear at all. If there are any questions, concerns, or suggested improvements about this hit me up via email or Rocket Chat.

**Comment by jhawkzz** [comment]
@ethan-sparkdevnetwork Wow, impressive! Thanks so much for the update. We're excited to see look into this!
