### ISSUE TITLE
No Data View Results with Inherited Defined Value Group Attribute Filter

### ISSUE THREAD

**Issue by kenmulford** [SparkDevNetwork/Rock#4343]
### Prerequisites
* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

A data view based on a Group entity will cease to return results when filter criteria are populated for a filter that points to an inherited group attribute with a field type of "defined value" (I have not tested other field types).

### Steps to Reproduce

1. Configure a group type with a group attribute. I've specifically tested a group attribute field type of "Defined Value" (GROUP TYPE A)
2. Configure a second group type to inherit from the first group type. (GROUP TYPE B)
2. Create multiple groups of the second group type (GROUP TYPE B). Populate different attribute values for each group, leaving at least one with no value.
3. Create a data view, setting the group type filter to (GROUP TYPE B), and a second filter for the attribute from (GROUP TYPE A).
4. On the attribute filter, check a box for any value that you assigned to one of your groups in step 2.
5. Observe that no results come back.
6. Uncheck the attribute filter (so no values are set to default). Observe all groups of that type are returned in the data view results.

**Expected behavior:**

I expected to see groups matching the selected filter criteria.

**Actual behavior:**

I saw no groups at all when at least one value was set as a default value on the data view filter. 

Test performed in the 8/13/2020 instance of the demo site: https://rock.rocksolidchurchdemo.com/page/145?DataViewId=16&ExpandedIds=C1235

![image](https://user-images.githubusercontent.com/1336749/90141352-0d143280-dd49-11ea-89c3-896903233476.png)
![image](https://user-images.githubusercontent.com/1336749/90141375-11d8e680-dd49-11ea-8f54-a7881ded8758.png)

### Versions

* **Rock Version:** [10.3]
* **Client Culture Setting:** [en-US]

**Comment by sam-crisp** [comment]
Went into the Reporting code and found this commit that affects the Expression generator for dataview filters:
https://github.com/SparkDevNetwork/Rock/commit/2e992ebacf8edfedf710e9a1632a1f198ac9c163
Released on version 9.0.

This code creates a GroupTypeId filter when selecting that Inherited Group Attribute filter. The problem comes when it creates the 'where GroupTypeId = ' filter to equal the original group type Id associated with the attribute (not desirable). 

So for example, we create two group types, with Ids of 36 and 37 and create group attributes on the 36 group type, while set 37 group type to inherit from 36 group type. We then create some groups of group type 37 and set up (inherited) attribute values. When creating dataview and report, if we set filters on those inherited attributes, the queryable returned to the Report block has a where clause that says "where GroupTypeId = 36" along with the correct attribute value filter subqueries, thus returning no groups. 

Dynamic Report Use Cases:
Unselected
![Screen Shot 2020-08-18 at 2 57 06 PM](https://user-images.githubusercontent.com/44408754/90559399-2828dd00-e163-11ea-900d-c3770646e105.png)

Selected
![Screen Shot 2020-08-18 at 2 57 20 PM](https://user-images.githubusercontent.com/44408754/90559417-3119ae80-e163-11ea-94a8-da508190b0db.png)

Group Type EDIT Group Attributes
![Screen Shot 2020-08-18 at 2 56 50 PM](https://user-images.githubusercontent.com/44408754/90559447-3c6cda00-e163-11ea-814a-1979ca885dc2.png)

Query from LINQ:
![Screen Shot 2020-08-18 at 2 56 11 PM](https://user-images.githubusercontent.com/44408754/90559497-468ed880-e163-11ea-98b5-8efa75aaebf0.png)

**Comment by sam-crisp** [comment]
Can we get an update on this issue?

**Comment by nairdo** [comment]
Hi @sam-crisp Sam, for issues like this we don't necessarily start investigating until someone from [the community has classified and  'Confirmed' the issue](https://community.rockrms.com/getinvolved).  It sounds like you're implying you've confirmed this bug... if so, feel free to update the issue here:  https://community.rockrms.com/contribute/issues

In the mean time, it sounds like this could be related to the #4059 issue which we are working on.

**Comment by sam-crisp** [comment]
Excellent thank you @nairdo  I'll pass this along and confirm it. 

And yes looks like this is related to #4059 so looking forward to the fix.
