### ISSUE TITLE
Rock v11 not recording/receiving transactions from Iprocess (Transnational)

### ISSUE THREAD

**Issue by CdavisLMC** [SparkDevNetwork/Rock#4350]
### Description
Five Transactions run last Thursday evening through IProcess (Transnational Gateway) have not uploaded to Rock. 
Downloaded Payments and errors exist.
Payments have settled in Transnational, but not in Rock. All were run specifically through IProcess

**Transnational:**
![image](https://user-images.githubusercontent.com/69787557/90563066-dc793200-e168-11ea-9dc1-c499befbc16d.png)
**Rock**
![image](https://user-images.githubusercontent.com/69787557/90563124-f31f8900-e168-11ea-9945-f9eba5206a25.png)

This was tested yesterday for reproducibility and has yielded the same [failure to communicate] result.

The process worked properly before v11

### Steps to Reproduce
Use IProcess to pay (Ipad app from Transnational)
Payments process through Transnational (automatic, no action on users part)
No record of transaction exists in Rock

**Expected behavior:**

All payments processed to completion and transactions uploaded and recorded in Rock

**Actual behavior:**

Payments process successfully but have not communicated with Rock

### Versions
* **Rock Version:** [Rock McKinley 11.0 (1.11.0.3)]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi @CdavisLMC After looking at this closer, we realize you've stated that the transactions are actually being generated outside of Rock (from another iPad app; IProcess in this case).  Rock only expects the gateway to handle transactions that are originated from Rock, and Rock's Get Scheduled Payments job, Download Payments, also expects/assumes all the transactions it finds at the gateway were from Rock.  Starting with v11, that job now reports when it finds payment transactions at the gateway that have no corresponding transaction in Rock.  (Sorry we didn't make that clearer.)

So, since this is not really a bug, I'd recommend using a separate gateway for non-Rock originated transactions or you could consider opening a feature feature request on the [Ideas board](http://community.rockrms.com/ideas) to vote for a possible (?) Rock enhancement to try to somehow better distinguish its own transactions in a multi-system-use-gateway environment (if the job's new warning/summary is problematic for you).

Are you comfortable if we close this issue?

**Comment by nairdo** [comment]
@CdavisLMC  I heard from a back channel that your team has this all sorted out, so I'm going to close this issue out.  FYI.  It does look like a community Pull Request (from Daniel) is going to add a new setting-feature to that job to control whether or not it reports/logs the transactions that cannot be matched.
