### ISSUE TITLE
Group Finder does not respect campus context

### ISSUE THREAD

**Issue by emilykbcc** [SparkDevNetwork/Rock#4355]
### Description
We used this URL [https://www.churchbcc.org/GLgroups?CampusId=1](https://www.churchbcc.org/GLgroups?CampusId=1) and tested the Campus Context Setter drop down list block. Neither worked. Small groups for 4 different campuses kept showing up.

### Steps to Reproduce
1. Go to [https://www.churchbcc.org/GLgroups?CampusId=5](https://www.churchbcc.org/GLgroups?CampusId=5) and you will see Green Lake campus groups.
1. Or change the ID to 1 and after marking a Ballard campus small group as Public, it will start showing up.

**Expected behavior:**

It should only show Green Lake Campus groups when the context is Green Lake.

**Actual behavior:**

It shows all campus groups.

### Versions
* **Rock Version:** [10.2]
* **Client Culture Setting:** [Cloud hosted in Azure] ![<a href="https://user-images.githubusercontent.com/69941597/90698872-b7eb8b80-e236-11ea-8d26-7cf8eb7e89d0.png">https://user-images.githubusercontent.com/69941597/90698872-b7eb8b80-e236-11ea-8d26-7cf8eb7e89d0.png</a> image001]()

**Comment by nairdo** [comment]
@emilykbcc Have you checked the "**Enable Campus Context**" feature and enabled the "**Display Campus Filter**" in the Group Picker?
![image](https://user-images.githubusercontent.com/383807/91227151-e526b680-e6da-11ea-94a4-bba07b4b9589.png)

Once you do that, it should behave as expected (as seen in this video):
https://screencast-o-matic.com/watch/cYjTY9mygR

**Comment by nairdo** [comment]
@emilykbcc After some additional review, we're going to adjust this block so that campus filtering will occur when the "Enable Campus Context" is enabled (and a campus **is** in the context) when the "Display Campus Filter" is disabled.  If there is no campus in set in the context, then it will continue to show all campuses.  If the "Display Campus Filter" is enabled, it will honor the items chosen in the filter instead of the context (as it does today).
