### ISSUE TITLE
Outlook does not display event registrant names in confirmation email

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4363]
### Description
Registration confirmation emails viewed in Outlook hide the name of registrants because of known issue with Outlook and bullet points.

Here is what user sent. Note the grey box is grey because he has selected it to show that the text is actually there.  Prior to selecting it, this section appears white as if there is no text.

![](https://user-images.githubusercontent.com/4658177/90830628-d913b100-e2f6-11ea-89c2-46e19b30b422.jpg)

### Steps to Reproduce
1. Set up event. 
1. Register for the event.
1. Use Outlook (verson?) to view the confirmation email.
1. See error

**Expected behavior:**

The confirmation email should list the recipients in black text. 

**Actual behavior:**

The list of recipients is hidden / not displayed / displayed in white text (???) in Outlook.

**Suggested fix:**

Option 1.
Do not list recipients using bullet points.

Option 2
Add additional code to the HTML for the confirmation email to accommodate the problem.
Here are some links that I found along this subject (I didn't look too far):
[https://litmus.com/community/discussions/7556-bullet-points-in-outlook](https://litmus.com/community/discussions/7556-bullet-points-in-outlook)
[https://litmus.com/community/discussions/1093-bulletproof-lists-using-ul-and-li](https://litmus.com/community/discussions/1093-bulletproof-lists-using-ul-and-li)
[https://email.uplers.com/blog/bullet-list-outlook-hacks/](https://email.uplers.com/blog/bullet-list-outlook-hacks/)
[https://stackoverflow.com/questions/57142744/html-tags-ul-li-not-working-in-windows-outlook](https://stackoverflow.com/questions/57142744/html-tags-ul-li-not-working-in-windows-outlook)

### Versions
* **Rock Version:** Rock McKinley 10.2 (1.10.2.3)
* **Client Culture Setting:** en-NZ

**Comment by ElimAdmin** [comment]
Outlook version:
![confirmation-email-outlook-version](https://user-images.githubusercontent.com/4658177/90852940-acc75700-e32d-11ea-8d47-4dccb443f2ab.jpg)

**Comment by nairdo** [comment]
@ElimAdmin  Ken, Although we don't have access to that older version of Outlook, we've attempted to reproduce this with other versions but have been unable.    Are you still seeing this situation for your clients using Outlook 2007?

The markup used in the stock Registration Template Detail block is pretty straight forward with no styling...

![image](https://user-images.githubusercontent.com/383807/178564406-b2ece892-d2be-42ec-93e3-44cd7b1a8c9a.png)

You might want to look at your Global Attribute for the `EmailHeader` (which is included in the top line in that template).  There could be some default styling in there that is the cause of issues with Outlook 2007.

Since the markup in the stock Registration Template Detail block is relatively simple and customizable, I think we would recommend you might consider changing that or the `EmailHeader` to match the needs of your client base.  Does this sound like a reasonable move forward?

**Comment by ElimAdmin** [comment]
Hi Nick.
Thanks for the follow up.
Let me check.
Ken

**Comment by nairdo** [comment]
I'll mark this as closed, but please feel free to re-open if you feel this is still something that Rock core needs to resolve.
