### ISSUE TITLE
Group Maintenance Edit block (GroupDetailRight) not respecting Security roles

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#4369]
### Prerequisites
* [  X  ] Put an X between the brackets on this line if you have done all of the following:
    YES * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    YES * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    YES  * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

May be related to #3569 #4079 ??
And #3247 

### Description

Please let me know if this is intended behavior or if I've misunderstood how this should work.  Looks like there has already been discussion on this - refer #3247.
This is not a biggie given that there is an easy work around, and this detail will not change often, but seems inconsistent that a group attribute (like Small Group 'Topic') should need to be maintained by an Administrator, and the Administrator role seems   too powerful to give to someone just so they can maintain small group topics.

Group Maintenance does not display, nor allow edit of, Group Attribute Values, if user has RSR - Staff Worker security role, despite the block allowing this security role. 
![groupatt1](https://user-images.githubusercontent.com/4658177/90990336-8d127780-e555-11ea-96c2-d2567f3b4c17.jpg)

(Changing the block security to Allow RSR - Staff Worker Edit and Administrate does not change the behavior.)

As a result the Staff Worker cannot edit or maintain the Small Groups attributes - such as Topic.  

The Group Attributes are added and maintained under Admin Tools/General Settings/Groups/Small Group under Group Attributes.

### Steps to Reproduce

1. Confirm the user has RSR - Staff Worker role.  I tested with Daniel Peak (dpeak) in the demo site (changed password to dpeak1).
![groupatt2](https://user-images.githubusercontent.com/4658177/90990206-5851f080-e554-11ea-9ab5-f88e7a01203e.jpg)

2. On demo site go to Group Viewer/ Section A/Pete's Group and click Edit.  The Group Attribute section does not display in the GroupDetailRight block.  The Staff Worker cannot view or maintain the group attribute settings despite having the required security role.
![groupatt1](https://user-images.githubusercontent.com/4658177/90990224-833c4480-e554-11ea-88a1-7ba8dcd8d6a7.jpg)

3. Confirm the security settings on the Group Edit block allow RSR - Staff Worker to view.  (Same behaviour if the RSR - Staff Worker also has Edit and Administrate - Allow).
![groupatt3](https://user-images.githubusercontent.com/4658177/90990199-3fe1d600-e554-11ea-975e-35ef1f0e624a.jpg)

   Confirm the page has the same security settings.  (Not sure if this is relevant.)

4. Give the user Admin rights.  Now they can view and edit the Group Attributes.
![groupatt4](https://user-images.githubusercontent.com/4658177/90990511-09598a80-e557-11ea-86b3-3d0cc52f09e7.jpg)

**Expected behavior:**

The GroupDetailRight block on the GroupViewr/ small groups/ Edit page should respect the security settings on the block:  The RSR - Staff Worker should see and be able to edit the Group Attribute settings.

**Actual behavior:**

The RSR - Staff Worker cannot see and hence cannot maintain the Group Attributes, despite the RSR - Staff Worker being defined with 'Allow' security.

### Versions

The demo site.

Consistent on our version:
Rock Version: Rock McKinley 10.2 (1.10.2.3)

Client Culture Setting: en-NZ

**Comment by milescarmany** [comment]
Each Group Attribute also has its own security, which may be causing the behavior you are seeing. I'm certainly not a Rock security expert, but that has caught me before.

**Comment by OnlyByGrace** [comment]
Coming here because of the reference to #3247. I would confirm that the issue being described here is not a bug. In order for a person to view the attributes on a group, they need to have Administrate permissions on the Group Type or block, which is @ElimAdmin is describing.

**Comment by cwomack** [comment]
@ElimAdmin, I went back to **v10.2** just to make sure there wasn't a bug in that minor release.  This is **not** a bug, but it takes a few steps to get it working in the way you've described.  

The following steps should allow someone (like Daniel Peak) with the "RSR - Staff Workers" role to edit Group Value Attributes from the Group Viewer page:

1. Go to _Admin Tools > General Settings > Group Types > Small Group_ and expand the "Group Attributes" section. 
2. Click the lock icon to open up permissions on "Group Attributes"

![image](https://user-images.githubusercontent.com/67726635/127911660-148b5eda-b270-4e67-8473-e4c3824e4aaa.png)

3. Click on the "Edit" (not Administrate) tab to give your intended role/user the permission to edit the values of Group Attributes.

![image](https://user-images.githubusercontent.com/67726635/127911951-84a89a36-326b-4033-97ab-9c7dabfddefb.png)

4. Click "Done" on the security modal to save the changes. 


Note - These instructions are only going to allow **all** "RSR - Staff Workers" to edit "Small Groups" **Group Attribute Values**. If you only want to give a specific person rights to do this, you may want to consider giving that individual/user permissions rather than the entire role for an extra layer of security (if needed).

**Comment by knolly42** [comment]
I've had to give staff workers admin rights on the attributes they need to update in order for the 'group attributes' section to appear when editing a group
