### ISSUE TITLE
Person Documents Do Not Survive Merging

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4373]
### Description

When merging a person that has a Document (new v11-type of document under the Documents tab) it is possible to lose those documents during the merge.

### Steps to Reproduce

1. Create a duplicate person you plan on merging with an existing person
2. Add a new document to this new person under the Documents tab. If no Document Types have been added yet, you'll need to create one under Admin | General | Document Types.
3. Merge the new person (that has the document) with an existing person. Choose the existing (not new) family to merge into.
4. Observe that the resulting merged person no longer has the document under the Documents tab.

**Expected behavior:**

Documents would survive merging.

**Actual behavior:**

During merge, if you choose to put the person in the family where that existing person does NOT have the document(s), the documents are lost. If you choose the family of the person that DOES have the document(s), the documents survive the merge.

I was able to dupe this on prealpha as well as v11 and 11.1.

### Versions

* **Rock Version:** v11.0-prealpha

**Comment by cabal95** [comment]
Confirmed.

The data is not lost, the Document records are still in the database but have the old PersonId. Because that is the case, a SQL query could probably be devised and included in a migration - or sent ot people as needed - that finds those "orphaned" documents and updates them to link to the new person id.

The above could be done via the PersonAlias table which records the old person ids.

**Comment by ethan-sparkdevnetwork** [comment]
Included in the fix is to update orphaned person documents and update the EntityId.
