### ISSUE TITLE
Editing MetricCategory Entity Security Gives Permissions Error

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#4388]
### Description
When attempting to edit the security as a user in the Rock Administration security role on the Rock.Model.MetricCategory Entity under _Security_ > _Entity Administration_, I get the following error:
![Screen Shot 2020-09-03 at 11 35 18 AM](https://user-images.githubusercontent.com/66277785/92136277-d4142e80-edd9-11ea-8cd6-1e1bc5bea392.png)

### Steps to Reproduce
1. Go to the demo site and login as the Rock administrator (admin/admin)
1. Go to _Security_ > _Entity Administration_
1. Filter the Entity list by putting _metric_ into the "Entity Type or Name Contains" field ![image](https://user-images.githubusercontent.com/66277785/92136625-3b31e300-edda-11ea-83a9-2151a40d71d1.png)
1. Click the lock at the end of the row of the entity Rock.Model.MetricCategory
1. You get the following error: "_Error Unfortunately, you are not able to edit security because you do not belong to a role that has been configured to allow administration of this item._"

**Expected behavior:**

As a Rock administrator, I would expect that I would be allowed to edit the security on the MetricCategory entity.

**Actual behavior:**

Rock errors out that I do not have the appropriate permissions to edit the security on the MetricCategory entity.

### Versions
* **Rock Version:** Rock McKinley 11.0 (1.11.0.3)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@leahjennings Can you describe your intent in wanting to set security for all (the whole set) MetricCategory entities?

**Comment by leahjennings** [comment]
Sure @nairdo! We were enlisting the help of one of our other staff members to help create a bunch of metrics and categories for a volunteer tracking project we were doing, but that staff person is not a Rock administrator. We wanted to give that person edit/administrate rights on metric categories in the hopes that they would be able to add/edit categories as needed without having to be a Rock admin. That's when I ran across that error.

**Comment by nairdo** [comment]
Hi @leahjennings Leah, We reviewed this situation and I can now tell you that the Metric Category entity was not designed for setting the security in this way.  I know it's a bit confusing when a general purpose block (such as the Entity Administration) won't let you do something -- but in this case it's on purpose.  

However, we think this could make a good candidate for the Ideas board (http://community.rockrms.com/Ideas) if you're still interested in setting up custom metric category security.  If you are, please include that use-case you provided in the idea write-up since it helps provide the context around what you're wanting to achieve.
