### ISSUE TITLE
Connection Campaigns Not Honoring "Prefer Previous Connector" Setting

### ISSUE THREAD

**Issue by adamhann** [SparkDevNetwork/Rock#4434]
### Description
When setting up a Connection Campaign there is a setting to "Prefer Previous Connector" when a new connection request of that type is created through the Connection Campaign job. Currently this setting is not being honored or working. If you select that option to be "True" and you have Connection Campaign connection requests created (after a given amount of lapsed time from last connection request of that type) the new connection request is created without a Connector assigned. 

**This image shows the setting is turned on.**
![Campaign-Configuration-Rock-RMS](https://user-images.githubusercontent.com/23084345/94627550-e4f67980-028b-11eb-883f-1c1b80353345.png)

**This image shows two connection requests assigned to a user in Rock.**
![Screen Shot 2020-09-29 at 8 35 23 AM](https://user-images.githubusercontent.com/23084345/94627641-1ec78000-028c-11eb-9745-9a8a269d5ec4.png)

**This screen shows a connection request connected by the connector.**
![Screen Shot 2020-09-29 at 8 37 47 AM](https://user-images.githubusercontent.com/23084345/94627712-43235c80-028c-11eb-89f2-2424c6591dde.png)

**This screen shows the old connection requests, and the new connection requests for the same people after the Connection Campaign job ran again. As you can see the old Connectors were not assigned to the new connection requests.**
![Screen Shot 2020-09-29 at 8 39 12 AM](https://user-images.githubusercontent.com/23084345/94628637-7cf56280-028e-11eb-8ea5-0030306b1d76.png)

### Steps to Reproduce
1. Go through the steps to setup a Connection Type, Connection Opportunity, and Connection Campaign for the Connection Opportunity you made. 
1. As you are setting up the Connection Campaign select "Everyone In Data view" for Family Limits. Select "All At Once" for Create Connection Requests. Set a desired length of time. 
1. As you are setting up the Connection Campaign select "Prefer Previous Connector".
1. Run the Connection Campaign Job to create the new connection requests.
1. Assign a couple connection requests to a connector, then complete (Connect) those connection requests. 
1. Run the Connection Campaign job again. It should just create connection requests for the requests you just completed. (depending on the Number of days in between setting) Those requests will not have the previous connector assigned even though the option for them to be assigned is checked. 

**Expected behavior:**

I would expect that when someone is eligible for a new Connection Campaign request, and it is created, the new connection request would be assigned to the previous connector. 

**Actual behavior:**

When a new Connection Campaign requests is created, and the Requestor had a previous connection request of the same opportunity, the previous connector is not being assigned. 

### Versions
* **Rock Version:** [11.1]
* **Client Culture Setting:** [en-US]

**Comment by nairdo** [comment]
Hi Adam @adamhann We are making some corrections and clarifications to the  and Campaign Manager job and Campaign Configuration block so that if you use the "All At Once" option, the "Daily Limit of Assigned Connection Requests" will not be hidden.

However...

I also wanted to point out that if you configure a campaign as pictured in the first screenshot (All At Once) with the "Daily Limit of Assigned Connection Requests" set to 0/blank, then it will create all the requests but _not assign connectors_ to any of them (which essentially voids the "Prefer Previous Connector" setting.

**Comment by adamhann** [comment]
@nairdo Thanks for the response! That's helpful to know. We are loading our connections weekly so setting a daily threshold won't really work for us (unless we set some really high threshold). Either way, with what you are saying it sounds like it's working as designed except for the part where we can't select "Daily Limit of Assigned Connection Requests".

**Comment by nairdo** [comment]
> it sounds like it's working as designed except for the part where we can't select "Daily Limit of Assigned Connection Requests".

@adamhann Yeah, that's essentially true (except for two edge case bugs we're working on that we found when investing this).

> setting a daily threshold won't really work for us (unless we set some really high threshold).

Also, realize if you set a "really high" Daily Limit  -- it is _per connector_.  So that would mean one connector would get that many items assigned to themselves.

If you are really looking for a feature where the Campaign Manager can also perform auto-assignment on old, unassigned requests, that would be something I would ask you to post on the Ideas board at: http://community.rockrms.com/ideas

**Comment by notGerryMiller** [comment]
Hey Nick, 

What's the definition of "really high" 1k+?  Depending on the size of the organization that could mean anything.  

Also, we noticed that the connections are created four weeks after the last modified date of the connection request instead of four weeks after the connection activity.  This isn't a huge deal.  We had staff assign some of their contact to volunteers.  They updated old connection requests so the next one created would go right to the volunteer.  The assignment essentially reset the clock and made the second round of connection requests appear later than anticipated.  

Thanks!

**Comment by cabal95** [comment]
Really high is just whatever number is high to you.  I believe what @nairdo is saying is that if you set that "Daily Limit" to 50, then each connector (person) will get 50 connections assigned to them.  If you have 5 connectors, it will assign 50 to each for a total of 250.

**Comment by notGerryMiller** [comment]
Thanks @cabal95.

**Comment by nairdo** [comment]
Yes, and "really high" was just me quoting Adam's phrasing. The Campaign Manager job doesn't qualify or care how large the value is.

**Comment by notGerryMiller** [comment]
Awesome thanks.  I was afraid there was some kind of upper limit.
