### ISSUE TITLE
Group Scheduling: "Show Matching Preference" not honoring time/location preferences

### ISSUE THREAD

**Issue by MicahO** [SparkDevNetwork/Rock#4435]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

In the Group Scheduler block, the "Show Matching Preference" radio button appears to be broken in 11.1. It matches preference for dates, but will not match preferences for service times or location. Curiously, the auto-scheduler DOES work, but the group filter does not.

### Steps to Reproduce

1. Go to https://rock.rocksolidchurchdemo.com/Person/16/Groups and confirm Alisha Marble's serving preferences.
2. Go to https://rock.rocksolidchurchdemo.com/GroupScheduler/1220 and experiment with different combinations of dates, times, and rooms. Make sure to click "Show Matching Preference" and attempt auto-scheduling each one.

**Expected behavior:**

It's expected that "Show Matching Preference" will only show people whose preferences match the current serving schedule. 

**Actual behavior:**

On both our instance and the Rock Sandbox, "Show Matching Preference" filters correctly for date but ignores time and location.

### Versions

* **Rock Version:** [11.1]
* **Client Culture Setting:** [en-US]

**Comment by MicahO** [comment]
For some reason I kept getting errors while uploading the screenshots. Here they are for Step 1:
<img width="819" alt="Screen Shot 2020-09-29 at 11 19 22 PM" src="https://user-images.githubusercontent.com/44377420/94639989-76c1af00-02ab-11eb-9326-241e71da1702.png">

And Step 2:
<img width="780" alt="Screen Shot 2020-09-29 at 11 18 56 PM" src="https://user-images.githubusercontent.com/44377420/94639991-77f2dc00-02ab-11eb-96d3-a3f2ff52efcb.png">

**Comment by darringraham** [comment]
We are experiencing this same behavior and hope to deploy scheduling across multiple ministries soon. Is there a timeframe for this bug being addressed?

**Comment by cwomack** [comment]
@MicahO or @darringraham, does this issue still happen if the capacities are set on the "Group Meeting Location" when editing a group under the Meeting Details section?  If so, what version of Rock are you on (since this was reported back on v11.1)?

![image](https://user-images.githubusercontent.com/67726635/127042722-98510427-7444-496b-bcaf-88c22f91cb16.png)

**Comment by TheCoreyHall** [comment]
@cwomack I am with BEMA and am working with @darringraham on this issue. They are on 12.2 and I can confirm that the capacities are set on the location detail in the group in question. Here is an example screenshot of their scheduler not honoring the location filter:
![image](https://user-images.githubusercontent.com/38293092/127049546-59f170a8-b369-450c-94f9-8366eada8030.png)

**Comment by nairdo** [comment]
Hi @MicahO, Although this is a little older now and the UI has changed in later versions, we did some research on this to verify the original intention.  The current behavior is correct.  While the auto-scheduler will use the group member's location and schedule preference, the `List: Group Members (Matching Preference)` only accounts for the person's 'Current Schedule' setting (Every week, every other week, 1st and 3rd Week, etc.):

![image](https://user-images.githubusercontent.com/383807/144941129-99768127-7d4a-4556-951e-bde5ea437cf1.png)

Because it would be near impossible for the scheduler to be able to exclude people with anything other than the "Every Week" option, those people who don't match the currently selected week are not shown.   To aid the scheduler with filling schedule slots, the group member's location/schedule (if any) preference is shown in the draggable 'card' but it does not filter them out:

![image](https://user-images.githubusercontent.com/383807/144942282-0d8842be-c2fe-42b2-98a9-f5b58c822864.png)

So, if that is a feature you'd like to see implemented for the "List: Group Members (Matching Preference)" filter, I would ask you to open it up on the Ideas board at https://community.rockrms.com/Ideas.

Thanks!

**Comment by nairdo** [comment]
One last follow-up on this one...  A church has sponsored an adjustment in Rock v13.2 which adjusts those Group Members filter options.  It is now mentioned in the [Rock Your Groups manual](https://community.rockrms.com/documentation/bookcontent/7#groupscheduler), but is basically this:

* **Group Members - All**: Literally all group members.
* **Group Members - Matching Week**: Group members whose week to work is the selected week.
* **Group Members - Matching Assignment**: Group members whose week to work is the selected week AND whose assignment (location/schedule) matches the filters OR they have no assignment preference.
