### ISSUE TITLE
User able to submit blank event registration after refreshing Registration Review screen

### ISSUE THREAD

**Issue by jyarrowks** [SparkDevNetwork/Rock#4493]
### Description
For event registrations, when the setting "Allow Multiple Registrants" is turned off, refreshing the page on the "Review Registration" screen will lose registrant data, but allow registration and payment to go through. This causes there to be registrations that have registrars, but not registrants. The registrants for these erroneous registrations have blank values for required registration fields.

### Steps to Reproduce
1. Create an event registration
1. Set "Allow Multiple Registrants" to false
1. Fill out form and on "Review Registration" screen, refresh the browser window

**Expected behavior:**

Registration form would reset back to the first page of the form. If "Allow Multiple Registrants" is set to "True," the form resets when the user refreshes the page as expected.

**Actual behavior:**

The browser remains on the "Review Registration" screen, but all registrant data is lost, including any fee items (required or optional). The user is still able to submit the form and pay, but no registrant data is collected and potentially the incorrect amount is paid (if there were required fees).

### Versions
* **Rock Version:** 11.3
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Terms used:

- Registrar - The person filling out the form
- Registrant - The person attending the event

Observed the following behaviors when reproducing the issue:
- Refreshing the Review page will clear out the Registrant values entered earlier.
- The Registrar values remain in the current form since the browser retains them.
- The Registrant values are gone and no longer appear on the Review Registration page.
- The registration is allowed to be submitted.
- Viewing the data there is a Registrant, but it does not have values, e.g. First name and last name.
