### ISSUE TITLE
Delete Document only an option for admins

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4502]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

For the new documents feature in v11, by default only a person with the Security Role `RSR - Rock Administration` can delete a document that is uploaded to a Person's Profile. Giving Edit _and_ Administrate permissions to another Security Role on a Document Type _and/or_ File Type does not give them permission to delete. They have no issue editing/uploading, but cannot delete.

If you give Edit permissions to a Security Role (e.g. `RSR - Staff Workers`) on the Entity `Rock.Model.Document` (Admin Tools > Security > Entity Administration), now people in that role have the option to delete documents. This is not ideal however, as it also shows them the Security Lock on the Document. If that is clicked, an error is shown. I am not sure if there are other negative side-effects of doing this either.

I confirmed this behavior with others in the community: https://chat.rockrms.com/channel/security?msg=fRrX26oxoTPLmY9Wo

This is what it looks like for an Admin:
<img width="1586" alt="Screen Shot 2020-11-24 at 16 05 01" src="https://user-images.githubusercontent.com/23226974/100240109-2dcf5500-2f00-11eb-8625-046a99555630.png">

This is what it looks like for a person who has Edit and Administrate permissions on both the File Type and Document Type:
<img width="1592" alt="Screen Shot 2020-11-24 at 16 05 26" src="https://user-images.githubusercontent.com/23226974/100240177-40e22500-2f00-11eb-839e-a65fbd67408f.png">

### Steps to Reproduce

1. Create a new File Type - Give Edit permissions to a Security Role other than `RSR - Rock Administration`
2. Create a new Document Type - Give Edit permissions to the same role
3. Login as (or impersonate) a person on that Security Role and upload a document of that Document Type.
4. See that there is no option to delete the document.
5. Login as Admin and see that the option to delete now appears.

**Expected behavior:**

I would expect that giving Edit permissions to a Security Role on the Document Type (or possibly File Type) would allow the user to delete a document.

**Actual behavior:**

Unless giving Edit permissions on the Entity `Rock.Model.Document`, a user other than Admin cannot delete a document -- however doing this has at least 1 adverse side effect. 

### Versions

* **Rock Version:** [v11.3 (1.11.3.1)]
* **Client Culture Setting:** [en-US]

**Comment by smross** [comment]
Mike, thanks for submitting this bug report. We went round and around on this yesterday in chat, and I'm grateful for you collecting all of this info. There are a lot of moving pieces here.

## Summary

To be able to delete a document, a person (preferably through security role) needs the following additions made:
* *Edit* permissions for the Entity type *Document*. This is done through *Entity Administration* using the security modal for *Rock.Model.Document*
* *Edit* permissions for the *Document Type*. This is done through *Document Types* using the security modal for the appropriate Document Type
* *Edit* permissions for the *File Type*. This is done through *File Types* using the security modal for the appropriate File Type

**At this point I think that it actually works as needed when configured appropriately.** However, this may not be the way it is *supposed* to work.

### Side Note regarding document create permissions

To be able to create a document, a person (preferably through security role) needs the following additions made:
* *Edit* permissions for the *Document Type*. This is done through *Document Types* using the security modal for the appropriate Document Type
* *Edit* permissions for the *File Type*. This is done through *File Types* using the security modal for the appropriate File Type
*notice that they don't need entity type edit permissions*

## Background

Here's how the process of a working document delete option worked for me (on the demo server, which is v11.2):
1. Create a file type, in my case with *filesystem* as the storage provider, and *Requires View Security* un-selected
2. Leave the new file type's permissions at the default (*all users* can *view*, only *rock admins* can *edit* or *administrate*)
3. Create a document type, with the previously created file type as the associated file type. I used the entity type of *Person*, and selected the *Manually Selectable* property
4. Leave the new document type's permissions at the default (*all users* can *view*, only *rock admins* can *edit*, only *rock admins* can *administrate*)
    * At this point only *Rock Admins* can create documents of this type
    * At this point only *Rock Admins* can edit or delete documents of this type (even though on the security modal *Staff Workers* inherit the edit permission from "(Person)")
    * At this point *Staff Workers* **cannot** edit or delete documents of this type that they did not create
5. Change the Document Type's permissions, adding edit permissions for the role *Staff Worker*. We have not adjusted the *File Type* permissions, just the *Document Type*
6. Log in as a *Staff Worker* and navigate to the document. You can't edit or delete the document
7. Change the File Type's permissions, adding edit permissions for the role *Staff Worker*.
8. Log in as a *Staff Worker* and navigate to the document. You can't edit or delete the document
9. Undo the item permissions you added for the file type and document type
10. Change the permissions for the Entity *Rock.Model.Document* to include *Edit* item permissions for the role *Staff Worker* (Rock > Security > Entity Administration)
11. Log in as a *Staff Worker* and navigate to the document. You can't edit or delete the document
12. Change the Document Type's permissions, adding edit permissions for the role *Staff Worker*. We have not adjusted the *File Type* permissions, just the *Document Type*
13. Log in as a *Staff Worker* and navigate to the document. You can't edit or delete the document. You *can* start the creation process for a new document, but can't actually upload the file for the document type. You receive the error "Warning not authorized to upload this type of file"
14. Change the File Type's permissions, adding edit permissions for the role *Staff Worker*.
15. Log in as a *Staff Worker* and navigate to the documents tab. You **can** edit or delete documents created by others. You *can* create a new document, edit it, and delete it. The security button appears, and can be selected. Selecting the security button yields the security dialog, but with an error message in the dialog: "**Error** Unfortunately, you are not able to edit security because you do not belong to a role that has been configured to allow administration of this item."

I think there is a bug regarding the security button (probably a different bug report). It's *not* helpful that the security button appears when a person doesn't have security edit (administrate) permissions for a document, i.e. when they have edit permissions it appears but doesn't allow permissions changes

So, regarding the administrate permission and deletion of person entity documents:
- The entity *Administrate* permission is **not** required for delete access of a document
- The document type *Administrate* permission is **not** required for delete access of a document
- The file type *Administrate* permission is **not** required for delete access of a document

**Comment by ethan-sparkdevnetwork** [comment]
Changed the Document entity to point to the DocumentType as the parent authority.

**Comment by smross** [comment]
I'm grateful that there has been some work done on this.

However, I'm curious:
- Did anyone (besides what I did above) do any more confirmation work?
- It's not clear to me what the way it's _supposed_ to work is. I have been wondering _how_ to explain how file types, document type, entity types, and documents all fit together, but I'm not super confident.

Again, thanks for the fix so that the Document Entity points to the Document Type as it's parent. That's wonderful progress. I'm just not sure how to test or understand if there are any nuances/edge situations I still need to be thinking about when using these functions.
