### ISSUE TITLE
Transaction Entry block does not maintain Fluid layout setting when certain input values are changed. [12.0.9 alpha]

### ISSUE THREAD

**Issue by BEGamache** [SparkDevNetwork/Rock#4512]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

On the Give Now page, if the Transaction Entry block is set to the Fluid layout style and the Schedule Frequency or date is changed, or if an account is added I believe a postback occurs but ignores the block setting for the layout to be Fluid and reverts to the Vertical layout.

It's not a big deal, it's just not adhering to the block's settings.

### Steps to Reproduce

1. On the Give Now page, set the Transaction Entry block's layout to Fluid.
2. Refresh the page to make sure it starts off fresh.
3. Change either the Frequency, Date or add an account
4. The block will revert to the Vertical layout instead of maintaining the Fluid layout

**Expected behavior:**

Maintains Fluid layout on input changes.

**Actual behavior:**

Reverts to the Vertical layout.

### Versions

* **Rock Version:** 11.2 (demo site), 11.3, 12.0.9 Alpha
* **Client Culture Setting:** en-US

**Comment by taylorbrooks** [comment]
Bump, any movement on this. Had someone call in today.

**Comment by MichaelAllen** [comment]
For a quick fix, you can move [this line](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.12.3/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L1762) up to [here](https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.12.3/RockWeb/Blocks/Finance/TransactionEntry.ascx.cs#L775). That will cause the block to check the value of that option on every postback instead of just 1 time when the block loads. 

I'm not sure I completely understand why checking every time would necessary for that specific attribute, but not for any of the other attributes that were being read in the same method. But moving it does fix the issue on my test system, so... 🤷‍♂️
