### ISSUE TITLE
Editing Scheduled Transactions on the Recurrence Date leads to Orphaned Transactions due to GatewayScheduleId Mismatch (NMI)

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#4526]
Submitted on behalf of Flatirons Church

### Prerequisites

Could not reproduce on demo site, since it is not configured with an NMI gateway

### Description

If a user has a scheduled transaction configured and modifies it on the day a transaction is supposed to be processed, there's a potential for a payment to fail to import if the payment was processed using the old Gateway Schedule Id. For example, for one of our users, the following occurred:

9/27: User creates a scheduled transaction that occurs on the 15th of every month with schedule ID: xxx1234
10/15: First payment successfully imported.
11/15 5am: The Download Payments job is run. Past payments are pulled into Rock
11/15 Noon-ish: A new transaction with schedule ID xxx1234 is processed
11/15 10pm: User updates their scheduled transaction with an increase in giving. The schedule Id is updated from xxx1234 to xxx5678
11/16 5am: The Download Payments job is run. A transaction with schedule ID xxx1234 is pulled into Rock. Since there's no matching scheduled transactions, it isn't saved to Rock.

### Steps to Reproduce

1. Create a scheduled transaction
2. In between the time the gateway processes a payment and the time your Download Payments job runs, edit the scheduled transaction
3. Run the Download Payments job

**Expected behavior:**

The payment should be properly imported

**Actual behavior:**

The payment does not import

### Potential Solution

One solution is to create a table that stores old GatewayScheduleIds and the scheduled transaction they're tied to, and then check that table if there's not a match on current ScheduledTransaction.GatewayScheduleIds.

### Versions

* **Rock Version:** 11.2
* **Client Culture Setting:** EN-US

**Comment by darringraham** [comment]
We would like to allow people to edit their own gifts but at this point we cannot because of this bug. Is there a timeframe to get this fixed?

**Comment by JimMichael** [comment]
Is there any idea on when this bug might get some love? We're moving to NMI and it's somewhat concerning that we'll have this known issue right off the bat...

**Comment by rutledgek** [comment]
I was working on this issue with Northway Church where transactions were not downloaded before the change was made.  This caused transactions under the old Subscription Id to be orphaned without any relatively easy way to rectify the issue.  Is there any word on a fix for this issue raised in December?

**Comment by josephmccarty** [comment]
We are also experiencing this issue several times per month.  It logs the attached exception.
![image (1)](https://user-images.githubusercontent.com/13207386/133475750-9bff1f08-b772-48f3-b9a2-127ff3799c3a.png)

**Comment by JimMichael** [comment]
Can anyone tell me... when this situation DOES happen (where NMI has a recurring transaction Id that cannot be matched to an existing Rock GatewayScheduleId... and you CAN find the "same" recurring transaction for a user, but with a different GatewayScheduleId)... is the "fix" to update via SQL the existing Scheduled Transaction's GatewayScheduleId to the one that NMI has? Will that work to fix these?

**Comment by rutledgek** [comment]
It's amazing this hasnt been a higher priority.  If people change their schedule transaction which was added a few versions back, then the new gateway id gets associated with that schedule.  If it happens while transactions are still being processed, there is no process to find the previous value for that transaction so the transaction is just orphaned in NMI.  The only fix I have found is through SQL where I look up the old value in NMI's site, update the gateway id on the schedule, download payments, and then change it back(usually storing the current value in the foreign key field so it is easier to change it back.

**Comment by MikeDPeterson** [comment]
@JimMichael No, it would be a little more complicated than that. @rutledgek's solution would be a good way to do it.

**Comment by rutledgek** [comment]
Does make me wonder how many orphaned transactions are out there that won’t be on people’s year end statement when they are printed next month.  After all the level of work to match and the need for sql does elevate the problem above many finance admin’s/rock admin’s ability or comfort.

**Comment by JimMichael** [comment]
Interesting. In my case, there doesn't seem to BE an "old transaction" in NMI. In this (first) case I have, the user was doing a "transfer" from Payflow Pro to NMI, via Rock's transfer feature...  I can see the person created the new scheduled transaction in NMI and its GatewayScheduleId, but that Id does NOT exist at all in NMI. The recurring transaction that exists in NMI matches this person's name, amount, etc exactly... it's just a different Id, which can't import into Rock as there is no scheduled transaction with that number (but I KNOW which transaction it's SUPPOSED to be). And this is the first transaction (12/15) for this person on this new gateway.

Any advice for this situation?

**Comment by JimMichael** [comment]
Well, I may have made things worse, but in this specific instance it doesn't seem so. I updated the existing ScheduleId in Rock with the one NMI was saying it couldn't match, then did a Download Payments... and voila, the person now has that transaction from yesterday on their record. 

I think this worked because there WAS no prior transactions in NMI for this person... somehow the ScheduleId that got stored in Rock was different than the one NMI used to create the initial (first time ever for this person) recurring payment... my guess is she refreshed the browser or something when in the 3-step process when "transferring" her Payflow to NMI... somehow in that process Rock recorded the original Id, but NMI got a new one.

**Comment by nairdo** [comment]
@rutledgek What timing.  Although this should only be an edge case, we had already started working on this several months ago.  It was much more challenging than we first thought.  With each approach we wanted to take we ran into limitations.  So, in the end, we ended up having to create a new property (via [ea645ee](https://github.com/sparkdevnetwork/rock/commit/ea645eeb37dce65936a92d5fc0f3bdea87116a6b#diff-5755833385ceb9baa353e3d93587d6b6505a458381017d9ed877d845d67c9f8fR33))  on the FinancialScheduledTransaction called `PreviousGatewayScheduleIdsJson` to keep track of any/all "previous Ids" since some gateways generate a new Id when a change is made.  Because of that model change, we're in the unfortunate situation where the fix can't be provided in the v12.x build.

**Comment by JimMichael** [comment]
Just a note that there appears to be a similar -- but different -- edge case where a scheduleId in NMI cannot be found in Rock, but it is NOT due to someone changing an existing schedule, which is the one I ran into yesterday. 

In my example, the person used the "transfer" functionality on 12/9/2021 to move their recurring payment from Payflow to NMI. Her scheduled transaction list in Rock shows the payflow one being inactivated and the NMI one being created at nearly the exact same time, which is what you would expect from this process and hundreds of other people here have done already.

However, she set up the new NMI (on 12/9) to start on 12/15, and on 12/15 the download payments job could not find a ScheduleId in Rock that existed in NMI. I investigated and could not find ANY prior transactions for this person (which is expected, as she never used NMI until 12/9) yet NMI *did* have a new scheduled transaction for her... just one different thatn the one Rock had recorded for this scheduled payment. The audit log on her (new as of 12/9) Rock scheduled transaction for NMI also shows NO additional activity (like, an edit) after she created it initially. It was not touched at all after initial creation as far as the log indicates.

This means that something (a page reload, maybe? Or using back to go to a prior screen?) during her initial creation of the new scheduled transaction caused Rock to record ONE ScheduleId, and NMI to ultimately record another. I also think it could be related to the problem I identified here https://github.com/SparkDevNetwork/Rock/issues/4805 where just visiting the transaction entry block causes a NMI scheduleId to be handed out to Rock, yet that scheduleId never actually gets used.

I'm going to attempt to duplicate what I saw with this one user and if I can I'll open another issue for it.
