### ISSUE TITLE
Grade is wrongly reflected on Grade Transition Date

### ISSUE THREAD

**Issue by lauweijie** [SparkDevNetwork/Rock#4533]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Grades are off by one on the Grade Transition Date.

### Steps to Reproduce

1. Go to 'Global Attributes'
2. Update 'Grade Transition Date' to current date
3. Go to a profile with a grade that is set (try Alex Decker)
4. See that the grade has not transitioned

Another way to see this bug in action is to set Alex Decker's grade to 4th Grade (or any other grade). The graduation year is calculated correctly. However, after saving, it gets displayed as 3rd Grade.

**Expected behavior:**

Assuming current year is 2021, if graduation year is 2029, the expected grade is 5th.

**Actual behavior:**

Grade displayed is 4th.

### Versions

* **Rock Version:** Rock McKinley 11.2 (1.11.2.1)
* **Client Culture Setting:** en-US

**Comment by lauweijie** [comment]
https://github.com/SparkDevNetwork/Rock/blob/689e6a5f7e6fd7781e0963028242fe92f97e55e7/Rock/Utility/RockDateTime.cs#L298

This should be changed to either:

```
if ( graduationDateWithCurrentYear <= RockDateTime.Today )
```

or

```
if ( graduationDateWithCurrentYear < RockDateTime.Now )
```

**Comment by JimMichael** [comment]
Is this only an issue when transitioning dates early in the year (most orgs transition mid-year), or was it a bug introduced in 11.x?

**Comment by JimMichael** [comment]
I can dupe this as described (change transition date to TODAY and the grade doesn't change), but isn't this just due to the way Rock does the "transition" at the very END (11:59:59 or whatever) of the selected day? If you put the transition date to 1/3 instead of 1/4 (today's date as I write this), the grade changes as expected.

**Comment by nairdo** [comment]
@lauweijie Hi Jonathan. As per the docs (https://community.rockrms.com/documentation/bookcontent/5/195#grade), the Grade Transition Date "transition occurs at the end of the specified date".  

So, we can't actually pull in that PR since it would adjust the current behavior for all existing Rock systems/usage.

**Comment by lauweijie** [comment]
Hi @nairdo and @JimMichael, I think the issue should still be reopened since the JS logic for graduation date based on the grade dropdown is incorrect.

With the transition date set to today, selecting 12th grade should suggest a graduation year of 2023 rather than 2022.

**Comment by nairdo** [comment]
Thanks @lauweijie !
