### ISSUE TITLE
Workflow Trigger on Communication object not catching Status change

### ISSUE THREAD

**Issue by garethseeto** [SparkDevNetwork/Rock#4552]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
A workflow trigger for a communication object changing status to 3 (approved) doesn't seem to be triggering.
![communicationWorkflowTrigger](https://user-images.githubusercontent.com/77647927/104973265-06997f00-59a9-11eb-83c4-c260fe811af3.jpg)

### Steps to Reproduce

1. I created a standard workflow to send notification of an approved communication
2. I then set up a workflow trigger on Communication object, qualifier column of Status, Changing from anything to 3.
3. I then observed behavior whenever communication requests were approved.
4. Nothing was ever triggered. I tested using a different qualifier column (eg. ReviewedDateTime) and found the workflow was triggered using that qualifier.

**Expected behavior:**

That the Status qualifier would work and trigger the workflow whenever Communication status changed.

**Actual behavior:**
No trigger.

### Versions
Rock Version: Rock McKinley 11.3 (1.11.3.1)
Client Culture Setting: en-US

**Comment by shauncummings** [comment]
@garethseeto The Status field of Communications uses an enumerated value (of type Rock.Model.CommunicationStatus - see here:  https://github.com/SparkDevNetwork/Rock/blob/97567d24b17c61d809075c4afda1d89b6e41ecf1/Rock/Model/Communication.cs#L161).

The values for the field are defined in the enum, here:  https://github.com/SparkDevNetwork/Rock/blob/97567d24b17c61d809075c4afda1d89b6e41ecf1/Rock/Model/Communication.cs#L1056

This is a little confusing as it was not communicated to users and the only way to figure this out would be to examine the code above, so there's an update coming in v12.5 to allow you to create triggers on fields like this with the integer value you see in the database.  In the meantime, you can get your trigger to work by using the string value "Approved" instead of "3".
