### ISSUE TITLE
Lava Webhooks do not run as the authenticated user

### ISSUE THREAD

**Issue by andypullen** [SparkDevNetwork/Rock#4575]
### Description
Webhook endpoints created with the [Lava Webhooks](https://community.rockrms.com/lava/lava-api) feature don't execute lava as the currently logged in person.

### Steps to Reproduce
1. Go to General Settings > Defined Types > Lava Webhook
1. Create a new webhook naming it "current-person-test", ensuring that GET is enabled (either by leaving the HTTP verb dropdown blank or selecting it explicitly), and enter in `{{ CurrentPerson | ToJSON }}` as the code to execute
1. Open up a new tab navigating to the newly created webhook (`/Webhooks/Lava.ashx/current-person-test`)
1. The returned CurrentPerson object will be null

**Expected behavior:**
The CurrentPerson object should be defined from the currently logged in person.

**Actual behavior:**
It doesn't do that :stuck_out_tongue_winking_eye:

### Versions
* **Rock Version:** Rock McKinley 11.3 (1.11.3.1)
* **Client Culture Setting:** en-US

**Comment by cabal95** [comment]
Note: Regression started in Rock 11.0

Wow. Thanks @andypullen for reporting this. It used to work but looks like a commit last year to fix another bug had a side-effect to make this stop working (https://github.com/SparkDevNetwork/Rock/commit/20c798f7862fe42f1cf6e560dc8eac8b816a475c). I know that commit is needed and there is an easy way to fix the Lava Webhooks without breaking the previous fix - but I'll bring it up with the team to see if we can make sure that previous commit didn't cause related `CurrentPerson` issues in other places - though I suspect they would have been reported by now.

Dev Note: The mentioned commit makes is so that the `InstanceAssigns` that get set for `CurrentPerson` from `ResolveMergeFields( ..., currentPersonOverride, ...)` don't always get set. And the way Lava.ashx was setting current person was through this method. I probably should have set it inside the mergeFields as well. Oops.
