### ISSUE TITLE
Using Transfer to Reassign Connection Request Tosses Data

### ISSUE THREAD

**Issue by SteveSwaringen** [SparkDevNetwork/Rock#4660]
### Description
The recently added feature of using the Transfer button on a connection request for a simple change of Connector nulls the Placement Group assignment and can result in the loss of any placement-group-related attribute data.

### Steps to Reproduce
1. Create a connection type that uses placement groups that have group member attributes defined and has more than one connector available.
1. Create a connection request of this type. Assign a placement group and populate the fields of the group member attributes. Assign a connector and save the connection request.
1. Use the Transfer button to change the connector (leaving the connection opportunity unchanged).
1. Observe that the placement group has been unassigned and the attribute data is not visible.
1. At this point if you edit the connection request and reassign the same placement group, you'll probably get your data back. However, if you edit and re-save the connection request without first re-setting the placement group, the data appears to be lost.

**Expected behavior:**

If the connection opportunity is not changed by the "Transfer" dialog, the placement group should not be nulled. 

(It does make sense to null the placement group if Transfer is used to transfer to a new opportunity type--the original purpose--but not for the new purpose of changing the connector.)

**Actual behavior:**

Placement Group is nulled and group member attribute data is (potentially) lost if Placement Group is not immediately restored.

### Versions
* **Rock Version:** 11.2
* **Client Culture Setting:** en-us

**Comment by cwomack** [comment]
@SteveSwaringen Thanks for your issue submission, as there were some deeper layers to Connection Requests that we'll be improving that are tied to this.   Just some clarity on how the "Transfer" button works within Connections Requests [per the documentation](https://community.rockrms.com/documentation/bookcontent/39/218#placementgroupconfiguration), it's meant to transfer the request to a different _Connection Opportunity_ (e.g. from Greeter to Usher).  

Additionally, when a connection request is transferred to a **new** connection opportunity, the placement group information is cleared because they may not be compatible with the next connection opportunity.  The placement group **member attribute values** are temporarily retained (although they are hidden) and once a new placement group is selected, any old values will be cleared upon saving. The exception to this will be if said placement group's member attributes are the **exact same** attribute "Key" on both the initial opportunity AND the transferred-to opportunity. 

**First improvement** will be that we will fix this so that you cannot press save on a "Transfer" without making an actual change to a different opportunity. 

**Second Improvement** will be to fix a bug that this issue helped us see regarding group placement group member attribute values that were being prevented from being displayed.  

Thank you for helping us make Rock better and hopefully this explanation clarifies how to use the transfer button in Connection Opportunity Requests.

**Comment by camrun91** [comment]
@SteveSwaringen I agree I updated to 12.4 this morning and already have a question about this ability to transfer to re-assign.

**Comment by PastorMario** [comment]
> @SteveSwaringen I agree I updated to 12.4 this morning and already have a question about this ability to transfer to re-assign.

I completely agree. What provision is being made to TRANSFER to REASSIGN to another Connector, a feature that our Call Center uses daily.

**Comment by nairdo** [comment]
We are going to re-open and handle the original problem in a different manner.

**Comment by ethan-sparkdevnetwork** [comment]
Adjusted the logic in v13.0 to allow the transfer if the Opportunity **or** Connector has changed.

**Comment by PastorMario** [comment]
Awesome! Thank you so very much.

Reset, Because You Deserve A Fresh Start!
Pastor Mario Moxey 
Twitter @MarioMoxey <https://twitter.com/MarioMoxey>
Facebook: Pastor Mario Moxey <https://www.facebook.com/pastormariomoxey/>

**Comment by nairdo** [comment]
> What provision is being made to TRANSFER to REASSIGN to another Connector, a feature that our Call Center uses daily?

Although you will be able to use the "Transfer" button to change a Connector, I should have also mentioned in my last response that _it is still possible_ to transfer a connection request to another connector -- you just have to do it the original way -- by editing the request (with the Edit button) and changing the connector as shown here:

![image](https://user-images.githubusercontent.com/383807/129225875-c423e4c1-856a-4748-96c9-1a4107427078.png)

**Comment by PastorMario** [comment]
Thank you so much Nick!

RESET, Because You Deserve A Fresh Start
Pastor Mario Moxey 
Twitter: @MarioMoxey <https://twitter.com/MarioMoxey>     
Facebook: Pastor Mario Moxey <https://www.facebook.com/pastormariomoxey?ref=bookmarks>
