### ISSUE TITLE
Streak List Custom Grid Option

### ISSUE THREAD

**Issue by MargaretMailhiot** [SparkDevNetwork/Rock#4662]
### Description
On the steak list block, when trying to add a custom grid column, the following error appears: "Liquid syntax error: Object 'RockWeb.Blocks.Streaks.StreakList+EnrollmentViewModel' is invalid because it is neither a built-in type nor implements ILiquidizable"

### Steps to Reproduce
1. Go to 'Streak List Block'
1. Click on 'Custom Grid Option', 'Custom Column'
1. Add Lava Template: {{ Row.PersonAlias.Person.PrimaryCampus }}
1. Erro appears in column: "Liquid syntax error: Object 'RockWeb.Blocks.Streaks.StreakList+EnrollmentViewModel' is invalid because it is neither a built-in type nor implements ILiquidizable"

**Expected behavior:**

_[Campus for each row is expected to display]_

**Actual behavior:**

_[Error is displaying]_

### Versions
* **Rock Version:** [12.0]

**Comment by cwomack** [comment]
@MargaretMailhiot, just wanted to update you that the fix for the Streak List Custom Grid Option will be in v13... but the Lava used in step 3 above " **{{ Row.PersonAlias.Person.PrimaryCampus }}** " likley never worked and may have been a typo.

Did you mean  " **{{ Row.Person.PrimaryCampus }}** " by chance?

**Comment by MargaretMailhiot** [comment]
We have updated to v13. When trying to add this to the custom grid, I no longer get an error but the column is blank.
