### ISSUE TITLE
Enable Person Entry will not Create a New Person when Autofill Current Person is Selected

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#4704]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

I am not sure if this is intended behavior, but wanted to report it so you all can decide. 

When using _Enable Person Entry_ on a Workflow Form, and then selecting _Autofill Current Person_, the Current Person who is viewing the form will have their information populated automatically. However, if the Current Person changes ALL of the information that is autofilled into the form, it does not create a new person, but instead changes all of the Current Person's information. This makes sense, because if a person enters a new email, we want to capture that and update their profile. 

However, if the form is used as a sign up for something, and the Current Person changes all their information to sign up a friend or other family member, instead of a new person being created, the Current Person's profile is updated, overwriting all their actual information with the information of the person they entered. 

**Autofilled information:**
<img width="1680" alt="Screen Shot 2021-06-02 at 14 41 54" src="https://user-images.githubusercontent.com/23226974/120536709-66ba1c00-c3b2-11eb-8da5-c436dea78a43.png">

**Manually Changed information before submission:**
<img width="1680" alt="Screen Shot 2021-06-02 at 14 42 33" src="https://user-images.githubusercontent.com/23226974/120536711-6752b280-c3b2-11eb-9fe0-04ddcd30dcf4.png">

**See profile is updated with all the changed information:**
<img width="1679" alt="Screen Shot 2021-06-02 at 14 43 11" src="https://user-images.githubusercontent.com/23226974/120536714-67eb4900-c3b2-11eb-8758-cf85a1fec1c0.png">

### Steps to Reproduce

1. Create a Workflow with a Form, using _Enable Person Entry_ and _Autofill Current Person_
2. Put form on a page, and see that it is autofilled with the logged in person's information.
3. Change all the fields, and submit the form.
4. See that the person's profile is updated with all the changed information, instead of a new profile being created.

**Expected behavior:**

_One possible fix to this is if FirstName and LastName are changed, that a new person is created instead of just updating the current persons profile. I am not sure if there are other adverse effects that would come from this, or if there is a better way to do it._

**Actual behavior:**

_The Current Person's profile is overwritten with all the other person's information._

### Versions

* **Rock Version:** [v12.3, v13.0]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
And alternative I'd prefer is if the action grayed-out (making them un-editable) the First and Last name *if* Autofill is enabled, as this would then keep current behavior (no new person is created because it's "you") but at least the name couldn't be over-written... but either way I'm guessing this would likely be considered an enhancement request (Ideas page) and not a bug.

**Comment by mikedotmundy** [comment]
I like the idea of grayed-out fields. If it is an enhancement, I'll enter it on the ideas page.

**Comment by rutledgek** [comment]
Grayed out fields and an "I'm completing this for someone else button" would go a long way.

**Comment by JimMichael** [comment]
I don't disagree, but the solution to a form that you anticipate *could* be filled out on behalf of another person probably shouldn't have _Auto Fill_ enabled in the first place.

**Comment by rutledgek** [comment]
While I understand that philosophy, in my experience, most users can never be trusted to fill out a form correctly.  so Autofill is never a safe option if it is always going to update the current person's records.  Another option that would reduce the friction is to do a comparison score of the edits and update the person if it is above a certain score and create a new record if it is below.  As for now, I really don't use the new feature because if the person is known I want to fill in the info, but I don't want to update their record if they change most of the information.  

So I still build my forms manually, add actions to set fields to the current person values, and then after the form have the create/match.  This has the added benefit of if they change their email address a new record is created and can be reviewed to make sure it isn't a type etc.  I have a few data admins that like to review email changes.  Until I can be more certain that records won't be completely overwritten, especially without some alert that it happened for review by an admin, I can't really use this form feature because I don't want to give up the ease of autofill.

**Comment by markewampler** [comment]
As a follow up to what I am reading here and to make sure I understand the expected behaviour of this enhancement functionality.

If we turn the person entry form on, and we check autofill current person values. It will of course autofill all the values as they exist, but lets say that my daughter was going through a class at our church and I went to the page on the family computer and she deleted my name/email...etc and put in her stuff for the form it would override all my person information because it always assumed it is the logged in person no matter how badly the data matches?

If so this is a really cool feature, but that would cause so many "What the heck happened here" issues that we couldn't use it.  Even if the odds of it happening are 1 in a 100 it is hours spent tracking down what happened and fixing the values that we could just have put into making the workflow more complex by adding in additional workflow actions that set the values and then doing a person/match create action afterwards.

I feel like @rutledgek has more in line what I would assume would happen as that is how most things in rock function so we just assumed this would happen this way, and were surprised when it didn't thinking it was a bug.  Understand it may have a use case that is not ours just putting in our 2 cents as it were.

**Comment by JimMichael** [comment]
No. If you read the commit for the fix at the link above, it says _Updated Workflow Person Entry so that a new person will be created/matched if LastName or FirstName changes when Autofill Current Person is enabled_

So in your daughter example, if it auto-fills as you, and she changes the first or last name, it will create a new record.
