### ISSUE TITLE
[Beta 1.12.4.1] SendGrid Opne and Click Stats Not Reporting

### ISSUE THREAD

**Issue by jennifertroeger** [SparkDevNetwork/Rock#4709]
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Email communication sent using SendGrid transport isn't reporting back the 'Open' or click rates. "Delivered" is reporting back. I've verified in SendGrid that the communication is showing as Delivered, Opened, and Clicked.
![Screen Shot 2021-06-07 at 2 09 32 PM](https://user-images.githubusercontent.com/36419045/121068249-0a803f00-c79a-11eb-853f-77dda852c70f.png)
![Screen Shot 2021-06-07 at 2 11 05 PM](https://user-images.githubusercontent.com/36419045/121068394-3b607400-c79a-11eb-88b5-3d55d5569d9a.png)

### Steps to Reproduce

1. Send Communication Transport to SendGrid
2. Send New Communication to yourself with hyperlink to 3rd party site
3. Open email, click link
4. Verify in SendGrid that the communication was delivered, opened and clicked
5. Check Email Analytics/Activity for this communication in Rock, noting that it only shows delivered, not opened or clicked

**Expected behavior:**
I would expect the Email Analytics to show that the communication was delivered, opened and the link clicked.

**Actual behavior:**

Actual behavior is that only "Delivered" rates are coming through.

### Versions

* **Rock Version:** [1.12.4.1]
* **Client Culture Setting:** [en-US]

**Comment by JimMichael** [comment]
If you're testing 12.4 in a non-production environment, this is (likely) to be expected because (presumably) the webbook set up in SendGrid is pointing at your production Rock URL and not your sandbox/dev/test Rock URL, and the webbook is how that data gets back to Rock. 

That said, if you ARE using a sub-user in SendGrid for testing and its webbook IS pointing at your sandbox/dev/test instance of Rock and your 12.4 test instance is logging is as THAT sub-user, let me know and I'll try to dupe!

**Comment by jennifertroeger** [comment]
@JimMichael Thanks! I just changed the webhook and sent another test. This time it shows delivered and opened, but the click didn't come through. Thoughts on why that would be?
<img width="996" alt="Screen Shot 2021-06-07 at 8 51 27 PM" src="https://user-images.githubusercontent.com/36419045/121105459-269fd280-c7d2-11eb-9c75-c01c7ef2b11c.png">
<img width="1360" alt="Screen Shot 2021-06-07 at 8 51 49 PM" src="https://user-images.githubusercontent.com/36419045/121105478-33242b00-c7d2-11eb-8f94-4c8cc07cd4f5.png">

**Comment by JimMichael** [comment]
How long did you wait? Sendgrid does not send stats back via the webhook in real time (nor do they all come in together). I’ve seen it take 5min for data to make it back into Rock. 

Also, realize that when you changed the webhook, you broke it for production Rock, so be sure to put it back :-)

**Comment by jennifertroeger** [comment]
Okay, I didn't know that the stats don't all come in together. I'll figure out how to add the sub-user in SendGrid and try it that way. Yep, I did realize that I broke it for production, that's why I waited until a lag time in the evening and reversed it within minutes (which is possibly why the click rate didn't come through). I'll update you later today, when I figure out the sub-user mumbo-jumbo.

**Comment by jennifertroeger** [comment]
Well, I'm not having any luck in successfully setting up the Subuser account. I'm going to go ahead and assume I just didn't give it enough time to come through last night, and delete this ticket.

**Comment by JimMichael** [comment]
I think you're right... you just switched it back before the clicks came in. For what it's worth, I just tried it here and it worked fine on my 12.4beta instance.
![image](https://user-images.githubusercontent.com/3903408/121213785-2b9d6a00-c844-11eb-8a76-26e3a6e4f1bc.png)

Hit me up in RocketChat about subuser... it might be something simple. That's been a great tool for me to be able to fully test SendGrid in my alpha/beta instance by just swapping out the API key, since my subuser has its webhook permanently pointing at my test instance.

**Comment by jonedmiston** [comment]
@jennifertroeger @JimMichael thanks both for your diligence in testing!
