### ISSUE TITLE
Workflow Forms no longer respect the "no validation" button type

### ISSUE THREAD

**Issue by chrismcgrath** [SparkDevNetwork/Rock#4713]
### Description
Selecting the Primary (no validation) Button Type on a Workflow Form does not prevent the form from requiring a value in a required field. Noticed first in v12.2 but confirmed it's happening in 12.4 on rock.rocksolidchurchdemo.com.

I created this Test Button Validation workflow at https://rock.rocksolidchurchdemo.com/page/136?workflowTypeId=24 but if it's been deleted or you want to test on another install, here is the workflow, just remove .txt from the filename and import.
[Test Button Validation_202106101146.json.txt](https://github.com/SparkDevNetwork/Rock/files/6633730/Test.Button.Validation_202106101146.json.txt)

### Steps to Reproduce
1. Create a Workflow with an attribute and an entry form.
1. Make the attribute editable on the entry form.
1. Make two buttons on the form, a Submit button with Primary button type and a Cancel button with Primary (no validation) button type.
1. Run the workflow
1. Click the cancel button

**Expected behavior:**

The form should submit/cancel successfully.

**Actual behavior:**

The form says that the required field is required.

Interestingly, the validation displays differently when using the Submit button or the Cancel button.

Submit button:

![image](https://user-images.githubusercontent.com/18447084/121580955-f2efc300-c9f2-11eb-8db1-db30fb4c14ae.png)

Cancel button:

![image](https://user-images.githubusercontent.com/18447084/121580989-fbe09480-c9f2-11eb-9106-6f9c2f0d9a8b.png)

### Versions
* **Rock Version:** Rock McKinley 12.2 (1.12.2.2), Rock McKinley 12.4 (1.12.4.1)
* **Client Culture Setting:** en-US

**Comment by nairdo** [comment]
@chrismcgrath I was able to dig into this one and see what was going on.  It turns out the [core/stock "Cancel" button](https://prealpha.rocksolidchurchdemo.com/page/119?DefinedTypeId=44) is **special** and has extra stuff that happens behind the scenes -- namely that [it is specifically tuned to disable validation](https://github.com/SparkDevNetwork/Rock/blob/7461501a83f551942ba4fe8929e7f837c4be91d9/Rock/Model/WorkflowActionForm.cs#L571) when it is used in the workflow form.  I also reviewed this with the design team to conclude that this is not actually a bug, but I would understand if you decided you wanted to open a feature request over at http://community.rockrms.com/Ideas to perhaps enhance the stock HTML Buttons with a new attribute or something to control that feature.
