### ISSUE TITLE
Conditional Filter Icon Missing on Default Form

### ISSUE THREAD

**Issue by DTS-Mike** [SparkDevNetwork/Rock#4714]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)? 
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/24752345/121693472-cb4e3880-ca8e-11eb-8d31-d35d5f8126ae.png)

### Description

Conditional form fields work on additional forms but not the default form.  

### Steps to Reproduce

1. Go to Event Registrations and make/edit an event.
2. Click on Add new registration attribute
3. Click on Save.
4. See the filter icon is missing.

**Expected behavior:**

The documentation shows the conditional filter icon on event registrations but not able to make one in Rock.

**Actual behavior:**

Filter Icon is missing much like: https://github.com/SparkDevNetwork/Rock/issues/4353

Here is the image and link to the demo sever till it gets removed:
https://rock.rocksolidchurchdemo.com/page/403?RegistrationTemplateId=4
![image](https://user-images.githubusercontent.com/24752345/121695696-eae66080-ca90-11eb-9d42-99881cb8c3cf.png)

### Versions

* **Rock Version:** V1.12.3.1
* **Client Culture Setting:** [EN-US]

**Comment by nairdo** [comment]
@DTS-Mike We did some research and digging to get to the bottom of this.  It turns out there are a few things happening here.  First of all you'll need to have at least one previous field that is **_compatible_** with the filter-criteria before the filter icon-button will appear.  The other thing is, only certain fields are compatible with filtering. 

We're going to be updating [that section in the documentation](https://community.rockrms.com/documentation/bookcontent/29#conditionalregistrationfields) to make this clearer, but for now the compatible fields are essentially the following:  Only the _gender_ field for Person Fields, and for the other "Attribute" type fields, only those that use a control which is a simple textbox, list, checkbox, person picker, and/or most of the date pickers.

Can you confirm that once you add one of those types of fields, the icon/button shows up?  If you are able to confirm that, you or I can close this issue out.

**Comment by cwomack** [comment]
@DTS-Mike, I'll close out this issue given the updates to documentation and clarity @nairdo provided.  Should there still be concerns or questions, feel free to comment back and we can assess if this needs to be reopened.
