### ISSUE TITLE
Using Lava in Subject field for workflow Email Send Action for an SMTP Communication Transport throws exception

### ISSUE THREAD

**Issue by hbcpn** [SparkDevNetwork/Rock#4718]
#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.

### Description
The Email Send workflow action when paired with a SMTP based Communication Transport is not handling lava properly in the Subject field.

### Steps to Reproduce
1. Create a simple workflow with an Email Send action type
1. Add simple lava tag into the Subject field of said Email Send action such as {{ 'Global' | Attribute:'OrganizationName' }}
1. Ensure you are using an SMTP based Communication Transport
1. Fire workflow
1. Check Exception Detail for "The specified string is not in the form required for a subject."

Exception Type: System.ArgumentException
Source: System
Stack Trace: 
`   at System.Net.Mail.Message.set_Subject(String value)
 at Rock.Communication.Transport.SMTPComponent.GetMailMessageFromRockEmailMessage(RockEmailMessage rockEmailMessage) in C:\Source\Repos\Rock12\Rock\Communication\Transport\SMTPComponent.cs:line 178
 at Rock.Communication.Transport.SMTPComponent.SendEmail(RockEmailMessage rockEmailMessage) in C:\Source\Repos\Rock12\Rock\Communication\Transport\SMTPComponent.cs:line 127
 at Rock.Communication.EmailTransportComponent.Send(RockMessage rockMessage, Int32 mediumEntityTypeId, Dictionary2 mediumAttributes, List1& errorMessages) in C:\Source\Repos\Rock12\Rock\Communication\EmailTransportComponent.cs:line 82`

**Expected behavior:**

The Subject field of the Email Send action parses correctly for an SMTP Communication Transport type, sends the communication, completes the Action and WF.

**Actual behavior:**

An exception occurs and the email does not send, workflow will not complete even though the action itself gets marked complete.

### Versions
* **Rock Version:** [12.3]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
@hbcpn are you able to provide screenshots of the workflow's configuration and the SMTP setup page by chance?

**Comment by bmurphy-dev** [comment]
I'm not sure these will help much...but as soon as any lava is removed from the subject field everything works as expected.
![image](https://user-images.githubusercontent.com/73124289/121944095-41b59980-cd20-11eb-9c6c-d806c63b4d52.png)
![image](https://user-images.githubusercontent.com/73124289/121944109-4712e400-cd20-11eb-8c75-6e26c7f24f8e.png)

**Comment by cwomack** [comment]
@hbcpn thank you for providing the additional screenshots! I tried using the demo server (running v12.2) as well as my own local version of v12.3, but couldn't reproduce any problems with sending emails containing lava in the subject field.  

I've placed the "Not Yet Reproduced" tag on this issue to see if we can invite others to try their hand at it.

**Comment by JimMichael** [comment]
I was also unable to dupe this on 12.4, using the core SMTP transport. I even used `{{ 'Global' | Attribute:'OrganizationName' }}` like the example, and it sent fine with no exception. Is it possible your OrganizationName global attribute has some weird character that's tripping up the email send action? (assuming that's the one you actually got the error on).

![image](https://user-images.githubusercontent.com/3903408/122264686-6edb8680-ce9d-11eb-8ccb-226aede64e3f.png)

**Comment by nairdo** [comment]
@hbcpn / @bmurphy-dev I may have been able to reproduce _at least one way_ to see this error using Jim's suggested hint.  I added some newlines into the "Organization Name" Rock Solid Church (which is difficult to do without SQL) via this:

```Sql
UPDATE av 
SET av.[Value] = 'Rock
Solid
Church' 
FROM AttributeValue AS av
INNER JOIN [Attribute] a ON a.[Id] = av.[AttributeId]
WHERE a.[Key] = 'OrganizationName'
```

...and then I get that error I _think_ you are seeing:
![image](https://user-images.githubusercontent.com/383807/124335976-1c62c100-db51-11eb-9eb6-96d3865f501b.png)

Since carriage return / line feed characters are difficult to see, can you run this SQL and send us the resulting hex string it returns:

```Sql
SELECT [Value], CAST([Value] AS VARBINARY(MAX)) FROM [AttributeValue] av
INNER JOIN [Attribute] a ON a.[Id] = av.[AttributeId]
WHERE a.[Key] = 'OrganizationName'
```

(_you can also chop off the 0x prefix and paste it into this online converter: https://www.rapidtables.com/convert/number/hex-to-ascii.html_)

If we can confirm this is the issue you're running into, you can work around it and we can find the best code solution to avoid this from happening.

**Comment by bmurphy-dev** [comment]
Nick, this is may be the issue I ran into but I can't easily validate it. I used the Global Attribute OrganizationName and a custom WF attribute set with a SQL Run into a Text Type WF attr field which results in just one word. So one of these two in the Subject field was culprit. However I cannot find any carriage returns in either scenario.
Results from the SQL above:
`Value	Column 1
Cascade Hills Church	System.Byte[]`

**Comment by nairdo** [comment]
I'm sorry Ben, I should have encoded that binary value to a string so we could easily copy/paste it from Rock's SQL Command block.  Here is an updated `SELECT`:

```Sql
SELECT [Value], sys.fn_varbintohexstr( CAST([Value] AS VARBINARY(MAX))) FROM [AttributeValue] av
INNER JOIN [Attribute] a ON a.[Id] = av.[AttributeId]
WHERE a.[Key] = 'OrganizationName'
```

Can you run this one and paste the value of the string as a reply.  It looks something like `0x52006f0...`

**Comment by bmurphy-dev** [comment]
Ah, it's definitely the carriage returns! The OrgName is good, but I used your SQL select to check some of the WF attr values as well, those are the culprit. It's interesting because that last one doesn't have the returns issue, but it is a rare one as most do.

<html>
<body>


Value | Column 1
-- | --
Cascade Hills Church | 0x43006100730063006100640065002000480069006c006c0073002000430068007500720063006800


</body>
</html>


<html>
<body>


Value | Column 1
-- | --
Gift | 0x0a000a000a00200020002000200047006900660074000a00
Payment | 0x0a000a000a0020002000200020005000610079006d0065006e0074000a00
Gift | 0x4700690066007400


</body>
</html>

![image](https://user-images.githubusercontent.com/73124289/124627990-06eddf80-de4e-11eb-949f-a82d04c2f774.png)

Okay, so even if I'm using a SQL Update to populate a Text field, how would I avoid this formatting so that it can be used in a Subject field knowing that it doesn't display that way when put into another attr field?
Add  **| SanitizeSql** or **| UnescapeDataString** or  **| StripNewlines** when pulling it into the Subject field?

**Comment by nairdo** [comment]
@bmurphy-dev Yes, the `StripNewlines` Lava filter should work nicely.  We're also going to modify the mail subsystem in an upcoming release to strip them out _before_ underlying mail library has a chance to generate the error message.
