### ISSUE TITLE
Send Email With Events Workflow Action - Open/Click Events Still Affect Completed Workflows

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#4722]
### Description

When using the *Send Email With Events* workflow action, even if the workflow is **Completed**, events for opens and/or clicks coming in from the webhook still activate additional opened/clicked activities.

### Steps to Reproduce

Create a new Workflow with 2 activities:

1. In first activity, add 1 action: 
     - *Email Send With Events* with an *On Open* Activity that points to 2nd activity
     - Configure valid from address and Send To address you have access to.
     
2. In second activity (call it "email opened" or similar) add 2 actions: 
     - Action 1: Rename workflow to "Opened!" or some similar simple action.
     - Action 2: Complete Workflow

Now run these steps:
1. Run workflow

2. Open the email received at the Send To address

3. Open workflow details and confirm second activity was triggered/ran and the workflow is now completed.

4. Open the email again in the client (this should trigger another Opened event from the webhook)

5. Observe in the workflow activity log that there is now a second instance of the "email was opened" activity that is active, but no actions run because the workflow is complete.

6. Any subsequent opens of the original email will continue to activate addition "email was opened" activities in the workflow even though the workflow is complete

**Expected behavior:**

Once the workflow is completed, no open/clicked events sent from the webhook would affect the completed workflow.

**Actual behavior:**

Open/clicked events sent from the webhook seem to ignore the fact that a workflow is completed and just keep stuffing new activity instances into said workflow.

### Versions

* **Rock Version:** All

**Comment by nairdo** [comment]
@JimMichael  Thanks for letting us know.  We had some discussion about this one since it appears to have been like this since the beginning.  We're also looking at a similar situation in the WorkflowActivity's Activate call.  Before _something**_ activates a workflow _activity_, we think it should check that the workflow has not completed. 

** _This should really only effect those 'somethings' that are external to the workflow since a non-running/completed workflow can't really fire off its activities on its own._
