### ISSUE TITLE
Add shortcode support for Calendar Event Detail

### ISSUE THREAD

**Issue by bengoshow** [SparkDevNetwork/Rock#4724]
#### A Picture Is worth a Thousand Words
![rockadmin whitewatercrossing org!UNITO-UNDERSCORE!page!UNITO-UNDERSCORE!396!UNITO-UNDERSCORE!EventCalendarId=1 EventItemId=397](https://user-images.githubusercontent.com/1636930/122652381-92583880-d10c-11eb-9584-6b32efc21327.png)

![](https://user-images.githubusercontent.com/1636930/122652396-a439db80-d10c-11eb-8ea0-db5a763f5cfc.png)

### Description
Adding a Lava Shortcode in an Event Detail does not result in the shortcode being processed within the "Calendar Event Item Occurrence Lava" Block - the code is just displayed on the page.

There is no "Merge Content" checkbox within that Block's advanced settings.

### Versions
* **Rock Version:** [12.3]
* **Client Culture Setting:** [en-US]

**Comment by cwomack** [comment]
Hello @bengoshow and thanks for marking this as an enhancement rather than a bug.  The issue here is Lava can't be resolved in ALL areas of Rock where you can input text (i.e. the "Description" text box within this **CalendarEventItemOccurrence** block).  Most areas that allow for this will mention this in a tool tip or even include it in the field name (e.g. Group View Lava Template) that Lava can be used.  

However, here's two things you can do to build on this suggestion: 

1. If there's value in having this particular area be able to resolve Lava, please submit the idea as an enhancement at: https://community.rockrms.com/Ideas which will allow the community to vote on it!

2. While it may require a little extra configuration, there may be ways to leverage the RunLava filter (but note, this new filter does not exist until Rock v13).  Here's a link to the documentation if you want to learn more: 
https://community.rockrms.com/lava/filters/other-filters#runlava 


I'll close this issue out as there's no bug with Rock in this instance, but feel free to comment back if you have questions and thanks helping make Rock better.
