### ISSUE TITLE
hos to install it locally

### ISSUE THREAD

**Issue by theophilusjtt** [SparkDevNetwork/Rock#4742]
PLease I need guides to run this project using XAMP or Loccal install.

Thank you.

**Comment by bmurphy-dev** [comment]
@theophilusjtt this is not an issue to create. The best place to ask questions is at [https://community.rockrms.com](https://community.rockrms.com) and go to the [https://chat.rockrms.com/channel/hosting](https://chat.rockrms.com/channel/hosting)
With that being said, there is a ton of documentation: [https://community.rockrms.com/documentation/bookcontent/1/148](https://community.rockrms.com/documentation/bookcontent/1/148)

If you need a dev environment locally you can follow this guide: [https://community.rockrms.com/developer/book/19/55/content#appendixnewdeveloperenvironmentsetup](https://community.rockrms.com/developer/book/19/55/content#appendixnewdeveloperenvironmentsetup)
This will very likely get closed because it's not really an issue.

**Comment by jonedmiston** [comment]
Closing based on @bmurphy-dev helpful links and advice above.

**Comment by cwomack** [comment]
@theophilusjtt the resources that @bmurphy-dev provided are definitely the place to start to make sure you can install Rock locally.  I'll close this issue out as there is no bug tied to this. 

@bmurphy-dev Thank you for taking the time to reply to the issue and provide helpful resources to someone else!
