### ISSUE TITLE
Inactive group members with failed group requirements are shown as "warning"

### ISSUE THREAD

**Issue by mkinyon** [SparkDevNetwork/Rock#4750]
Submitted on behalf of [Parkview Church](https://www.parkviewchurch.com/)

### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Inactive group members that failed to meet the group requirements are flagged with a yellow warning icon instead of the red failed icon:
![image](https://user-images.githubusercontent.com/2349102/128081833-3f8c8e3e-4ddc-49e1-9c0f-184e06eac17b.png)

![image](https://user-images.githubusercontent.com/2349102/128082035-db2b95f8-00e2-4b39-a21c-edff99248674.png)

This issue only appears in v12.4+ and we believe the bug was introduced in this commit:
https://github.com/SparkDevNetwork/Rock/commit/c481f7ce9632c03a6f787f1ddb16abc77129c546

### Steps to Reproduce

1. Setup a group with a group requirement.
2. Add a group member that does not meet the requirement.  The group member should have a red triangle next to their name.
2. Mark the group member as inactive.  The group member should now have a yellow warning icon next to their name

**Expected behavior:**

Inactive group members that do not meet the requirements to get a red alert icon next to their name.

**Actual behavior:**

Inactive group members that do not meet the requirements are flagged with a yellow warning icon next to their name.

### Versions

* **Rock Version:** v12.4+
* **Client Culture Setting:** en-US

**Comment by shauncummings** [comment]
@nairdo Issue description/identification is inaccurate.  This is the behavior on v12.2 (from the current Rock RMS Demo site, with a requirement I created to flag anyone with the last name "Decker"):

![image](https://user-images.githubusercontent.com/46500397/128350531-937966da-1fec-4b33-adba-39e6252c3b89.png)

Both Ted and Cindy fail the requirement check, but Ted's failed requirement is ignored because he's inactive.

The identified commit introduced the red warning flag in v12.4.  Prior to that commit, all warnings were yellow ("text-warning" rather than "text-danger") and inactive group members that did not meet the requirements **were ignored** (intentionally, apparently).

The method to check for members with failed group requirements (in the Group service) [includes a flag to include inactive members](https://github.com/SparkDevNetwork/Rock/blob/c481f7ce9632c03a6f787f1ddb16abc77129c546/Rock/Model/GroupService.Partial.cs#L708), which defaults to false and the default value is being used.

As of v12.4 (via the identified commit), inactive group members are still being ignored for the failed requirement check but are now being included in the warning check, resulting in the behavior @mkinyon has identified.

![image](https://user-images.githubusercontent.com/46500397/128352181-b51507ec-e43c-4a02-8db9-501e2927b059.png)

The check for group members who do not meet the requirements is used in three additional places:

1. [The Send Group Requirements Notification Job](https://github.com/SparkDevNetwork/Rock/blob/c481f7ce9632c03a6f787f1ddb16abc77129c546/Rock/Jobs/SendGroupRequirementsNotification.cs#L96)
2. [The Attendance Service](https://github.com/SparkDevNetwork/Rock/blob/c481f7ce9632c03a6f787f1ddb16abc77129c546/Rock/Model/AttendanceService.Partial.cs#L940)
3. [The Group Scheduling Toolbox](https://github.com/SparkDevNetwork/Rock/blob/c481f7ce9632c03a6f787f1ddb16abc77129c546/RockWeb/Blocks/GroupScheduling/GroupScheduleToolbox.ascx.cs#L1798)

The first two of these also depend on the default value for the "includeInactive" flag, but the third (Group Scheduling Toolbox) explicitly passes "false" (for some unknown reason).

I believe the "expected behavior" described in the issue report is an improvement over the current behavior, so I have changed the "includeInactive" flag to "true" for Group Member List block (in [this commit](https://github.com/SparkDevNetwork/Rock/commit/32fa71f8e020c3b4c454716588d8c62bd65348f9)) and am marking this issue as fixed in v12.5, but a review of the behavior of the other places that call this method (particularly #1) would probably be a good idea.

**Comment by shauncummings** [comment]
Just for reference, this is the updated behavior with new change:
![image](https://user-images.githubusercontent.com/46500397/128356391-08c5b022-2360-4226-ba2d-a4282422fd85.png)

**Comment by nairdo** [comment]
Ethan is going to try to squeeze this last minute fix into the v12.5 alpha that is about to start today.  Thanks @shauncummings for the quick fix and thanks @mkinyon for helping to find/report this.
