### ISSUE TITLE
[v12.5 Alpha] Personal Links JS syntax error using Check-in on Windows Client

### ISSUE THREAD

**Issue by trydyingtolive** [SparkDevNetwork/Rock#4765]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/495787/129404251-bf8b2b1f-eb90-40b6-ab77-4a06ff21ae31.png)

### Description
https://github.com/SparkDevNetwork/Rock/blob/hotfix-1.12.5/RockWeb/Scripts/Rock/personalLinks.js#L110
`const found = _quickReturnItemArray.some(el => el.url.toLowerCase() === window.location.href.toLowerCase());`

Internet Explorer doesn't support arrow functions. Normally I wouldn't care; unfortunately, the Windows check-in client uses IE. 

### Steps to Reproduce
1. Use Rock 1.12.5 or greater
2. Use the Windows check-in client (or Internet Explorer)

**Expected behavior:**
No errors

**Actual behavior:**
You get a pop up of the error

### Versions

* **Rock Version:** 1.12.5 - develop
* **Client Culture Setting:** EN-US

**Comment by nairdo** [comment]
I just DM'd you, but for the sake of everyone else... We are looking into this because that Bookmark (aka personal links) stuff should only be on the RockRMS site, and it should not be getting bundled for use with everything else (such as the check-in site).  

Also, we have a new Windows Check-in wrapper app (which does not use IE) that we've been having the alpha and beta teams use in their production environment.  Our plan is to release that new wrapper app with v13.

**Comment by MikeDPeterson** [comment]
Thanks for find this @trydyingtolive!
