### ISSUE TITLE
Group Requirements are not updated after changing roles

### ISSUE THREAD

**Issue by tcavaletto** [SparkDevNetwork/Rock#4800]
Submitted on behalf of Mariners Church

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

If a group member is changed from a role that has a group requirement to one that doesn't, the previous group requirement won't go away, and the group member list will always show a warning triangle.
![image](https://user-images.githubusercontent.com/5482014/135110764-d158433e-c254-4d19-9da5-87775366a9e5.png)
![image](https://user-images.githubusercontent.com/5482014/135110854-26e7d297-e379-4ecf-ae26-c8e1198517d6.png)

### Steps to Reproduce

1. Add a group requirement of type 'Background Check Required' to the Serving Team's leader role
2. Add Ted Decker to a Serving Team with a role of Leader
3. Check Group Requirements ( Either by running the job or re-checking them in the Group Member Detail
4. See a Danger Triangle on the Group Member List as expected
5. Change Ted Decker to a Member role
6. Check Group Requirements ( Either by running the job or re-checking them in the Group Member Detail
7. Go back to the Group Member List

**Expected behavior:**

There should now be no warning or danger icon, since there are no requirements for the member role

**Actual behavior:**

A warning icon remains next to Ted Decker's name.

### Versions

Rock Version: Rock McKinley 12.5 (1.12.5.2)

Client Culture Setting: en-US

**Comment by tmcfall01** [comment]
Submitted on behalf of Bayside Church

**Description**
If a group member is changed from a role that has a group requirement to one that doesn't, the previous group requirement won't go away, and the group member list will always show a warning triangle.

**Steps to Reproduce**

1. Add a group requirement of type 'Background Check Required' to the Serving Team's leader role
2. Add user to a Serving Team with a role of Leader
3. Check Group Requirements ( Either by running the job or re-checking them in the Group Member Detail
4. See a Danger Triangle on the Group Member List as expected
5. Change user to a Member role
6. Check Group Requirements ( Either by running the job or re-checking them in the Group Member Detail
7. Go back to the Group Member List

**Expected behavior:**

There should now be no warning or danger icon, since there are no requirements for the member role

**Actual behavior:**

A warning icon remains next to the user's name.

**Versions**
Rock Version: Rock McKinley 12.4
