### ISSUE TITLE
Multiple Phone Numbers of Same Type

### ISSUE THREAD

**Issue by cfunkdev** [SparkDevNetwork/Rock#4822]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description

Since the early versions, Rock has had a business rule where a person can only have one phone number of each phone number type (mobile, home, work, etc) that was managed in Rock's UI. Which does make pretty good sense. However this is not enforced at the database/entity level, and data imports and possibly other processes can support the ability to enter multiple numbers of the same type.   

I realize having multiple numbers of the same type on a person's record is not ideal.  However, data integrity users do need to have the ability to easily clean up/edit these records instead of the current process of copying the correct number to their clipboard from the person profile page and then editing the record and updating the number.  What I would propose is an update to the edit person block that would display all numbers of each type and allow the user to edit and/or remove one of these numbers. Currently Rock will only show the top number of each type on the edit page.  I am only suggesting the ability to  view and edit these numbers, and not to enable the ability to add multiple of the same type through the UI.

### Steps to Reproduce

1. Create a new person
2. Enter both a home and mobile number 
3. Update the home number record to be a mobile number in the PhoneNumber table
4. Refresh the user's profile page, you will see 2 mobile numbers
5. Click the edit person button
6. Only one of the mobile numbers will display.

**Expected behavior:**

Based on the example above, both of the mobile phone numbers would be displayed in Edit Person block.

**Actual behavior:**

Only one of the mobile phone numbers are displayed in the Edit Person block.

### Versions

* **Rock Version:** 1.12.6.1
* **Client Culture Setting:** en-us

**Comment by nairdo** [comment]
Hi @cfunkdev Chris, we looked this over and had a discussion about it.  Our primary philosophy, in general, is: **prevent** the intake of 'bad' data on import, etc. -- and not try to deal with it on the back side.  (Otherwise that could be a never ending game that leads to additional cruft throughout the code base.)

Since it sound like you're are dealing with this data issue in your environment _(and of course I would suggest you try to track down the source of issue first)_, I might suggest you could create a custom block that lists the problem records and maybe provides some UI interface for allowing an administrator to remove them. 

If you can identify a spot in Rock core where this data problem is happening, we'd be open to correcting that issue. (Note: @cwomack's confirmation above was based on him manually running SQL to mess up the records.)  Let us know if you think this is happening in Rock core, otherwise we'll just close this issue in a week or so.
