### ISSUE TITLE
Giving Statement Salutation Excludes Inactive Names

### ISSUE THREAD

**Issue by azturner** [SparkDevNetwork/Rock#4865]
Submitted on behalf of Fairhaven Church and The Crossing Church.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
  * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
  * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
  * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

### Description
The Salutation on Giving Statement will incorrectly list the children's names on the giving statement for adults, when the adults are inactive and children are active in the family. If parent is marked inactive (i.e. no longer is attending church) but has giving for the year, and there is still an active child in the family, the salutation on the parent's giving statement will only include the active child names.

This is sample statement that is created for Decker family when Ted and Cindy are marked inactive, but Noah and Alex are still active.

![image](https://user-images.githubusercontent.com/548180/146981545-f3c44334-43ee-4de5-8500-558004f0baad.png)

### Steps to Reproduce
1. Go to Rock Demo
1. Navigate to Decker Family
1. Inactivate Ted & Cindy Decker
1. From Ted or Cindy's record, click the "Contributions" tab
1. Click the 2021 YTD statement

**Expected behavior:**

Salutation on statement should include Ted & Cindy's name

**Actual behavior:**

Salutation on statement includes Noah and Alex's name

### Versions
* **Rock Version:** 12.7
* **Client Culture Setting:** en-US

**Comment by bjacky** [comment]
We are seeing this same issue on Rock 12.4. We are also concerned that NickName is used on the statements now instead of FirstName as in years past. For example, Alex instead of Alexis is on the statement above. Since giving statements are used for filling taxes, we believe legal names should be used.

**Comment by adamhann** [comment]
I have the same thoughts/concerns on @bjacky comments above. One other thing that we found interesting, is we used {{ Salutation }} in the footer as a way to help keep statements together. To identify who they belong to if we messed up the order of statements. We are finding adult children who have been moved out of the household and are connected by known relationships that are showing up with the {{ Salutation }} lava. I'm assuming this is because they are an inactive member in that family even though they aren't visible in that family anymore??

**Comment by nairdo** [comment]
For those who did not see this discussion in RocketChat... We are working on this now and as soon as this is fixed, we're moving to alpha.  I suspect we will start alpha on Monday with a very compressed alpha and beta phase (~2-4 days each; there are only about [6 fixes in v12.8](https://github.com/SparkDevNetwork/Rock/issues?q=label%3A%22Fixed+in+v12.8%22+is%3Aclosed)) and then it will go to General Availability.
