### ISSUE TITLE
Registration Manual Discounts Are Overridden On The External Page

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#4922]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
Did you know you you can simply copy and paste an image below?  Please do that. It really helps us quickly understand the problem.
![Screen Shot 2022-02-10 at 3 25 52 PM](https://user-images.githubusercontent.com/87141140/153499891-e4235c1b-64b2-4836-8b44-562c210a8071.png)
![Screen Shot 2022-02-10 at 4 32 12 PM](https://user-images.githubusercontent.com/87141140/153500028-deb0ed32-3bf5-4f54-a896-5bed683cf971.png)

### Description
On a registration if you have a manual discount amount, The internal site will reflect the discount but when a person goes to make a payment the discount is not applied. This only happens when there is an auto applied discount that does not apply to the registration. 

### Steps to Reproduce

1. Go to the test summer camp registration on demo site.
2. Add an auto applied discount that has conditions like max and min registrants.
3. Register someone 
4. Go to the registration and click edit and add a manual discount 
5. At this point there should be an amount due on the registration and show a discount. 
6. Now go to the external page like you are making a payment. 
7. The discount will not be applied to the amount the person sees.

**Expected behavior:**
The expected behavior would be for a manual discount to not be overridden by an auto applied discount

**Actual behavior:**

The manual discount is set not applied to the amount.

### Versions

* **Rock Version:** [12.8,13.0]
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by RufenachtPW** [comment]
On the Registration Entry block cs, on line 5955, there is a check for existing discount codes. If there is existing code then  it returns false. If we add to this a check for existing discounts (|| RegistrationState.DiscountPercentage >0 || RegistrationState.DiscountAmount  >0 ) then we can return and not override manual discounts.

**Comment by IzabellaDTS** [comment]
Hello! I would like to request that this issue be reopened.

### Overview
It has come to my attention that changes made to a discount on a registration aren't being respected when externally viewed by the user.

Given the context of the original issue, I believe this to be the same bug. Please refer to description below.


### Description
Below is an individual whose registration is fully paid.

<img width="2377" height="590" alt="Image" src="https://github.com/user-attachments/assets/184cff1d-dbb3-461e-91df-52bccd7726d4" />

When we dive into the registration we can see that they have a manual discount amount applied:

<img width="2404" height="815" alt="Image" src="https://github.com/user-attachments/assets/924a43c4-8ea1-4656-95e5-1edced025b3c" />

When I view the audit log I can see that a Discount Code was automatically applied to the registration but was later removed and replaced with the above custom discount amount.

If this individual were to view their registration externally, this change is not reflected and instead the original Discount Code is applied:

<img width="1405" height="1176" alt="Image" src="https://github.com/user-attachments/assets/2937e6d5-eb80-4a01-b18f-582cd29f87d3" />



**Expected behavior:**

The expected behavior would be that discounts are auto-applied only at initial registration. Afterwards, the internal changes should be respected externally.

**Actual behavior:**

The actual behavior is that internal changes to registrations regarding discounts are not be respected externally.

### Versions
**Rock Version:** 17.6 (17.6.1)
**Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
@IzabellaDTS if you believe this is still an issue and have confirmed it on the pre-alpha site please open a new issue and we'll look at it. It's important though to confirm the logic on pre-alpha.
