### ISSUE TITLE
Protection Profile Level of "High" may reveal Giving Status on Person Bio

### ISSUE THREAD

**Issue by jamrphy-bwd** [SparkDevNetwork/Rock#4968]
### Prerequisites
* [X] Put an X between the brackets on this line if you have done all of the following:
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

The Person Bio shows the Protection Profile Level. The "High" level is determined by 

1. Active Scheduled Financial Transaction
2. Saved Payment Account
3. In a Security Role Marked w/ High Elevated Security

If it can be reasonably certain to staff/volunteers that the Person is not in any security roles (i.e. not in any serving team, no attendance data, the record is new, etc.) then the presence of the Protection Profile "High" level reveals that a person is giving.

Some churches may not want to expose who is or is not giving except to certain levels of staff.

### Steps to Reproduce

1. Create a new Person
2. Schedule a transaction for the Person
3. Run the "Process Elevated Security" Job

**Expected behavior:** 

Protection Profile Level is hidden except for Data Integrity or Rock Administration. 

**Actual behavior:** 

Protection Profile is shown always to anyone with access to the page. Since I can see that Mr. Testy McTesterson is a new user and has a high protection profile, I can be pretty sure that he is giving.

![image](https://user-images.githubusercontent.com/44368014/161816434-0f831ee7-9c70-4db5-973e-40a56f243a25.png)

I'd like to also mention that we have had some staff members express concern that "Protection Profile: High" and "Protection Profile: Extreme" look like they might indicate something more serious regarding that Person, i.e. "maybe this person shouldn't be around kids". 

Since the bulk of staff and volunteers should not be impacted by the Protection Profile features, it seems better that they shouldn't see it at all.

### Versions

* **Rock Version:** 13.2
* **Client Culture Setting:** en-US

**Comment by jonedmiston** [comment]
Can you please open this as an Idea (https://community.rockrms.com/Ideas) since it is not a bug. 

Couple of other things to consider:

* Any staff person who can update a individual's email or mobile phone number should be aware of the enhanced security profile as these data points could allow a person to gain access to the individuals login through a password reset.
* The largest security risk for any software is the social hack of getting a staff person to subvert data.
* A 'High Profile' could also mean that a person has registered for an event and saved their payment information.
* We discussed this feature in detail in Episode 125 of the RockCast Podcast. We recommend anyone interested in this topic check it out. https://community.rockrms.com/connect/podcast-episode-125-security
