### ISSUE TITLE
Group Scheduler not honoring roles.

### ISSUE THREAD

**Issue by KarenRossi84** [SparkDevNetwork/Rock#4981]
### Description

When scheduling a person with multiple roles in one group, the role will change when scheduled to the highest role that the person has. 

![Group Scheduler issue 1](https://user-images.githubusercontent.com/104036471/164310943-94cbf319-bcf4-481e-8cb3-96edb19213e0.png)

![Group Scheduler issue 1 5](https://user-images.githubusercontent.com/104036471/164311122-fbe637ce-3ada-47d4-9971-2e8f7111ae08.png)

![Group Scheduler issue 2](https://user-images.githubusercontent.com/104036471/164311246-42f0c2e6-584e-4860-892e-305b402c3ccb.png)

### Steps to Reproduce

1. Assign a person multiple roles in one group. (for example: coach and member)
2. Search for that person, both roles will show on the cards on the left.
3. Move the card that has the role lowest in the group list to the schedule.
4. Observe all of the person's cards on left and the card on the schedule have changed to have matching roles.

**Expected behavior:**

The person can be scheduled by the role chosen.

**Actual behavior:**

The person's role will automatically change when scheduled to the highest option in the list that they have if there are multiple options.

### Versions

* **Rock Version:** [12.4-13.2]

**Comment by nairdo** [comment]
Hi Karen (@KarenRossi84 ), Thanks for letting us know about this.  The concept of trying to the Group Scheduling tool for a group with a person in the group multiple times with different roles came up during design of the group scheduler.  We decided it would be best to avoid multiple downstream complications by keeping things simple:  A person can only be scheduled for one group, location, schedule (and particular date). 

For situations where you needed to schedule a certain position with a person _with a special role_ ("leader", "director", etc.) we suggested it would be best if a related location-position was used instead (see https://github.com/SparkDevNetwork/Rock/issues/3108#issuecomment-404206896)

For example, you might set up a "A/V Booth Director" chair (location) as the position that requires you to schedule someone in leader. (See screenshot.)
![image](https://user-images.githubusercontent.com/383807/166289524-87b27cde-1b5c-45c0-aa0f-a9287858c72a.png)


This concept also plays well with setting up the Capacities for that location (see second screenshot).  In this situation, we only want 1 single director at the A/V Booth Director chair, so now we can set up proper capacity for that location-role.
![image](https://user-images.githubusercontent.com/383807/166289591-022854f7-b4c0-4b71-be64-5a2f5effbe9c.png)

Finally, for this issue we will be adding a special warning indicator when a group (whose GroupType has scheduling enabled) has the same person with multiple roles. (Something similar to the third screenshot).
![image](https://user-images.githubusercontent.com/383807/166289630-cb1f6744-04a5-4ce4-81da-2f882c083ee6.png)

**Comment by JimMichael** [comment]
If this is in fact the intended design, shouldn't Group Scheduler be fixed to not even SHOW a person's role in the group? Right now it implies that it should work.

**Comment by nairdo** [comment]
Hi @JimMichael, The original intention of showing the roles was so that the scheduling administrator would know who their leaders (or any role) were when they were scheduling.  There are some situations where you just want to know what other leaders (etc.) will be available at a location when you've scheduled them.

**Comment by KarenRossi84** [comment]
@nairdo I appreciate the response. I do want to clarify, we are in fact talking about only scheduling them in one role at any given time and we were hoping to have the roles show due to the exact reason you replied to Jim with. 

At the present moment we have groups broken by role but we are only scheduling a small portion of the options as a test batch and our volunteers are having a very hard time seeing who is serving in what capacity in each room. Utilizing roles would solve this for us however, some of our folks serve in multiple options depending on the given week. We would love to be able to schedule them and have the role we chose be the one displayed on the scheduler. 

I do see the benefit in locations but in our kids ministry we have 5 different roles serving across 6 different rooms. It would be too much to completely separate it out each with their own location and make it even more challenging than it already is for the teams leading in each space.

**Comment by nairdo** [comment]
> I do want to clarify...

Hi again Karen (@KarenRossi84), we did fully understand what you were describing.  I was just trying to point out that we definitely considered that back when the feature was being designed.  Once we started looking deeper at that idea (the same idea you are describing), we realized it opened up many different cans of worms in the system -- and that's why we decided we would not go down that path.

Although we're closing this issue, we do have two related changes that are coming later today.  One was described above where the Group Member list will show you the warning for 'duplicated' people (but differing roles) in a group and the other is that the group scheduling "card" will show you all the roles** of the person in that group (instead of showing only one semi-randomly as it is today). 
![image](https://user-images.githubusercontent.com/383807/166566835-6f4327c3-4ace-4d14-ac24-d9c1573af8ad.png)


** _To be clear, the existing **`Attendance`** model/table where the "scheduling" data is stored does not support anything else about the person other than their identifier (no group member or role data is in there)._
