### ISSUE TITLE
Issue upgrading to 13.4 beta

### ISSUE THREAD

**Issue by austinspooner** [SparkDevNetwork/Rock#5035]
#### A Picture Is worth a Thousand Words
<img width="2543" alt="2022-06-02_11-36-33" src="https://user-images.githubusercontent.com/657005/171680250-45a056c0-73ce-4191-b163-04939bfbf4e5.png">

### Description

Migrations fail when upgrading to 13.4 beta

### Steps to Reproduce

1. Update Rock in this environment to 13.4 beta
2. Fails with screen above

**Expected behavior:**

Complete fine

**Actual behavior:**

Fails

### Versions

* **Rock Version:** v13.3 to v.13.4
* **Client Culture Setting:** EN-US

**Comment by nairdo** [comment]
The problem was there were two migrations that were trying to both perform the same change. Thankfully we were able to just remove the [faulty one](https://github.com/SparkDevNetwork/Rock/blob/563cf6febb94024bf7441c784a025d3c4f4919ee/Rock.Migrations/Migrations/Version%2013.0/Version%201.13.4/202205091654423_RemoveContentChannelViewDetail.cs#L32) and leave the [correct one](https://github.com/SparkDevNetwork/Rock/blob/563cf6febb94024bf7441c784a025d3c4f4919ee/Rock.Migrations/Migrations/Version%2013.0/Version%201.13.3/202204122327349_Rollup_20220412.cs#L48) in place.

After correcting that issue, we repackaged the v13.4 update (and I just verified that).
