### ISSUE TITLE
Job Pulse - Exceptions

### ISSUE THREAD

**Issue by radams22** [SparkDevNetwork/Rock#5056]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

**Description**

The Job Pulse system job is failing almost the entire time that the Family Analytics job is running. When error notification emails are turned on in the Job Pulse job we receive multiple emails every week during the time the Family Analytics job is running. The Job Pulse job status indicates that it's failing, and an exception is thrown every time the job runs and fails.

It's not clear that this is causing other problems (the Process Workflows job seems to continue to run), but there have been other exceptions at the same time with logged-in people and Registrations and Connections.

Job Pulse failures correlate with the Family Analytics job -- changing the time the Family Analytics job runs changes the time that the Job Pulse job fails.

Our Family Analytics job usually takes about 10 minutes to complete, but sometimes it takes ~45 minutes. When it takes longer we receive more emails, sometimes as many as one per minute for most of that time.

The list of exceptions for one "occurrence" is in screenshot 1, and the expanded stack traces are in screenshot 2.

**Steps to Reproduce**

1. On our instance, set the Job Pulse job to send notification emails on errors.
2. Run the Family Analytics job.
3. Receive a lot of emails.

**Expected behavior:**

The Job Pulse job wouldn't fail when the Family Analytics job is running.

**Actual behavior:**

The Job Pulse job fails almost every minute while the Family Analytics job is running, throws an exception when it fails, and sends an email if configured to send an error email.

### Versions

* **Rock Version:** [v13.3, but this has been happening at least since v13.0, and possibly before that]
* **Client Culture Setting:** [en-US]
![image](https://user-images.githubusercontent.com/72230330/176714099-3af568de-7d38-45eb-9e14-6221c974c76e.png)
![image](https://user-images.githubusercontent.com/72230330/176714188-d3766155-3823-4f18-a536-f8ee70c47abd.png)

**Comment by JimMichael** [comment]
This is just an opinion from a non-developer type, but this sure *seems* like a underpowered webserver and/or SQL server scenario. The Job Pulse does nothing more than try to visit a "keepalive url" at your site, which is what keeps Rock "alive" and prevents it from "falling asleep" from lack of traffic, so to speak.

You can see in the exception that your job pulse is timing out, meaning your webserver is taking *too long* to respond, presumably because the Family Analytics job is using so many resources that Rock literally can't do anything else during that time. (again, just conjecture on my part based on what I see)

Are you running on a particularly small Azure/SQL instance, or some similarly under-powered host? For what it's worth, we've never seen that exception here.

**Comment by nairdo** [comment]
We recently (April) made significant optimizations to the `Job Pulse` job back in April (starting in Rock version 1.14.0.9) which will be seen in the upcoming v14 release.  We've been running this for several months now on the Rock/Spark site -- so I'm going to mark this one as being corrected by that change (https://github.com/sparkdevnetwork/rock/commit/5da3701f104b6aceb41b5b19c546510d7df02e09).  

(In actuality it is a loop inside the Global.asax that does the "Keep Alive" and you might think the Job Pulse seemingly does not do too much, but it does quite a bit more and was formerly making 100s of DB calls each minute.  That has been significantly improved, and a new setting under System Configuration will allow you to control that Keep Alive loop if you can't permanently configure your IIs to automatically keep your Rock instance alive -- something we recommend you definitely do)
![image](https://user-images.githubusercontent.com/383807/176941639-20e66968-b0d8-4a30-8a51-11513ba4f814.png)

Jim could definitely be on to something regarding the amount of horsepower available to your Rock server since the Family Analytics job is quite intense.  We are also going to look at the Family Analytics job to see if there are obvious performance adjustments we can make there as well.

Once you're on Rock v14, if you are still seeing issues with the Family Analytics job, you can open a new issue with more details about your environment (server size, # records involved, etc.).
