### ISSUE TITLE
Data View In Group(s) (Advanced) checkbox left margin

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5066]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
    * Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words
![image](https://user-images.githubusercontent.com/54962439/177809771-bebb21d3-ff68-4a3a-8f43-8a10acb6bf47.png)

### Description

Include Selected Group(s), Include All Descendants(s), Include Inactive Groups are indented which visually implies they are related in some way to the Include Child Group(s) checkbox when using the In Group(s) advanced Person filter in a dataview.

### Steps to Reproduce

1. Create or open an existing dataview in an Edge Browser (I have not specifically tested this in other browsers)
2. Add a In Group(s) advanced Person filter
3. See style issue

**Expected behavior:**

All checkboxes for this filter would have identical left alignment

**Actual behavior:**

Some of the checkboxes are indented

### Versions

Rock Version: Rock McKinley 12.7 (1.12.7.2)

Client Culture Setting: en-US

**Comment by leahjennings** [comment]
@dataCollegechurch have you seen any behavior with that filter that indicates the indented checkboxes _aren't_ actually related to `Include Child Group(s)`?

By default, the filter will just look at whatever groups you select in the dropdown. The indented checkboxes don't seem to be necessary if you just have the groups you want selected. Maybe I'm misunderstanding your use case, but I believe the checkboxes are indented because they _do_ relate to `Include Child Group(s)`. 

Can you help me verify what I'm thinking with your thought process?
