### ISSUE TITLE
[Alpha 1.14.0.7] Using a Modal On Obsidian Registration Breaks The Forms

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5147]
### Description

This issue seems similar to https://github.com/SparkDevNetwork/Rock/issues/5143 but since ours is not throwing an exception and looks a bit different, I thought I should open a new issue for it.

We have many registrations where we pop up a modal on a form (for example, to provide a statement the registrant must agree to, etc). We do this by adding our modal HTML to the Pre-HTML of a single select attribute that they select yes/no on.

This has always worked fine in the normal block but completely breaks the Obsidian Registration block.

### Steps to Reproduce

1. In a Registration template add a single select registrant attribute and then add modal code to the Pre-HTML of that attribute. Our code looks like
```<a class="btn btn-lg btn-default" data-toggle="modal" href='#modal-id'>Outreach Agreement</a>
    <div class="modal fade" id="modal-id">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Outreach Participation Agreement and Liability Waiver </h4>
                </div>
                <div class="modal-body">
```
(no closing tags for brevity)

2. Access the registration via the public site and attempt to register.

**Expected behavior:**

On the NON Obsidian block, this is what we see:
![image](https://user-images.githubusercontent.com/3903408/186778384-88a662eb-a207-4e63-979f-455826d2a876.png)

And clicking the OUTREACH AGREEMENT button pops up the modal as expected

![image](https://user-images.githubusercontent.com/3903408/186778485-fe0d22d3-fd31-46d3-8b78-301b2669accb.png)

**Actual behavior:**

Via the same registration using the Obsidian block, we instead see:

![image](https://user-images.githubusercontent.com/3903408/186778614-ad893502-4f57-491a-b85c-0ec3f472286b.png)

This occurs on whatever form the modal code is on. If it's the first form, then the above is show immediately after clicking NEXT on the "how many people are you registering" page and you can't progress through the remaining registration at all. But if it's the third form, for example, then the first two forms are displayed fine and only the third (and after) breaks.

### Versions

* **Rock Version:** v14 alpha

**Comment by abpena1979** [comment]
Hi @JimMichael 

We reviewed this item and as you indicated, this is similar to Issue #5143.  Obsidian blocks need to be able to control the DOM, therefore this type of functionality (pop-up modal initiated from the Obsidian block), will not be feasible.  I'm going to re-title this issue and close it since this will not be supported, but you can open a feature request on the Ideas board (http://community.rockrms.com/Ideas/) board to request an alternate mechanism be built into Obsidian blocks for this purpose. I'm sorry about that!

Thanks again for helping us test the new Obsidian blocks in your environment. We really appreciate your partnership.
