### ISSUE TITLE
Age with no BirthYear is 2021

### ISSUE THREAD

**Issue by brigettestephens** [SparkDevNetwork/Rock#5160]
### Description
![image](https://user-images.githubusercontent.com/112983647/188732323-b5fa1bfa-17f3-4ba7-8f26-72065547f621.png)

### Steps to Reproduce
none given

**Expected behavior:**

The age shouldn't show at all if no birth year.

**Actual behavior:**

Rock is treating no birth year as 0000

### Versions
* **Rock Version:** [Enter Rock version here] 13.2
* **Client Culture Setting:** [Enter Client Culture here]

**Comment by nlBayside** [comment]
I think this is intentional behavior. When calculating the age of someone in the database, Rock checks to see if the birth year exists. If the birth year is greater than 1, then it will calculate an age (based on the user defined function [GetAge SQL function](https://github.com/SparkDevNetwork/Rock/blob/develop/database/Functions/ufnCrm_GetAge.sql) )

The report data select component calculates it a different way though. The report component will always return a value, while the UDF will only under certain conditions. If it should behave the same as the UDF, then it should return null as well.

![Screen Shot 2022-09-07 at 11 53 28 AM](https://user-images.githubusercontent.com/85907597/188959407-3cc25aeb-6b51-4dbb-96bc-694f1b4c8ef2.png)

![Screen Shot 2022-09-07 at 11 53 35 AM](https://user-images.githubusercontent.com/85907597/188959433-0e8a55e6-f2c4-4622-9620-aa620a5407dc.png)

Hope this helps!

**Comment by tstephens17** [comment]
@nlBayside 
I think a better way to handle this would be to check the year first. If no year exist then do not display an age. Just like if no birthday exist, then nothing is displayed.

Displaying an age of 2021 is not intentional. Its an oversight.

**Comment by nairdo** [comment]
If we're reading the reported issue correctly (from the URL of the screenshot), the problem is with the Advanced "Age" field in the Reporting system.    We've confirmed the issue and will work on a fix for v14.1.
