### ISSUE TITLE
Changes and deletions to calendar events don't show up correctly in ICS file for Google Calendar

### ISSUE THREAD

**Issue by jacksojourn** [SparkDevNetwork/Rock#5323]
### Prerequisites
*  Put an X between the brackets on this line if you have done all of the following:
    * [ ] **Impossible to test due to demo site resetting daily—need multiple days to test.** Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?
    * [X] Did you include your Rock version number and [client culture](https://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?
    * [X] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ASparkDevNetwork%2FSlack) to see if your bug or enhancement is already reported?

### Description

When a Rock calendar event is edited (e.g. time changed, details changed, deleted entirely), the edits aren't pushed to Google Calendar (it does work in some other calendar apps). I went on a troubleshooting search thinking this was Google's fault, but apparently the problem is that [the ICS file exported by the Rock doesn't correctly report new changes to events](https://support.google.com/calendar/thread/185683354?hl=en).

Needless to say this makes the ICS export feature useless or dangerous since there's no way for subscribers to know that what's showing up on their Google Calendar is accurate: if Rock events have since been edited, they can't see the edits.

### Steps to Reproduce

1. Create an event on a Rock calendar.
2. Export the calendar feed and subscribe to it via Google Calendar. Confirm that the event is showing up correctly in Google Calendar.
3. Make changes to the Rock event. For example, add one minute to the start time so it begins at 7:01pm instead of 7:00pm.
4. Wait ~24 hours for Google Calendar to update. Check and see if Google Calendar now correctly shows the event at 7:01pm.

**Expected behavior:** 

Google Calendar reflects changes to Rock event

**Actual behavior:** 

Google Calendar shows original event without latest changes

### Versions

* **Rock Version:** 1.14.1.1 
* **Client Culture Setting:** en-US

**Comment by ethan-sparkdevnetwork** [comment]
Hello @jacksojourn We have this in the queue, it should be fixed in the next hotfix or two depending on circumstances.

**Comment by jacksojourn** [comment]
@ethan-sparkdevnetwork ❤️

**Comment by MrUpsideDown** [comment]
@jacksojourn, to try and reproduce your issue, I followed these steps on the Rock Demo site:
1. Edit the "Customs and Classics Car Show" Event Occurrence and set the Schedule to "Once at 1/05/2023 9:00 AM".
2. Export the Calender Feed for the Public Calendar to a *.ics file.
3. Import the *.ics file to a Google Calendar.
4. Verify that the Customs and Classics Car show is scheduled for 9:00am on the specified date.
5. Re-edit the "Customs and Classics Car Show" Event Occurrence and set the Schedule to "Once at 1/05/2023 9:15 AM".
6. Again, export the Calender Feed for the Public Calendar to a new *.ics file.
7. Import the new *.ics file to the same Google Calendar.
8. Verify that the Customs and Classics Car show is now re-scheduled for 9:15am on the specified date.

From these steps, it appears to me that the calendar feed is working as expected to adjust the scheduled time of a previously imported event. If there is something I've missed here, please let me know the steps you used to re-create the issue.

With regard to *deleted* events, it is a current limitation of the Rock calendar feed that these events are not removed from the calendar when importing a new *.ics file. As you have discovered, deleting a calendar event requires that the *.ics file include a specific instruction to identify and remove that event. However, the information for these deleted events no longer exists in Rock. To support this functionality, Rock would need to be modified to retain information about these events for some period of time after they are deleted so that they could be included in subsequent *.ics export files. If this functionality is important to you, please add it to the "Ideas" list so it can be tracked: https://community.rockrms.com/Ideas

**Comment by MrUpsideDown** [comment]
@jacksojourn - I was able to reproduce your issue on a subsequent attempt. It seems that Google Calendar caches the calendar feed and that cache may persist even after the calendar is removed and re-added if it has exactly the same URL. The only sure way of forcing the calendar to refresh is change the URL by adding an anchor to the end - for example "http://www.rocksolidchurchdemo.com/GetEventCalendarFeed.ashx?CalendarId=1**#v2**". The anchor part of the URL is ignored by Rock, but it forces Google to ignore its own cached version of the calendar and refresh immediately, rather than waiting for its cache to expire. Provided that you use an anchor that has not been used in the past 24 hours, the calendar events should update immediately.

I have also updated my earlier instructions (above) in case somebody else is troubleshooting this issue in the future.

Please try this and let me know if it fixes the issue you are seeing.

**Comment by jacksojourn** [comment]
@MrUpsideDown Awesome! Totally working for me now. This is a wonderful gift for the planning work I need to do in my role. Thanks!

**Comment by MrUpsideDown** [comment]
@jacksojourn - you're welcome, pleased to hear you got the result you need.

**Comment by raufrecht** [comment]
Wait, I am confused, you are saying if I make a change to a calendar event, in order for it to reflect correctly in Google Calendar, I have to remove the calendar and add it back in with #v2 or subsequent change so the event is changed? Why does it not do it automatically? This means I have to notify everyone when we make an event change to update their calendars, that defeats the purpose. Am I missing something?

**Comment by jacksojourn** [comment]
Hey @MrUpsideDown @ethan-sparkdevnetwork let me know if I need to create a new issue for this, but this problem has returned in a different form. Now when an event is rescheduled on the Rock (time/date change etc.), that change is not reflected on Google calendar.
