### ISSUE TITLE
Fundraising Participant block not saving information when editing profile

### ISSUE THREAD

**Issue by IzabellaDTS** [SparkDevNetwork/Rock#5337]
### Please go through all the tasks below ###

* [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side. ###

Upon clicking the save button when editing a profile from the Fundraising Participant block, nothing would happen. Rock exception logs would note 'Object reference not set to an instance of an object'.  Upon further investigation, some temporary code was added to the Fundraising Participant block to determine the root of the cause. Upon testing again, the Rock exception log now noted: 'hfGroupMemberId is null or empty'.

Temporary Code Added to btnSaveEditPreferences_Click

```
if (string.IsNullOrEmpty(hfGroupMemberId.Value))
{
    throw new ArgumentException("hfGroupMemberId is null or empty");
}

if (imgProfilePhoto == null)
{
    throw new ArgumentException("imgProfilePhoto is null");
}

var rockContext = new RockContext();
var groupMember = new GroupMemberService( rockContext ).Get( hfGroupMemberId.Value.AsInteger() );
if (groupMember == null)
{
    throw new ArgumentException("groupMember is null");
}
```

Code Reference Photo:

![image](https://user-images.githubusercontent.com/84338278/224177083-3ea8317e-8428-4df5-8beb-9591785f999c.png)

Resulting Exception after adding code:

![image](https://user-images.githubusercontent.com/84338278/224177154-e7d996f3-d669-4fae-a83b-2563a16b8d7d.png)

### Expected Behavior ###

Information to save upon save click.

### Actual Behavior ###

Information does not save upon save click.

### Steps to Reproduce ###

* Create a fundraising event
* Access Fundraising Participant page for a participant
* Click Edit profile.
* Make some changes and then click 'Save'
* See error

### Rock Version ###

13.7

### Client Culture Setting ###

en-US

**Comment by nairdo** [comment]
@IzabellaDTS  I tried reproducing this on Rock v13.8 (which has only a few unrelated fixes) but I was unable to reproduce it.  Since the [Edit Profile] button is only used by the logged in person who is going on the trip, I made that assumption and tried editing the profile while logged in as Cindy Decker.

In this recording, I'm logged in as Cindy on the left and the admin on the right browser to see if there are any exceptions recorded:

https://github.com/SparkDevNetwork/Rock/assets/383807/6ab4027d-3f85-4e85-b02f-79d9a8efe5b8


Now, since there have been major changes to this block since v13, can you confirm you are still able to reproduce this issue and let us know what details we're missing so we can reopen this.
