### ISSUE TITLE
Recent Registrations Block - Date Range

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#5368]
## Please go through all the tasks below

* [x] Check this box only after you have successfully completed both the above tasks

## Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.
I am experiencing an issue with the Date Range option on the **Recent Registrations** block on the external site. I have not yet been able to determine the entire issue yet. However, when I set the date range not all registration instances available during that time show up. When the Date Range is left blank, everything appears as expected.![](https://user-images.githubusercontent.com/41912840/229316571-8c49632a-8ebc-4933-a407-f1c9f413e10b.png)## Expected Behavior
I would expect that when a date range is set on the [recent registrations] block, any registrations _entered_ during the time period submitted during the date range set on the block would show.## Actual Behavior
Not all registrations _entered_ during the time period submitted during the date range set on the block show. I am not sure exactly what is causing the registrations to not show. However, when the date range is not set, all registrations show as expected.## Steps to Reproduce

* Go to Tools, Event Registrations
* Add a Registration to an Instance
* Go To My Account
* Set the 'Recent Registrations' block to a specific date range.

Note: I have not been able to totally replicate this on the demo site yet.## Rock Version
1.14.2.1## Client Culture Setting
en-US

**Comment by timlem** [comment]
I am experiencing this on v14.2 as well.

**Comment by timlem** [comment]
All registrations show up for me and ignores the date range. Also if I have, 'Limit to registrations where money is still owed' set to No - nothing shows up. When I change it to yes, everything shows up. Even a registration from 2018 even though my previous days is set to 120 days

**Comment by nairdo** [comment]
Hi @timlem Related to issue #5467, we created a new Obsidian version of this Registration List Lava (https://github.com/SparkDevNetwork/Rock/commit/4d1073d58a24fbc7011fa37571262104411f6379) block that will replace the old block in v17.0.  That change should resolve this bug, so I'm going to close this issue.

However...

The way it's currently configured, if you are running v16.0, it looks like you _could_ have an early go at it by manually replacing the old block with the new block:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/00100be4-f8b9-4e36-8701-4cf49679aacf)
 
No problem if you're not interested, because it will be automatically replaced during the v17.0 upgrade.
