### ISSUE TITLE
Media Player Not Pulling Correct URL

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5386]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

When using a HLS stream for a media element, the video player is not pulling the correct URL. When using a service like Sardius or HaiVision. The provided HLS stream is an overall "playlist" stream that encompasses the audio and video URLs to be able to adjust the resolution. These are shown in the media files for the media element. The audio and video sub feeds are listed as HLS since they are part of the HLS stream. They can be labeled as video 1-5, audio and the overall playlist. Since the Default URL is being shorted in descending order the video file gets chosen instead of the overall playlist. This is causing the video only to play with not audio and the quality to not be able to be adjusted. 

### Expected Behavior

The media player should be using the overall HLS playlist stream instead of the individual video files.

### Actual Behavior

A video file with no audio is being defaulted to.

### Steps to Reproduce

Go to the demo site and add in a HLS stream with the supporting files and add the media player to a page using the media element id.

### Rock Version

13.7

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@RufenachtPW We have a number of churches using this with HLS streams without problems, but there might be something about the HLS streams you are trying to use that differs from the others we have tested. Can you post one of the URLs from each service you are trying to use as well as sample code for how you are trying to create the media player with that URL?

This would allow us to look into this further. Without some samples there isn't much we can do since it is working with other HLS streams.
