### ISSUE TITLE
Gender Label Missing on Check-in New Family Adult Screen

### ISSUE THREAD

**Issue by stevekleinliquid** [SparkDevNetwork/Rock#5390]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

<img width="1166" alt="Screen Shot 2023-04-12 at 9 41 52 PM" src="https://user-images.githubusercontent.com/114983828/231625580-dd79b8b8-35bc-4bcc-9bec-c5b09ca01f6e.png">

Digging into the code, EditFamily.ascx, line 186:

`<Rock:ButtonGroup ID="bgGender" runat="server" FormGroupCssClass="toggle-container" SelectedItemClass="btn btn-primary active" UnselectedItemClass="btn btn-default" Label="&nbsp;" Required="true" ValidationGroup="vgEditPerson" RequiredErrorMessage="Gender is required.">`

Note that the field label is set to a blank, not "Gender".

### Expected Behavior

The field label should be Gender.

### Actual Behavior

The field label is blank.

### Steps to Reproduce

- Configure check-in to allow adding new families
- Run check-in
- Perform a search and click on Add Family
- Select Adult on Add Family screen
- Note that the gender field is missing a label

### Rock Version

14.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @stevekleinliquid -- this was an intentional design decision back when the feature was first added.  Although some fields moved around a bit since the original mockups, this same treatment was used on the Age Classification and Married Status fields as seen in this screenshot:

![image](https://user-images.githubusercontent.com/383807/232576508-99246d55-0643-4123-a73d-21f45b98e290.png)

So, we won't consider this a bug to be fixed, but you can submit an idea over at the Ideas board at https://community.rockrms.com/Ideas

**Comment by bmurphy-dev** [comment]
I understand the original intent but think it's strange to leave a label off completely as display choices should be driven by styling, not just missing. Not everyone will use the default theme(s) available for this block, therefor not having a label all together is less convenient than having to hide one with styling in certain circumstances based on your design choices/needs. But, as mentioned by @nairdo this can be added as an Idea @stevekleinliquid
