### ISSUE TITLE
Obsidian Event Registration - Moving Waitlisted Registrations Does Not Permit Fee Selection

### ISSUE THREAD

**Issue by jeremyhoff** [SparkDevNetwork/Rock#5429]
### Please go through all the tasks below

- [X] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

Using Obsidian Event Registration, regardless of whether "Use Inline Signatures" is enabled/disabled, moving a registrant from the waitlist produces an email with a rckpid that successfully identifies the registrant but not permit the selection of Fees by this registrant. 

### Expected Behavior

I believe the link ought to send the registrant to the first Registration Form, allowing the registrant to complete registration as if they were not waitlisted.

### Actual Behavior

The URL sends the registrant to the "Summary" page, the step before the payment is collected.

### Steps to Reproduce

- Create Registration w/ Waitlist enabled
- Waitlist a registrant
- Move registrant from Waitlist -> send email
- Email contains working link that identifies the registrant and puts them on the second-to-last step in the registration (steps.review in the code).

### Rock Version

Rock McKinley 14.2 (1.14.2.1)  

### Client Culture Setting

Client Culture Setting: en-US

**Comment by ethan-sparkdevnetwork** [comment]
Fixed a few issues concerning using the Obsidian block with waitlist, moving, and the communication:

- [Email: Link is only created if AdditionalFieldsNeeded is true](https://github.com/sparkdevnetwork/rock/commit/ec04108b6039723e99584a8490618173326f01a4)
- [Registration.Cost is not set when the registrant is waitlisted](https://github.com/sparkdevnetwork/rock/commit/4a9e44b9915a5fcde11599117bcb8cfa62364605)
- [Capacity waitlist warnings are displayed after clicking the link](https://github.com/sparkdevnetwork/rock/commit/cfe08741e9d51f6d9b4695a119f722ec20f11a52)
- [The waitlist link starts at the Intro instead of Registrants](https://github.com/sparkdevnetwork/rock/commit/e1742f46581a35970daf46ad8dd08c34fbaea113)

**Comment by jeremyhoff** [comment]
@ethan-sparkdevnetwork according to this thread on the chat, the issue might not be solved. Please advise. https://chat.rockrms.com/channel/events-registrations?msg=uYTTh8xcL8pmYjZY8

**Comment by chead4** [comment]
@jeremyhoff Hi Jeremy - I wasn't able to recreate the issue with the Additional Information link in the Wait List Update communication not sending the registrant to the correct step in the registration.  I attempted to recreate in both v15.4 and v16.3.  Were you able to recreate in v15.4 or v16.2?
