### ISSUE TITLE
AddToDictionary Lava filter - behavior diffs between Liquid & Fluid

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5536]
### Please go through all the tasks below

- [x] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

During Liquid/Fluid transition prep - discovered an possible issue with the AddToDictionary filter. I'm not sure if this is a bug in Fluid or us mis-using the filter under Liquid and getting lucky. The issue is we're seeing different behavior/results in Liquid vs Fluid. 

Here is sample code that will reproduce what we're seeing:

```
{% assign prsnObj = CurrentPerson %}
{% assign personIds = '' | AddToDictionary:'PersonId',prsnObj.Id %}
personIds = {{ personIds | ToJSON }} <br>
{% for personId in personIds %}
    personId = {{ personId | ToJSON }}<br>
    {{ personId.PersonId }}<br>
{% endfor %}
```

### Expected Behavior

I would expect to see the same results under both Liquid and Fluid

### Actual Behavior

_There were the results in Liquid:_
personIds = { "PersonId": 126 }
personId = { "Key": "PersonId", "Value": 126 }
126

_These were the results in Fluid:_
personIds = { "PersonId": 126 }
personId = [ "PersonId", 126 ]

### Steps to Reproduce

In a Rock instance setup for DotLiquid - run the code above in Lava Tester.
Note results.
Now run same code in Lava Tester on an Rock instance setup for Fluid.
Compare results.

### Rock Version

v1.15.1.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @stanalyst  Thanks for letting us know about this one!  We're going to acknowledge there is an difference with the internal structure of the AddToDictionary, and we've added that as a note on the [Differences Between DotLiquid and Fluid](https://community.rockrms.com/lava/fluid/differences#addtodictionary) page, but since that filter was introduced with addition of Fluid, we're not comfortable trying to change that behavior without breaking it's use in the go-forward Fluid Lava engine.

The good news is however, if you need to iterate over all the items in the dictionary in a more standard way (via the AllKeysFromDictionary filter) seen below, both Fluid and DotLiquid operate the same.

```Liquid
{% assign colors = '' | AddToDictionary:'success','green' | AddToDictionary:'warning','orange' | AddToDictionary:'error','red' %}

{% assign keys = colors | AllKeysFromDictionary %}

{% for key in keys %}
    {{key}}: {{ colors[key] }}<br>
{% endfor %}
```

That should produce this result with both engines:
```
success: green
warning: orange
error: red
```
