### ISSUE TITLE
[Alpha v1.16.0.10] Obsidian Registration List Lava block ignoring context and pulling in large quantities of registrations

### ISSUE THREAD

**Issue by leahjennings** [SparkDevNetwork/Rock#5549]
### Please go through all the tasks below

- [ ] Check this box only after you have successfully completed both the above tasks

### Please provide a brief description of the problem. Please do not forget to attach the relevant screenshots from your side.

I added the new Obsidian Registration List Lava block to our website's My Account page. After adding the block when attempting to load the page, I get a Request Timed Out exception. This occurs when loading anyone's profile, not just my own.
<img width="1728" alt="Screenshot 2023-08-22 at 11 35 33 AM" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/421a9f8b-ad71-4715-8ae8-623014ac117f">

<img width="1728" alt="image" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/340916bb-72ea-4244-a1b8-062381f86933">

Here's the block configuration:
<img width="1718" alt="Screenshot 2023-08-22 at 11 35 50 AM" src="https://github.com/SparkDevNetwork/Rock/assets/66277785/2b6d114a-59f8-44ed-9cf4-8303ea4962d5">
tion:

And the issue occurs whether or not the block is added concurrently with the Legacy Registration List Lava block or independently (meaning the Legacy Registration List Lava block is not on the page at all). The page loads quickly and correctly when that block is removed.

### Expected Behavior

I would expect the page would load like normal when the Obsidian Registration List Lava block is present on the page.

### Actual Behavior

A _Request Timed Out_ exception occurs when loading a page that contains the Registration List Lava block.

### Steps to Reproduce

- Go to a Rock instance that is running the Alpha v1.16.0.10 version
- On the external site My Account page, add the new Obsidian Registration List Lava block
- Load the page as an authenticated user
- Notice that the page doesn't load and shows the _That Wasn't Supposed to Happen_ screen

### Rock Version

Rock McKinley 16.0 (1.16.0.10)

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I am unable to duplicate the Request Timed Out exception, but I'm seeing some odd behavior with this block that's likely related.

1. I AM able to put the Obsidian Registration List Lava block on the /myaccount page... it takes about 15 seconds.

2. After the block is added and I refresh the page, the new block shows a GIANT (many hundreds) list of Events that have nothing to do with me (the logged-in person).
3. Events seem to be duplicated many times.
4. The original LIQUID block on this page correctly shows "nothing", because there happen to be no recent events associated with me.

It seems like the Obsidian block is lacking some sort of context and showing events over and over for LOTS of different people. This could explain why Leah's page timed out... maybe she has way more events trying to load than we do?
![image](https://github.com/SparkDevNetwork/Rock/assets/3903408/8f7a3f34-a7d8-4ea6-af49-59e7f3236778)

**Comment by JimMichael** [comment]
Wow!

**Comment by JimMichael** [comment]
Can this block be downloaded and installed to test? If so, how? I can't find an existing _RegistrationListLava.cs_ on my v16 file system. I have _RegistrationListLava.ascx.cs_ but that appears to be the old webforms block.

**Comment by leahjennings** [comment]
@JimMichael I worked with @nairdo via DM to test the changes to the block and confirmed the changes fixed the issue. :)
