### ISSUE TITLE
[v16.0] Obsidian Following Event Type Detail Block Odd Behavior

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#5605]
### Description

The Obsidian Following Event Type Detail Block is exhibiting odd behavior. I have experienced this behavior 1), when adding a new Following Event Type _and_ 2), when editing an existing Following Event Type.

See video:
https://github.com/SparkDevNetwork/Rock/assets/23226974/6c03a250-38b5-4b34-9448-93cf9c415b52

Based on my selection in the `Event Type` field, I have noticed incorrect Attributes for all of them at different times. I have not been able to figure out if there is one `Event Type` that is specifically causing the issue.

Also, while I was unable to reproduce this next result on the demo site (v1.17.0.2), this is what I am seeing on my dev site (v1.16.0.11):
<img width="1722" alt="Screenshot 2023-09-15 at 22 34 01" src="https://github.com/SparkDevNetwork/Rock/assets/23226974/9df97fb8-eba8-4224-b017-694db1c30cc9">

### Actual Behavior

No issues adding/editing Following Event Types.

### Expected Behavior

Issues with adding/editing Following Event Types.

### Steps to Reproduce

See above.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.0, v17.0

### Client Culture Setting

en-US

**Comment by mikedotmundy** [comment]
Will this be fixed in v16?

**Comment by chead4** [comment]
@mikedotmundy HI Mike, this is planned to be fixed in v16.1

**Comment by chead4** [comment]
@mikedotmundy HI Mike, I wanted to keep you updated on this issue.  We were planning to have this issue fixed in v16.1 but it is more complex than expected and will take longer to resolve.

**Comment by jasonhendee** [comment]
@mikedotmundy sorry for the back-and-forth on this issue. We spent some time yesterday getting to the bottom of it, and determined the following:

### You've actually reported 2 separate issues:
1. The video you provided from [rockrmslatest.com](https://rockrmslatest.com/) showcases an issue where the attributes for a given Following Event Type fail to properly load as a whole.
   - This issue is not present in v16.0 or 16.1 of Rock; it was not introduced until very recently.
   - This issue **was not** fixed in commit [f4fb9ce](https://github.com/SparkDevNetwork/Rock/commit/f4fb9cecbbd489c74311bcfc89bf2d1e45113bc2), which is why we re-opened the issue.
2. The screenshot you provided (from your dev site) showcases an issue where Note Type Field Type attributes - specifically - failed to load.
   - This issue **was** fixed in @PraveenMathew92's commit above.
---
Given this info, just know that we'll be closing this issue soon, once we've properly tackled both issues, but also know that v16.0 & v16.1 of Rock should no longer exhibit **either** issue.

**Comment by mikedotmundy** [comment]
Thank you @jasonhendee - So far as I can tell, the issue seems to be cleared up in my Alpha v16.1 instance. Are you saying that I should still be seeing a part of the issue in v16.1 Alpha?

**Comment by jasonhendee** [comment]
> So far as I can tell, the issue seems to be cleared up in my Alpha v16.1 instance.

@mikedotmundy This sounds correct; you should no longer be seeing the issue v16.1 Alpha. Thank you for confirming!
