### ISSUE TITLE
iPads - Currency Field & Commas

### ISSUE THREAD

**Issue by MatthewKyle22** [SparkDevNetwork/Rock#5611]
### Description

When a user tries to submit a workflow or pledge that uses the currency field using an iPad they are able to input commas into the field.

The form errors out with "Please Correct the following: {Field Name} is required"

### Actual Behavior

![IMG_0001](https://github.com/SparkDevNetwork/Rock/assets/11671126/1eb708b8-4af4-44e3-9ecc-500d73c34750)

The field is not valid and shows as such, as well as errors on submission.

### Expected Behavior

Like on desktop and mobile I would expect to not able to enter a comma in the field.

### Steps to Reproduce

- Using an iPad,
- Go to https://rock.rocksolidchurchdemo.com/page/303
- Click on Total Pledge Amount and enter a number containing a comma. Ex. 1,000
- Try submitting pledge
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v14.3-v15.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @MatthewKyle22, We've had several developers research this issue and each has reached the same conclusion (as well as several articles on the web describing this same problem) -- we're going to call this one a bug with Safari/iOS.  [This article](https://stackoverflow.com/questions/16006202/using-currency-symbols-and-commas-in-an-input-of-type-number) concisely describes it as:

> Unfortunately, iOS currently has built-in validation for the `number` input type which screens out commas and dollar symbols. Since this validation "feature" is embedded in the browser and Mobile Safari hasn't yet implemented the `novalidate` directive, there is currently no way to do this validation manually.

On the technical side, we are opting to _not_ change Rock's number control from using `type="number"` to `type="text"` as that leads to other gotchas we want to avoid.  To make matters more difficult with internationalization, [some countries](https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma) use a comma `,` as the _decimal_ separator which is why the non-Safari browsers have taken the task to prevent people from entering numbers in incorrectly.
