### ISSUE TITLE
Sign-Ups Does not Hide the Search and Clear Filter Actions When all of the filters are turned off

### ISSUE THREAD

**Issue by frogydiak** [SparkDevNetwork/Rock#5621]
### Description

The search and clear filter actions are still visible although all of the filters are not enabled.

![image](https://github.com/SparkDevNetwork/Rock/assets/1373815/ea71a940-8fc4-4f33-97c5-cc7dea5bed7e)

### Actual Behavior

See screenshot above

### Expected Behavior

The search and clear buttons should disappear when there is nothing to filter.

### Steps to Reproduce

Uncheck all available filters for Sign-Ups, do this by going to the sign-up page in the external website Block Configuration since there is a bug in the internal site. The setting for the Sign-Up Finder block does not show the [Settings](https://github.com/SparkDevNetwork/Rock/issues/5412).

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by jasonhendee** [comment]
@frogydiak This should be resolved as of Rock v15.2. Thanks for reporting it! Also, note that you can change the **Results Header Lava Template** to a more appropriate message in this case, since the individual will no longer be performing a search.

![GitHub Issue 5621 - Results Header Lava Template](https://github.com/SparkDevNetwork/Rock/assets/59710095/4a8a46eb-345b-4118-a9b2-8d319bbda730)
