### ISSUE TITLE
Send Group Requirement Notification Job - Does not honor archived people

### ISSUE THREAD

**Issue by jcjones37** [SparkDevNetwork/Rock#5638]
### Description

I am experiencing an issue where users who are set to receive a Group Requirement Notification are still receiving the notifications after they have been archived in the group.

### Actual Behavior

If a person is set to receive the Group Requirement Notification, but you 'archive' them while they are still 'active' in the group... the Group Requirement Notification Job still sends that archived user a notification.

### Expected Behavior

I would expect that if a user is archived (regardless of active/inactive) Group Member status, they would not receive the Group Requirement Notification.

### Steps to Reproduce

- Go to General Settings > Group Types > Small Group
- Add a Role called > Notifier
- Set this new role to receive Group Requirement Notifications
- Add a group requirement that the current group members will not meet (Like background check)
- Go to System Settings > Jobs
- Run the 'Calculate Group Requirements Job'
- Go to any small group
- Add someone to that small group with the role of Notifier
- Go to System Settings > Jobs
- Run the 'Send Group Requirements Notification' Job
- Notice the user you added as a notifier gets sent an email
- Go back to the small group and archive that user (not delete)
- Go back to run the 'Send Group Requirements Notifications' Job
- Notice the user still receives the email notificaiton.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi Jason @jcjones37 , I tried reproducing this on the upcoming v15.3 branch, but I was not able to reproduce this issue.  (_I found a few steps missing shown in bold below such as 10a: setting up the "Send Group Requirements Notification" job and 13a: running the "Process Group History" job, but I'm sure you probably had all that ready on your system already_).

1. Go to General Settings > Group Types > Small Group
2. Add a Role called > Notifier
3. Set this new role to receive Group Requirement Notifications
4. Add a group requirement that the current group members will not meet (Like background check)
5. Go to System Settings > Jobs
6. Run the 'Calculate Group Requirements Job'
7. Go to any small group
8. Add someone to that small group with the role of Notifier
9. Go to System Settings > Jobs
10. Run the 'Send Group Requirements Notification' Job
    a. **(First setup a Send Group Requirements Notification Job.  Settings are shown below.)**
12. Notice the user you added as a notifier gets sent an email
13. Go back to the small group and archive that user (not delete)
    a.  **(Run the "Process Group History" job to allow archiving recently added group members.)**
14. Go back to run the 'Send Group Requirements Notifications' Job
15. Notice the user still receives the email notification.

Can you verify this is similar/same as how your job is configured?

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/b7cbc450-20b5-4faf-8707-e1aacbff4cad)

I can see way back in v12.9 that the code was missing the check on the `IsArchived` bit, but [it has been checking that since 12.9](https://github.com/SparkDevNetwork/Rock/commit/a90dfb8bf72d9178973b1787b4037c012ca7ceda#diff-d1f42e27573d01f6bf17746aeb8f78fc87c7014c73807fbd8877c6b6a40deec3R113).

Here's a video showing what I did.  Is this essentially what you are doing too?

https://github.com/SparkDevNetwork/Rock/assets/383807/f9d2aef0-b078-496d-a9b2-95eeca10f253

(I had breakpoints set so I could see what was going on behind the scenes.  Notice how when I stepped through the code in that second time it did not find anyone in the membersToNotify list.)

Also, no second email was received in PaperCut.  Once I unarchived Pete and re-ran the job again, it did find him in the collection and then he received that second email shown here:

https://github.com/SparkDevNetwork/Rock/assets/383807/75a948fb-ea25-4e16-8972-d8d697fd1b08

Do you see something we've missed?

**Comment by nairdo** [comment]
With @jcjones37 help, we were able to track the issue down to the Accountability Group feature in the Job.  The code was not checking the active/inactive status of members.
