### ISSUE TITLE
Connection Request Attribute Permissions

### ISSUE THREAD

**Issue by RufenachtPW** [SparkDevNetwork/Rock#5644]
### Description

Connection request attributes do not obey connection opportunity or connection type permissions. Attributes can be assigned on the opportunity or type. This effects adding a new connection request or editing attributes on an existing connection request. 

### Actual Behavior

If there is a group assigned to connection types or connection opportunities that have edit rights to the connection request, they can not edit the attributes on the connection request. No attributes are shown when adding a new connection request unless permissions are assigned directly to the attribute. 

### Expected Behavior

If a security group is assigned to be able to edit a connection request, whether on the connection type or opportunity they should be able to edit attributes. 

### Steps to Reproduce

Go to rock solid demo site. 
Add an attribute to a connection opportunity.
The Connection Administration role should already have edit permissions on the opportunity. 
Impersonate someone with connection administration role. (Ted Decker). Make sure they do not have Rock administration permissions. 
Go try to add a connection request and see that no attributes are listed.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.2,15.1

### Client Culture Setting

en-Us

**Comment by nairdo** [comment]
> No attributes are shown when adding a new connection request unless permissions are assigned directly to the attribute.

Hi @RufenachtPW, This is the expected behavior of Rock Attributes (in general).  If you'd like to open an enhancement request, we would ask that you do that over on the [Ideas board](https://community.rockrms.com/Ideas).

**Comment by RufenachtPW** [comment]
So all connection request attribute permissions will need to be hard coded to the connection administrations security role when attributes are added to a connection request? Currently, only the Rock Administration role has edit permissions to these attributes.

**Comment by JimMichael** [comment]
Typically the same role(s) you defined that grant access to the connection requests get Edit on any attributes of the connection request. This is how Groups (and group member attributes) work as well.

**Comment by RufenachtPW** [comment]
Yes that’s how it is supposed to work but it is not working that way. That’s why I opened the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JimMichael** [comment]
Sorry, I think you misunderstood my reply. Edit rights to a Connection Requests do NOT grant edit rights to attributes of the request. You always need to grant Edit rights to Attributes individually for the roles intended to edit them.

You said
_So all connection request attribute permissions will need to be hard coded to the connection administrations security role when attributes are added to a connection request?_

and I was just trying to convey that you can grant *any* role (that needs it) edit rights to connection request attributes and there’s nothing special about Connection Administration role being the only role to have them. 

So yes, you always need to add edit rights to attributes. They don’t get inherited. This is actually a good feature as it lets you grant granular rights to individual attributes to *different* roles vs “getting edit to all attributes just because I I can edit a connection request “

**Comment by RufenachtPW** [comment]
I understand. This changed in version 15 though. Before version 15 connection request attributes did inherit permission rights from the connection opportunity or connection type. The problem we are running into is clients who built connection request forms for serving opportunities. In 14 the staff could edit those attributes on a connection request. Now in v15 they do not have edit rights if they need to update an attribute on the specific connection request. In was in version 14 (and before) and removed in 15.

**Comment by chead4** [comment]
@RufenachtPW Thank you for the additional details.  We will review and get back to you early next week.

**Comment by chead4** [comment]
@RufenachtPW Hi - thank you for your patience while we reviewed this issue.

In v14.3, there was an issue where security for a connection request attribute for a connection type was allowing a person who was not in a security role to edit the connection request attribute in the connection.

This was fixed in v15.0 in [7bfb2c85](https://github.com/SparkDevNetwork/Rock/commit/7bfb2c8502a8dc1fa7f7d5c71208bd711988ff1f).  I have tested this in v15.2 and v16.1 for both View and Edit security set up for a connection request attribute.   When logged as someone within the security role they can view and edit the connection request attribute.  When logged in as someone not in the security role they are unable to view or edit the connection request attribute.

**Comment by RufenachtPW** [comment]
Thanks @chead4 for the response. I found the commit where the change happened. [ce31c21](https://github.com/SparkDevNetwork/Rock/commit/ce31c21ddc4e5ae4ec60e4d4e27ad3562bdae1fc) I agree that this change needed to happen so that attributes could be locked down accordingly. Maybe this is how it was always supposed to function but never did. The main question is should connection opportunity or connection type attributes initially inherit permissions from the connection opportunity or type like they do elsewhere like groups. Currently, the code in Authorization.cs only looks at the explicit permissions on the attribute entity only, which comes from the Attribute entity type. Line 1057

**Comment by chead4** [comment]
@RufenachtPW I am so sorry this took so long to get back to you.  I wanted to take the time to make sure that I understood your question and went through the use case in Rock.  

After testing and consulting with development, you're correct - security permission inheritance differs between Groups and Connections.  Specifically, Connection Opportunity and Connection Type attributes do not inherit security permissions from the Connection Opportunity or Connection Type.  

While this aligns with the original design of Connections, this is a great idea for an enhancement to Rock. Feel free to submit an enhancement request on the [Ideas board](https://community.rockrms.com/Ideas).
