### ISSUE TITLE
Form Builder Template does not "lock" person entry setting

### ISSUE THREAD

**Issue by dataCollegechurch** [SparkDevNetwork/Rock#5699]
### Description

When using a form template with Person Entry Settings disabled, the form builder page does not indicate this setting is locked. This causes confusion for the form builder who may not be the person who setup the template.

### Actual Behavior

Workflow entry ignores the Enable Person Entry Setting selected on Form Builder Page and instead uses the Form Template Setting. The form builder is confused why the setting they selected in form builder is being ignored.

### Expected Behavior

Form Builder Page should disable the ability to toggle the Enable Person Entry Setting and instead show the setting as locked. The actual value of Enable Person Entry Setting should match what is selected in the template, if a template is selected.

It may be desirable to allow for the creation of Templates that don't lock the Enable Person Entry Setting.

### Steps to Reproduce

1. Create a form template where the Person Entry Setting is not enabled
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/e2a5906b-e76c-48dd-a165-eca49edf0225)
2. Create a form that leverages this template, make sure Enable Person Entry is set in the form builder settings
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/f137707e-60ba-45b0-b0cd-7b441c770ddf)
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/f16df974-4eaa-4230-9844-f3d7d6c435ce)
3. View Form, note that person form entry is not included
![image](https://github.com/SparkDevNetwork/Rock/assets/54962439/5234a805-7def-4dd3-bf1d-9398ad451a26)

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

15.1/16.0

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@dataCollegechurch Interesting find.  This is actually a bug with the WorkflowEntry block -- in other words, if the template does not enable PersonEntry, then the form can _optionally_ enable it.  But currently the workflow entry is currently ignoring the form's setting and is only considering the template.  That's not right so we'll fix this.

It should behave like the other template settings (such as **Confirmation Email** or **Completion Settings**) so that only if they are enabled, are they locked from being set/re-set on the form that uses the template.

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/d691b637-b467-40e0-b6b8-b3d83a3d6c8d)
...then...
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/8ed723e5-1cb7-4094-b014-ec53e5b826e9)
