### ISSUE TITLE
Bulk Update Block does not honor Person Property Defined Type permissions

### ISSUE THREAD

**Issue by smross** [SparkDevNetwork/Rock#5745]
### Description

The Bulk Update block does not obey permissions of defined types for Person Properties.

### Actual Behavior

If someone has access to the Bulk Update block (such as the Bulk update page launched from a grid), then they can bulk update _Defined Values_ of person properties that use _Defined Types_. It's _possible_ that this issue exists for situations beyond person properties that are defined types, but I have not had time to test all the possibilities yet.

![BulkUpdateDefinedTypeBug](https://github.com/SparkDevNetwork/Rock/assets/8688424/72c96035-91e5-46c4-ba1b-e8506cd199af)

### Expected Behavior

The bulk update block should obey permissions that have been set for Defined Types

### Steps to Reproduce

1. Locate a Defined Type that corresponds to a person property, such as _Title_.
2. Set the permissions for the Defined Type to not have _Edit_ permissions for a security role.
3. Navigate to a grid as a person that has a security role that does _not_ have Edit permissions for the Defined Type.
4. Press the Bulk Update button on the grid.
5. Select the person property Defined Type that you restricted edit permissions on, such as _Title_, and select a defined value.
6. Select the _Next_ button and complete the bulk update process.
7. The person(s) on the grid have the person property Defined Type updated.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.2

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
I spoke with Shawn about this earlier today.  The Bulk Update block does check security for Person _Attributes_ but it is not currently designed to use security settings that the PersonEdit block uses for controlling who can edit the Connection Status and Record Status (added 7+ years ago [in v7](https://github.com/SparkDevNetwork/Rock/commit/203bc630712d017283bd31075fbf3979f8bb327a)):

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/82ee8252-b965-46fa-8896-da21d0b2d2a6)

...nor does it use security settings of any corresponding DefinedTypes for those properties such as Title, Record Status, Connection Status, etc.  So, we're going to ask that a request be created over on [the Ideas board](https://community.rockrms.com/ideas) for this idea.

**Comment by JimMichael** [comment]
This does seem like a huge security hole, however, because Staff Workers have access to the Bulk Update page by default, which allows anyone in that role to update person properties they’re otherwise prevented from updating via the Edit Person page. 

Is it worth alerting all rock users of this issue so that they can at least lock down access to Bulk Update page, if they consider it a risk?

**Comment by zackdutra** [comment]
@nairdo we agree with Jim’s assessment that it is a major security hole.  Some of the attributes are tied to group syncs on security groups, so anyone having the ability to make changes could be an issue worthy of more attention than an idea.

**Comment by nairdo** [comment]
We do not consider this a major security hole but I'd like to clarify the BulkUpdate block functionality we are referring to.

This block has always functioned in the manner we're discussing, specifically in relation to DefinedTypes/DefinedValues Person properties (not person Attributes): Title, Suffix, Marital Status Connection Status, Record Status, Race and Ethnicity.   As it currently stands, the PersonEdit block only has special security controls for two of those properties, Connection Status and Record Status (added in v7). This implies that any staff member with editing rights can modify the _other_ mentioned properties. While this is not a critical security concern, it's important to be aware of it. If there are staff members with access to these features who may not be fully trusted, it might be prudent to reconsider their access levels.

> This, in my opinion, is capable of being a bug of sorts, but it's also an improvement that needs to be made, and it's working as designed.

And thanks for everyone's feedback.

**Comment by JimMichael** [comment]
For some reason I never saw your last comment, @nairdo... 

> This implies that any staff member with editing rights can modify the other mentioned properties. While this is not a critical security concern, it's important to be aware of it. If there are staff members with access to these features who may not be fully trusted, it might be prudent to reconsider their access levels.

I think you are assuming all orgs run with default _Staff Workers_ security permissions, in which case a _Staff Worker_ WOULD have Edit rights to the various Person Properties you mention, thus allowing them to Bulk Update them is No Big Deal... 

But if an org (like ours) has RESTRICTED _Staff Worker_ from Editing Person Properties **AT ALL** (they don't get the Edit button on a Person record) and those rights have been given to a different _Person Add/Edit_ role that only a subset of Staff get... People with such a Staff Worker role (and can't Edit a Person at all) can **STILL** use Bulk Update to easily modify any Person Property they choose.

That's why I consider it a security problem... because this one block (Bulk Update) is granting rights we've intentionally taken away when editing a Person directly. Anyway, just wanted to give that additional perspective.
