### ISSUE TITLE
Content Channel Item View Block Issues

### ISSUE THREAD

**Issue by asdf1nit** [SparkDevNetwork/Rock#5791]
### Description

When adding a Content Channel Item View block to a page you receive an error message.
![image](https://github.com/SparkDevNetwork/Rock/assets/18108765/2b61e3f1-7e18-4946-b550-8d2b0bff7aaf)

Here is an example https://rockrmslatest.com/admin/cms/pages?Page=231&ExpandedIds=1%2c229&Redirect=false

I believe this happened after the 16.3 release as I just added this block to a page a few days ago and had no issues with it.

### Actual Behavior

An error message is shown, and the block cannot be configured.

### Expected Behavior

Adding this block should not produce an error and you should be able to configure it.

### Steps to Reproduce

- Go to Admin Tools > CMS Configuration > Pages
- Click on a page
- Add a content channel item view block
- See error

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.3

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@asdf1nit Jonathan, that message shows up only if you have "Administrate" permission on the block, and that was by design.  But, has also been that way for a long time.  I tested this on v13 via Time Machine
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/c8502cc1-7640-496c-a70a-fce6f0b0fe51)

...but the commit ([106f94e](https://github.com/SparkDevNetwork/Rock/commit/106f94ef876b97c0a914b4eb7bf4bc1db582e87d#diff-52cae3162358874786622c7ef01bd846bd8ba3e48785cc781afe03f129c2973cR302-R313)) that added that feature happened in v8.0.

Are you saying you are not able to go into Block Configuration mode to edit the settings:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/7ebc3606-18b6-4e38-8608-9089b179b722)

**Comment by nairdo** [comment]
We had a chance to review this with @asdf1nit and he agreed it does still let you (the admin) configure the block's settings.  We did decide [to change](https://github.com/SparkDevNetwork/Rock/commit/10e8fca55db564bd64244801a1de7e5ed67d4271#diff-bf901c74541edf9c9f50b43ff3e76cd61c4f69274391d2023f5357c60fdb76d8R576) the color to yellow/warning in v16.4 so it does not look like a hard-fail.
