### ISSUE TITLE
Captcha Support Is Enabled On Blocks Even When Captcha Isn't Set Up

### ISSUE THREAD

**Issue by JimMichael** [SparkDevNetwork/Rock#5796]
### Description

When Upgrading to v16.3, the Captcha support on the Account Entry, Change Password, and Forgot Username blocks is enabled by default ON EXISTING PAGES THAT USE THE BLOCKS, IF Captcha support *itself* is not set up on the system, this results in broken blocks that don't submit properly.

### Actual Behavior

Upgrading to v16.3 sets the new block setting of *Disable Captcha Support* to *No* in the above three blocks (specifically, on all existing instances of the blocks), but there seems to be an *assumption* that Captcha support is configured properly on the system at all. 

Instead, if you DON'T yet have Captcha support configured in the instance, the various Forms these blocks generate cannot be submitted properly. Depending on if you're logged-in or not, you will either see an error related to Captcha support, OR you will see no error at all... just a form you frustratingly cannot submit.

### Expected Behavior

Blocks wouldn't be updated with new functionality without verifying that the support for that functionality is already set up... OR they would not enable the new functionality by default.

Obviously it's too late to fix this in 16.3, and there's nothing I can think of that can be done in 16.4alpha to improve the situation. I'm bringing this up so that perhaps the upgrade "warning" section wen upgrading to 16.3 can be revised to CALL OUT that an admin must visit these pages/blocks immediately after upgrading to 16.3 if they don't yet have captcha support in place, so they can disable the Captcha feature until they're ready for it.

There is a brief mention in the 16.3 release notes of _Added optional CAPTCHA to Forgot Username and Change Password blocks. _, but this is insufficient as it 1. Doesn't say you'll have a broken system unless Captcha support is already properly configured, and 2. Doesn't mention one of the three affected blocks at all.

### Steps to Reproduce

1. Upgrade to v16.3. 
2. Go the Account Registration, Forgot Password, or Change Password pages
3. Edit the block and Observe that _Disable Captcha Support_ is set to No (meaning, it's ENabled.)
4. Try to create a new account on the site and submit the form and observe it fail with either a captcha error, or nothing at all but a form with grayed out fields and submit button.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v16.3+

### Client Culture Setting

en-US

**Comment by bmurphy-dev** [comment]
Wow thanks for pointing this out @JimMichael ! I didn't realize this was an issue on my own external site because the default isn't what I'd expect either when a new option is available. I don't use Captcha and therefor this bit me too.

**Comment by nairdo** [comment]
@JimMichael @bmurphy-dev That bug was discovered during v16.3 beta testing and was updated in the 1.16.3.4 beta package.  I know I watched the test of that fix after the Rock Demo site was updated v16.3 [1.16.3.4].

...
We uncovered the problem.  During the final packaging of 1.16.3.**5**, that earlier change was not included.  So that fix was not in the final v16.3 [1.16.3.5] package.

This is quite upsetting and embarrassing.

Since we can't let anyone else trip on that situation, we just put that fix (the updated `\Obsidian\Controls\captcha.obs.js` file) into the v16.3 package.

We're also re-examining our process to make sure this sort of thing doesn't happen again. If anyone else updated to v16.3 prior to Mar 18, 4:40PM MST and needs the fix, [this zip file](https://rockrms.blob.core.windows.net/updates/temp_pre_release_patches/v16_3_5_captcha.obs.js.zip) can be unzipped and the contents should replace the old `\Obsidian\Controls\captcha.obs.js` file.

We're going to keep this open until we hear back from either of you.

**Comment by JimMichael** [comment]
Thanks for the detail and quick response, @nairdo !

**Comment by bmurphy-dev** [comment]
We really appreciate it @nairdo !

**Comment by nairdo** [comment]
I spoke with Jim via DM and he confirmed that file/fix did resolve the issue.
