### ISSUE TITLE
Note View Lava Template Field is not showing

### ISSUE THREAD

**Issue by bkerekffy** [SparkDevNetwork/Rock#5803]
### Description

The Notes block no longer utilizes a Note View Lava Template field which churches previously use for customizing the display of different Note Types. Different use-cases could be:
1. Only showing notes of a specific type that were created by the Current Person.
2. Hiding notes of a specific type from a Current Person but allowing them to create new notes of that type.
3. Only showing notes during a specific time period.

The new obsidian version of the block and security role permissions are unable to replicate these above use-cases. 

### Actual Behavior

The Notes block no longer has the Note View Lava Template field.

Legacy block:
 
![image](https://github.com/SparkDevNetwork/Rock/assets/148915082/2cc668ee-5ede-4e70-8579-305f1dc08886)

New Obsidian Block:

![image](https://github.com/SparkDevNetwork/Rock/assets/148915082/428e894f-7ef7-448d-ad5e-ae63070f19fe)

### Expected Behavior

The Notes block is expected to have the Note View Lava Template field.

### Steps to Reproduce

1. Go to a person profile page that utilizes the Obsidian Notes block.
    a. This can be done on Athey Creek's sandbox environment.
2. Open the block's properties.
3. The Note View Lava Template field will not be present.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 17.0 (1.17.0.15)

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
@bkerekffy  The 'Note View Lava Template' feature was removed from the Obsidian version of the Notes block due to some amazing new features coming to that block soon. 

When making this decision, we collaborated with many churches to determine their usage of that aspect of the Notes block, and nearly all were not using it. Therefore, although we try to avoid removing features from a block, such changes do occur occasionally. However, we always carefully consider the costs and consequences before making such decisions.

Lastly, because we anticipated an organization might need time to adjust their process/usage, we left the legacy **Notes** block on the Rock instance so it could be manually added back in (temporarily) but we wanted organizations to let us know if/why they did it.  That's what this "Heads Up!" note is all about:
![image](https://github.com/SparkDevNetwork/Rock/assets/383807/89ba4436-d50b-4cfd-8c91-8693612948f2)
