### ISSUE TITLE
Sign-Up Blocks creating new profiles as Active

### ISSUE THREAD

**Issue by JoshuaMaiorino** [SparkDevNetwork/Rock#5871]
### Description

When people are added to Rock via the new Sign-Up Block, they are added as Active Visitors.  In most places in Rock, when a new Person is created, they get added as pending with a configuration option for what connection status should be used.

### Actual Behavior

New People are created as Active with a connection status of Visitor.

### Expected Behavior

Records should be added with Status of Pending with a configuration option for Connection Status.

### Steps to Reproduce

Use the Sign-Up block with the anonymous mode.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16

### Client Culture Setting

en-us

**Comment by JoshuaMaiorino** [comment]
This issue was entered on behalf of Vox Church in CT

**Comment by JoshuaMaiorino** [comment]
Also, I'm willing to go in and make these changes and create a pull request.  Just let me know.

**Comment by luke-infoministry** [comment]
@JoshuaMaiorino for clarity, are you talking about the Sign Up Register block type?
Obsidian > Engagement > Sign-Up

**Comment by chead4** [comment]
@JoshuaMaiorino Hi Joshua After reviewing, this is an enhancement to Sign-Ups Finder to add a block setting to configure the Connection Status and to set the Record Status as Pending.  Please share you feature/idea with us on the Rock Community Ideas & Core Changes board via [https://community.rockrms.com/ideas-changes](https://community.rockrms.com/ideas-changes) This allows the full community to speak into it and help us determine it's priority. 

I will be closing this request at this time.  Let me know if you have any questions. 
Thank you for helping to make Rock better!

**Comment by JoshuaMaiorino** [comment]
@chead4 This feature is very important, as the lack of it is causing data integrity issues for Vox Church.  I'm happy to put in a PR for this.  Please let me know if that would be helpful.

**Comment by chead4** [comment]
@JoshuaMaiorino  Hi Joshua, Please share our Rock Community Ideas & Core Changes board https://community.rockrms.com/ideas-changes with Vox church and let them know that this enhancement can be requested and funded by them.

**Comment by zackdutra** [comment]
@chead4 while it makes sense for a new block setting to be an enhancement, would the team consider just changing the default value to Pending? No enhancement, just a simple change to what seems more in line with what it should be.  New people are normatively “Pending”, so if the core block isn’t going to offer a setting out of the box, it would make sense that it at least doesn’t mark new people as something other than Pending. 
Or, is the opinion of the team that because someone signed up for an event that they’re Active? 
Could you share what the philosophy behind this is? When can we expect a core block to mark someone as Pending vs Active by default? 
Thanks for your time!

**Comment by JoshuaMaiorino** [comment]
That was my thought. It's why I didn't put this in as a feature request but a bug.  Because the form can filled out anonymously, duplicate records can be created. Records created in this fashion should be pending to fall into the pending record bucket so the data integrity team can review it to ensure it's not a duplicate.

@chead4 Does Rock no longer take pull requests from the community?

**Comment by nairdo** [comment]
Colleen is out today so let me help answer these questions. 

> …would the team consider just changing the default value to Pending? 

We have a general principle to avoid changing default behavior on a block whenever possible.  (It’s disruptive to those who already expect a block to behave the way it currently does.)


> Or, is the opinion of the team that because someone signed up for an event that they’re Active?

We can see that both statuses might be considered valid, depending on the church’s use cases and needs. In general, we typically would let the organization decide via block settings like the Registration Entry block uses:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/1479b16e-d6c4-4929-bd2e-9c83836a5721)


> Does Rock no longer take pull requests from the community?

In recent years, our policy has been to consider Pull Requests (PRs) from churches as they tend to be infrequent, and we no longer accept PRs from non-church partner organizations.  Managing a large volume of submissions from diverse sources can lead to inconsistencies and increase the maintenance burden on our core team – which has a cost to everyone in the community.

Now, in recent months we set up a slightly different starting point for the old “Ideas” page to let everyone know that the core team can accelerate funded change requests.  On that page (linked above) you’ll see these two options:

![image](https://github.com/SparkDevNetwork/Rock/assets/383807/e7d5a874-416c-4ce6-b59e-4321dd450060)

(@JoshuaMaiorino we also forgot that you’re no longer with Bema so you likely did not hear about the recent changes.  Are you on staff at Vox church or do you work at Razayya?)

I hope this makes sense to everyone.  We just need to be prudent with our time and use it wisely because there is much work to be done.

**Comment by JoshuaMaiorino** [comment]
Razayya is my company. But Vox is our only Rock Client, as it's my home church.  We're not planning on taking on Rock clients or anything like that.

**Comment by HeatherFoster** [comment]
I wanted to add to the convo, thought closed, as it relates to credit card issue because of Sign Ups. Has anyone experienced what I'm about to describe? Please bear with me please as I explain. We used Sign Ups for some weekend service projects (with Anonymous as the "Mode"). We had a person/registrant (call her Rhonda), sign up both herself and her friend (call the friend Terri). For ease and so these ladies could make sure they got on the same service project before slots filled up, Rhonda registered herself and her friend Terri in one sitting/instance. Turns out Rhonda didn't know Terri's email, so Rhonda put Rhonda's email on both her and Terri's Sign Up entry. Turns out the next time Terri logged into her account to give online, in addition to the VISA card Terri has on her account for giving, she now also had a MASTERCARD listed, and turns out it was Terri's mastercard! The new, active, visitor record for Terri that was built because of the Sign Up of course had Rhonda's email. We called and verified with Terri (who was a little freaked out) that the last 4-digits of the MASTERCARD she was seeing were in fact Rhonda's (we verified by looking at Rhonda's past giving history). The only way we could RESOLVE the CREDIT CARD ISSUE was to manually merge Terri's records (Rock > People > Merge People), meaning we merged Terri's long-term attendee profile with Terri's new visitor profile created by Sign Up (and made sure we had Terri's email selected, not Rhonda's, before we performed the merge). Before we did the merge, we had Terri on the phone who logged into her account and once again saw both her VISA and Rhonda’s MASTERCARD on her account. I manually merged Terri; I had Terri log out, then back in; after the merge Terri then only showed her VISA on her account – and the problem was resolved. I’m not sure how just the email caused this, but it did. **Like the originator of this post, with Sign Ups making people an active Visitor (and not a pending Prospect) is causing data integrity issues. [You may be wondering, but Rhonda was not logged into her Rock account when she did the Sign Ups, but we easily and routinely merged Rhonda, as usual, since her Sign Up info flagged her as a duplicate.)

**Comment by KCKurz** [comment]
@HeatherFoster we have been using Sign-Ups pretty extensively this summer and have also been using in the Anonymous mode, but haven't seen this. I tried to recreate what you discussed here to make sure it isn't happening. When I follow what you said: Anonymous, user not logged in, using same individual email on both - there was no crossover of saved credit cards. I don't know why it would do that, but I hope you find the reason. As I try to recreate it and see if it's an issue in our site, I wonder, was it something that happened instantaneously or after a job ran? 

@nairdo thank you for your response. Our use cases for the Sign Up tool are narrowed specifically for people within our church to sign up for our church-wide local outreach events; it has been a very effective tool for our needs and has allowed us to get away from Sign-Up Genius, Google Forms, and spreadsheets. Both the users and the staff have been very pleased with the ease of use. It took us a minute to decide what strategy to use as we built out what we needed, but it has been a huge blessing. Participants coming through as "Visitor" Connection Status hasn't been an issue as we have been able to stay on top of the duplicates as they come through. With Event Registrations, we often have registrants outside of our church, who are a part of our community or have other church homes, so yes, it's necessary to have the option to default everyone to a Pending Prospect so we can determine what Connection Status they should land in. Thank you!
