### ISSUE TITLE
Default Rock Theme does not display custom Site Logo correctly when browser size is less than 768px wide (like a mobile browser)

### ISSUE THREAD

**Issue by stanalyst** [SparkDevNetwork/Rock#5891]
### Description

Setting up a site that uses the default Rock theme (like for an internal staff site) - and changing the "Site Logo" to a custom image. When the site is viewed on a browser that is less than 768px wide (like a mobile browser) - the logo does NOT display correctly - and it affects functionality (ability to easily click the logo to return to home page)

### Actual Behavior

A picture explains it better than words...
![SiteLogo-Bad](https://github.com/SparkDevNetwork/Rock/assets/112125627/de0b5679-fa1a-40fe-876a-f90618f89fd7)

### Expected Behavior

Again a picture explains it better ...
![SiteLogo-Good](https://github.com/SparkDevNetwork/Rock/assets/112125627/ba5875f2-0a84-4ee8-ba5c-1c0a616b3db5)

NOTE: We figured out how to adjust the styling for .navbar-brand-side .logo in _navbar.less so it displays correctly ... but felt it would be good if this were fixed in the default theme for the benefit of others.

### Steps to Reproduce

- Go to /admin/cms/sites/1 (or whatever site is using the default Rock theme)
- Upload a custom image to the "Site Logo" setting and save
- Navigate to that site - and resize browser window less than 768px wide
- click the "hamburger" icon in the upper left to open the dropdown menu - and observe the logo

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Try to reproduce the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

1.16.2.1

### Client Culture Setting

en-US

**Comment by sparkdevnetwork-service** [comment]
@stanalyst We were not able to reproduce this on v16.5.  Although it can be difficult to track down fixes that happened in the past, it does appear that this issue has been discovered and addressed since v16.2.  Here is a screenshot showing v15.4 vs v16.5 for some of the related CSS styling that is involved:
![image](https://github.com/SparkDevNetwork/Rock/assets/6056081/ad37bb7c-6fdc-413c-ada9-1ec7e0ff76a4)

...where it looked like this:
![image](https://github.com/SparkDevNetwork/Rock/assets/6056081/b3f8ae53-1ba3-483b-b979-f7d2ade532d7)

Please feel free to reopen this and include an example image if you still experience this in v16.5.

**Comment by JimMichael** [comment]
Should that be "Fixed in 16.6"?
