### ISSUE TITLE
Content Channel Item View Block Does Not Respect Channel Item Set Permission

### ISSUE THREAD

**Issue by lacwebadmin** [SparkDevNetwork/Rock#5931]
### Description

I have this HTML block in a page where I list a content channel items using `contentchannelitem` entity and I forgot to remove the option `securityenabled:'false'`, and was wondering why am I seeing the content item (with permission ALL - Denied and Only Rock Admin can View) in the list page. So I removed it and the item went away when I refreshed the page.

![image](https://github.com/SparkDevNetwork/Rock/assets/171614378/78aa013f-ff24-43fc-b516-543a59d2f43c)

The issue is with the page where the Content Channel Item View block is where you see the details of the content channel item. I tried to manually enter the supposed detail link of that item with slug as the url parameter and I can still see the details as non-logged in user where it supposed to ask me to login.

![image](https://github.com/SparkDevNetwork/Rock/assets/171614378/a0313051-83ae-4eea-8671-7c00026893fa)

I don't know if this is intentional but to me it is a bug.

![image](https://github.com/SparkDevNetwork/Rock/assets/171614378/fc3b367b-5fa3-4272-b273-63d126fc3a74)

### Actual Behavior

Please read my description above.

### Expected Behavior

The Content Channel Item View Block should respect the permissions set in the channel item.

### Steps to Reproduce

Please read description.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

16.4

### Client Culture Setting

en-US

**Comment by chead4** [comment]
@lacwebadmin To help us investigate this issue, it would be greatly appreciated if you could please provide the steps to reproduce the issue, along with screenshots.

**Comment by lacwebadmin** [comment]
@chead4 I've added screenshots from the demo site. The only difference with my setup is I use a Lava using Entity to list the content items but the issue is with with the `Content Channel Item View` block.

**Comment by chead4** [comment]
@lacwebadmin Since Rock isn't sure which security verb you want to filter by, there's a general principle in Lava that it's the Lava admin's responsibility to decide what to display (if authorization or rights checking is needed).

Once you have set security for the ContentChannelItem, the Lava Template on the Content Channel View Item block can be updated to use the HasRightsTo filter. This filter will check the security of the model passed.  (You can find more details on that filter [here](https://community.rockrms.com/lava/filters/other-filters#hasrightsto).

Update the Lava template to include the following (which can be seen in lines 75 and 76 of the screenshot), which will check security before displaying the child Content Channel Item. 

{% for message in Item.ChildItems %}
	{% assign viewAuth =  message.ChildContentChannelItem | HasRightsTo:'View' %}
	{% if viewAuth != true %}{% continue %}{% endif %}
		<li> ...
![chrome_W09VmODSCX](https://github.com/user-attachments/assets/6bc91df7-9aee-4377-b956-8f804f94976d)

In this example, 'Of Myths and Money' does not display as security is set to All Users - Deny.
![image](https://github.com/user-attachments/assets/fd39c554-6f21-4a01-b4aa-c218476ae392)

I'll go ahead and close this issue.

**Comment by lacwebadmin** [comment]
@chead4 Yeah, but isn't that a work around via Lava? What if I forgot to do that check? That is still a security issue by default using the Content View Block and Content View Item Block.

**Comment by chead4** [comment]
@lacwebadmin  The way the security is designed for this block is intentional, not a workaround.  Other blocks in Rock function similarly, like Group Types/Group Attributes. For example, in the Group View Lava Template under Display Options, you need to have the HasRightsTo filter.
 
If you forget to include the HasRightsTo filter on the Lava Template, security won’t be checked and users will be able to see the content.
