### ISSUE TITLE
[Alpha 1.16.7.2] Next Gen Checkin-Cancel out of edit family or add family screen takes you back to the beginning

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6078]
### Description

When you are on a kiosk and go to the edit family or add family screen and then decide to cancel out of it, it takes you back to the very first page of the kiosk with the Start button on it. You have to re-enter the families phone number and start all over.

### Actual Behavior

When you are on a kiosk and go to the edit family or add family screen and then decide to cancel out of it, it takes you back to the very first page of the kiosk with the Start button on it. You have to re-enter the families phone number and start all over.

### Expected Behavior

It should take you back to the screen you were on when you went to the Edit Family option. Here is what it looks like in 16.6. I'm not saying it has to be exactly like this but something similar in the new technology. 
![Screenshot 2024-11-14 at 2 42 39 PM](https://github.com/user-attachments/assets/04f2f6f6-d8be-4093-bfd4-5f7caa1f991e)

### Steps to Reproduce

Add Family
1. Go to the kiosk page
2. click start
3. enter a phone number
4. click Add Family
5. click Cancel ---> returned to step 1

Edit Family
1. Go to the kiosk page
2. click start
3. enter a phone number
4. click on the Family
5. Click Edit Family
6. click Cancel ---> returned to step 1

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@kimlongcr I just wanted to note that the fix for this will always show the confirmation when clicking "Cancel" even if no changes have been made. Due to the way the internal data for editing a family is tracked and the way Rock stores some data, if we tried to actually detect changes we would get a lot of false positives.

As one example, if you had any Attribute Values configured for the family or person, there is a high chance it would trigger a false "change detected" because if the original value was _null_ (meaning, it had never been set before) then the UI would immediately "fix" that by making it a blank string which would be detected as a change.

So rather than having it seemingly randomly pop up saying "changes were made" when they weren't, we decided instead to always pop up a confirmation but change the text to just say "Do you want to leave without saving?".
