### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Configuration Refresh issues after adding a configuration

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6083]
### Description

When you add a new configuration, you have to manually refresh the page to actually see the configuration in the list. If you then change campus and kiosk at the top and click on refresh, it takes you back to the original campus you were on when it refreshes; doesn't refresh the campus and kiosk selected. 

### Actual Behavior

When you add a new configuration, you have to manually refresh the page to actually see the configuration in the list. If you then change campus and kiosk at the top and click on refresh, it takes you back to the original campus you were on when it refreshes; doesn't refresh the campus and kiosk selected. 

### Expected Behavior

After saving a new configuration, it would be displayed automatically in the list. A refresh of a page would maintain the campus and kiosk selected. 

### Steps to Reproduce

Make sure you are logged in before beginning these steps
1. Go to checkin setup (https://rockalpha.crossroads.net/nextgen-checkin/setup)
2. Select a campus and a kiosk
3. Add a new configuration for at least two campuses (the one you are on and another one) --> takes you the /nextgen-checkin
4. Click on back --> returns you to the same campus and kiosk selection. However, the configuration you just added is not in the list = issue 
5. Refresh the page --> new configuration is displayed in list
6. Choose the second campus for this configuration and a kiosk --> configuration is not in the list = issue
7. Click on refresh on the browser --> refreshes the page back to the same campus and kiosk as step 4 and 5 = issue 

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by nairdo** [comment]
Hi @kimlongcr, Thank you for bringing this up and for the detailed steps you provided. After reviewing this further, we’ve determined that the `back` button in step 4 is referring to the browser’s back button. Unfortunately, this behavior is controlled by the browser itself, which is why it returns you to the page state as it was when you left it.

We understand the frustration this might cause in certain scenarios. While we often include an application-level "< Back" button to provide more controlled navigation, in this specific case, we’ve opted not to include one to avoid returning to the setup page unnecessarily.

We really appreciate your feedback and your understanding. Please don’t hesitate to share more ideas or suggestions in the future!

**Comment by kimlongcr** [comment]
@nairdo I understand the issue except for this one issue - to get a new configuration to display, I have to do a manual refresh  no matter what I try.

**Comment by kimlongcr** [comment]
@nairdo Did you see my last comment where I have to do a hard refresh to see the new configuration I just added?

**Comment by kimlongcr** [comment]
Do these steps:
1. Go to checkin setup (https://rockalpha.crossroads.net/nextgen-checkin/setup)
2. Select a campus and a kiosk
3. Add a new configuration for at least two campuses (the one you are on and another one) --> takes you the /nextgen-checkin
4. Click on back --> returns you to the same campus and kiosk selection. 
5. Choose the second campus for this configuration and a kiosk --> configuration is not in the list 
Unless I manually click on the refresh button on the browser, the configuration never shows in the list for any campus. I understand the not showing after a back button from the browser (although still confusing to the user) but after picking different options and it still doesn't refresh the list to show the new one you added, it is very intuitive. I can see our people trying to recreate it again thinking it didn't save.

**Comment by nairdo** [comment]
Thank you. I believe I'm following your instructions but I'll let you verify that I did this correctly:

![image](https://github.com/user-attachments/assets/482662b2-da59-42d8-a7ad-99b920938333)

If that is what you are saying, this is the behavior I was trying to describe is normal.  

What I did not see happen was what you said happened in your original step 6 -- after you had manually refreshed the page in step 5:

> 5. **Refresh** the page --> new configuration is displayed in list
> 6. Choose the second campus for this configuration and a kiosk --> configuration is **not** in the list = issue

**Comment by kimlongcr** [comment]
@nairdo If you skip your step 4 and just do step 5, you still have to click on the browser refresh button to see the new configuration. Why isn't selecting a new campus and kiosk changing the list of configurations and picking up the new one I just created?

**Comment by nairdo** [comment]
Thanks again.  I think I understand what you're seeing, but I'm going to give you a call later today so we can walk through this together.

**Comment by nairdo** [comment]
@kimlongcr It was nice to talk with you earlier today.  After discussing some options this afternoon with the team, we're going to adjust the block so that when you press "Save" (when adding a new configuration) it will return you to that Check-in Options page where the new option will be listed:
![image](https://github.com/user-attachments/assets/ff89cada-c4c9-4ea8-b2b7-89317074007d)

Then, if one wants to navigate to check-in using one of the listed configurations, they just click the appropriate button in the list.

**Comment by nairdo** [comment]
@kimlongcr This has been adjusted via https://github.com/SparkDevNetwork/Rock/commit/532c99b4c6a228abdb2001c367df0eabe322b056 and is in the 1.16.7.4 alpha release/beta release.
