### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Reprint Labels screen usability

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6084]
### Description

When I first opened the reprint labels screen, it took a full 15-30 seconds for me to understand what the search field was for and how to use the screen. 

### Actual Behavior

When you first go to the Reprint Labels screen, it shows the following:
![Screenshot 2024-11-14 at 2 52 43 PM](https://github.com/user-attachments/assets/a41d801b-ae3e-4adb-9be4-073e658f4e61)

Having the word filter in the search box is confusing. And telling me to tap a button below to reprint when the button goes the entire width of the screen is confusing. While behind the scenes this might be a "button", it is not normal for a button to go the entire width of a screen. 

### Expected Behavior

The language and action to take to be super clear. Example wording:  
Reprint Labels
Search by name
<search field is blank / does not contain the word filter>

It is obvious that they need to select the person to reprint for once they find them. 

### Steps to Reproduce

Go to the kiosk /next-gen/checkin
click on gear icon
enter the supervisor login
click on reprint label button

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by cabal95** [comment]
@kimlongcr We have updated the placeholder text from "Filter" to "Search" and adjusted the subtitle text to be clearer. If you also wanted to adjust the width of the buttons on your instance you could do that with some CSS overrides.

I also created a follow up task for our UX designer to check on why the placeholder text color ("Filter/Search") is the same color as the normal text rather than being a lighter color.
