### ISSUE TITLE
[Alpha 1.16.7.2] Registration Payment Plan Not Working

### ISSUE THREAD

**Issue by mikedotmundy** [SparkDevNetwork/Rock#6085]
### Description

I currently have a Sandbox Gateway setup with My Well. It works correctly for an Event Registration _without_ creating a payment plan. However, when setting up the payment plan, I am greeted with an error and the registration never completes.

<img width="1344" alt="Screenshot 2024-11-15 at 12 28 06" src="https://github.com/user-attachments/assets/ffe63f47-331a-4e30-9735-57fd370321f3">

<img width="1343" alt="Screenshot 2024-11-15 at 12 15 16" src="https://github.com/user-attachments/assets/22fcd7b9-c91b-4b36-a371-94689ca34816">

<img width="1933" alt="Screenshot 2024-11-15 at 12 15 33" src="https://github.com/user-attachments/assets/f26669d8-4eb5-4e86-83dd-5f3b5349d802">

Not sure if this is helpful, but here is what my console is showing when I try to submit the registration and the error displays on the page:
<img width="1616" alt="Screenshot 2024-11-15 at 12 31 54" src="https://github.com/user-attachments/assets/f4971c31-5d42-44b7-9975-088caf86e8dd">

### Actual Behavior

Event Registrations with Payment Plan do not work.

### Expected Behavior

Event Registrations with Payment Plan should work.

### Steps to Reproduce

I am not sure how to reproduce this, as it is happening in our local environment, running a My Well Sandbox Gateway.

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

v1.16.7.2 Alpha

### Client Culture Setting

en-US

**Comment by shauncummings** [comment]
@mikedotmundy I am not able to duplicate this.  Using a My Well sandbox gateway, I set up the Summer Camp registration template from our demo data with a payment plan and then created a new registration instance for it, and the payment with payment plan was processed successfully (screenshots below).

For reference, I'm using the newest release of the My Well Gateway plugin from the Rock Shop (v1.5.5).  It looks like you've downloaded that version from the Rock Shop, but please make sure you've updated it on your dev environment.

The error you're receiving indicates that the scheduled transaction was not created by the gateway, and since this is a plugin, the code that is actually causing the error is not part of Rock.  I suspect there's a gateway error happening that we can't see, since it's all handled in the plugin gateway code and My Well's API.  I'm going to close this issue and refer you to My Well for additional support on this, but please let us know if you think this needs more follow-up on our side.

![Payment Plan Registration 1 - Plan Details](https://github.com/user-attachments/assets/6d75f7cb-4d37-4f23-a5bc-78081402799b)
![Payment Plan Registration 2 - Registration Complete](https://github.com/user-attachments/assets/7e8efd20-366a-4606-b0a1-e19575cd54a9)
![Payment Plan Registration 3 - Admin View](https://github.com/user-attachments/assets/5dcb1c67-a6f1-4087-bec3-467007f3e650)

**Comment by mikedotmundy** [comment]
Thank you @shauncummings - I will follow up with My Well.
