### ISSUE TITLE
[Alpha 1.16.7.2]-NextGen Checkin-Labels don't allow parent name

### ISSUE THREAD

**Issue by kimlongcr** [SparkDevNetwork/Rock#6102]
### Description

On our labels today, we print the parent's name that checked them in for the day. This allows volunteers to call the parent by name when picking their child up. 

### Actual Behavior

Nextgen labels don't allow you to add the parent name via the new interface. I attached what our labels look like in 16.6 that I was trying to recreate.
![Screenshot 2024-11-22 at 9 29 29 AM](https://github.com/user-attachments/assets/517215f0-20a5-48f0-b610-758348e8840d)

### Expected Behavior

Parent name can be added to labels

### Steps to Reproduce

Go to the nextgen labels menu option
Select a label
Select Label Designer option = parent name is not an option under Attendee Info or Checkin Info

### Issue Confirmation

- [X] Perform a search on the [Github Issues](https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock) to see if your bug or enhancement is already reported.
- [X] Reproduced the problem on a fresh install or on the [demo site](https://rock.rocksolidchurchdemo.com/).

### Rock Version

Rock McKinley 16.7 (1.16.7.2)

### Client Culture Setting

en-US

**Comment by JimMichael** [comment]
I could be completely wrong about this, but I think because the "Label Type" in Nextgen only has certain built-in merge fields, for anything _else_ we want to display we have to write our own "merge field" Lava, just like in v1 checkin.

To my knowledge this hasn't been documented yet, but by poking around I was able to get Parents to print via a _Text_ control set to _Dynamic Text_, with the following in the Lava template:

{% assign parents = Person | Parents %}
   {% for person in parents %}
      {{ person.FullName }}, 
{% endfor %}

**Comment by kimlongcr** [comment]
@JimMichael If this worked for you, I'm good with it. We'll use Lava. Thanks!

**Comment by jonedmiston** [comment]
Closing this as it is possible with Lava. We'll look at the practicality of adding it through the UI in the near future.
