### ISSUE TITLE
Schedule Builder page in Check-In Configuration

### ISSUE THREAD

**Issue by FrankGrand** [SparkDevNetwork/Rock#626]
Can a "select/unselect all" option please be added to the schedule builder page for Check-In Configuration.

Also would be very helpful if schedules were listed in order of the week instead of alphabetically.  For example, I have a category for weekdays, with M-F added.  They are listed Friday, Monday, Thursday, Tuesday, Wednesday.

**Comment by cabal95** [comment]
Mockup of select/unselect all:

![screen shot 2017-04-06 at 4 05 09 pm](https://cloud.githubusercontent.com/assets/1119863/24779098/f3484156-1ae2-11e7-82ca-c29434a73ab3.png)

**Comment by edmistj** [comment]
Nice work! What if we used icons instead of words? Like:

![chrome_2017-04-06_16-16-30](https://cloud.githubusercontent.com/assets/548178/24779329/82c3631e-1ae4-11e7-8956-fd1bfeb6d98f.png)
![chrome_2017-04-06_16-16-08](https://cloud.githubusercontent.com/assets/548178/24779328/82c22b70-1ae4-11e7-847e-30929a98f6c4.png)

https://www.youtube.com/watch?v=feLnBXdny1M&feature=youtu.be&t=51s

Could add a little padding-h-sm if needed to make the buttons a bit easier to click. This would also make them consistent sizes.

**Comment by cabal95** [comment]
Two mockups in one. One with the bootstrap btn borders, the rest just the fa icons:

![screen shot 2017-04-06 at 4 40 34 pm](https://cloud.githubusercontent.com/assets/1119863/24779869/fbd34faa-1ae7-11e7-88d0-b1c922128c85.png)

It might also look better if I center the buttons/icons in the header. Just not sure how that will look on larger screens with the text left-aligned and the buttons centered.

**Comment by JimMichael** [comment]
Are the icons obvious functionality? I doubt I'd look at an unchecked box and think it meant "deselect all".

**Comment by cabal95** [comment]
that was my thought for using `All` and `None`, but I'm game to do whatever. Functionality is the same either way and it's just swapping some classes around. It would take more space but could combine the "fa-check-square-o" with the word "All" and the "fa-square-o" with the word None. I don't think we will be wasting too much space that way since I would think most schedule names have at least a partial day name in them.

**Comment by cabal95** [comment]
One more mockup with the icons and text, but no button borders. Also centered the text and buttons for that column mockup.

![screen shot 2017-04-06 at 5 44 23 pm](https://cloud.githubusercontent.com/assets/1119863/24780965/d7eb0b60-1af0-11e7-8723-7dec59b940e5.png)

**Comment by edmistj** [comment]
What if there was one checkbox at the top that toggles them all off and on. That would match the grids.

**Comment by cabal95** [comment]
A single "toggle" would work, though I'm not sure a checkbox-style would make sense to the user any more than the two checkboxes (without text) would. Personally, the single toggle style have always felt weird to me from a UX standpoint. It's like a crap shoot what will happen when you click it if I have some already checked and some not. It's a small point because at worst I just have to click it again to get the desired results.

To address the "hey you can click me to do something" issue, possibly would be to use a tri-state check-box with the checked, unchecked and "partial fill" style. And have it update dynamically with javascript so they notice it changing on screen while they are doing stuff.

<img width="118" alt="2017-04-07 08_52_06-font awesome icons" src="https://cloud.githubusercontent.com/assets/1119863/24808191/b95bf450-1b6f-11e7-9303-8d7fdd93221c.png">
<img width="106" alt="2017-04-07 08_53_00-font awesome icons" src="https://cloud.githubusercontent.com/assets/1119863/24808192/bb02552e-1b6f-11e7-9108-7e0fdbb23082.png">
<img width="85" alt="2017-04-07 08_53_11-font awesome icons" src="https://cloud.githubusercontent.com/assets/1119863/24808195/bcd42a8a-1b6f-11e7-81f4-4f9d5bc7f702.png">

**Comment by edmistj** [comment]
Let's mirror the table checkboxes with just the checked and unchecked. It's simple and consistent.

<img width="118" alt="2017-04-07 08_52_06-font awesome icons" src="https://cloud.githubusercontent.com/assets/1119863/24808191/b95bf450-1b6f-11e7-9303-8d7fdd93221c.png">

<img width="85" alt="2017-04-07 08_53_11-font awesome icons" src="https://cloud.githubusercontent.com/assets/1119863/24808195/bcd42a8a-1b6f-11e7-81f4-4f9d5bc7f702.png">

**Comment by cabal95** [comment]
Sorry just making sure on the same page with you :) 

a) A single checkbox that toggles it's state between the two and whose action changes (check all, uncheck all) depending on the state.

or b) two different checkboxes (one showing checked, one showing unchecked) each with their own action.

?

**Comment by edmistj** [comment]
Sorry wasn't clear, A

**Comment by cabal95** [comment]
PR adds ability to select/unselect the entire column for a schedule. I looked at the ordering thing, but that is looking to be a massively complex sorting algorithm. I think a better way to go would be to allow manual ordering of Schedules in a category, ala #1260.
