### ISSUE TITLE
Person Attributes - Allow Descriptions to be shown for Defined Value field type?

### ISSUE THREAD

**Issue by MrUpsideDown** [SparkDevNetwork/Rock#758]
When creating a new Person Attribute with a Field Type of "Defined Value", I select the Defined Type "Countries" to supply a list of possible values for the new Attribute.

When selecting a value for this Attribute in the Person Details screen, I am offered a drop-down list of two-letter country codes (representing the Value field of the Defined Value). What I really want the user to see is a list of the Descriptions (ie. the full country name) rather than the Values.

Two possible solutions to this are:
1. Always show a concatenated list of Value/Description in the drop-down list.
(eg. [AF] Afghanistan, [AX] Aland Islands).
2. Add an option to the Person Attribute definition which enables the list of Defined Values to be displayed as Value or Description (or Both?)

**Comment by azturner** [comment]
We'll add this as a possible feature request list (which you can also [do here](http://www.rockrms.com/Rock/Ideas)). However, as a developer, you can also easily add your own field types to be used by attributes in Rock. [Here is sample code](https://gist.github.com/azturner/59620d17576aa03290a6) to add a field type that would accomplish what you are trying to do.  

If you haven't already, make sure to take a look at the [RockKit SDK](http://www.rockrms.com/Rock/Developer/Rockit). If you added the class in the Gist above to the sample project, compiled it, and added it to your RockWeb bin folder, you could then use your custom field type for any attribute (cache does need to be refreshed, or app restarted in order to load new field types)...

![image](https://cloud.githubusercontent.com/assets/548180/5592493/8416451e-918f-11e4-993d-355512778f88.png)

And, we're closing this issue, since it's not really an issue.

**Comment by MrUpsideDown** [comment]
Thanks for taking the time to provide the additional information, that's very helpful.
