### ISSUE TITLE
Lava Issue - {{ Person.BackgroundCheckDate }} not displaying

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#760]
I'm trying to get the Background Check Date from the current person using Liquid, but I'm having trouble - `{{ Person.BackgroundCheckDate }}` is always blank.  I've verified that the background check data exists on the person profile screen, as well as in the database.  Other liquid relating to background checks, like `{{ Person.BackgroundChecked }}`, work fine.

**Comment by azturner** [comment]
@bwitting That is due to the security on that attribute.  Currently Lava assumes an unknown or anonymous user when checking security on attributes. If you edit the security for that person attribute and remove the rules specific to that attribute for "View" access, it should then show up ( make sure your HTML isn't cached ).  

We'll also leave this open as an issue to have Lava use the currently logged in user's credentials when resolving attribute values instead of defaulting to anonymous user.

**Comment by azturner** [comment]
In v3.0, the Lava Attribute filter will use the current person when checking security rather than defaulting to anonymous user ( this will require using the new attribute format: `{{ CurrentPerson | Attribute:'BackgroundCheckDate' }}`.

**Comment by ccofnow** [comment]
FYI, at least in v2.0, the syntax appears to actually be {{ Person | Attribute:'BackgroundCheckDate' }}. Thanks for the fix, and the heads-up about the new syntax.
