### ISSUE TITLE
Content Channel Item Start/Expire Dates not respecting local time zone differences

### ISSUE THREAD

**Issue by ElimAdmin** [SparkDevNetwork/Rock#788]
Hosting on Arvixe - in the States.  Local time zone - New Zealand.  9 hours ahead.
To get a channel item to display I have to adjust the start date by the date/time difference between our local time zone and the server's time zone.  E.g., set to a start date of 01/19/2015 to get the item to display even though local date is 01/20/2015.  Is it possible for the start date to respect the local time zone?
The following does not work to get the item to display on the 01/20/2015 in this time zone.
![contentstart](https://cloud.githubusercontent.com/assets/4658177/5815770/a436e290-a0fd-11e4-8ba3-5f9015e1e820.JPG)

**Comment by azturner** [comment]
This is due to a filter comparison issue with the 'current date' option always using 12:00 am for the datetime that it compares to, and not really a timezone issue.  The filter is likely configured to use a start date less than or equal to the 'current date', and in current version or Rock, the "current date" would always be 12:00 am of current day. So a start date of 20/01/2015 12:01am, would not be less than or equal to the current date of 20/01/2015 12:00am, which is why when you set start date of 19/01/15 12:01am, that is less than or equal to current date of 20/01/2015 12:00am.

We have fixed this issue here: https://github.com/SparkDevNetwork/Rock/commit/8555692698da17765f5f0c87edbcdf752e06fe0c

Next version of Rock will take into account the time when comparing against datetime values.
