### ISSUE TITLE
Content Channel Showing Pending Items

### ISSUE THREAD

**Issue by dsmallman** [SparkDevNetwork/Rock#863]
![contentissue](https://cloud.githubusercontent.com/assets/9287272/6407804/433f49bc-be05-11e4-819e-68e3cdb9e001.JPG)

I have a new content channel that is showing items pending approval, even though there are no items to approve.  I think I added items to this content channel before unchecking the "Items Require Approval" check box.  Once I unchecked the box, the items no longer needed approval, however the Channel still shows one item pending.

**Comment by tcavaletto** [comment]
When you uncheck the "Items Require Approval" checkbox in the channel details, it hides the pending / approved statuses of the items, but those statuses are still there. The reason that the content channel is showing pending items is because there are one or more left over from before you unchecked the box. Just go back to those items and set them as approved, and the badge will go away.

**Comment by dsmallman** [comment]
.Thanks!  Please close.
