### ISSUE TITLE
Creating a login via api/UserLogins results in 500 with matching info

### ISSUE THREAD

**Issue by jhawkzz** [SparkDevNetwork/Rock#896]
If a new login is created using api/UserLogins, using a POST with model UserLoginWithPlainTextPassword, Rock will throw a 500 if there's already a login created with the same username and password.

Creating a login this way with a unique username / password works fine.

**Comment by edmistj** [comment]
@jhawkzz as far as you know is this still an issue?

**Comment by cabal95** [comment]
Confirmed. It generates an error 500 complaining about duplicate key IX_UserName.

Either this would be considered correct behavior, since I don't think any of the API methods really check for SQL errors about primary key violations on INSERT, OR we should modify the API to do so (can it be done globally somewhere?) and return a `409 Conflict` status.

**Comment by edmistj** [comment]
@cabal95 think we just need to check if the username exists before inserting and reply with a 409 with a nice message.
