### ISSUE TITLE
Known and Implied Relationship Headers not Appearing

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#930]
On McKinley 3.0/3.1:

When logged in as an administrator, staff worker, or staff-like worker role, the Known Relationship and Implied Relationship boxes on a person's profile look correct:

![2015-04-07 14_22_06-henry witting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7030332/dbce1cb2-dd31-11e4-929c-a7a219169d37.png)

However, when logged in as the check-in user (with a check-in role that I made for check-in volunteers), the headers don't show up:

![2015-04-07 14_21_56-bronson witting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7030338/f36bc3b0-dd31-11e4-84ce-cc0b599764f7.png)

The Plus buttons appear though, so the user can still add known relationships (those permissions are correct and this is working correctly)

If you look at the HTML, the icon and text just aren't there (I thought maybe they were hidden):

Admin user:
![2015-04-07 14_20_57-henry witting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7030376/2909c13e-dd32-11e4-86f6-bcbcc671b868.png)

Check-in User:
![2015-04-07 14_21_46-bronson witting _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7030383/2f0b6060-dd32-11e4-90cc-2051bfe2a6a4.png)

Is there somewhere I'm missing to change permissions so these headers show up?

**Comment by edmistj** [comment]
This bug turned out to be a little different. Looks like the 'Check-in User' role did not have View or Edit rights to the 'Known Relationships' / 'Implied Relationships' group type. This kept the label from showing but also incorrectly let users add new relationships.

I fixed this to:
* Always show the heading label (no matter the permission)
* Correctly show the + button if the user has Edit access to the group type
* Show a warning message if they do not have View access

**Comment by bwitting** [comment]
Thanks Jon!  Just so you know, that problem only started with the update to 3.0 (everything was working as expected on 2.0)
