### ISSUE TITLE
Unable to delete Sites

### ISSUE THREAD

**Issue by nairdo** [SparkDevNetwork/Rock#937]
From @BelAirIT (Jeremy Turgeon):
Sites cannot be deleted.  They display a “This Site has a Layout which is used by a page.”

**Comment by azturner** [comment]
@tcavaletto , still get an exception when trying to delete a site if any of the page's on the site were viewed. This is because there are PageView records associated with one or more of the pages that are being attempted to be deleted.

**Comment by azturner** [comment]
@tcavaletto , we really don't want to lose PageView records when a site or page is deleted. Rather than cascade deleting all the PageView records when the site (and it's pages) are deleted, it should instead set the PageId to null.  Take a look at the PageList block. It does the same thing when a page is deleted.
