### ISSUE TITLE
Incorrect Date/Time on items from Check Scanner App

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#956]
On McKinley 3.1: 

Some dates/times on the Check Scanner app don't match what is in the Rock Batch info.  For example, these items were scanned on 4/1:

![2015-04-16 16_50_09-rock rms - check scanner](https://cloud.githubusercontent.com/assets/1859094/7191099/ff51b5a8-e458-11e4-8955-51a41a082dee.png)

But the Transaction date in Rock shows 3/13: 

![2015-04-16 16_50_19-financial batch detail _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7191203/c54e6fbc-e459-11e4-803a-1786e0a3a39a.png)

Maybe this is a timezone issue?  On many transactions, the time is midnight, but in the example above, it is 3 hours behind (although we're in EST, UTC-4)

This isn't a problem with every batch, just some.  Here is one where the date is correct:

![2015-04-16 16_58_11-rock rms - check scanner](https://cloud.githubusercontent.com/assets/1859094/7191211/d20efdac-e459-11e4-8783-43480e86b2f5.png)

![2015-04-16 16_56_58-financial batch detail _ rock rms](https://cloud.githubusercontent.com/assets/1859094/7191212/d3f99802-e459-11e4-9c4b-340c04901ad8.png)

**Comment by mikepetersonccv** [comment]
The 3 hour difference that you found is due to a bug, which is fixed in  https://github.com/SparkDevNetwork/Rock/commit/5ae46e52d062594c9c4424d65795adf04a4ce451

Besides that, the Transaction DateTime and Scanned DateTime for scanned item can be a little confusing, so we'll update the documentation to make that more clear.  Here is how it works

The Scanned Date/Time that you see in the Scanner Grid is the Date/Time that the scanned item was uploaded. The Transaction Date/Time of each scanned transaction is determined by the Batch Date at the time of the scan.  Note that if the Batch Date was changed after some checks were already uploaded, the previously scanned checks would have the old Batch Date and the new scanned checks with have the new Batch Date.

**Comment by bwitting** [comment]
Great, thanks for the info @mikepetersonccv! I seem to be good at finding fringe cases...
