### ISSUE TITLE
Checkin Configuration resets GroupTypeAssociations on Save

### ISSUE THREAD

**Issue by dcs619** [SparkDevNetwork/Rock#968]
We've been playing around with Check-in Config to be able to use it for volunteers (jumping the gun for v4, I know).  We've got all our campuses set up now and can add volunteers as Group Members, with respective Roles and an attribute for their assigned Schedule.

However, we've noticed that when a Group (Greeter) is set up with a GroupType (Sunday Volunteers), we can't add or edit groups unless Sunday Volunteers allows a child GroupType.  So we changed Sunday Volunteers to allow a child GroupType of Sunday Volunteers and everything works perfectly.  In the database, there's a GroupTypeAssociation set as GroupType: "Sunday Volunteers", ChildGroupType: "Sunday Volunteers".

![screenshot 2015-04-21 10 00 50](https://cloud.githubusercontent.com/assets/1210933/7253846/50e4fc6a-e80d-11e4-9aea-a72bd7bc35b7.png)

The problem is that any change/save to the Check-in Config will remove the GroupTypeAssociation Sunday Volunteers : Sunday Volunteers.  I've stepped through the code but haven't quite figured this out.

**Comment by azturner** [comment]
@dcs619 Are you using latest from dev branch? We made some changes last week that might address this issue.

**Comment by dcs619** [comment]
Not yet.  I still have to get our gateway updated before I can pull the latest develop.

**Comment by dcs619** [comment]
@azturner The change to Check-in Config in v3 removes all our child groups and wipes out all their assignments, attendances, and attributes :(

Is there a diagram/workflow you could put together so I know how to set up the child groups?  This is a major breaking change that I'll have to update before we launch.  See https://github.com/NewSpring/Rock-Plugins/issues/126

**Comment by azturner** [comment]
I'm a bit confused.. are you having issue with v3.2 or the latest code in development? If this is with v3.2, I'm not aware of any significant changes to check-in config in that version. 

The reason we made the recent changes ( after 3.2 ) were to fix issues similar to what you are experiencing where the check-in configurator and group viewer would not work together. Previous to these changes you could not configure groups in both places without getting exceptions or data loss. For example the check-in configurator would create group types but configure them so that it couldn't have any child groups ( like you pointed out above). It also did not allow any levels of group hierarchy ( and of course the group viewer allows for infinite levels ). 

I'm a bit surprised that this was ever working for you. But if there's a specific change that broke something for you, please let me know. We obviously don't want to be introducing breaking changes. That said, being able to edit the same group types and groups in Group Viewer and in Check-in Configurator is not something that was supported ( or pretty-sure, would even work ) prior to the most recent change in our development branch.

**Comment by dcs619** [comment]
@azturner Whoops, I mean the latest code from development.  Sorry about that.

Prior to the latest change, we had enabled each GroupType's "Show in Group Lists" and "Show in Navigation" options and that allowed check-in groups to show up in Group Viewer.
![screenshot 2015-04-29 15 47 47](https://cloud.githubusercontent.com/assets/1210933/7399913/1f21bf30-ee87-11e4-9559-3709d9e97026.png)

**Comment by dcs619** [comment]
I'll find out what changed and why it didn't recognize our child groups.  It sounds like we're on a different page with the structure though...

If I get you a login, would you have time to look at our check-in groups and give me feedback for how they *should* be set up?  Because of the admin overhead setting up 19 campuses, we've scripted all the initial groups and then used check-in config to update/manage them.

**Comment by azturner** [comment]
I would just use the configurator to create a sample heirachy of groups, make sure they are editable in both the viewer and in configurator ( without data-loss ) and then see how they differ from the groups you've scripted.

**Comment by dcs619** [comment]
@azturner is a rock star and fixed this in d72e83b8e42dfd6c8f608d1a67a540bdf5080ad0
