### ISSUE TITLE
Group Registration Not Accepting Entity

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#973]
I've created a workflow that sets an attribute(Person) to entity and specified it to be used when someone registers for a group.  When the attribute is set to Text, it outputs the person's GUID.  But when set to Person, it remains blank.  I've tested the workflow by putting it under Actions like Person Data Error and it works fine.  It seems that the Group Registration block is somehow interfering with the workflow getting the entity information.

**Comment by azturner** [comment]
@BelAirIT if this is a workflow triggered by the Group Registration block, then the "Entity" getting passed to the workflow would be a Group Member and not a person. Technically, you should be able to still set a "person" attribute using the Lava Template property of that action since Person is a property of the GroupMember object. You'd use a value like: 

    {{ Entity.Person.PrimaryAlias.Guid }}

However... It appears the 'PrimaryAlias' property for the person object is not currently available to Lava. We've fixed that for v3.2 which is being released soon.
