### ISSUE TITLE
Default Sorting for Contributions on Individual Profile

### ISSUE THREAD

**Issue by bwitting** [SparkDevNetwork/Rock#980]
As of McKinley 3.0, the sorting (Descending by Date / Time Column) on the Contributions tab on an Individual's profile is no longer happening.  (I think it was sorted that way before, at least our Finance team is telling me it was)

I know it can be sorted by that column by clicking on the header, but Descending by Date / Time Column makes the most logical sense for the default sort. Thanks!

**Comment by nairdo** [comment]
According to [the code](https://github.com/SparkDevNetwork/Rock/blob/develop/RockWeb/Blocks/Finance/TransactionList.ascx.cs#L745), the default behavior is to order by the transaction's Id.  I think it makes sense to change this to use the TransactionDateTime property but let me double check...

**Comment by nairdo** [comment]
Ok, problem resolved.  Since the block is used in two pages -- on batch details and on person profile -- it needs to default sort with some intelligence.  (I also corrected the ascending/descending error I made in that my initial commit.) https://github.com/SparkDevNetwork/Rock/commit/9bab1cd098a5c9f9aaab539626eb222ffdbedeba
