### ISSUE TITLE
Dataview Still Doesn't Use 'Is Not Blank' In Filtering

### ISSUE THREAD

**Issue by BelAirIT** [SparkDevNetwork/Rock#992]
This issue is still present after the 3.2 update. The following screenshot is from the demo site.
![image](https://cloud.githubusercontent.com/assets/7409839/7351849/b1d62554-ecbc-11e4-9f4f-c0d6169289ca.png)

Related to this previously reported issue : https://github.com/SparkDevNetwork/Rock/issues/948

**Comment by arranf** [comment]
Also experienced this today.

On 27 April 2015 at 17:07, Jeremy Turgeon <notifications@github.com> wrote:

> This issue is still present after the 3.2 update. The following screenshot
> is from the demo site.
> [image: image]
> <https://cloud.githubusercontent.com/assets/7409839/7351849/b1d62554-ecbc-11e4-9f4f-c0d6169289ca.png>
>
> Related to this previously reported issue : #948
> <https://github.com/SparkDevNetwork/Rock/issues/948>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SparkDevNetwork/Rock/issues/992>.
>



-- 
*Arran France*
Communications, Youth Work, and Administration
*T*. 07425 159471

*Hope Church Corby*
Registered UK Charity 251549
The Hope Centre
8 Princewood Road
Corby
NN174AP

**Comment by MrUpsideDown** [comment]
It looks like the fix for this issue did not make it into the 3.2 release.
The current master branch does not include the code change, and there is no reference to this issue in the release notes.

**Comment by azturner** [comment]
We've recently changed our default branch to be 'Develop' instead of 'Master' which means that issues get closed as soon as the fix is checked into our develop branch (rather than when we release an update). Because of this we will try to be better about labeling the issue with which version it will be fixed in.  Closing this as a duplicate and will label the other one as fixed in 4.0
